### ISSUE TITLE
hue connect presto  Problems encountered

### ISSUE THREAD

**Issue by haoziyunwei** [cloudera/hue#1000]
java.lang.ClassNotFoundException: com.facebook.presto.jdbc.PrestoDriver

"An error occurred while calling z:java.lang.Class.forName.
: java.lang.ClassNotFoundException: com.facebook.presto.jdbc.PrestoDriver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:209)
	at java.lang.Thread.run(Thread.java:748)
"

config：
#presto
export PRESTO_HOME=/data/presto-server-0.228
export CLASSPATH=$PRESTO_HOME/presto-jdbc-325.jar:$CLASSPATH

 source /etc/profile
 echo $CLASSPATH
/data/presto-server-0.228/presto-jdbc-325.jar:/data/presto-server-0.228/presto-jdbc-325.jar:/data/presto-server-0.228/mysql-connector-java.jar:

**Comment by haoziyunwei** [comment]
/usr/share/hue/desktop/libs/librdbms/src/librdbms/jdbc.py
 classpath=classpath+':/opt/presto-jar/presto-jdbc-325.jar'

**Comment by haoziyunwei** [comment]
JavaObject object is not an iterator
hue connect presto 提示 JavaObject object is not an iterator
但是presto数据是能看到的

**Comment by romainr** [comment]
In case it helps, using the SqlAlchemy connector is the recommended way: https://docs.gethue.com/administrator/configuration/connectors/#apache-presto

**Comment by greendisc777** [comment]
> In case it helps, using the SqlAlchemy connector is the recommended way: https://docs.gethue.com/administrator/configuration/connectors/#apache-presto

Within Hue and using SqlAlchemy, it doesn't prompt for username/password.

**Comment by romainr** [comment]
Feel free to open in a new post https://discourse.gethue.com/ or github issue
