### ISSUE TITLE
hue install with python3.7.3 errors

### ISSUE THREAD

**Issue by fsilent** [cloudera/hue#1004]
= proxy v.4.5.0 is already installed
=== Installing app at rdbms
=== rdbms v.4.5.0 is already installed
=== Installing app at search
=== search v.4.5.0 is already installed
=== Installing app at security
=== security v.4.5.0 is already installed
=== Installing app at spark
=== spark v.4.5.0 is already installed
=== Installing app at sqoop
=== sqoop v.4.5.0 is already installed
=== Installing app at useradmin
=== useradmin v.4.5.0 is already installed
=== Installing app at zookeeper
=== zookeeper v.4.5.0 is already installed
=== Saved registry at /home/hue-master/app.reg
=== Saved /home/hue-master/build/env/lib/python3.7/site-packages/hue.pth
Running '/home/hue-master/build/env/bin/hue makemigrations --noinput' with None
[02/Dec/2019 15:30:18 +0800] settings     DEBUG    DESKTOP_DB_TEST_NAME SET: /home/hue-master/desktop/desktop-test.db
[02/Dec/2019 15:30:18 +0800] settings     DEBUG    DESKTOP_DB_TEST_USER SET: hue_test
[01/Dec/2019 23:30:18 -0800] sslcompat    DEBUG    ipaddress module is available
[01/Dec/2019 23:30:18 -0800] sslcompat    DEBUG    ssl.match_hostname is available
Traceback (most recent call last):
  File "/home/hue-master/build/env/bin/hue", line 11, in <module>
    load_entry_point('desktop', 'console_scripts', 'hue')()
  File "/home/hue-master/desktop/core/src/desktop/manage_entry.py", line 225, in entry
    execute_from_command_line(sys.argv)
  File "/home/hue-master/build/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/hue-master/build/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/hue-master/build/env/lib/python3.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/hue-master/build/env/lib/python3.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/home/hue-master/build/env/lib/python3.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/hue-master/build/env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/hue-master/apps/search/src/search/models.py", line 28, in <module>
    from libsolr.api import SolrApi
  File "/home/hue-master/desktop/libs/libsolr/src/libsolr/api.py", line 35, in <module>
    from dashboard.models import Collection2
  File "/home/hue-master/desktop/libs/dashboard/src/dashboard/models.py", line 39, in <module>
    from notebook.connectors.base import Notebook, _get_snippet_name
  File "/home/hue-master/desktop/libs/notebook/src/notebook/connectors/base.py", line 472
    def get_sample_data(self, snippet, database=None, table=None, column=None, async=False, operation=None): raise NotImplementedError()
                                                                                   ^
SyntaxError: invalid syntax

**Comment by romainr** [comment]
Problem with `async` keyword now reversed in 3.7?

One solution could rename to `async_` or `is_async`.

@wing2fly FYI

**Comment by fsilent** [comment]
I modify the code and success, but find another problem when execute:build/env/bin/supervisor
Traceback (most recent call last):
  File "build/env/bin/supervisor", line 11, in <module>
    load_entry_point('desktop', 'console_scripts', 'supervisor')()
  File "/home/hue-master/desktop/core/src/desktop/supervisor.py", line 326, in main
    pidfile_context = TimeOutPIDLockFile(pid_file, LOCKFILE_TIMEOUT)
NameError: name 'TimeOutPIDLockFile' is not defined

**Comment by wing2fly** [comment]
I am working on py3 tests, and I will check this one.

**Comment by fsilent** [comment]
Is this test on Python3.7.3? @wing2fly 
I use Python 3.7.3 and finds some errors.
![hue](https://user-images.githubusercontent.com/9815890/71793316-657aa780-3077-11ea-8c9c-d7b5b8b38aac.png)
I try to pip install lxml==3.3.6, and find 
![image](https://user-images.githubusercontent.com/9815890/71793348-7fb48580-3077-11ea-9c1f-bb64d7bbdbe1.png)
And then I tried rm -rf /opt/hue-release-4.6.0/desktop/core/ext-py/lxml-3.3.6, and find 
![hue](https://user-images.githubusercontent.com/9815890/71793474-fc476400-3077-11ea-9ce1-c922cb9fe607.png)

**Comment by romainr** [comment]
Could you open a new issue? (as it is not the same problem now, it might be because you have the wrong OS package installed, with 3.8 and Ubuntu you only need https://github.com/cloudera/hue/blob/master/.circleci/config.yml#L160)
