### ISSUE TITLE
Error in log files on resource /desktop/workers/aceSqlSyntaxWorker.js?v=4.4.0

### ISSUE THREAD

**Issue by sbaudoin** [cloudera/hue#1016]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
Not as far as I could search for it

What is the Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...)
Open source 4.3 and 4.4

Is there a way to help reproduce it?
On every login/everytime the browser requests /desktop/workers/aceSqlSyntaxWorker.js?v=4.4.0

Everytime we log in Hue, we get the following error in the log files:

```
[10/Dec/2019 23:21:00 +0100] middleware   INFO     Processing exception: 'NoneType' object has no attribute 'update': Traceback (most recent call last):
  File "/usr/local/hue/build/env/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/hue/build/env/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/usr/local/hue/desktop/core/src/desktop/views.py", line 376, in ace_sql_syntax_worker
    return HttpResponse(render('ace_sql_syntax_worker.mako', request, None), content_type="application/javascript")
  File "/usr/local/hue/desktop/core/src/desktop/lib/django_util.py", line 225, in render
    data.update({'user': request.user})
AttributeError: 'NoneType' object has no attribute 'update'

[10/Dec/2019 23:21:00 +0100] middleware   INFO     Processing exception: 'NoneType' object has no attribute 'update': Traceback (most recent call last):
  File "/usr/local/hue/build/env/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/hue/build/env/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/usr/local/hue/desktop/core/src/desktop/views.py", line 373, in ace_sql_location_worker
    return HttpResponse(render('ace_sql_location_worker.mako', request, None), content_type="application/javascript")
  File "/usr/local/hue/desktop/core/src/desktop/lib/django_util.py", line 225, in render
    data.update({'user': request.user})
AttributeError: 'NoneType' object has no attribute 'update'

[10/Dec/2019 23:21:00 +0100] exception    ERROR    Internal Server Error: /desktop/workers/aceSqlSyntaxWorker.js
Traceback (most recent call last):
  File "/usr/local/hue/build/env/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/hue/build/env/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/hue/build/env/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/hue/build/env/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/hue/build/env/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/usr/local/hue/desktop/core/src/desktop/views.py", line 376, in ace_sql_syntax_worker
    return HttpResponse(render('ace_sql_syntax_worker.mako', request, None), content_type="application/javascript")
  File "/usr/local/hue/desktop/core/src/desktop/lib/django_util.py", line 225, in render
    data.update({'user': request.user})
AttributeError: 'NoneType' object has no attribute 'update'
[10/Dec/2019 23:21:00 +0100] exception    ERROR    Internal Server Error: /desktop/workers/aceSqlLocationWorker.js
Traceback (most recent call last):
  File "/usr/local/hue/build/env/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/hue/build/env/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/hue/build/env/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/hue/build/env/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/hue/build/env/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/usr/local/hue/desktop/core/src/desktop/views.py", line 373, in ace_sql_location_worker
    return HttpResponse(render('ace_sql_location_worker.mako', request, None), content_type="application/javascript")
  File "/usr/local/hue/desktop/core/src/desktop/lib/django_util.py", line 225, in render
    data.update({'user': request.user})
AttributeError: 'NoneType' object has no attribute 'update'
```

The interface, though, seems to work fine.
This happens in the URL: /desktop/workers/aceSqlSyntaxWorker.js?v=4.4.0

**Comment by sbaudoin** [comment]
Forget about that, there is a fix: https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/lib/django_util.py#L225 (coming from https://github.com/cloudera/hue/commit/d0c74976b9c79c838f371d8047558cea8ab98f4c)
