### ISSUE TITLE
raise PopupException(_('Encountered unexpected error in SentryApi.'), detail=e)

### ISSUE THREAD

**Issue by 915816744** [cloudera/hue#1049]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?

What is the Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...)
CDH6.2.1、CDH6.3.2
Is there a way to help reproduce it?
in the hue,could not create role 
![image](https://user-images.githubusercontent.com/35521373/75125452-27514a00-56f0-11ea-82bc-932321f4ee54.png)

logs:
error.log:
[23/Feb/2020 17:25:56 -0800] access       ERROR    10.33.125.141 hive - "POST /desktop/log_js_error HTTP/1.1"-- JS ERROR: {"msg":"Uncaught SyntaxError: Unexpected token ':'","url":"http://hadoop01:8888/hue/security/hive#@roles","line":2,"column":12,"stack":"SyntaxError: Unexpected token ':'\n    at w (http://hadoop01:8888/static/desktop/js/bundles/hue/vendors~hue~notebook-bundle-41591f6ae86af9eaf574.57a1adf046f8.js:37:676)\n    at Function.globalEval (http://hadoop01:8888/static/desktop/js/bundles/hue/vendors~hue~notebook-bundle-41591f6ae86af9eaf574.57a1adf046f8.js:37:2584)\n    at text script (http://hadoop01:8888/static/desktop/js/bundles/hue/vendors~hue~notebook-bundle-41591f6ae86af9eaf574.57a1adf046f8.js:48:76954)\n    at http://hadoop01:8888/static/desktop/js/bundles/hue/vendors~hue~notebook-bundle-41591f6ae86af9eaf574.57a1adf046f8.js:48:73527\n    at C (http://hadoop01:8888/static/desktop/js/bundles/hue/vendors~hue~notebook-bundle-41591f6ae86af9eaf574.57a1adf046f8.js:48:73644)\n    at XMLHttpRequest.<anonymous> (http://hadoop01:8888/static/desktop/js/bundles/hue/vendors~hue~notebook-bundle-41591f6ae86af9eaf574.57a1adf046f8.js:48:76224)"}
[23/Feb/2020 17:42:24 -0800] exceptions_renderable ERROR    Potential detail: timed out (code THRIFTSOCKET): None
[23/Feb/2020 17:42:24 -0800] exceptions_renderable ERROR    Potential trace: [('/u01/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hue/desktop/libs/libsentry/src/libsentry/api.py', 41, 'decorator', 'return func(*args, **kwargs)'), ('/u01/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hue/desktop/libs/libsentry/src/libsentry/api.py', 111, 'create_sentry_role', 'response = self.client.create_sentry_role(roleName)'), ('/u01/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hue/desktop/libs/libsentry/src/libsentry/client.py', 100, 'create_sentry_role', 'return self.client.create_sentry_role(request)'), ('/u01/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hue/desktop/core/src/desktop/lib/thrift_util.py', 414, 'wrapper', "raise StructuredException('THRIFTSOCKET', str(e), data=None, error_code=502)")]
[23/Feb/2020 17:42:24 -0800] hive         ERROR    could not create role
Traceback (most recent call last):
  File "/u01/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hue/apps/security/src/security/api/hive.py", line 177, in create_role
    api.create_sentry_role(role['name'])
  File "/u01/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hue/desktop/libs/libsentry/src/libsentry/api.py", line 57, in decorator
    raise PopupException(_('Encountered unexpected error in SentryApi.'), detail=e)
PopupException: SentryApi 发生意外错误。

runcpserver.log

[23/Feb/2020 17:42:24 -0800] thrift_util  WARNING  Not retrying thrift call create_sentry_role due to socket timeout
[23/Feb/2020 17:42:24 -0800] thrift_util  INFO     Thrift saw a socket error: timed out
[23/Feb/2020 17:42:24 -0800] exceptions_renderable ERROR    Potential detail: timed out (code THRIFTSOCKET): None
[23/Feb/2020 17:42:24 -0800] exceptions_renderable ERROR    Potential trace: [('/u01/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hue/desktop/libs/libsentry/src/libsentry/api.py', 41, 'decorator', 'return func(*args, **kwargs)'), ('/u01/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hue/desktop/libs/libsentry/src/libsentry/api.py', 111, 'create_sentry_role', 'response = self.client.create_sentry_role(roleName)'), ('/u01/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hue/desktop/libs/libsentry/src/libsentry/client.py', 100, 'create_sentry_role', 'return self.client.create_sentry_role(request)'), ('/u01/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hue/desktop/core/src/desktop/lib/thrift_util.py', 414, 'wrapper', "raise StructuredException('THRIFTSOCKET', str(e), data=None, error_code=502)")]
[23/Feb/2020 17:42:24 -0800] hive         ERROR    could not create role
Traceback (most recent call last):
  File "/u01/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hue/apps/security/src/security/api/hive.py", line 177, in create_role
    api.create_sentry_role(role['name'])
  File "/u01/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hue/desktop/libs/libsentry/src/libsentry/api.py", line 57, in decorator
    raise PopupException(_('Encountered unexpected error in SentryApi.'), detail=e)
PopupException: SentryApi 发生意外错误。

**Comment by romainr** [comment]
"timed out --> the Sentry service is probably hanging or there is a wrong authentication
