### ISSUE TITLE
[Helm-GKE] - ProgrammingError: relation "desktop_settings" does not exist

### ISSUE THREAD

**Issue by RohitR1** [cloudera/hue#1052]
What is the Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...)
latest 

Is there a way to help reproduce it?
helm install gethue/hue

ProgrammingError in http://localhost:8080/hue/accounts/login?next=/

```bash
Traceback (most recent call last):
  File "/usr/share/hue/desktop/core/src/desktop/lib/wsgiserver.py", line 1228, in communicate
    req.respond()
  File "/usr/share/hue/desktop/core/src/desktop/lib/wsgiserver.py", line 589, in respond
    self._respond()
  File "/usr/share/hue/desktop/core/src/desktop/lib/wsgiserver.py", line 601, in _respond
    response = self.wsgi_app(self.environ, self.start_response)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/handlers/exception.py", line 143, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/usr/share/hue/desktop/core/src/desktop/views.py", line 429, in serve_500_error
    return render("500.mako", request, {'traceback': traceback.extract_tb(exc_info[2])})
  File "/usr/share/hue/desktop/core/src/desktop/lib/django_util.py", line 241, in render
    **kwargs
  File "/usr/share/hue/desktop/core/src/desktop/lib/django_util.py", line 154, in _render_to_response
    return django_mako.render_to_response(template, *args, **kwargs)
  File "/usr/share/hue/desktop/core/src/desktop/lib/django_mako.py", line 127, in render_to_response
    return HttpResponse(render_to_string(template_name, data_dictionary), **kwargs)
  File "/usr/share/hue/desktop/core/src/desktop/lib/django_mako.py", line 116, in render_to_string_normal
    result = template.render(**data_dict)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "/tmp/tmpvxXohF/desktop/500.mako.py", line 90, in render_body
    __M_writer(unicode( commonfooter(request, messages) ))
  File "/usr/share/hue/desktop/core/src/desktop/views.py", line 559, in commonfooter
    hue_settings = Settings.get_settings()
  File "/usr/share/hue/desktop/core/src/desktop/models.py", line 135, in get_settings
    settings, created = Settings.objects.get_or_create(id=1)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/db/models/query.py", line 464, in get_or_create
    return self.get(**lookup), False
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/db/models/query.py", line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
ProgrammingError: relation "desktop_settings" does not exist
LINE 1: ...e", "desktop_settings"."tours_and_tutorials" FROM "desktop_s...
                                                             ^
```

**Comment by romainr** [comment]
It seems like the Hue database does not contain the existing tables. They should be automatically created at startup via https://github.com/cloudera/hue/blob/master/tools/docker/hue/startup.sh

**Comment by rawipfel** [comment]
Hi, I've seen this too. It's a race between Hue's startup and the database backend if one Helm installs with `hue.database.create: true`. The following patch resolves the race. It forces Hue to wait until the database backend is ready to accept a connection. See also https://stackoverflow.com/questions/51079849/kubernetes-wait-for-other-pod-to-be-ready
```
diff --git a/tools/kubernetes/helm/hue/templates/deployment-hue.yaml b/tools/kubernetes/helm/hue/templates/deployment-hue.yaml
index 5921d6ce68..e115c9a512 100644
--- a/tools/kubernetes/helm/hue/templates/deployment-hue.yaml
+++ b/tools/kubernetes/helm/hue/templates/deployment-hue.yaml
@@ -24,6 +24,18 @@ spec:
 {{ toYaml . | indent 8 }}
 {{- end }}
     spec:
+      initContainers:
+        - name: hue-init
+          image: {{ .Values.image.registry }}/hue:{{ .Values.image.tag }}
+          imagePullPolicy: {{ .Values.image.pullPolicy }}
+          args:
+            - /bin/sh
+            - -c
+            - >
+              set -x;
+              while [ $(curl -s --connect-timeout 1 {{ .Values.hue.database.host }}:{{ .Values.hue.database.port }} || echo $?) -ne 52 ]; do
+                sleep 1;
+              done
       containers:
       - name: hue
         image: {{ .Values.image.registry }}/hue:{{ .Values.image.tag }}
```

**Comment by romainr** [comment]
Do you think if it works with other DBs, e.g. MySql for example?

Feel free to send a PR, this is a good improvement!

**Comment by rawipfel** [comment]
Thanks @romainr I'll send a PR. It should work with other DBs given parameterized `database.host` and `database.port` assuming they all return "(52) Empty reply from server" when ready.

**Comment by romainr** [comment]
Excellent, thanks!

And if not tested, maybe better to just {{ if add the initCoinainer fragment if the DB is mysql}}

**Comment by rawipfel** [comment]
Not sure about MySQL; I don't see any explicit support for that in the chart yaml. The problem occurs if creating a new PgSQL by setting `hue.database.create: true`. I did think about making the initContainer conditional upon that setting, but it's a good idea to anyway check the dependent DB is available at startup. So if that makes sense I'll send a PR for the patch as-is.

**Comment by romainr** [comment]
`P.S. Otoh, maybe you meant make the initContainer conditional upon hue.database.engine: "postgresql_psycopg2"?`

Yes! 

If we could wrap the new code in a if checking the engine is postgresql, we will be sure that we don't break the other DB and then it will be easy to add support and test the new ones in follow-up steps!

**Comment by rawipfel** [comment]
Cool, thanks: #1283

**Comment by rawipfel** [comment]
Thanks for the feedback so far, new PR: #1284
