### ISSUE TITLE
HUE 4.6 [Filebrowser] Create/Touch file in Cyrillic directory 

### ISSUE THREAD

**Issue by vkuryata** [cloudera/hue#1093]
Hello I use Hue™ 4.5.0 and Hue™ 4.6.0 

When I try create file in directory with Cyrillic patch (/hdfs/user/vkuryata/**тест**/file.txt)
I will find that file in other directory.

EGG.:
1) Create Cyrillic directory:
<img width="1102" alt="1" src="https://user-images.githubusercontent.com/63292820/78665443-7f2dc400-78de-11ea-9960-93fbfac68e17.png">

2) Create file "test.txt" in new directory with Cyrillic name 
<img width="1075" alt="2" src="https://user-images.githubusercontent.com/63292820/78665643-d0d64e80-78de-11ea-8ca6-32faa3fbe44a.png">

<img width="807" alt="3" src="https://user-images.githubusercontent.com/63292820/78665918-3e827a80-78df-11ea-9efd-e34605affb58.png">

> In step 2 hue make dir "/user /vkuryata / %C3%91%C2%82%C3%90%C2%B5%C3%91%C2%81%C3%91%C2%82/" (/ user/ vkuryata/ ÑÐµÑÑ) and put here file "test.txt"

<img width="1102" alt="4" src="https://user-images.githubusercontent.com/63292820/78666155-9c16c700-78df-11ea-9b11-93369b5a0c37.png">
<img width="1102" alt="5" src="https://user-images.githubusercontent.com/63292820/78666163-9e792100-78df-11ea-842a-c0c1bb277f2b.png">

**I got ERROR:**
`File "/usr/share/local/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/share/local/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/share/local/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/share/local/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/share/local/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/usr/share/local/hue/apps/filebrowser/src/filebrowser/views.py", line 213, in view
    stats = request.fs.stats(path)
  File "/usr/share/local/hue/desktop/core/src/desktop/lib/fs/proxyfs.py", line 148, in stats
    return self._get_fs(path).stats(path)
  File "/usr/share/local/hue/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py", line 314, in stats
    res = self._stats(path)
  File "/usr/share/local/hue/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py", line 303, in _stats
    json = self._root.get(path, params, headers)
  File "/usr/share/local/hue/desktop/core/src/desktop/lib/rest/resource.py", line 142, in get
    return self.invoke("GET", relpath, params, headers=headers, allow_redirects=True, clear_cookies=clear_cookies)
  File "/usr/share/local/hue/desktop/core/src/desktop/lib/rest/resource.py", line 87, in invoke
    log_response=log_response)
  File "/usr/share/local/hue/desktop/core/src/desktop/lib/rest/resource.py", line 124, in _invoke
    log_length and len(resp.content) > log_length and "..." or "" if resp else ""
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 79: ordinal not in range(128)`

**Comment by romainr** [comment]
There are two error here as the logging is erroring and hiding the initial HDFS message. This was fixed in master. 

There was some changes in master for better URL but it might still not work. 4.7 release should be out next week or we could try on master to confirm.

**Comment by vkuryata** [comment]
When I try Create new dir with Cyrillic name I got Error:

> [06/Apr/2020 17:34:30 +0300] exception    ERROR    Internal Server Error: /filebrowser/mkdir
Traceback (most recent call last):
  File "/usr/share/local/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/share/local/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/share/local/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/share/local/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/share/local/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/usr/share/local/hue/apps/filebrowser/src/filebrowser/views.py", line 1173, in mkdir
    return generic_op(MkDirForm, request, smart_mkdir, ["path", "name"], "path")
  File "/usr/share/local/hue/apps/filebrowser/src/filebrowser/views.py", line 1102, in generic_op
    op(*args)
  File "/usr/share/local/hue/apps/filebrowser/src/filebrowser/views.py", line 1171, in smart_mkdir
    request.fs.mkdir(request.fs.join(urllib_unquote(path), urllib_unquote(name)))
  File "/usr/share/local/hue/desktop/core/src/desktop/lib/fs/proxyfs.py", line 178, in mkdir
    return self._get_fs(path).mkdir(path, *args, **kwargs)
  File "/usr/share/local/hue/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py", line 458, in mkdir
    success = self._root.put(path, params, headers=headers)
  File "/usr/share/local/hue/desktop/core/src/desktop/lib/rest/resource.py", line 189, in put
    allow_redirects=allow_redirects, clear_cookies=clear_cookies)
  File "/usr/share/local/hue/desktop/core/src/desktop/lib/rest/resource.py", line 87, in invoke
    log_response=log_response)
  File "/usr/share/local/hue/desktop/core/src/desktop/lib/rest/resource.py", line 124, in _invoke
    log_length and len(resp.content) > log_length and "..." or "" if resp else ""
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 79: ordinal not in range(128)

**Comment by vkuryata** [comment]
if I modify: /usr/share/local/hue/apps/filebrowser/src/filebrowser/views.py and add sys.setdefaultencoding('utf8'),  I don't got any Error messages in error.log, but I can't create files in Cyrillic patch.
```
...
**vi /usr/share/local/hue/apps/filebrowser/src/filebrowser/views.py**
import sys  
reload(sys)  
sys.setdefaultencoding('utf8')
...
```

**Comment by romainr** [comment]
utf-8 is the default https://github.com/cloudera/hue/blob/master/desktop/conf/pseudo-distributed.ini.tmpl#L157

What is the trace of the new error?
