### ISSUE TITLE
HUE cannot access kerberized HDFS

### ISSUE THREAD

**Issue by eubnara** [cloudera/hue#1101]
## Describe the bug:

https://github.com/cloudera/hue/blob/faebb36a7b1b3f56e1871189c45359f4d6ac4e02/desktop/core/ext-py/kerberos-1.1.1/pysrc/kerberos.py#L102

https://github.com/cloudera/hue/blob/b99879b7a0faf5dc1492ad9fa102ec47510e6b02/desktop/core/ext-py/requests-kerberos-0.12.0/requests_kerberos/kerberos_.py#L219-L220

I think the error below is caused when `kerberos.authGSSClientInit()` is called in a wrong way.
It might be changed in this way:

```diff
- result, self.context[host_port_thread] = kerberos.authGSSClientInit(kerb_spn,
-     gssflags=gssflags, principal=self.principal)
+ result, self.context[host_port_thread] = kerberos.authGSSClientInit(kerb_spn,
+        gssflags=gssflags)
```

```
[16/Apr/2020 07:46:45 +0000] middleware   INFO     Processing exception: function takes at most 2 arguments (3 given): Traceback (most recent call last):
  File "/usr/share/hue/build/env/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/share/hue/build/env/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/usr/share/hue/apps/filebrowser/src/filebrowser/views.py", line 213, in view
    stats = request.fs.stats(path)
  File "/usr/share/hue/desktop/core/src/desktop/lib/fs/proxyfs.py", line 148, in stats
    return self._get_fs(path).stats(path)
  File "/usr/share/hue/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py", line 317, in stats
    res = self._stats(path)
  File "/usr/share/hue/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py", line 306, in _stats
    json = self._root.get(path, params, headers)
  File "/usr/share/hue/desktop/core/src/desktop/lib/rest/resource.py", line 157, in get
    return self.invoke("GET", relpath, params, headers=headers, allow_redirects=True, clear_cookies=clear_cookies)
  File "/usr/share/hue/desktop/core/src/desktop/lib/rest/resource.py", line 87, in invoke
    log_response=log_response
  File "/usr/share/hue/desktop/core/src/desktop/lib/rest/resource.py", line 114, in _invoke
    clear_cookies=clear_cookies
  File "/usr/share/hue/desktop/core/src/desktop/lib/rest/http_client.py", line 217, in execute
    resp = getattr(self._session, http_method.lower())(url, **request_kwargs)
  File "/usr/share/hue/build/env/lib/python2.7/site-packages/requests-2.23.0-py2.7.egg/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/share/hue/build/env/lib/python2.7/site-packages/requests-2.23.0-py2.7.egg/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/hue/build/env/lib/python2.7/site-packages/requests-2.23.0-py2.7.egg/requests/sessions.py", line 650, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/usr/share/hue/build/env/lib/python2.7/site-packages/requests-2.23.0-py2.7.egg/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/usr/share/hue/build/env/lib/python2.7/site-packages/requests_kerberos-0.12.0-py2.7.egg/requests_kerberos/kerberos_.py", line 432, in handle_response
    _r = self.handle_401(response, **kwargs)
  File "/usr/share/hue/build/env/lib/python2.7/site-packages/requests_kerberos-0.12.0-py2.7.egg/requests_kerberos/kerberos_.py", line 303, in handle_401
    _r = self.authenticate_user(response, **kwargs)
  File "/usr/share/hue/build/env/lib/python2.7/site-packages/requests_kerberos-0.12.0-py2.7.egg/requests_kerberos/kerberos_.py", line 278, in authenticate_user
    auth_header = self.generate_request_header(response, host)
  File "/usr/share/hue/build/env/lib/python2.7/site-packages/requests_kerberos-0.12.0-py2.7.egg/requests_kerberos/kerberos_.py", line 223, in generate_request_header
    gssflags=gssflags, principal=self.principal)
TypeError: function takes at most 2 arguments (3 given)
```

## Steps to reproduce it?

Using master branch source (20200416), compile and execute HUE and try to access kerberized HDFS.

## Hue version or source?

open source 4.6.0
System info: centos7, firefox

**Comment by ranade1** [comment]
Thanks for reporting. I will work on it.

**Comment by romainr** [comment]
Should be fixed with https://github.com/cloudera/hue/commit/812cd39fa490db91f56f7f5ffd2da7b20aa958d0

Thank you everybody!
