### ISSUE TITLE
Hiveserver2/beeswax TSocket read 0 bytes 

### ISSUE THREAD

**Issue by gary324** [cloudera/hue#1113]
I installed Hue 4.7.0 and HDP 3.1 using Ambari 2.4.7.

I have tried many days to connect to hive, but I couldn't solve it. Can anyone help me?
I guess it is authentication problem...... but I didn't any authentication methods.

![image](https://user-images.githubusercontent.com/42162514/80399972-0fb35f00-88f5-11ea-95c3-761de850730a.png)

Hear is Hue log:
[28/Apr/2020 01:48:55 +0000] dbms         DEBUG    Query via ini beeswax
[28/Apr/2020 01:48:55 +0000] dbms         DEBUG    Query Server: {'dialect': 'beeswax', 'has_session_pool': False, 'server_name': 'beeswax', 'transport_mode': 'socket', 'auth_username': 'hue', 'server_host': u'centos0.xis.edu', 'server_port': 10000, 'use_sasl': False, 'auth_password_used': False, 'http_url': u'http://centos0.xis.edu:10001/cliservice', 'max_number_of_sessions': 1, 'close_sessions': False, 'principal': None}
[28/Apr/2020 01:48:55 +0000] thrift_util  DEBUG    Thrift client <desktop.lib.thrift_util.ConnectionPooler object at 0x7f231eb458d0> got connection 49 after 0.00 seconds
[28/Apr/2020 01:48:55 +0000] hive_server2_lib INFO     Opening beeswax thrift session for user hue
[28/Apr/2020 01:48:55 +0000] thrift_util  DEBUG    Thrift client <desktop.lib.thrift_util.ConnectionPooler object at 0x7f231eb458d0> got connection 49 after 0.00 seconds
[28/Apr/2020 01:48:55 +0000] thrift_util  DEBUG    Thrift client <desktop.lib.thrift_util.ConnectionPooler object at 0x7f231eb458d0> got connection 49 after 0.00 seconds
[28/Apr/2020 01:48:55 +0000] thrift_util  DEBUG    Thrift call: <class 'TCLIService.TCLIService.Client'>.OpenSession(args=(TOpenSessionReq(username='hue', password=None, client_protocol=10, configuration={'hive.server2.proxy.user': u'hue'}),), kwargs={})
[28/Apr/2020 01:48:55 +0000] thrift_util  INFO     Thrift exception; retrying: TSocket read 0 bytes
[28/Apr/2020 01:48:55 +0000] thrift_util  DEBUG    Thrift call: <class 'TCLIService.TCLIService.Client'>.OpenSession(args=(TOpenSessionReq(username='hue', password=None, client_protocol=10, configuration={'hive.server2.proxy.user': u'hue'}),), kwargs={})
[28/Apr/2020 01:48:55 +0000] thrift_util  INFO     Thrift exception; retrying: TSocket read 0 bytes
[28/Apr/2020 01:48:55 +0000] thrift_util  DEBUG    Thrift call: <class 'TCLIService.TCLIService.Client'>.OpenSession(args=(TOpenSessionReq(username='hue', password=None, client_protocol=10, configuration={'hive.server2.proxy.user': u'hue'}),), kwargs={})
[28/Apr/2020 01:48:55 +0000] thrift_util  INFO     Thrift saw a transport exception: TSocket read 0 bytes

Hear is Hiveserver2 log:
2020-04-28T01:48:55,728 ERROR [HiveServer2-Handler-Pool: Thread-97]: server.TThreadPoolServer (:()) - Error occurred during processing of message.
java.lang.RuntimeException: org.apache.thrift.transport.TTransportException: Invalid status -128
	at org.apache.thrift.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:219) ~[hive-exec-3.1.0.3.1.0.0-78.jar:3.1.0.3.1.0.0-78]
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:269) ~[hive-exec-3.1.0.3.1.0.0-78.jar:3.1.0.3.1.0.0-78]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: org.apache.thrift.transport.TTransportException: Invalid status -128
	at org.apache.thrift.transport.TSaslTransport.sendAndThrowMessage(TSaslTransport.java:232) ~[hive-exec-3.1.0.3.1.0.0-78.jar:3.1.0.3.1.0.0-78]
	at org.apache.thrift.transport.TSaslTransport.receiveSaslMessage(TSaslTransport.java:184) ~[hive-exec-3.1.0.3.1.0.0-78.jar:3.1.0.3.1.0.0-78]
	at org.apache.thrift.transport.TSaslServerTransport.handleSaslStartMessage(TSaslServerTransport.java:125) ~[hive-exec-3.1.0.3.1.0.0-78.jar:3.1.0.3.1.0.0-78]
	at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:271) ~[hive-exec-3.1.0.3.1.0.0-78.jar:3.1.0.3.1.0.0-78]
	at org.apache.thrift.transport.TSaslServerTransport.open(TSaslServerTransport.java:41) ~[hive-exec-3.1.0.3.1.0.0-78.jar:3.1.0.3.1.0.0-78]
	at org.apache.thrift.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:216) ~[hive-exec-3.1.0.3.1.0.0-78.jar:3.1.0.3.1.0.0-78]
	... 4 more

**Comment by romainr** [comment]
Thanks for the report!

For non bugs, please use the Forum for more help: https://discourse.gethue.com/
