### ISSUE TITLE
Getting KeyError when checking Hive query status

### ISSUE THREAD

**Issue by jimistry123** [cloudera/hue#1122]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?

* No

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).

* open source 4.7, Chrome browser, Hue server running on Linux.

Describe the bug:

* In Hive editor, query status always transitions from ```Running``` to ```Query failed``` even if the underlying YARN job succeeded.

  Following error is seen inside the error.log file:

```
[24/Apr/2020 14:39:32 -0700] decorators   ERROR    Error running check_status
Traceback (most recent call last):
File "/usr/lib/hue/desktop/libs/notebook/src/notebook/decorators.py", line 114, in wrapper
 return f(*args, **kwargs)
File "/usr/lib/hue/desktop/libs/notebook/src/notebook/api.py", line 246, in check_status
 response = _check_status(request, notebook=notebook, snippet=snippet, operation_id=operation_id)
File "/usr/lib/hue/desktop/libs/notebook/src/notebook/api.py", line 260, in _check_status
 response['query_status'] = get_api(request, snippet).check_status(notebook, snippet)
File "/usr/lib/hue/desktop/libs/notebook/src/notebook/models.py", line 512, in get_api
 return ApiWrapper(request, snippet)
File "/usr/lib/hue/desktop/libs/notebook/src/notebook/models.py", line 498, in __init__
 self.api = _get_api(request, snippet)
File "/usr/lib/hue/desktop/libs/notebook/src/notebook/connectors/base.py", line 396, in get_api
 patch_snippet_for_connector(snippet)
File "/usr/lib/hue/desktop/libs/notebook/src/notebook/connectors/base.py", line 382, in patch_snippet_for_connector
 snippet['dialect'] = snippet['connector']['dialect']
KeyError: 'dialect'

```

Steps to reproduce it?

* In Hue 4.7.0, run any query from the Hive editor and observe the query status and one can see the query status showing ```Query failed```.

[This line of code](https://github.com/cloudera/hue/blob/release-4.7.0/desktop/libs/notebook/src/notebook/connectors/base.py#L382) is throwing the KeyError, which was added as part of [this commit](https://github.com/cloudera/hue/commit/fb2c7f0986006e2fe4469d6a9821b2ea3e93adb4). 

If ```get()``` method is used to fetch the ```dialect``` key then the issue seems to be resolved and the query status is displayed correctly. Like this:

```
snippet['dialect'] = snippet['connector'].get('dialect')
``` 

I would like to confirm if this is the correct way to fix this issue or am I missing something from my end?

**Comment by romainr** [comment]
IIRC it was fixed since (and could not repro on master) and we probably should do a 4.7.1 release so.

If not, probably safer to add an extra check, e.g:
https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/connectors/base.py#L392

`... and snippet['connector'].get('dialect'):`
