### ISSUE TITLE
FAIL: notebook.api_tests.TestNotebookApiMocked.test_export_result during `test fast`

### ISSUE THREAD

**Issue by sungpeo** [cloudera/hue#1152]
Describe the bug:
I try to run unit tests

``` sh
build/env/bin/hue test fast
```

But I got this error.
```
======================================================================
FAIL: notebook.api_tests.TestNotebookApiMocked.test_export_result
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/deploy/hadoopeng/hue/build/env/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/deploy/hadoopeng/hue/desktop/libs/notebook/src/notebook/api_tests.py", line 496, in test_export_result
    assert_equal('The destination is not a empty directory!', data['message'], data)
AssertionError: {u'status': -1, u'message': u'The destination is not an empty directory!'}

```
Steps to reproduce it?

``` sh
build/env/bin/hue test specific notebook.api_tests:TestNotebookApiMocked.test_export_result
```

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).

open source 4.7.0
CentOS Linux release 7.7.1908
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)

**Comment by sungpeo** [comment]
Sorry, I confused.
This issues was resolved by https://github.com/cloudera/hue/commit/c0c404f73239630dd56e3f3f862188e022eff90f I wrote
