### ISSUE TITLE
During `test all`, FAIL: metastore.tests.TestApi.test_show_tables

### ISSUE THREAD

**Issue by sungpeo** [cloudera/hue#1157]
**Describe the bug:**

During `./build/env/bin/hue test all`, `metastore.tests.TestApi.test_show_tables` fails like below.

```
======================================================================
FAIL: metastore.tests.TestApi.test_show_tables
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/deploy/hadoopeng/hue/build/env/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/deploy/hadoopeng/hue/apps/metastore/src/metastore/tests.py", line 96, in test_show_tables
    get.assert_called()
  File "/home/deploy/hadoopeng/hue/build/env/lib/python2.7/site-packages/mock-3.0.5-py2.7.egg/mock/mock.py", line 908, in assert_called
    raise AssertionError(msg)
AssertionError: Expected 'get' to have been called.
```

**Steps to reproduce it?**

``` sh
./build/env/bin/hue test all
```
These tests fails only during integration test.
Those succeed when it triggered by test specific

**Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).**

open source 4.7.0
CentOS Linux release 7.7.1908
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)

**Comment by sungpeo** [comment]
I debugged it.
The test user need to have permission to access the Metastore application.

```
Content-Length: 159
x-xss-protection: 1; mode=block
Content-Security-Policy: script-src 'self' 'unsafe-inline' 'unsafe-eval' *.google-analytics.com *.doubleclick.net data:;img-src 'self' *.google-analytics.com *.doubleclick.net http://*.tile.osm.org *.tile.osm.org *.gstatic.com data:;style-src 'self' 'unsafe-inline' fonts.googleapis.com;connect-src 'self';frame-src *;child-src 'self' data: *.vimeo.com;object-src 'none'
x-content-type-options: nosniff
Content-Language: en-us
Vary: Accept-Language, Cookie
X-Frame-Options: SAMEORIGIN
Content-Type: text/javascript

{
"message": "You do not have permission to access the Metastore application.",
"traceback": [],
"detail": null,
"is_embeddable": false,
"title": "Error"
}
```
