### ISSUE TITLE
During `test all`, FAIL: filebrowser.views_test.TestFileBrowserWithHadoop.test_extract_zip

### ISSUE THREAD

**Issue by sungpeo** [cloudera/hue#1159]
**Describe the bug:**

`filebrowser.views_test.TestFileBrowserWithHadoop.test_extract_zip` fails.

``` sh
./build/env/bin/hue test all
```

```
======================================================================
FAIL: filebrowser.views_test.TestFileBrowserWithHadoop.test_extract_zip
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/deploy/hadoopeng/hue/build/env/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/deploy/hadoopeng/hue/apps/filebrowser/src/filebrowser/views_test.py", line 1125, in test_extract_zip
    assert_equal(0, response['status'], response)
AssertionError: {u'status': -1, u'message': u"Exception occurred while extracting archive: Error submitting workflow Batch for HDFS Extraction of /tmp/hue_tests_1591458574.68/test_upload_zip/tmp/fb-upload-test/te st.zip: The Oozie server is not running: HTTPConnectionPool(host='infra-hadoop-build1.dakao.io', port=18001): Max retries exceeded with url: /oozie/v1/jobs?timezone=America%2FLos_Angeles&user.name=hue&doAs=test (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbb3293f7d0>: Failed to establish a new connection: [Errno 111] Connection refused',))", u'data': u''}

```

**Steps to reproduce it?**

mentioned above
``` sh
./build/env/bin/hue test all
```

**Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).**

open source 4.7.0
CentOS Linux release 7.7.1908
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)

**Comment by sungpeo** [comment]
Sorry, it was the reason why I configured wrong. (hadoop-2.10)
