### ISSUE TITLE
During `test all`, FAIL: desktop.auth.views_test.TestLoginWithHadoop.test_login

### ISSUE THREAD

**Issue by sungpeo** [cloudera/hue#1163]
**Describe the bug:**

`desktop.auth.views_test.TestLoginWithHadoop.test_login` fails.

``` sh
./build/env/bin/hue test all
```

```
======================================================================
FAIL: desktop.auth.views_test.TestLoginWithHadoop.test_login
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/deploy/hadoopeng/hue/build/env/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/deploy/hadoopeng/hue/desktop/core/src/desktop/auth/views_test.py", line 86, in test_login
    assert_true(self.cluster.fs.do_as_user(self.test_username, self.fs.exists, "/user/%s" % self.test_username))
AssertionError: False is not true
-------------------- >> begin captured logging << --------------------
desktop.middleware: INFO: Unloading AuditLoggingMiddleware
desktop.middleware: INFO: Unloading ProxyMiddleware
desktop.middleware: INFO: Unloading SpnegoMiddleware
desktop.middleware: INFO: Unloading HueRemoteUserMiddleware
desktop.middleware: INFO: Unloading MimeTypeJSFileFixStreamingMiddleware
access: DEBUG: 127.0.0.1 -anon- - "GET /hue/accounts/login/ HTTP/1.1" - (mem: 4077mb)
axes.watch_login: INFO: AXES: Calling decorated function: dt_login
access: INFO: 127.0.0.1 -anon- - "GET /hue/accounts/login/ HTTP/1.1" returned in 23ms 200 114894 (mem: 4077mb)
access: DEBUG: 127.0.0.1 -anon- - "POST /hue/accounts/login/ HTTP/1.1" - (mem: 4077mb)
axes.watch_login: INFO: AXES: Calling decorated function: dt_login
hadoop.fs.upload: DEBUG: Chunk size = 67108864
desktop.auth.backend: INFO: User test_login_with_hadoop was created.
useradmin.views: WARNING: Not creating home directory of test_login_with_hadoop as no file system connector is configured
access: WARNING: 127.0.0.1 test_login_with_hadoop - "POST /hue/accounts/login/ HTTP/1.1" - (mem: 4077mb)-- Successful login for user: test_login_with_hadoop
access: INFO: 127.0.0.1 test_login_with_hadoop - "POST /hue/accounts/login/ HTTP/1.1" returned in 159ms 302 0 (mem: 4077mb)
desktop.lib.rest.resource: ERROR: Error logging return call GET http://infra-hadoop-build1.dakao.io:33161/webhdfs/v1
Traceback (most recent call last):
  File "/home/deploy/hadoopeng/hue/desktop/core/src/desktop/lib/rest/resource.py", line 122, in _invoke
    resp_content = smart_unicode(resp.content, errors='replace')
AttributeError: 'NoneType' object has no attribute 'content'
root: DEBUG: GET http://infra-hadoop-build1.dakao.io:33161/webhdfs/v1 returned in 0ms
--------------------- >> end captured logging << ---------------------

```

**Steps to reproduce it?**

``` sh
./build/env/bin/hue test specific desktop.auth.views_test:TestLoginWithHadoop.test_login
```

**Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).**

open source 4.7.0
CentOS Linux release 7.7.1908
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)

**Comment by sungpeo** [comment]
Thank you for noticing me the commit. (I cherry picked the commit, and no more error logs)
The reason of the fail is `Not creating home directory`.
```
desktop.middleware: INFO: Unloading AuditLoggingMiddleware
desktop.middleware: INFO: Unloading ProxyMiddleware
desktop.middleware: INFO: Unloading SpnegoMiddleware
desktop.middleware: INFO: Unloading HueRemoteUserMiddleware
desktop.middleware: INFO: Unloading MimeTypeJSFileFixStreamingMiddleware
parquet: INFO: Couldn't import snappy. Support for snappy compression disabled.
access: DEBUG: 127.0.0.1 -anon- - "GET /hue/accounts/login/ HTTP/1.1" - (mem: 142mb)
axes.watch_login: INFO: AXES: Calling decorated function: dt_login
access: INFO: 127.0.0.1 -anon- - "GET /hue/accounts/login/ HTTP/1.1" returned in 1325ms 200 114894 (mem: 148mb)
access: DEBUG: 127.0.0.1 -anon- - "POST /hue/accounts/login/ HTTP/1.1" - (mem: 148mb)
axes.watch_login: INFO: AXES: Calling decorated function: dt_login
hadoop.fs.webhdfs: DEBUG: Initializing Hadoop WebHdfs: http://infra-hadoop-build1.dakao.io:36712/webhdfs/v1 (security: False, superuser: None)
hadoop.fs.upload: DEBUG: Chunk size = 67108864
desktop.auth.backend: INFO: User test_login_with_hadoop was created.
desktop.auth.backend: INFO: Augmenting users with class: <class 'desktop.auth.backend.DefaultUserAugmentor'>
useradmin.views: WARNING: Not creating home directory of test_login_with_hadoop as no file system connector is configured
access: WARNING: 127.0.0.1 test_login_with_hadoop - "POST /hue/accounts/login/ HTTP/1.1" - (mem: 148mb)-- Successful login for user: test_login_with_hadoop
access: INFO: 127.0.0.1 test_login_with_hadoop - "POST /hue/accounts/login/ HTTP/1.1" returned in 166ms 302 0 (mem: 148mb)
root: DEBUG: GET None http://infra-hadoop-build1.dakao.io:36712/webhdfs/v1//user/test_login_with_hadoop?op=GETFILESTATUS&user.name=hue&doas=test_login_with_hadoop  returned in 8ms 0 0
```

**Comment by romainr** [comment]
We would so need to trobuleshoot back up why `def ensure_home_directory(fs, user):` is getting None for the fs argument

**Comment by sungpeo** [comment]
Yes, I coundn't find it.
so I wanted to know a way to set the `fs` to the request? `request.fs`

**Comment by romainr** [comment]
Yes, it is called with `request.fs`, which should be set via the middeware:
https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/middleware.py#L133

Maybe adding more debug info there?
