### ISSUE TITLE
HUE 4.4 'ascii' codec can't encode characters in position

### ISSUE THREAD

**Issue by tulingfeng** [cloudera/hue#1187]
Hello, I want to access hdfs file by hue，but when I click the file,the error appeared:
```text
 Processing exception: 'ascii' codec can't encode characters in position 5952-6026: ordinal not in range(128): Traceback (most recent call last):
  File "/clouddragonData/hue-master/build/env/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/core/handlers/base.py", line 188, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/clouddragonData/hue-master/build/env/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/clouddragonData/hue-master/apps/filebrowser/src/filebrowser/views.py", line 232, in view
    if "Connection refused" in str(e):
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5952-6026: ordinal not in range(128)
```
Someone suggested me to fix python2.7 sys encoding,I did it by touch sitecustomize.py in /usr/lib/python2.7/site-packages folder,But this time another error appeared:
```text
ERROR    Potential detail: 403 Client Error: Proxy_WarningPage for url: http://www.internalrequests.org/showconfirmpage/?url=http://szvphispra13849:50075/webhdfs/v1/input/sample.txt?op=OPEN&doas=hue&user.name=hue&namenoderpcaddress=szvphispra13844:9000&length=3&offset=0
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
...
lots of js
...
 ERROR    Potential trace: [('/clouddragonData/hue-master/apps/filebrowser/src/filebrowser/views.py', 219, 'view', 'return display(request, path)'), ('/clouddragonData/hue-master/apps/filebrowser/src/filebrowser/views.py', 693, 'display', 'compression, offset, length, contents = read_contents(compression, path, request.fs, offset, length)'), ('/clouddragonData/hue-master/apps/filebrowser/src/filebrowser/views.py', 771, 'read_contents', 'contents = fhandle.read(3)'), ('/clouddragonData/hue-master/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py', 995, 'read', 'data = self._fs.read(self._path, self._pos, length)'), ('/clouddragonData/hue-master/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py', 595, 'read', 'raise ex')]
[19/Jun/2020 10:25:20 +0000] middleware   INFO     Processing exception: Cannot access: /input/sample.txt. : Traceback (most recent call last):
  File "/clouddragonData/hue-master/build/env/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/core/handlers/base.py", line 188, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/clouddragonData/hue-master/build/env/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/clouddragonData/hue-master/apps/filebrowser/src/filebrowser/views.py", line 241, in view
    raise PopupException(msg , detail=e)
PopupException: Cannot access: /input/sample.txt.
```
My Hdfs config is as follows:
```text
[hadoop]
  [[hdfs_clusters]]
    [[[default]]]
      # Enter the filesystem uri
      fs_defaultfs=hdfs://hadoop1:8020
      webhdfs_url=http://hadoop1/webhdfs/v1
      hadoop_conf_dir=${HADOOP_HOME}/etc/hadoop
```

How could I fix this?

**Comment by romainr** [comment]
What are your Hue and Python versions?

**Comment by romainr** [comment]
2.7 amd git clone of master?

Hum, second error is not very clear. Can you browse other parts of the file system without problems?

**Comment by tulingfeng** [comment]
> What are your Hue and Python versions?

Hello,I download the master hue zip to make，what's version is it? My python version is 2.7.15

**Comment by tulingfeng** [comment]
> 2.7 amd git clone of master?
> Hum, second error is not very clear. Can you browse other parts of the file system without problems?
I can browser folders of hdfs but cannot click textfile to view its content.In addition， I can view hive table content

**Comment by tulingfeng** [comment]
> 2.7 amd git clone of master?
> 
> Hum, second error is not very clear. Can you browse other parts of the file system without problems?

I can browser folders of hdfs but cannot click textfile to view its content.In addition, I can view hive table content

**Comment by tulingfeng** [comment]
> 2.7 amd git clone of master?
> 
> Hum, second error is not very clear. Can you browse other parts of the file system without problems?

hello，I found the error may: cannot access the hdfs file，I logger the message:
```text
[20/Jun/2020 10:39:26 +0000] resource     DEBUG    GET None http://ip:50070/webhdfs/v1//test/test.txt?length=3&op=OPEN&user.name=hue&offset=0&doas=hue  returned in 151ms 0 0
[20/Jun/2020 10:39:26 +0000] views        INFO     msg: Cannot access: /test/test.txt.
```
I doubt whether my name is hue but hdfs user is dev? how could I fix it?
