### ISSUE TITLE
KSQLDB Query Error Message "list indices must be integers, not str"

### ISSUE THREAD

**Issue by Faiz2** [cloudera/hue#1198]
Sorry i don't have good english

**I am using k8s to deploy hue, configured KSQLDB, and encountered error feedback during query.
I am clueless and need help
I configured according to the official document, this is the link**:[https://docs.gethue.com/administrator/configuration/connectors/#ksqldb](https://docs.gethue.com/administrator/configuration/connectors/#ksqldb)
**This is the configuration of my hue.ini**:
![image](https://user-images.githubusercontent.com/18616592/86213884-f658b880-bbac-11ea-9e58-74541a4dbaea.png)
![image](https://user-images.githubusercontent.com/18616592/86213961-18ead180-bbad-11ea-9afc-871990a3ccd5.png)
**Below is the result of my running**:
![image](https://user-images.githubusercontent.com/18616592/86214070-3fa90800-bbad-11ea-9bd0-aee7dcf5450d.png)

**Comment by romainr** [comment]
There should be a trace in the Hue logs with more info.

Will have a more specific look next week

**Comment by Faiz2** [comment]
@romainr 
**exectue ksql log info**

![image](https://user-images.githubusercontent.com/18616592/86318017-73466980-bc63-11ea-9cd7-c7e5507dad82.png)

[02/Jul/2020 12:41:12 +0800] access       INFO     142.11.215.210 alex - "POST /desktop/log_analytics HTTP/1.1" - (mem: 1196mb)-- PAGE: editor/showLongOperationWarning
[02/Jul/2020 12:41:12 +0800] access       INFO     142.11.215.210 alex - "POST /desktop/log_analytics HTTP/1.1" - (mem: 1196mb)-- PAGE: editor/showLongOperationWarning
[{u'tables': [{u'topic': u'oss_msg', u'isWindowed': False, u'type': u'TABLE', u'name': u'MSG_TABLE', u'format': u'AVRO'}], u'warnings': [], u'@type': u'tables', u'statementText': u'show tables;'}]
[02/Jul/2020 12:41:12 +0800] decorators   ERROR    Error running execute
Traceback (most recent call last):
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/decorators.py", line 114, in wrapper
    return f(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/api.py", line 222, in execute
    response = _execute_notebook(request, notebook, snippet)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/api.py", line 200, in _execute_notebook
    raise ex
QueryError: list indices must be integers, not str
[02/Jul/2020 12:41:12 +0800] access       INFO     142.11.215.210 alex - "POST /desktop/log_analytics HTTP/1.1" returned in 807ms 200 13 (mem: 1203mb)
[02/Jul/2020 12:41:12 +0800] access       INFO     142.11.215.210 alex - "POST /desktop/log_analytics HTTP/1.1" returned in 807ms 200 13 (mem: 1203mb)
[02/Jul/2020 12:41:12 +0800] access       INFO     142.11.215.210 alex - "POST /notebook/api/close_statement HTTP/1.1" returned in 3187ms 200 57 (mem: 1204mb)
[02/Jul/2020 12:41:12 +0800] access       INFO     142.11.215.210 alex - "POST /notebook/api/close_statement HTTP/1.1" returned in 3187ms 200 57 (mem: 1204mb)
[02/Jul/2020 12:41:13 +0800] access       INFO     142.11.215.210 alex - "POST /notebook/api/execute/ksql HTTP/1.1" returned in 2424ms 200 66 (mem: 1205mb)
[02/Jul/2020 12:41:13 +0800] access       INFO     142.11.215.210 alex - "POST /notebook/api/execute/ksql HTTP/1.1" returned in 2424ms 200 66 (mem: 1205mb)

![image](https://user-images.githubusercontent.com/18616592/86317985-5e69d600-bc63-11ea-9cfb-0abfa66c198c.png)

[02/Jul/2020 12:54:41 +0800] access       INFO     221.219.246.98 admin - "POST /notebook/api/close_statement HTTP/1.1" returned in 243ms 200 57 (mem: 302mb)
[02/Jul/2020 12:54:41 +0800] access       INFO     221.219.246.98 admin - "POST /notebook/api/close_statement HTTP/1.1" returned in 243ms 200 57 (mem: 302mb)
[02/Jul/2020 12:54:41 +0800] decorators   ERROR    Error running execute
Traceback (most recent call last):
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/decorators.py", line 114, in wrapper
    return f(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/api.py", line 222, in execute
    response = _execute_notebook(request, notebook, snippet)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/api.py", line 200, in _execute_notebook
    raise ex
QueryError: No JSON object could be decoded
[02/Jul/2020 12:54:41 +0800] access       INFO     221.219.246.98 admin - "POST /notebook/api/execute/ksql HTTP/1.1" returned in 446ms 200 59 (mem: 304mb)
[02/Jul/2020 12:54:41 +0800] access       INFO     221.219.246.98 admin - "POST /notebook/api/execute/ksql HTTP/1.1" returned in 446ms 200 59 (mem: 304mb)

It seems to be executed but I don’t know why it went wrong,This is the log printed by the console

**Comment by romainr** [comment]
How about?

`SELECT * FROM MY_STREAM EMIT CHANGES LIMIT 3;`

`SHOW STREAMS`

**Comment by Faiz2** [comment]
@romainr
No change, the error is the same as the log I provided last time
`SHOW STREAMS`
![image](https://user-images.githubusercontent.com/18616592/87775868-5f048e00-c859-11ea-88a7-14014bcaeeca.png)

> 

`SELECT * FROM MY_STREAM EMIT CHANGES LIMIT 3`
![image](https://user-images.githubusercontent.com/18616592/87775944-7ba0c600-c859-11ea-8cf1-14dbb2957e8b.png)

**Comment by romainr** [comment]
Could you use with a real stream table that gets live data if you do a live query, e.g. `pageviews_original`

`SELECT pageid FROM pageviews_original EMIT CHANGES LIMIT 3;`
