### ISSUE TITLE
Demo sql parser app in tools directory is not compiling

### ISSUE THREAD

**Issue by SachinJanani** [cloudera/hue#1212]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?

Describe the bug:
* Compilation of demo app for sql parser in tools directory is failing
Throws following error:

`ERROR in /root/sachin/test_parsers1/hue/desktop/core/src/desktop/js/sql/reference/typeUtils.ts
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /root/sachin/test_parsers1/hue/desktop/core/src/desktop/js/sql/reference/typeUtils.ts: Unexpected token, expected "," (22:29)

  20 | import { TYPE_CONVERSION as GENERIC_TYPE_CONVERSION } from './generic/typeConversion';
  21 | 
> 22 | const stripPrecision = (types: string[]): string[] => {
     |                              ^
  23 |   const result: string[] = [];
  24 |   types.forEach(type => {
  25 |     if (type.indexOf('(') > -1) {
    at Parser._raise (/root/sachin/test_parsers1/hue/tools/parser/hue_dep/node_modules/@babel/parser/lib/index.js:757:17)
    at Parser.raiseWithData (/root/sachin/test_parsers1/hue/tools/parser/hue_dep/node_modules/@babel/parser/lib/index.js:750:17)
    at Parser.raise (/root/sachin/test_parsers1/hue/tools/parser/hue_dep/node_modules/@babel/parser/lib/index.js:744:17)
    at Parser.unexpected (/root/sachin/test_parsers1/hue/tools/parser/hue_dep/node_modules/@babel/parser/lib/index.js:8834:16)
    at Parser.expect (/root/sachin/test_parsers1/hue/tools/parser/hue_dep/node_modules/@babel/parser/lib/index.js:8820:28)
    at Parser.parseParenAndDistinguishExpression (/root/sachin/test_parsers1/hue/tools/parser/hue_dep/node_modules/@babel/parser/lib/index.js:10297:14)
    at Parser.parseExprAtom (/root/sachin/test_parsers1/hue/tools/parser/hue_dep/node_modules/@babel/parser/lib/index.js:10042:21)
    at Parser.parseExprSubscripts (/root/sachin/test_parsers1/hue/tools/parser/hue_dep/node_modules/@babel/parser/lib/index.js:9688:23)
    at Parser.parseMaybeUnary (/root/sachin/test_parsers1/hue/tools/parser/hue_dep/node_modules/@babel/parser/lib/index.js:9668:21)
    at Parser.parseExprOps (/root/sachin/test_parsers1/hue/tools/parser/hue_dep/node_modules/@babel/parser/lib/index.js:9538:23)
    at Parser.parseMaybeConditional (/root/sachin/test_parsers1/hue/tools/parser/hue_dep/node_modules/@babel/parser/lib/index.js:9511:23)
    at Parser.parseMaybeAssign (/root/sachin/test_parsers1/hue/tools/parser/hue_dep/node_modules/@babel/parser/lib/index.js:9466:21)
    at Parser.parseVar (/root/sachin/test_parsers1/hue/tools/parser/hue_dep/node_modules/@babel/parser/lib/index.js:11869:26)
    at Parser.parseVarStatement (/root/sachin/test_parsers1/hue/tools/parser/hue_dep/node_modules/@babel/parser/lib/index.js:11678:10)
    at Parser.parseStatementContent (/root/sachin/test_parsers1/hue/tools/parser/hue_dep/node_modules/@babel/parser/lib/index.js:11277:21)
    at Parser.parseStatement (/root/sachin/test_parsers1/hue/tools/parser/hue_dep/node_modules/@babel/parser/lib/index.js:11210:17)
    at Parser.parseBlockOrModuleBlockBody (/root/sachin/test_parsers1/hue/tools/parser/hue_dep/node_modules/@babel/parser/lib/index.js:11785:25)
    at Parser.parseBlockBody (/root/sachin/test_parsers1/hue/tools/parser/hue_dep/node_modules/@babel/parser/lib/index.js:11771:10)
    at Parser.parseTopLevel (/root/sachin/test_parsers1/hue/tools/parser/hue_dep/node_modules/@babel/parser/lib/index.js:11141:10)
    at Parser.parse (/root/sachin/test_parsers1/hue/tools/parser/hue_dep/node_modules/@babel/parser/lib/index.js:12843:10)
    at parse (/root/sachin/test_parsers1/hue/tools/parser/hue_dep/node_modules/@babel/parser/lib/index.js:12896:38)
    at parser (/root/sachin/test_parsers1/hue/tools/parser/hue_dep/node_modules/@babel/core/lib/parser/index.js:54:34)
    at parser.next (<anonymous>)
    at normalizeFile (/root/sachin/test_parsers1/hue/tools/parser/hue_dep/node_modules/@babel/core/lib/transformation/normalize-file.js:93:38)
    at normalizeFile.next (<anonymous>)
    at run (/root/sachin/test_parsers1/hue/tools/parser/hue_dep/node_modules/@babel/core/lib/transformation/index.js:31:50)
    at run.next (<anonymous>)
    at Function.transform (/root/sachin/test_parsers1/hue/tools/parser/hue_dep/node_modules/@babel/core/lib/transform.js:27:41)
    at transform.next (<anonymous>)
    at step (/root/sachin/test_parsers1/hue/tools/parser/hue_dep/node_modules/gensync/index.js:254:32)
 @ /root/sachin/test_parsers1/hue/desktop/core/src/desktop/js/parse/sql/hive/sqlParseSupport.js 17:0-54 176:8-19 180:8-19 184:8-19
 @ /root/sachin/test_parsers1/hue/desktop/core/src/desktop/js/parse/sql/hive/hiveAutocompleteParser.js`
Steps to reproduce it?
* switch to directory hue/tools/parser/hue_dep
* run npm install; npm run webpack

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).

**Comment by romainr** [comment]
Adding links with references:
https://docs.gethue.com/developer/api/#npm-package
https://github.com/cloudera/hue/tree/master/tools/parser/hue_dep

@sreenaths, maybe related to the recent changes?

**Comment by SachinJanani** [comment]
@romainr thanks for sharing this links. I followed the same document but it didn't worked.

**Comment by romainr** [comment]
Yes it is broken, maybe in the meantime, if you are just looking at reusing the parser as is, you could point to the published one?

e.g. remove the local dependency:

```
git diff
diff --git a/tools/parser/hue_dep/package.json b/tools/parser/hue_dep/package.json
index 59d66eeb8f..82ab41ac9a 100644
--- a/tools/parser/hue_dep/package.json
+++ b/tools/parser/hue_dep/package.json
@@ -11,7 +11,6 @@
   "author": "Queso",
   "license": "ISC",
   "dependencies": {
-    "hue": "file:../../.."
   },
   "devDependencies": {
     "@babel/cli": "^7.2.3",

```

and 

`npm install gethue`

**Comment by SachinJanani** [comment]
Thanks @romainr will try this out.

**Comment by SachinJanani** [comment]
I tried and it works fine with some modification in app code. Thanks @romainr
