### ISSUE TITLE
TypeError: parser.addFunctionArgumentLocations is not a function when using Syntax parser to parse sql query with UDF

### ISSUE THREAD

**Issue by sachinunravel** [cloudera/hue#1227]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com? No

Describe the bug:
When running a syntax parser test which parse sql queries with UDF it shows following error. This error can only be seen if **debug logs are enabled** and it definetly stopping the syntax parsing of that query. 

`TypeError: parser.addFunctionArgumentLocations is not a function
        at Object.apply (/root/sachin/hue/desktop/core/src/desktop/js/parse/sql/hive/hiveSyntaxParser.js:3254:13)
        at Object.parse (/root/sachin/hue/desktop/core/src/desktop/js/parse/sql/hive/hiveSyntaxParser.js:4970:40)
        at Parser.parseSyntax (/root/sachin/hue/desktop/core/src/desktop/js/parse/sql/sqlParseUtils.js:763:14)
        at Object.<anonymous> (/root/sachin/hue/desktop/core/src/desktop/js/parse/sql/hive/test/hiveSyntaxParser.test.js:29:38)
        at Object.asyncJestTest (/root/sachin/hue/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:100:37)
        at resolve (/root/sachin/hue/node_modules/jest-jasmine2/build/queueRunner.js:47:12)
        at new Promise (<anonymous>)
        at mapper (/root/sachin/hue/node_modules/jest-jasmine2/build/queueRunner.js:30:19)
        at promise.then (/root/sachin/hue/node_modules/jest-jasmine2/build/queueRunner.js:77:41)
`

Steps to reproduce it?
- Add a test for parsing syntax of a query with UDF and enable debug logs. This issue is seen with hive and impala parser

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).

**Comment by sachinunravel** [comment]
This issue is fixed if we add **addFunctionArgumentLocations** function name in constants array **SYNTAX_PARSER_NOOP_FUNCTIONS** in sqlParseUtils. But then it fails ahead with the following exception:

`TypeError: Cannot read property 'first_line' of undefined
        at Object.apply (/root/sachin/hue/desktop/core/src/desktop/js/parse/sql/hive/hiveSyntaxParser.js:3258:46)
        at Object.parse (/root/sachin/hue/desktop/core/src/desktop/js/parse/sql/hive/hiveSyntaxParser.js:4970:40)
        at Parser.parseSyntax (/root/sachin/hue/desktop/core/src/desktop/js/parse/sql/sqlParseUtils.js:764:14)
        at Object.<anonymous> (/root/sachin/hue/desktop/core/src/desktop/js/parse/sql/hive/test/hiveSyntaxParser.test.js:29:38)
        at Object.asyncJestTest (/root/sachin/hue/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:100:37)
        at resolve (/root/sachin/hue/node_modules/jest-jasmine2/build/queueRunner.js:47:12)
        at new Promise (<anonymous>)
        at mapper (/root/sachin/hue/node_modules/jest-jasmine2/build/queueRunner.js:30:19)
        at promise.then (/root/sachin/hue/node_modules/jest-jasmine2/build/queueRunner.js:77:41)
        at process._tickCallback (internal/process/next_tick.js:68:7)
`

**Comment by JohanAhlen** [comment]
Thanks for reporting this! It's indeed a recently introduced bug, I'll take a look.

**Comment by JohanAhlen** [comment]
Fixed with 8ba5f91a66d34b371a3f805677980f70c1b19349

**Comment by sachinunravel** [comment]
Thanks @JohanAhlen
