### ISSUE TITLE
Presto SQLAlchemy Interface over Https fails to connect to the server

### ISSUE THREAD

**Issue by DRavikanth** [cloudera/hue#1246]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?

Describe the bug: For SSL enabled Presto Cluster Hue's SQLAlchemy interface fails to connect.

Steps to reproduce it? 
Our Presto cluster is SSL LDAP enabled, so configured it like below in Notebook section:

Case-1:
[[[presto]]]
interface=sqlalchemy
name=Presto
options=’{“url”: “presto://user:password@presto-corrdinator:8443/hive/dwh”}’
In the above case, below is the exception in hue logs:

(exceptions.ValueError) Protocol must be https when passing a password [SQL: SHOW SCHEMAS]
Case-2:
[[[presto]]]
interface=sqlalchemy
name=Presto
options=’{“url”: “presto://username:password@https://presto coordinator:8443/hive/dwh”}’

In this case, following is the error:

ValueError: invalid literal for int() with base 10: ‘’
[14/Aug/2020 10:59:28 -0700] decorators ERROR Error running autocomplete
Traceback (most recent call last):
File “/usr/share/hue/desktop/libs/notebook/src/notebook/decorators.py”, line 114, in wrapper
return f(*args, **kwargs)
File “/usr/share/hue/desktop/libs/notebook/src/notebook/api.py”, line 729, in autocomplete
autocomplete_data = get_api(request, snippet).autocomplete(snippet, database, table, column, nested)
File “/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py”, line 113, in decorator
raise QueryError(message)
QueryError: invalid literal for int() with base 10: ‘’

Hue version or source? Docker image of hue 4.7.1 deployed in Kubernetes

**Comment by romainr** [comment]
It should also need `'auth': 'LDAP'` in the options

**Comment by DRavikanth** [comment]
OK. Added the suggested option and now my notebook is like below:
`
[[[presto]]]
          interface=sqlalchemy
          name=Presto
          options='{"url": "presto://user:pwd@https://presto-coordinator:8443/hive/dwh", "auth":"LDAP"}'
`

But, I get the same error:
`
[15/Aug/2020 09:21:45 -0700] sql_alchemy  ERROR    Query Error
Traceback (most recent call last):
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 98, in decorator
    return func(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 332, in autocomplete
    engine = self._get_engine()
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 135, in _get_engine
    ENGINES[engine_key] = self._create_engine()
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 187, in _create_engine
    return create_engine(url, **options)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/SQLAlchemy-1.3.16-py2.7-linux-x86_64.egg/sqlalchemy/engine/_
_init__.py", line 479, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/SQLAlchemy-1.3.16-py2.7-linux-x86_64.egg/sqlalchemy/engine/s
trategies.py", line 54, in create
    u = url.make_url(name_or_url)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/SQLAlchemy-1.3.16-py2.7-linux-x86_64.egg/sqlalchemy/engine/u
rl.py", line 229, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/SQLAlchemy-1.3.16-py2.7-linux-x86_64.egg/sqlalchemy/engine/u
rl.py", line 288, in _parse_rfc1738_args
    return URL(name, **components)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/SQLAlchemy-1.3.16-py2.7-linux-x86_64.egg/sqlalchemy/engine/u
rl.py", line 71, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: ''
[15/Aug/2020 09:21:45 -0700] decorators   ERROR    Error running autocomplete
Traceback (most recent call last):
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/decorators.py", line 114, in wrapper
    return f(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/api.py", line 729, in autocomplete
    autocomplete_data = get_api(request, snippet).autocomplete(snippet, database, table, column, nested)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 113, in decorator
    raise QueryError(message)
QueryError: invalid literal for int() with base 10: ''
`

**Comment by romainr** [comment]
`https://` seems to conflict here, it should be an hostname

**Comment by DRavikanth** [comment]
**Tried below:**
> [notebook]
      [[interpreters]]
        [[[presto]]]
          interface=sqlalchemy
          name=Presto
          options='{"url": "presto://user:password@presto-coordinator(without https):8443/hive/dwh", "auth": "LDAP"}'

**New exception:**
> ser-chunk-6764c3a506aefe553cbc.d0f154b71c44.js HTTP/1.1" returned in 1ms 200 -
[15/Aug/2020 12:20:02 -0700] sql_alchemy  ERROR    Query Error
Traceback (most recent call last):
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 98, in decorator
    return func(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 332, in autocomplete
    engine = self._get_engine()
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 135, in _get_engine
    ENGINES[engine_key] = self._create_engine()
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 187, in _create_engine
    return create_engine(url, **options)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/SQLAlchemy-1.3.16-py2.7-linux-x86_64.egg/sqlalchemy/engine/_
_init__.py", line 479, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/SQLAlchemy-1.3.16-py2.7-linux-x86_64.egg/sqlalchemy/engine/s
trategies.py", line 173, in create
    engineclass.__name__,
TypeError: Invalid argument(s) 'auth' sent to create_engine(), using configuration PrestoDialect/QueuePool/Engine.  Please chec
k that the keyword arguments are appropriate for this combination of components.
[15/Aug/2020 12:20:02 -0700] decorators   ERROR    Error running autocomplete
Traceback (most recent call last):
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/decorators.py", line 114, in wrapper
    return f(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/api.py", line 729, in autocomplete
    autocomplete_data = get_api(request, snippet).autocomplete(snippet, database, table, column, nested)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 113, in decorator
    raise QueryError(message)
QueryError: Invalid argument(s) 'auth' sent to create_engine(), using configuration PrestoDialect/QueuePool/Engine.  Please che
ck that the keyword arguments are appropriate for this combination of components.

**Comment by DRavikanth** [comment]
Referring to: https://github.com/dropbox/PyHive#sqlalchemy

It looks like we need to pass the additional options in connect_args So, tried the below(I am not sure how can translate these options but a try).

> [[[presto]]]
          interface=sqlalchemy
          name=Presto
          options='{"url": "presto://user:pwd@presto-coordinator(without https):8443/hive/dwh", "connect_args":"{'auth': 'LDAP', 'protocol': 'https'}"}'

**Exception:**

> File "/usr/share/hue/desktop/core/src/desktop/lib/conf.py", line 658, in coerce_json_dict
    raise Exception("Could not coerce %r to json dictionary." % value)
Exception: Could not coerce ['{"url": "presto://user:pwd@presto-coordinator(without https):8443/hive/dwh", "con
nect_args":"{\'auth\': \'LDAP', 'protocol\': \'https\'}"}'] to json dictionary.

There is no where in the documentation I could find a use for this. Thoughts @romainr ?

**Comment by DRavikanth** [comment]
**Update:**

> [[[presto]]]
          interface=sqlalchemy
          name=Presto
          options='{"url": "presto://user:pwd@presto-coordinator(without https):8443/hive/dwh", "connect_args":"{\"auth\": \"LDAP\", \"protocol\": \"https\"}"}'

**Exception:**

> [15/Aug/2020 13:09:00 -0700] sql_alchemy  ERROR    Query Error
Traceback (most recent call last):
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 98, in decorator
    return func(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 332, in autocomplete
    engine = self._get_engine()
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 135, in _get_engine
    ENGINES[engine_key] = self._create_engine()
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 187, in _create_engine
    return create_engine(url, **options)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/SQLAlchemy-1.3.16-py2.7-linux-x86_64.egg/sqlalchemy/engine/_
_init__.py", line 479, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/SQLAlchemy-1.3.16-py2.7-linux-x86_64.egg/sqlalchemy/engine/s
trategies.py", line 99, in create
    cparams.update(pop_kwarg("connect_args", {}))
ValueError: dictionary update sequence element #0 has length 1; 2 is required
[15/Aug/2020 13:09:00 -0700] decorators   ERROR    Error running autocomplete
Traceback (most recent call last):
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/decorators.py", line 114, in wrapper
    return f(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/api.py", line 729, in autocomplete
    autocomplete_data = get_api(request, snippet).autocomplete(snippet, database, table, column, nested)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 113, in decorator
    raise QueryError(message)
QueryError: dictionary update sequence element #0 has length 1; 2 is required

**Comment by romainr** [comment]
`options='{"url": "presto://user:pwd@presto-coordinator(without https):8443/hive/dwh", "auth": "LDAP", "protocol": "https"}'`

?

**Comment by DRavikanth** [comment]
@romainr, already tried this and pasted the result above. Please check: https://github.com/cloudera/hue/issues/1246#issuecomment-674438145

**Comment by romainr** [comment]
So as the content is not a simple type, we probably need to do the same as for `connect_args` same as `credentials_json`:

`options='{"url": "presto://user:pwd@presto-coordinator(without https):8443/hive/dwh", "connect_args":"{\"auth\": \"LDAP\", \"protocol\": \"https\"}"}'
`
And add the same block of code like:
https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py#L181
?

Bit tricky to provide options via options, but at least we keep the same names used by SqlAlchemy.

**Comment by DRavikanth** [comment]
@romainr, Thanks for the pointer. I will try to patch sql_alchemy.py in my local and see if this works.

**Comment by DRavikanth** [comment]
@romainr, Added the following block in sql_alchemy.py

> if self.options.get('connect_args'):
      self.options['connect_args'] = json.loads(
          self.options.pop('connect_args')
      )

Now, getting the following error:

> StatementError: (exceptions.TypeError) __init__() got an unexpected keyword argument 'auth'
[SQL: SHOW SCHEMAS]
[17/Aug/2020 19:45:02 -0700] decorators   ERROR    Error running autocomplete
Traceback (most recent call last):
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/decorators.py", line 114, in wrapper
    return f(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/api.py", line 729, in autocomplete
    autocomplete_data = get_api(request, snippet).autocomplete(snippet, database, table, column, nested, action)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 114, in decorator
    raise QueryError(message)
QueryError: (exceptions.TypeError) __init__() got an unexpected keyword argument 'auth'
[SQL: SHOW SCHEMAS]

It looks like it needs more changes in the python file. Any further inputs? TIA

**Comment by romainr** [comment]
And without 'auth' in the Json?

Getting there ;)

**Comment by DRavikanth** [comment]
Nice. That seems to work. Do you mind if I open a PR? Also, to which branch I need to open one? master?

**Comment by romainr** [comment]
Excellent & Congratz!

Yes, any PR on top of master is more than welcomed!

**Comment by DRavikanth** [comment]
@romainr, Thanks for your support and patience throughout. Here is the PR: https://github.com/cloudera/hue/pull/1249. Please review and let me know if there is anything else that I need to do. Also, as this merges to master when can this code be available for GA?

**Comment by romainr** [comment]
The code is GA as sounds as the PR will be merged into master, and the a more official release is coming soon with 4.8 https://issues.cloudera.org/browse/HUE-9276 and so will contain it

**Comment by DRavikanth** [comment]
Thanks for the information @romainr regarding the release. Just want to make a decision on whether we need to maintain this code based on Hue release schedules.

I opened a new PR: https://github.com/cloudera/hue/pull/1250. Please let me know if there is anything else that needs to be done.

**Comment by romainr** [comment]
This is great, thank you!

And FYI: the SQL Parsers are currently being revamped so that it is easier to customize the Apache Calcite based dialect like Presto

**Comment by DRavikanth** [comment]
Any idea on when is this planned for @romainr? Do you have a ticket that I can follow?

**Comment by romainr** [comment]
This is https://issues.cloudera.org/browse/HUE-9429 and @JohanAhlen did a lot already.

They are several parsers already and they work, and the doc will be refreshed soon:
https://docs.gethue.com/developer/parsers/
https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/js/parse/jison/sql/presto/structure.json
