### ISSUE TITLE
Hue: make apps - error when looking for winkerberos on Linux

### ISSUE THREAD

**Issue by vinhdiesal** [cloudera/hue#1247]
To build Hue with make apps, I set my PYTHON_VER=python3.8. 

I installed all the dependencies and it would run for awhile until it looks for Kerberos. 

Even though I'm on a MAC_OSX/Linux, the compiler will look for winkerberos and then errors out with `no moduled named winkerberos`

I do have kerberos and pykerberos installed. 

I looked at the kerberos.py and tried to change winkerberos to kerberos/pykerberos, but it results in the same errors. 

How do I get this to work, or how do I bypass Kerberos? 

Thanks,

**Comment by romainr** [comment]
What is the full error trace?

**Comment by vinhdiesal** [comment]
the following is the full error trace: 

```
Traceback (most recent call last):
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/requests_kerberos/kerberos_.py", line 2, in <module>
    import kerberos
ImportError: dlopen(/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/kerberos.cpython-38-darwin.so, 2): Symbol not found: _mempcpy
  Referenced from: /Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/kerberos.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/kerberos.cpython-38-darwin.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vinhdiesal/hue/build/env/bin/hue", line 33, in <module>
    sys.exit(load_entry_point('desktop', 'console_scripts', 'hue')())
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/manage_entry.py", line 225, in entry
    execute_from_command_line(sys.argv)
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/models.py", line 47, in <module>
    from useradmin.models import User, Group, get_organization
  File "/Users/vinhdiesal/hue/apps/useradmin/src/useradmin/models.py", line 56, in <module>
    from desktop.lib.connectors.models import _get_installed_connectors, Connector
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/connectors/models.py", line 29, in <module>
    from desktop.lib.connectors.types import get_connectors_types
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/connectors/types.py", line 24, in <module>
    from desktop.lib.exceptions_renderable import PopupException
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/exceptions_renderable.py", line 31, in <module>
    import desktop.lib.django_util
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/django_util.py", line 42, in <module>
    import desktop.lib.thrift_util
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/thrift_util.py", line 49, in <module>
    from desktop.lib.thrift_.http_client import THttpClient
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/thrift_/http_client.py", line 26, in <module>
    from desktop.lib.rest.http_client import HttpClient
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/rest/http_client.py", line 31, in <module>
    from requests_kerberos import HTTPKerberosAuth, REQUIRED, OPTIONAL, DISABLED
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/requests_kerberos/__init__.py", line 17, in <module>
    from .kerberos_ import HTTPKerberosAuth, REQUIRED, OPTIONAL, DISABLED
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/requests_kerberos/kerberos_.py", line 4, in <module>
    import winkerberos as kerberos
ModuleNotFoundError: No module named 'winkerberos'
Running '/Users/vinhdiesal/hue/build/env/bin/hue migrate --fake-initial' with None
[17/Aug/2020 18:10:18 -0700] settings     DEBUG    DESKTOP_DB_TEST_NAME SET: /Users/vinhdiesal/hue/desktop/desktop-test.db
[17/Aug/2020 18:10:18 -0700] settings     DEBUG    DESKTOP_DB_TEST_USER SET: hue_test
Traceback (most recent call last):
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/requests_kerberos/kerberos_.py", line 2, in <module>
    import kerberos
ImportError: dlopen(/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/kerberos.cpython-38-darwin.so, 2): Symbol not found: _mempcpy
  Referenced from: /Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/kerberos.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/kerberos.cpython-38-darwin.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vinhdiesal/hue/build/env/bin/hue", line 33, in <module>
    sys.exit(load_entry_point('desktop', 'console_scripts', 'hue')())
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/manage_entry.py", line 225, in entry
    execute_from_command_line(sys.argv)
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/models.py", line 47, in <module>
    from useradmin.models import User, Group, get_organization
  File "/Users/vinhdiesal/hue/apps/useradmin/src/useradmin/models.py", line 56, in <module>
    from desktop.lib.connectors.models import _get_installed_connectors, Connector
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/connectors/models.py", line 29, in <module>
    from desktop.lib.connectors.types import get_connectors_types
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/connectors/types.py", line 24, in <module>
    from desktop.lib.exceptions_renderable import PopupException
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/exceptions_renderable.py", line 31, in <module>
    import desktop.lib.django_util
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/django_util.py", line 42, in <module>
    import desktop.lib.thrift_util
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/thrift_util.py", line 49, in <module>
    from desktop.lib.thrift_.http_client import THttpClient
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/thrift_/http_client.py", line 26, in <module>
    from desktop.lib.rest.http_client import HttpClient
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/rest/http_client.py", line 31, in <module>
    from requests_kerberos import HTTPKerberosAuth, REQUIRED, OPTIONAL, DISABLED
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/requests_kerberos/__init__.py", line 17, in <module>
    from .kerberos_ import HTTPKerberosAuth, REQUIRED, OPTIONAL, DISABLED
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/requests_kerberos/kerberos_.py", line 4, in <module>
    import winkerberos as kerberos
ModuleNotFoundError: No module named 'winkerberos'
Running '/Users/vinhdiesal/hue/build/env/bin/hue collectstatic --noinput' with None
[17/Aug/2020 18:10:18 -0700] settings     DEBUG    DESKTOP_DB_TEST_NAME SET: /Users/vinhdiesal/hue/desktop/desktop-test.db
[17/Aug/2020 18:10:18 -0700] settings     DEBUG    DESKTOP_DB_TEST_USER SET: hue_test
Traceback (most recent call last):
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/requests_kerberos/kerberos_.py", line 2, in <module>
    import kerberos
ImportError: dlopen(/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/kerberos.cpython-38-darwin.so, 2): Symbol not found: _mempcpy
  Referenced from: /Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/kerberos.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/kerberos.cpython-38-darwin.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vinhdiesal/hue/build/env/bin/hue", line 33, in <module>
    sys.exit(load_entry_point('desktop', 'console_scripts', 'hue')())
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/manage_entry.py", line 225, in entry
    execute_from_command_line(sys.argv)
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/models.py", line 47, in <module>
    from useradmin.models import User, Group, get_organization
  File "/Users/vinhdiesal/hue/apps/useradmin/src/useradmin/models.py", line 56, in <module>
    from desktop.lib.connectors.models import _get_installed_connectors, Connector
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/connectors/models.py", line 29, in <module>
    from desktop.lib.connectors.types import get_connectors_types
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/connectors/types.py", line 24, in <module>
    from desktop.lib.exceptions_renderable import PopupException
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/exceptions_renderable.py", line 31, in <module>
    import desktop.lib.django_util
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/django_util.py", line 42, in <module>
    import desktop.lib.thrift_util
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/thrift_util.py", line 49, in <module>
    from desktop.lib.thrift_.http_client import THttpClient
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/thrift_/http_client.py", line 26, in <module>
    from desktop.lib.rest.http_client import HttpClient
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/rest/http_client.py", line 31, in <module>
    from requests_kerberos import HTTPKerberosAuth, REQUIRED, OPTIONAL, DISABLED
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/requests_kerberos/__init__.py", line 17, in <module>
    from .kerberos_ import HTTPKerberosAuth, REQUIRED, OPTIONAL, DISABLED
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/requests_kerberos/kerberos_.py", line 4, in <module>
    import winkerberos as kerberos
ModuleNotFoundError: No module named 'winkerberos'
"PYTHON_VER is python3.8."
"Python 3 module install via pip"
"SYS_PYTHON is /usr/local/bin/python3.8."
"ENV_PYTHON is /Users/vinhdiesal/hue/build/env/bin/python3.8."
./build/env/bin/hue collectstatic --noinput
[17/Aug/2020 18:10:19 -0700] settings     DEBUG    DESKTOP_DB_TEST_NAME SET: /Users/vinhdiesal/hue/desktop/desktop-test.db
[17/Aug/2020 18:10:19 -0700] settings     DEBUG    DESKTOP_DB_TEST_USER SET: hue_test
Traceback (most recent call last):
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/requests_kerberos/kerberos_.py", line 2, in <module>
    import kerberos
ImportError: dlopen(/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/kerberos.cpython-38-darwin.so, 2): Symbol not found: _mempcpy
  Referenced from: /Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/kerberos.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/kerberos.cpython-38-darwin.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./build/env/bin/hue", line 33, in <module>
    sys.exit(load_entry_point('desktop', 'console_scripts', 'hue')())
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/manage_entry.py", line 225, in entry
    execute_from_command_line(sys.argv)
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/models.py", line 47, in <module>
    from useradmin.models import User, Group, get_organization
  File "/Users/vinhdiesal/hue/apps/useradmin/src/useradmin/models.py", line 56, in <module>
    from desktop.lib.connectors.models import _get_installed_connectors, Connector
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/connectors/models.py", line 29, in <module>
    from desktop.lib.connectors.types import get_connectors_types
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/connectors/types.py", line 24, in <module>
    from desktop.lib.exceptions_renderable import PopupException
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/exceptions_renderable.py", line 31, in <module>
    import desktop.lib.django_util
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/django_util.py", line 42, in <module>
    import desktop.lib.thrift_util
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/thrift_util.py", line 49, in <module>
    from desktop.lib.thrift_.http_client import THttpClient
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/thrift_/http_client.py", line 26, in <module>
    from desktop.lib.rest.http_client import HttpClient
  File "/Users/vinhdiesal/hue/desktop/core/src/desktop/lib/rest/http_client.py", line 31, in <module>
    from requests_kerberos import HTTPKerberosAuth, REQUIRED, OPTIONAL, DISABLED
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/requests_kerberos/__init__.py", line 17, in <module>
    from .kerberos_ import HTTPKerberosAuth, REQUIRED, OPTIONAL, DISABLED
  File "/Users/vinhdiesal/hue/build/env/lib/python3.8/site-packages/requests_kerberos/kerberos_.py", line 4, in <module>
    import winkerberos as kerberos
ModuleNotFoundError: No module named 'winkerberos'
make[1]: *** [create-static] Error 1
make: *** [apps] Error 2
```

**Comment by romainr** [comment]
You could try first to add `winkerberos` to the requirement.txt too?

It seems like the package is not there for your OS. What are the exact versions? Typical OS are https://docs.gethue.com/administrator/installation/dependencies/#os-packages

**Comment by vinhdiesal** [comment]
I don't understand what is requirement.txt, where is that file located and what does that do?
winkerberos is a package that is only for windows and your typical OS includes other operating systems like Linux, and Mac OSx, 
How do we bypass kerberos?
Is there a pre-made binary where I can just configure and launch Hue without having to build?
