### ISSUE TITLE
Unable to build HUE on Ubuntu 16.04

### ISSUE THREAD

**Issue by ranavikas007** [cloudera/hue#1254]
Running make as root on Ubuntu 16.04, and followed doc: https://gethue.com/how-to-build-hue-on-ubuntu-14-04-trusty/
**System details:**
```
root@kafka1:~/hue-ui# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```
**NPM and Node:**
```
npm --version
6.14.6
node --version
v10.22.0
```
Build [cmd: make apps] is failing with following error:
```
~/hue-ui# make apps
"PYTHON_VER is python2.7."
"Python 2 module install of desktop/ext-py"
"SYS_PYTHON is /usr/bin/python2.7."
"ENV_PYTHON is /home/ubuntu/hue-ui/build/env/bin/python2.7."
make[1]: Entering directory '/home/ubuntu/hue-ui/desktop'
"PYTHON_VER is python2.7."
"Python 2 module install of desktop/ext-py"
"SYS_PYTHON is /usr/bin/python2.7."
"ENV_PYTHON is /home/ubuntu/hue-ui/build/env/bin/python2.7."
"----------------> ENV_INSTALL_TARGETS: .recursive-env-install/core .recursive-env-install/libs/aws .recursive-env-install/libs/azure .recursive-env-install/libs/hadoop .recursive-env-install/libs/indexer .recursive-env-install/libs/libanalyze .recursive-env-install/libs/liboauth .recursive-env-install/libs/liboozie .recursive-env-install/libs/librdbms .recursive-env-install/libs/libsaml .recursive-env-install/libs/libsentry .recursive-env-install/libs/libsolr .recursive-env-install/libs/libzookeeper .recursive-env-install/libs/metadata .recursive-env-install/libs/notebook .recursive-env-install/libs/dashboard .recursive-env-install/libs/kafka"
make -C core env-install
make[2]: Entering directory '/home/ubuntu/hue-ui/desktop/core'
"PYTHON_VER is python2.7."
"Python 2 module install of desktop/ext-py"
"SYS_PYTHON is /usr/bin/python2.7."
"ENV_PYTHON is /home/ubuntu/hue-ui/build/env/bin/python2.7."
--- Installing desktop into virtual-env
--- env-install: EXT_ENV_INSTALL: ext-env-install
running develop
running egg_info
writing requirements to src/desktop.egg-info/requires.txt
writing src/desktop.egg-info/PKG-INFO
writing top-level names to src/desktop.egg-info/top_level.txt
writing dependency_links to src/desktop.egg-info/dependency_links.txt
writing entry points to src/desktop.egg-info/entry_points.txt
reading manifest file 'src/desktop.egg-info/SOURCES.txt'
writing manifest file 'src/desktop.egg-info/SOURCES.txt'
running build_ext
Creating /home/ubuntu/hue-ui/build/env/lib/python2.7/site-packages/desktop.egg-link (link to src)
desktop 4.7.1 is already the active version in easy-install.pth
Installing hue script to /home/ubuntu/hue-ui/build/env/bin
Installing supervisor script to /home/ubuntu/hue-ui/build/env/bin

Installed /home/ubuntu/hue-ui/desktop/core/src
make[2]: Leaving directory '/home/ubuntu/hue-ui/desktop/core'
make -C libs/aws env-install
make[2]: Entering directory '/home/ubuntu/hue-ui/desktop/libs/aws'
"PYTHON_VER is python2.7."
"Python 2 module install of desktop/ext-py"
"SYS_PYTHON is /usr/bin/python2.7."
"ENV_PYTHON is /home/ubuntu/hue-ui/build/env/bin/python2.7."
--- Installing aws into virtual-env
running develop
running egg_info
writing requirements to src/aws.egg-info/requires.txt
writing src/aws.egg-info/PKG-INFO
writing top-level names to src/aws.egg-info/top_level.txt
writing dependency_links to src/aws.egg-info/dependency_links.txt
writing entry points to src/aws.egg-info/entry_points.txt
reading manifest file 'src/aws.egg-info/SOURCES.txt'
writing manifest file 'src/aws.egg-info/SOURCES.txt'
running build_ext
Creating /home/ubuntu/hue-ui/build/env/lib/python2.7/site-packages/aws.egg-link (link to src)
aws 4.7.1 is already the active version in easy-install.pth

Installed /home/ubuntu/hue-ui/desktop/libs/aws/src
make[2]: Leaving directory '/home/ubuntu/hue-ui/desktop/libs/aws'
make -C libs/azure env-install
make[2]: Entering directory '/home/ubuntu/hue-ui/desktop/libs/azure'
"PYTHON_VER is python2.7."
"Python 2 module install of desktop/ext-py"
"SYS_PYTHON is /usr/bin/python2.7."
"ENV_PYTHON is /home/ubuntu/hue-ui/build/env/bin/python2.7."
--- Installing azure into virtual-env
running develop
running egg_info
writing requirements to src/azure.egg-info/requires.txt
writing src/azure.egg-info/PKG-INFO
writing top-level names to src/azure.egg-info/top_level.txt
writing dependency_links to src/azure.egg-info/dependency_links.txt
writing entry points to src/azure.egg-info/entry_points.txt
reading manifest file 'src/azure.egg-info/SOURCES.txt'
writing manifest file 'src/azure.egg-info/SOURCES.txt'
running build_ext
Creating /home/ubuntu/hue-ui/build/env/lib/python2.7/site-packages/azure.egg-link (link to src)
azure 4.7.1 is already the active version in easy-install.pth

Installed /home/ubuntu/hue-ui/desktop/libs/azure/src
make[2]: Leaving directory '/home/ubuntu/hue-ui/desktop/libs/azure'
make -C libs/hadoop env-install
make[2]: Entering directory '/home/ubuntu/hue-ui/desktop/libs/hadoop'
"PYTHON_VER is python2.7."
"Python 2 module install of desktop/ext-py"
"SYS_PYTHON is /usr/bin/python2.7."
"ENV_PYTHON is /home/ubuntu/hue-ui/build/env/bin/python2.7."

--- Installing hadoop into virtual-env
running develop
running egg_info
writing requirements to src/hadoop.egg-info/requires.txt
writing src/hadoop.egg-info/PKG-INFO
writing top-level names to src/hadoop.egg-info/top_level.txt
writing dependency_links to src/hadoop.egg-info/dependency_links.txt
writing entry points to src/hadoop.egg-info/entry_points.txt
reading manifest file 'src/hadoop.egg-info/SOURCES.txt'
writing manifest file 'src/hadoop.egg-info/SOURCES.txt'
running build_ext
Creating /home/ubuntu/hue-ui/build/env/lib/python2.7/site-packages/hadoop.egg-link (link to src)
hadoop 4.7.1 is already the active version in easy-install.pth

Installed /home/ubuntu/hue-ui/desktop/libs/hadoop/src
make[2]: Leaving directory '/home/ubuntu/hue-ui/desktop/libs/hadoop'
make -C libs/indexer env-install
make[2]: Entering directory '/home/ubuntu/hue-ui/desktop/libs/indexer'
"PYTHON_VER is python2.7."
"Python 2 module install of desktop/ext-py"
"SYS_PYTHON is /usr/bin/python2.7."
"ENV_PYTHON is /home/ubuntu/hue-ui/build/env/bin/python2.7."
--- Installing indexer into virtual-env
running develop
running egg_info
writing requirements to src/indexer.egg-info/requires.txt
writing src/indexer.egg-info/PKG-INFO
writing top-level names to src/indexer.egg-info/top_level.txt
writing dependency_links to src/indexer.egg-info/dependency_links.txt
writing entry points to src/indexer.egg-info/entry_points.txt
reading manifest file 'src/indexer.egg-info/SOURCES.txt'
writing manifest file 'src/indexer.egg-info/SOURCES.txt'
running build_ext
Creating /home/ubuntu/hue-ui/build/env/lib/python2.7/site-packages/indexer.egg-link (link to src)
indexer 4.7.1 is already the active version in easy-install.pth

Installed /home/ubuntu/hue-ui/desktop/libs/indexer/src
make[2]: Leaving directory '/home/ubuntu/hue-ui/desktop/libs/indexer'
make -C libs/libanalyze env-install
make[2]: Entering directory '/home/ubuntu/hue-ui/desktop/libs/libanalyze'
"PYTHON_VER is python2.7."
"Python 2 module install of desktop/ext-py"
"SYS_PYTHON is /usr/bin/python2.7."
"ENV_PYTHON is /home/ubuntu/hue-ui/build/env/bin/python2.7."
--- Installing libanalyze into virtual-env
running develop
running egg_info
writing requirements to src/libanalyze.egg-info/requires.txt
writing src/libanalyze.egg-info/PKG-INFO
writing top-level names to src/libanalyze.egg-info/top_level.txt
writing dependency_links to src/libanalyze.egg-info/dependency_links.txt
writing entry points to src/libanalyze.egg-info/entry_points.txt
reading manifest file 'src/libanalyze.egg-info/SOURCES.txt'
writing manifest file 'src/libanalyze.egg-info/SOURCES.txt'
running build_ext
Creating /home/ubuntu/hue-ui/build/env/lib/python2.7/site-packages/libanalyze.egg-link (link to src)
libanalyze 4.7.1 is already the active version in easy-install.pth

Installed /home/ubuntu/hue-ui/desktop/libs/libanalyze/src
make[2]: Leaving directory '/home/ubuntu/hue-ui/desktop/libs/libanalyze'
make -C libs/liboauth env-install
make[2]: Entering directory '/home/ubuntu/hue-ui/desktop/libs/liboauth'
"PYTHON_VER is python2.7."
"Python 2 module install of desktop/ext-py"
"SYS_PYTHON is /usr/bin/python2.7."
"ENV_PYTHON is /home/ubuntu/hue-ui/build/env/bin/python2.7."
--- Installing liboauth into virtual-env
running develop
running egg_info
writing requirements to src/liboauth.egg-info/requires.txt
writing src/liboauth.egg-info/PKG-INFO
writing top-level names to src/liboauth.egg-info/top_level.txt
writing dependency_links to src/liboauth.egg-info/dependency_links.txt
writing entry points to src/liboauth.egg-info/entry_points.txt
reading manifest file 'src/liboauth.egg-info/SOURCES.txt'
writing manifest file 'src/liboauth.egg-info/SOURCES.txt'
running build_ext
Creating /home/ubuntu/hue-ui/build/env/lib/python2.7/site-packages/liboauth.egg-link (link to src)
liboauth 4.7.1 is already the active version in easy-install.pth

Installed /home/ubuntu/hue-ui/desktop/libs/liboauth/src
make[2]: Leaving directory '/home/ubuntu/hue-ui/desktop/libs/liboauth'
make -C libs/liboozie env-install
make[2]: Entering directory '/home/ubuntu/hue-ui/desktop/libs/liboozie'
"PYTHON_VER is python2.7."
"Python 2 module install of desktop/ext-py"
"SYS_PYTHON is /usr/bin/python2.7."
"ENV_PYTHON is /home/ubuntu/hue-ui/build/env/bin/python2.7."
--- Installing liboozie into virtual-env
running develop
running egg_info
writing requirements to src/liboozie.egg-info/requires.txt
writing src/liboozie.egg-info/PKG-INFO
writing top-level names to src/liboozie.egg-info/top_level.txt
writing dependency_links to src/liboozie.egg-info/dependency_links.txt
writing entry points to src/liboozie.egg-info/entry_points.txt
reading manifest file 'src/liboozie.egg-info/SOURCES.txt'
writing manifest file 'src/liboozie.egg-info/SOURCES.txt'
running build_ext
Creating /home/ubuntu/hue-ui/build/env/lib/python2.7/site-packages/liboozie.egg-link (link to src)
liboozie 4.7.1 is already the active version in easy-install.pth

Installed /home/ubuntu/hue-ui/desktop/libs/liboozie/src
make[2]: Leaving directory '/home/ubuntu/hue-ui/desktop/libs/liboozie'
make -C libs/librdbms env-install
make[2]: Entering directory '/home/ubuntu/hue-ui/desktop/libs/librdbms'
"PYTHON_VER is python2.7."
"Python 2 module install of desktop/ext-py"
"SYS_PYTHON is /usr/bin/python2.7."
"ENV_PYTHON is /home/ubuntu/hue-ui/build/env/bin/python2.7."
Skipping DB Proxy Jar build as BUILD_DB_PROXY not set.
--- Installing librdbms into virtual-env
running develop
running egg_info
writing requirements to src/librdbms.egg-info/requires.txt
writing src/librdbms.egg-info/PKG-INFO
writing top-level names to src/librdbms.egg-info/top_level.txt
writing dependency_links to src/librdbms.egg-info/dependency_links.txt
writing entry points to src/librdbms.egg-info/entry_points.txt
reading manifest file 'src/librdbms.egg-info/SOURCES.txt'
writing manifest file 'src/librdbms.egg-info/SOURCES.txt'
running build_ext
Creating /home/ubuntu/hue-ui/build/env/lib/python2.7/site-packages/librdbms.egg-link (link to src)
librdbms 4.7.1 is already the active version in easy-install.pth

Installed /home/ubuntu/hue-ui/desktop/libs/librdbms/src
make[2]: Leaving directory '/home/ubuntu/hue-ui/desktop/libs/librdbms'
make -C libs/libsaml env-install
make[2]: Entering directory '/home/ubuntu/hue-ui/desktop/libs/libsaml'
"PYTHON_VER is python2.7."
"Python 2 module install of desktop/ext-py"
"SYS_PYTHON is /usr/bin/python2.7."
"ENV_PYTHON is /home/ubuntu/hue-ui/build/env/bin/python2.7."
--- Installing libsaml into virtual-env
running develop
running egg_info
writing requirements to src/libsaml.egg-info/requires.txt
writing src/libsaml.egg-info/PKG-INFO
writing top-level names to src/libsaml.egg-info/top_level.txt
writing dependency_links to src/libsaml.egg-info/dependency_links.txt
writing entry points to src/libsaml.egg-info/entry_points.txt
reading manifest file 'src/libsaml.egg-info/SOURCES.txt'
writing manifest file 'src/libsaml.egg-info/SOURCES.txt'
running build_ext
Creating /home/ubuntu/hue-ui/build/env/lib/python2.7/site-packages/libsaml.egg-link (link to src)
libsaml 4.7.1 is already the active version in easy-install.pth

Installed /home/ubuntu/hue-ui/desktop/libs/libsaml/src
make[2]: Leaving directory '/home/ubuntu/hue-ui/desktop/libs/libsaml'
make -C libs/libsentry env-install
make[2]: Entering directory '/home/ubuntu/hue-ui/desktop/libs/libsentry'
"PYTHON_VER is python2.7."
"Python 2 module install of desktop/ext-py"
"SYS_PYTHON is /usr/bin/python2.7."
"ENV_PYTHON is /home/ubuntu/hue-ui/build/env/bin/python2.7."
--- Installing libsentry into virtual-env
running develop
running egg_info
writing requirements to src/libsentry.egg-info/requires.txt
writing src/libsentry.egg-info/PKG-INFO
writing top-level names to src/libsentry.egg-info/top_level.txt
writing dependency_links to src/libsentry.egg-info/dependency_links.txt
writing entry points to src/libsentry.egg-info/entry_points.txt
reading manifest file 'src/libsentry.egg-info/SOURCES.txt'
writing manifest file 'src/libsentry.egg-info/SOURCES.txt'
running build_ext
Creating /home/ubuntu/hue-ui/build/env/lib/python2.7/site-packages/libsentry.egg-link (link to src)
libsentry 4.7.1 is already the active version in easy-install.pth

Installed /home/ubuntu/hue-ui/desktop/libs/libsentry/src
make[2]: Leaving directory '/home/ubuntu/hue-ui/desktop/libs/libsentry'
make -C libs/libsolr env-install
make[2]: Entering directory '/home/ubuntu/hue-ui/desktop/libs/libsolr'
"PYTHON_VER is python2.7."
"Python 2 module install of desktop/ext-py"
"SYS_PYTHON is /usr/bin/python2.7."
"ENV_PYTHON is /home/ubuntu/hue-ui/build/env/bin/python2.7."
--- Installing libsolr into virtual-env
running develop
running egg_info
writing requirements to src/libsolr.egg-info/requires.txt
writing src/libsolr.egg-info/PKG-INFO
writing top-level names to src/libsolr.egg-info/top_level.txt
writing dependency_links to src/libsolr.egg-info/dependency_links.txt
writing entry points to src/libsolr.egg-info/entry_points.txt
reading manifest file 'src/libsolr.egg-info/SOURCES.txt'
writing manifest file 'src/libsolr.egg-info/SOURCES.txt'
running build_ext
Creating /home/ubuntu/hue-ui/build/env/lib/python2.7/site-packages/libsolr.egg-link (link to src)
libsolr 4.7.1 is already the active version in easy-install.pth

Installed /home/ubuntu/hue-ui/desktop/libs/libsolr/src
make[2]: Leaving directory '/home/ubuntu/hue-ui/desktop/libs/libsolr'
make -C libs/libzookeeper env-install
make[2]: Entering directory '/home/ubuntu/hue-ui/desktop/libs/libzookeeper'
"PYTHON_VER is python2.7."
"Python 2 module install of desktop/ext-py"
"SYS_PYTHON is /usr/bin/python2.7."
"ENV_PYTHON is /home/ubuntu/hue-ui/build/env/bin/python2.7."
--- Installing libzookeeper into virtual-env
running develop
running egg_info
writing requirements to src/libzookeeper.egg-info/requires.txt
writing src/libzookeeper.egg-info/PKG-INFO
writing top-level names to src/libzookeeper.egg-info/top_level.txt
writing dependency_links to src/libzookeeper.egg-info/dependency_links.txt
writing entry points to src/libzookeeper.egg-info/entry_points.txt
reading manifest file 'src/libzookeeper.egg-info/SOURCES.txt'
writing manifest file 'src/libzookeeper.egg-info/SOURCES.txt'
running build_ext
Creating /home/ubuntu/hue-ui/build/env/lib/python2.7/site-packages/libzookeeper.egg-link (link to src)
libzookeeper 4.7.1 is already the active version in easy-install.pth

Installed /home/ubuntu/hue-ui/desktop/libs/libzookeeper/src
make[2]: Leaving directory '/home/ubuntu/hue-ui/desktop/libs/libzookeeper'
make -C libs/metadata env-install
make[2]: Entering directory '/home/ubuntu/hue-ui/desktop/libs/metadata'
"PYTHON_VER is python2.7."
"Python 2 module install of desktop/ext-py"
"SYS_PYTHON is /usr/bin/python2.7."
"ENV_PYTHON is /home/ubuntu/hue-ui/build/env/bin/python2.7."
--- Installing metadata into virtual-env
running develop
running egg_info
writing requirements to src/metadata.egg-info/requires.txt
writing src/metadata.egg-info/PKG-INFO
writing top-level names to src/metadata.egg-info/top_level.txt
writing dependency_links to src/metadata.egg-info/dependency_links.txt
writing entry points to src/metadata.egg-info/entry_points.txt
reading manifest file 'src/metadata.egg-info/SOURCES.txt'
writing manifest file 'src/metadata.egg-info/SOURCES.txt'
running build_ext
Creating /home/ubuntu/hue-ui/build/env/lib/python2.7/site-packages/metadata.egg-link (link to src)
metadata 4.7.1 is already the active version in easy-install.pth

Installed /home/ubuntu/hue-ui/desktop/libs/metadata/src
make[2]: Leaving directory '/home/ubuntu/hue-ui/desktop/libs/metadata'
make -C libs/notebook env-install
make[2]: Entering directory '/home/ubuntu/hue-ui/desktop/libs/notebook'
"PYTHON_VER is python2.7."
"Python 2 module install of desktop/ext-py"
"SYS_PYTHON is /usr/bin/python2.7."
"ENV_PYTHON is /home/ubuntu/hue-ui/build/env/bin/python2.7."
--- Installing notebook into virtual-env
running develop
running egg_info
writing requirements to src/notebook.egg-info/requires.txt
writing src/notebook.egg-info/PKG-INFO
writing top-level names to src/notebook.egg-info/top_level.txt
writing dependency_links to src/notebook.egg-info/dependency_links.txt
writing entry points to src/notebook.egg-info/entry_points.txt
reading manifest file 'src/notebook.egg-info/SOURCES.txt'
writing manifest file 'src/notebook.egg-info/SOURCES.txt'
running build_ext
Creating /home/ubuntu/hue-ui/build/env/lib/python2.7/site-packages/notebook.egg-link (link to src)
notebook 4.7.1 is already the active version in easy-install.pth

Installed /home/ubuntu/hue-ui/desktop/libs/notebook/src
make[2]: Leaving directory '/home/ubuntu/hue-ui/desktop/libs/notebook'
make -C libs/dashboard env-install
make[2]: Entering directory '/home/ubuntu/hue-ui/desktop/libs/dashboard'
"PYTHON_VER is python2.7."
"Python 2 module install of desktop/ext-py"
"SYS_PYTHON is /usr/bin/python2.7."
"ENV_PYTHON is /home/ubuntu/hue-ui/build/env/bin/python2.7."
--- Installing dashboard into virtual-env
running develop
running egg_info
writing requirements to src/dashboard.egg-info/requires.txt
writing src/dashboard.egg-info/PKG-INFO
writing top-level names to src/dashboard.egg-info/top_level.txt
writing dependency_links to src/dashboard.egg-info/dependency_links.txt
writing entry points to src/dashboard.egg-info/entry_points.txt
reading manifest file 'src/dashboard.egg-info/SOURCES.txt'
writing manifest file 'src/dashboard.egg-info/SOURCES.txt'
running build_ext
Creating /home/ubuntu/hue-ui/build/env/lib/python2.7/site-packages/dashboard.egg-link (link to src)
dashboard 4.7.1 is already the active version in easy-install.pth

Installed /home/ubuntu/hue-ui/desktop/libs/dashboard/src
make[2]: Leaving directory '/home/ubuntu/hue-ui/desktop/libs/dashboard'
make -C libs/kafka env-install
make[2]: Entering directory '/home/ubuntu/hue-ui/desktop/libs/kafka'
"PYTHON_VER is python2.7."
"Python 2 module install of desktop/ext-py"
"SYS_PYTHON is /usr/bin/python2.7."
"ENV_PYTHON is /home/ubuntu/hue-ui/build/env/bin/python2.7."
--- Installing kafka into virtual-env
running develop
running egg_info
writing requirements to src/kafka.egg-info/requires.txt
writing src/kafka.egg-info/PKG-INFO
writing top-level names to src/kafka.egg-info/top_level.txt
writing dependency_links to src/kafka.egg-info/dependency_links.txt
writing entry points to src/kafka.egg-info/entry_points.txt
reading manifest file 'src/kafka.egg-info/SOURCES.txt'
writing manifest file 'src/kafka.egg-info/SOURCES.txt'
running build_ext
Creating /home/ubuntu/hue-ui/build/env/lib/python2.7/site-packages/kafka.egg-link (link to src)
kafka 4.7.1 is already the active version in easy-install.pth

Installed /home/ubuntu/hue-ui/desktop/libs/kafka/src
make[2]: Leaving directory '/home/ubuntu/hue-ui/desktop/libs/kafka'
make[1]: Leaving directory '/home/ubuntu/hue-ui/desktop'
make[1]: Entering directory '/home/ubuntu/hue-ui'
"PYTHON_VER is python2.7."
"Python 2 module install of desktop/ext-py"
"SYS_PYTHON is /usr/bin/python2.7."
"ENV_PYTHON is /home/ubuntu/hue-ui/build/env/bin/python2.7."
npm --version
6.14.6
node --version
v10.22.0
npm install

> node-sass@4.14.1 install /home/ubuntu/hue-ui/node_modules/node-sass
> node scripts/install.js

Unable to save binary /home/ubuntu/hue-ui/node_modules/node-sass/vendor/linux-x64-64 : { Error: EACCES: permission denied, mkdir '/home/ubuntu/hue-ui/node_modules/node-sass/vendor'
    at Object.mkdirSync (fs.js:757:3)
    at sync (/home/ubuntu/hue-ui/node_modules/mkdirp/index.js:72:13)
    at Function.sync (/home/ubuntu/hue-ui/node_modules/mkdirp/index.js:78:24)
    at checkAndDownloadBinary (/home/ubuntu/hue-ui/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/home/ubuntu/hue-ui/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/home/ubuntu/hue-ui/node_modules/node-sass/vendor' }

> node-sass@4.14.1 postinstall /home/ubuntu/hue-ui/node_modules/node-sass
> node scripts/build.js

Building: /home/ubuntu/node-v10.22.0-linux-x64/bin/node /home/ubuntu/hue-ui/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/home/ubuntu/node-v10.22.0-linux-x64/bin/node',
gyp verb cli   '/home/ubuntu/hue-ui/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.22.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.12
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.22.0
gyp verb command install [ '10.22.0' ]
gyp verb install input version string "10.22.0"
gyp verb install installing version: 10.22.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 10.22.0
gyp verb build dir attempting to create "build" dir: /home/ubuntu/hue-ui/node_modules/node-sass/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/ubuntu/hue-ui/node_modules/node-sass/build'
gyp ERR! System Linux 4.4.0-1111-aws
gyp ERR! command "/home/ubuntu/node-v10.22.0-linux-x64/bin/node" "/home/ubuntu/hue-ui/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/ubuntu/hue-ui/node_modules/node-sass
gyp ERR! node -v v10.22.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN ajv-keywords@3.4.1 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.14.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.14.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-08-28T12_12_09_516Z-debug.log
Makefile:231: recipe for target 'npm-install' failed
make[1]: *** [npm-install] Error 1
make[1]: Leaving directory '/home/ubuntu/hue-ui'
Makefile:158: recipe for target 'apps' failed
make: *** [apps] Error 2
```
```

**Comment by romainr** [comment]
Only 18.04 and 20.04 should be working now (at least with the very latest Hue)
https://docs.gethue.com/administrator/installation/dependencies/#ubuntu
