### ISSUE TITLE
"Object of type bytes is not JSON serializable" while running Hue with Python3

### ISSUE THREAD

**Issue by elukey** [cloudera/hue#1262]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?

Nope.

Describe the bug:

The following error appears in the log, and also in a UI's pop up:

```
[10/Sep/2020 12:14:33 +0000] api2         ERROR    Error running <function logs at 0x7f862f932e18>
Traceback (most recent call last):
  File "/usr/lib/hue/apps/jobbrowser/src/jobbrowser/api2.py", line 41, in decorator
    return func(*args, **kwargs)
  File "/usr/lib/hue/apps/jobbrowser/src/jobbrowser/api2.py", line 125, in logs
    response['logs'] = get_api(request.user, interface, cluster=cluster).logs(app_id, app_type, log_name, json_logs)
  File "/usr/lib/hue/apps/jobbrowser/src/jobbrowser/apis/workflow_api.py", line 113, in logs
    data = get_oozie_job_log(request, job_id=appid)
  File "/usr/lib/hue/apps/oozie/src/oozie/views/dashboard.py", line 179, in decorate
    return view_func(request, *args, **kwargs)
  File "/usr/lib/hue/apps/oozie/src/oozie/views/dashboard.py", line 619, in get_oozie_job_log
    return JsonResponse(return_obj, encoder=JSONEncoderForHTML)
  File "/usr/lib/hue/desktop/core/src/desktop/lib/django_util.py", line 497, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/hue/desktop/core/src/desktop/lib/json_utils.py", line 38, in encode
    return ''.join(chunks)
  File "/usr/lib/hue/desktop/core/src/desktop/lib/json_utils.py", line 44, in iterencode
    for chunk in chunks:
  File "/usr/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
```

Steps to reproduce it?

This happen when navigating to a page like `hue/jobbrowser/#!id=0094132-200720135922440-oozie-oozi-W`

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).

4.7.1

**Comment by elukey** [comment]
More precisely, the graph and XML tabs cause the error to pop up in the interface. The graph panel also seems to dump a PNG file that renders in a weird way (weird characters displayed).

**Comment by elukey** [comment]
So there are multiple encoding/decoding issues with the oozie lib apis, but I think I have solved the one described in the description.

There are others related to rendering svgs and xmls, but I don't have a good grasp on what's wrong yet.

**Comment by elukey** [comment]
The remaining problem is the following:

![Screen Shot 2020-09-10 at 5 46 38 PM](https://user-images.githubusercontent.com/1536240/92757065-aefd5e00-f38d-11ea-86a3-3747f72025ec.png)

It seems as if the browser didn't know how to interpret the bytes, and/or they get mangled in some function?

**Comment by romainr** [comment]
Indeed, probably the API sends back the data in the wrong format with Python3

**Comment by elukey** [comment]
> Indeed, probably the API sends back the data in the wrong format with Python3

I tried to debug a bit and in 3.9 (we used cloudera 5.16 atm) there is no call to the oozie API to get a svg/png, meanwhile there is in 4.7.1.

I am also running oozie 4.3, that has only the support for png, not svg (IIUC it was introduced in 5.x). I tried to manually curl the oozie endpoint, and I see this response:

```
curl -i --negotiate -u : "http://an-coord1001.eqiad.wmnet:11000/oozie/v2/job/0084592-200720135922440-oozie-oozi-W?doAs=elukey&timezone=UTC&show=graph"

HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
WWW-Authenticate: Negotiate XXXXXX
Set-Cookie: XXXXX
Content-Type: image/png
Transfer-Encoding: chunked
Date: Fri, 11 Sep 2020 14:12:44 GMT

Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
```

The transfer encoding is a little weird, since even https://oozie.apache.org/docs/4.2.0/WebServicesAPI.html#Job_graph seems to indicate something different. I tried to look for bugs in Oozie but I didn't find much. I am wondering if there is a way to avoid the png/svg rendering in Hue 4 to display the workflow's graph?

**Comment by romainr** [comment]
Check for 

`${ workflow_graph | n,unicode }`

?

BTW: maybe should not be unicode with Py3. There is no option AFAIK, but should be easy to use png or provide '' so that the Chart display get skipped?

```
    % if layout_json == '':
      $.ajax({
        'url': "${oozie_workflow.get_absolute_url()}?format=svg",
        'type': 'GET',
        success: function (svgData) {
          $("#workflow_graph").append(svgData);
        }
        });
    % endif
```

**Comment by elukey** [comment]
Not super familiar with this layout, are you suggesting to skip to display the workflow graph entirely? Because I'd love to keep seeing the graphs if possible :D

**Comment by elukey** [comment]
Also I see the call happening in `oozie_api.py`:

```
  def get_job_graph(self, jobid, format='svg'):
    params = self._get_params()
    params['show'] = 'graph'
    params['show-kill'] = 'true'
    params['format'] = format
    svg_data = self._root.get('job/%s' % (jobid,), params)
    return svg_data
```

**Comment by elukey** [comment]
After a little bit of testing, I found another issue:

```
[12/Sep/2020 07:21:33 +0000] dashboard    ERROR    Graph data could not be generated from Workflow 0095676-200720135922440-oozie-oozi-W: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
Traceback (most recent call last):
  File "/usr/lib/hue/apps/oozie/src/oozie/views/dashboard.py", line 364, in list_oozie_workflow
    workflow_data = Workflow.gen_workflow_data_from_xml(request.user, oozie_workflow)
  File "/usr/lib/hue/apps/oozie/src/oozie/models2.py", line 263, in gen_workflow_data_from_xml
    node_list = generate_v2_graph_nodes(oozie_workflow.definition)
  File "/usr/lib/hue/apps/oozie/src/oozie/importlib/workflows.py", line 700, in generate_v2_graph_nodes
    workflow_definition_root = etree.fromstring(workflow_definition)
  File "src/lxml/etree.pyx", line 3235, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1871, in lxml.etree._parseMemoryDocument
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```

In some workflows I have `<?xml version="1.0" encoding="UTF-8"?>`, and the etree.fromstring() function doesn't like it. I found another way using a different etree function, I am going to send a pull request to fix this. IIUC the png is requested only in case the graph cannot be drawn via XML nodes parsing, right? So I didn't find why the PNG is not  correctly rendered, but it should be a good step forward.
