### ISSUE TITLE
Usage of iterkeys() in list_oozie_info.mako not compatible with Python 3

### ISSUE THREAD

**Issue by elukey** [cloudera/hue#1270]
Describe the bug:

When I hit "Configuration" in a oozie coordinator I see Hue reporting a generic server failure and go back to the main landing page. In the logs I see:

```
[21/Sep/2020 15:54:39 +0000] exception    ERROR    Internal Server Error: /oozie/list_oozie_info/
Traceback (most recent call last):
  File "/usr/lib/hue/build/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/hue/build/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/lib/hue/build/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/hue/build/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/usr/lib/hue/apps/oozie/src/oozie/views/dashboard.py", line 179, in decorate
    return view_func(request, *args, **kwargs)
  File "/usr/lib/hue/apps/oozie/src/oozie/views/dashboard.py", line 642, in list_oozie_info
    'is_embeddable': request.GET.get('is_embeddable', False),
  File "/usr/lib/hue/desktop/core/src/desktop/lib/django_util.py", line 241, in render
    **kwargs
  File "/usr/lib/hue/desktop/core/src/desktop/lib/django_util.py", line 154, in _render_to_response
    return django_mako.render_to_response(template, *args, **kwargs)
  File "/usr/lib/hue/desktop/core/src/desktop/lib/django_mako.py", line 127, in render_to_response
    return HttpResponse(render_to_string(template_name, data_dictionary), **kwargs)
  File "/usr/lib/hue/desktop/core/src/desktop/lib/django_mako.py", line 116, in render_to_string_normal
    result = template.render(**data_dict)
  File "/usr/lib/hue/build/env/lib/python3.7/site-packages/mako/template.py", line 476, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/hue/build/env/lib/python3.7/site-packages/mako/runtime.py", line 883, in _render
    **_kwargs_for_callable(callable_, data)
  File "/usr/lib/hue/build/env/lib/python3.7/site-packages/mako/runtime.py", line 920, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/hue/build/env/lib/python3.7/site-packages/mako/runtime.py", line 947, in _exec_template
    callable_(context, *args, **kwargs)
  File "/tmp/tmpnvuq9_mn/oozie/dashboard/list_oozie_info.mako.py", line 93, in render_body
    loop = __M_loop._enter(instrumentation.iterkeys())
AttributeError: 'dict' object has no attribute 'iterkeys'
```

In list_oozie_info.mako there are indeed some occurrences of iterkeys() that are not supported anymore in Python 3, so we should replace those with a conditional, but I am not familiar with .mako enough to make a pull request or test a fix (I can in case someone has some suggestions).

Steps to reproduce it?

Deploy Hue 4.7.1 built with Python 3.7, and try to hit "Configuration" when listing an Oozie coordiantor.

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).

opensource 4.7.1

**Comment by elukey** [comment]
I replaced manually in my test instance `iterkeys` with `keys` and the exception went away (I am not sure though how can we make the old code and the new one in a mako file yet) and a new one popped up:

```
[21/Sep/2020 16:51:41 +0000] middleware   INFO     Processing exception: object of type 'zip' has no len(): Traceback (most recent call last):
  File "/usr/lib/hue/build/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/usr/lib/hue/apps/oozie/src/oozie/views/dashboard.py", line 179, in decorate
    return view_func(request, *args, **kwargs)
  File "/usr/lib/hue/apps/oozie/src/oozie/views/dashboard.py", line 642, in list_oozie_info
    'is_embeddable': request.GET.get('is_embeddable', False),
  File "/usr/lib/hue/desktop/core/src/desktop/lib/django_util.py", line 241, in render
    **kwargs
  File "/usr/lib/hue/desktop/core/src/desktop/lib/django_util.py", line 154, in _render_to_response
    return django_mako.render_to_response(template, *args, **kwargs)
  File "/usr/lib/hue/desktop/core/src/desktop/lib/django_mako.py", line 127, in render_to_response
    return HttpResponse(render_to_string(template_name, data_dictionary), **kwargs)
  File "/usr/lib/hue/desktop/core/src/desktop/lib/django_mako.py", line 116, in render_to_string_normal
    result = template.render(**data_dict)
  File "/usr/lib/hue/build/env/lib/python3.7/site-packages/mako/template.py", line 476, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/hue/build/env/lib/python3.7/site-packages/mako/runtime.py", line 883, in _render
    **_kwargs_for_callable(callable_, data)
  File "/usr/lib/hue/build/env/lib/python3.7/site-packages/mako/runtime.py", line 920, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/hue/build/env/lib/python3.7/site-packages/mako/runtime.py", line 947, in _exec_template
    callable_(context, *args, **kwargs)
  File "/tmp/tmpu_66wj6b/oozie/dashboard/list_oozie_info.mako.py", line 152, in render_body
    if not loop.last:
  File "/usr/lib/hue/build/env/lib/python3.7/site-packages/mako/runtime.py", line 331, in last
    return self.index == len(self) - 1
  File "/usr/lib/hue/build/env/lib/python3.7/site-packages/mako/util.py", line 115, in oneshot
    result = self.fget(obj, *args, **kw)
  File "/usr/lib/hue/build/env/lib/python3.7/site-packages/mako/runtime.py", line 319, in __len__
    return len(self._iterable)
TypeError: object of type 'zip' has no len()
```

**Comment by elukey** [comment]
Ok so a quick hack/fix is to modify the following line (in list_oozie_info.mako):

```
% for label, timer in zip(['ownMinTime', 'ownTimeStdVar', 'totalTimeStdVar', 'ownTimeAvg', 'ticks', 'name', 'ownMaxTime', 'totalMinTime', 'totalMaxTime', 'totalTimeAvg'], item.values()):
```

If I wrap `zip()` with `list(zip())` it works fine.

**Comment by elukey** [comment]
@romainr if you have time lemme know your thoughts, I'll send a pull request afterwards :)

**Comment by romainr** [comment]
+1 (and no real need of iterators in previous version anyway)
