### ISSUE TITLE
Oozie's workflow graph box links lead to HTTP 400s from Oozie's v1 apis

### ISSUE THREAD

**Issue by elukey** [cloudera/hue#1273]
Describe the bug:

In the Oozie workflow's graph I cannot click on any box link, since I get errors:

![Screen Shot 2020-09-24 at 7 56 25 PM](https://user-images.githubusercontent.com/1536240/94181710-2bb92d80-fea0-11ea-9d31-9c1c8fe1a93b.png)

![Screen Shot 2020-09-24 at 7 57 39 PM](https://user-images.githubusercontent.com/1536240/94181758-3a9fe000-fea0-11ea-8c30-eccc3a440049.png)

Steps to reproduce it?

Just click on any box link in a graph.

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).

4.7.1

**Comment by elukey** [comment]
I have some traces to add to the report.

On the Hue side:

```
[24/Sep/2020 17:48:35 +0000] api2         ERROR    Error running <function job at 0x7efc882f29d8>
Traceback (most recent call last):
  File "/usr/lib/hue/desktop/core/src/desktop/lib/rest/http_client.py", line 219, in execute
    resp.raise_for_status()
  File "/usr/lib/hue/build/env/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://an-coord1001.eqiad.wmnet:11000/oozie/v1/job?doAs=elukey&timezone=UTC

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/hue/apps/jobbrowser/src/jobbrowser/api2.py", line 40, in decorator
    return func(*args, **kwargs)
  File "/usr/lib/hue/apps/jobbrowser/src/jobbrowser/api2.py", line 82, in job
    response_app = get_api(request.user, interface, cluster=cluster).app(app_id)
  File "/usr/lib/hue/apps/jobbrowser/src/jobbrowser/apis/workflow_api.py", line 76, in app
    workflow = oozie_api.get_job(jobid=appid)
  File "/usr/lib/hue/desktop/libs/liboozie/src/liboozie/oozie_api.py", line 145, in get_job
    resp = self._root.get('job/%s' % (jobid,), params)
  File "/usr/lib/hue/desktop/core/src/desktop/lib/rest/resource.py", line 157, in get
    return self.invoke("GET", relpath, params, headers=headers, allow_redirects=True, clear_cookies=clear_cookies)
  File "/usr/lib/hue/desktop/core/src/desktop/lib/rest/resource.py", line 87, in invoke
    log_response=log_response
  File "/usr/lib/hue/desktop/core/src/desktop/lib/rest/resource.py", line 114, in _invoke
    clear_cookies=clear_cookies
  File "/usr/lib/hue/desktop/core/src/desktop/lib/rest/http_client.py", line 229, in execute
    raise self._exc_class(ex)
desktop.lib.rest.http_client.RestException: 400 Client Error: Bad Request for url: http://an-coord1001.eqiad.wmnet:11000/oozie/v1/job?doAs=elukey&timezone=UTC
```

On the Oozie side:

```
2020-09-24 17:42:12,004  WARN V1JobServlet:523 - SERVER[an-coord1001.eqiad.wmnet] USER[-] GROUP[-] TOKEN[-] APP[-] JOB[-] ACTION[-] URL[GET http://an-coord1001.eqiad.wmnet:11000/oozie/v1/job?doAs=elukey&timezone=UTC] user error, id cannot be empty
java.lang.IllegalArgumentException: id cannot be empty
	at org.apache.oozie.util.ParamChecker.notEmpty(ParamChecker.java:90)
	at org.apache.oozie.util.ParamChecker.notEmpty(ParamChecker.java:74)
	at org.apache.oozie.command.coord.CoordJobXCommand.<init>(CoordJobXCommand.java:71)
	at org.apache.oozie.CoordinatorEngine.getCoordJob(CoordinatorEngine.java:183)
	at org.apache.oozie.servlet.V1JobServlet.getCoordinatorJob(V1JobServlet.java:833)
	at org.apache.oozie.servlet.V1JobServlet.getJob(V1JobServlet.java:241)
	at org.apache.oozie.servlet.BaseJobServlet.doGet(BaseJobServlet.java:277)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.apache.oozie.servlet.JsonRestServlet.service(JsonRestServlet.java:289)
       [..]
```

If I go in `api2.py:82` I see that `app_id` is empty :(

**Comment by elukey** [comment]
@romainr any idea about this one?

**Comment by elukey** [comment]
Still need to be fixed :)

**Comment by elukey** [comment]
This is still a bug!

**Comment by elukey** [comment]
Still a bug :)
