### ISSUE TITLE
Hue 4.8.0 issue with Py2 vs Py3 when using CherryPy 

### ISSUE THREAD

**Issue by sandredd** [cloudera/hue#1337]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com? No

Describe the bug: When i try to start Hue4.8.0 with CherryPy webserver i see below error. When i use Gunicorn hue starts and i'm able to use it. 

WARNINGS:
jobbrowser.DagDetails.dag_info: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
jobbrowser.QueryDetails.hive_query: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
[23/Oct/2020 10:57:36 -0700] runcherrypyserver INFO     Starting server with options:
{'daemonize': False,
 'host': 'xxxx',
 'pidfile': None,
 'port': 8888,
 'server_group': 'xxxxx',
 'server_name': 'localhost',
 'server_user': 'xxxxx',
 'ssl_certificate': None,
 'ssl_certificate_chain': None,
 'ssl_cipher_list': ',
 'ssl_no_renegotiation': True,
 'ssl_private_key': None,
 'threads': 50,
 'workdir': None}
Traceback (most recent call last):
  File "/opt/paas/services/hue/hue-4.8.0_0-e030780/build/env/bin/hue", line 33, in <module>
    sys.exit(load_entry_point('desktop', 'console_scripts', 'hue')())
  File "/opt/paas/services/hue/hue-4.8.0_0-e030780/desktop/core/src/desktop/manage_entry.py", line 225, in entry
    execute_from_command_line(sys.argv)
  File "/opt/paas/services/hue/hue-4.8.0_0-e030780/build/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/paas/services/hue/hue-4.8.0_0-e030780/build/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/paas/services/hue/hue-4.8.0_0-e030780/build/env/lib/python3.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/paas/services/hue/hue-4.8.0_0-e030780/build/env/lib/python3.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/paas/services/hue/hue-4.8.0_0-e030780/desktop/core/src/desktop/management/commands/runcherrypyserver.py", line 69, in handle
    runcpserver(args)
  File "/opt/paas/services/hue/hue-4.8.0_0-e030780/desktop/core/src/desktop/management/commands/runcherrypyserver.py", line 131, in runcpserver
    start_server(options)
  File "/opt/paas/services/hue/hue-4.8.0_0-e030780/desktop/core/src/desktop/management/commands/runcherrypyserver.py", line 78, in start_server
    from desktop.lib.wsgiserver import CherryPyWSGIServer as Server
  File "/opt/paas/services/hue/hue-4.8.0_0-e030780/desktop/core/src/desktop/lib/wsgiserver.py", line 660
    raise exc_info[0], exc_info[1], exc_info[2]
                     ^
SyntaxError: invalid syntax
[23/Oct/2020 17:57:37 +0000] settings     DEBUG    DESKTOP_DB_TEST_NAME SET: /opt/paas/services/hue/hue-4.8.0_0-e030780/desktop/desktop-test.db
[23/Oct/2020 17:57:37 +0000] settings     DEBUG    DESKTOP_DB_TEST_USER SET: hue_test
[23/Oct/2020 10:57:37 -0700] sslcompat    DEBUG    ipaddress module is available
[23/Oct/2020 10:57:37 -0700] sslcompat    DEBUG    ssl.match_hostname is available
[23/Oct/2020 10:57:37 -0700] backend      WARNING  pam module not found
[23/Oct/2020 10:57:37 -0700] backend      WARNING  mozilla_django_oidc module not found
[23/Oct/2020 10:57:37 -0700] client       WARNING  gcs_oauth2_boto_plugin module not found
[23/Oct/2020 10:57:37 -0700] decorators   INFO     AXES: BEGIN LOG
[23/Oct/2020 10:57:37 -0700] decorators   INFO     Using django-axes 2.2.0
[23/Oct/2020 10:57:37 -0700] altus        WARNING  NavOpt module is not installed: No module named 'asn1crypto'
[23/Oct/2020 10:57:37 -0700] views        WARNING  httplib2 module not found
[23/Oct/2020 10:57:37 -0700] backend      WARNING  httplib2 module not found
[23/Oct/2020 10:57:37 -0700] urls         WARNING  djangosaml2 module not found
[23/Oct/2020 10:57:37 -0700] api3         WARNING  simple_salesforce module not found
[23/Oct/2020 10:57:37 -0700] jdbc         WARNING  Failed to import py4j
[23/Oct/2020 10:57:37 -0700] optimizer_client WARNING  NavOpt module is not installed: No module named 'asn1crypto'
System check identified some issues:

WARNINGS:
jobbrowser.DagDetails.dag_info: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
jobbrowser.QueryDetails.hive_query: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
[23/Oct/2020 10:57:38 -0700] settings     INFO     Welcome to Hue 4.8.0.post0
[23/Oct/2020 10:57:38 -0700] settings     DEBUG    Installed Django modules: DesktopModule(aws: aws),DesktopModule(azure: azure),DesktopModule(hadoop: hadoop),DesktopModule(libanalyze: libanalyze),DesktopModule(liboauth: liboauth),DesktopModule(liboozie: liboozie),DesktopModule(librdbms: librdbms),DesktopModule(libsaml: libsaml),DesktopModule(libsentry: libsentry),DesktopModule(libsolr: libsolr),DesktopModule(libzookeeper: libzookeeper),DesktopModule(Hue: desktop),DesktopModule(About: about),DesktopModule(Hive: beeswax),DesktopModule(File Browser: filebrowser),DesktopModule(Help: help),DesktopModule(hive: hive),DesktopModule(Job Browser: jobbrowser),DesktopModule(Job Designer: jobsub),DesktopModule(Table Browser: metastore),DesktopModule(Oozie Editor/Dashboard: oozie),DesktopModule(Pig Editor: pig),DesktopModule(Proxy: proxy),DesktopModule(User Admin: useradmin),DesktopModule(ZooKeeper Browser: zookeeper),DesktopModule(Data Importer: indexer),DesktopModule(Metadata: metadata),DesktopModule(Notebook: notebook),DesktopModule(Analytics Dashboards: dashboard),DesktopModule(Kafka: kafka)
[23/Oct/2020 10:57:38 -0700] settings     DEBUG    DESKTOP_DB_TEST_NAME SET: /opt/paas/services/hue/hue-4.8.0_0-e030780/desktop/desktop-test.db
[23/Oct/2020 10:57:38 -0700] settings     DEBUG    DESKTOP_DB_TEST_USER SET: hue_test
[23/Oct/2020 10:57:38 -0700] sslcompat    DEBUG    ipaddress module is available
[23/Oct/2020 10:57:38 -0700] sslcompat    DEBUG    ssl.match_hostname is available
[23/Oct/2020 10:57:38 -0700] backend      WARNING  pam module not found
[23/Oct/2020 10:57:38 -0700] backend      WARNING  mozilla_django_oidc module not found
[23/Oct/2020 10:57:38 -0700] client       WARNING  gcs_oauth2_boto_plugin module not found
[23/Oct/2020 10:57:39 -0700] decorators   INFO     AXES: BEGIN LOG
[23/Oct/2020 10:57:39 -0700] decorators   INFO     Using django-axes 2.2.0
[23/Oct/2020 10:57:39 -0700] altus        WARNING  NavOpt module is not installed: No module named 'asn1crypto'
[23/Oct/2020 10:57:39 -0700] views        WARNING  httplib2 module not found
[23/Oct/2020 10:57:39 -0700] backend      WARNING  httplib2 module not found
[23/Oct/2020 10:57:39 -0700] urls         WARNING  djangosaml2 module not found
[23/Oct/2020 10:57:39 -0700] api3         WARNING  simple_salesforce module not found
[23/Oct/2020 10:57:39 -0700] jdbc         WARNING  Failed to import py4j
[23/Oct/2020 10:57:39 -0700] optimizer_client WARNING  NavOpt module is not installed: No module named 'asn1crypto'

Steps to reproduce it? Toggle between Gunicorn and Cherrry py
 
Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...). Apache Hue 4.8.0

**Comment by romainr** [comment]
Cherrypy is indeed not fully ported to Python3

**Comment by sandredd** [comment]
Thanks @romainr. Can we proceed to use Gunicorn in production environments then?

**Comment by romainr** [comment]
Yes, it is working, at least when using a single worker process. Feel free
to report feedback
