### ISSUE TITLE
Hue requests library error

### ISSUE THREAD

**Issue by trK54Ylmz** [cloudera/hue#148]
I don't know anything about Python code but I think something wrong with .structures

```
$ python -V
Python 2.7.6
```

I got this error each time.

```
$ make apps
...
make[1]: Entering directory `/home/tarik/Downloads/hue-master/desktop'
make -C core env-install
make[2]: Entering directory `/home/tarik/Downloads/hue-master/desktop/core'
--- Building egg for requests-2.0.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tarik/Downloads/hue-master/build/env/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/sandbox.py", line 62, in run_setup
  File "/home/tarik/Downloads/hue-master/build/env/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/sandbox.py", line 105, in run
  File "/home/tarik/Downloads/hue-master/build/env/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/sandbox.py", line 64, in <lambda>
  File "setup.py", line 6, in <module>
    import requests
  File "/home/tarik/Downloads/hue-master/desktop/core/ext-py/requests-2.0.0/requests/__init__.py", line 58, in <module>
    import utils
  File "/home/tarik/Downloads/hue-master/desktop/core/ext-py/requests-2.0.0/requests/utils.py", line 27, in <module>
    from .structures import CaseInsensitiveDict
ImportError: No module named structures
make[2]: *** [/home/tarik/Downloads/hue-master/desktop/core/build/requests-2.0.0/egg.stamp] Error 1
make[2]: Leaving directory `/home/tarik/Downloads/hue-master/desktop/core'
make[1]: *** [.recursive-env-install/core] Error 2
make[1]: Leaving directory `/home/tarik/Downloads/hue-master/desktop'
make: *** [desktop] Error 2
```

**Comment by romainr** [comment]
This is weird, on which OS are you?

**Comment by Skyeee** [comment]
Maybe python  was not nanually installed by someone.

not originally there within the os .

**Comment by romainr** [comment]
What is your operating system?

**Comment by trK54Ylmz** [comment]
@romainr 
Ubuntu 14.04 64bit

I am trying to compile from github repo clone.

**Comment by romainr** [comment]
Could you do a ls of?
ls desktop/core/ext-py/requests-2.0.0/requests/

**Comment by trK54Ylmz** [comment]
```
adapters.py  auth.py     certs.py   compat.py   cookies.py   exceptions.py  __init__.py   models.py  sessions.py      structures.py  utils.pyc
api.py       cacert.pem  certs.pyc  compat.pyc  cookies.pyc  hooks.py       __init__.pyc  packages   status_codes.py  utils.py
```

**Comment by romainr** [comment]
Weird, you are missing the .pyc file.

Could you clear them, with something like?

find desktop/core -name "*.pyc" -delete

**Comment by sambit19** [comment]
I too am facing this issue! Any fixes so far?

**Comment by romainr** [comment]
Could you do a fresh clone, then 'make apps' and look carefully for errors? This is typical of broken installation because of dependencies problem

**Comment by sambit19** [comment]
We use modules environment on our machine and multiple versions of Python, possibly the older versions 2.5 & 2.6 caused this error to happen. I did a module load python2.7 and it got fixed.
