### ISSUE TITLE
While creating the jdbc connecting string getting the error invalid syntax (jdbc.py, line 47)

### ISSUE THREAD

**Issue by balajivenka** [cloudera/hue#1483]
Please find the below error message while accessing the data from JDBC connection string 

JDBC connection string: 
[[[Avalanche]]]
name=Avalanche
interface=jdbc
options='{"url": "jdbc:ingres://av-0pq13o8h1zrp.avdev.actiandatacloud.com:27839/db", "driver": "com.ingres.jdbc.IngresDriver", "user": "*****", "password": "******"}'
![jdbc py-error](https://user-images.githubusercontent.com/60769946/101787023-a0594b00-3b24-11eb-9826-16a8f2e5875d.JPG)

Error Message:

exceptions_renderable ERROR Potential trace: [<FrameSummary file /home/actian/Hue_server/hue/desktop/libs/hadoop/src/hadoop/yarn/resource_manager_api.py, line 172 in _execute>, <FrameSummary file /home/actian/Hue_server/hue/desktop/core/src/desktop/lib/rest/resource.py, line 157 in get>, <FrameSummary file /home/actian/Hue_server/hue/desktop/core/src/desktop/lib/rest/resource.py, line 78 in invoke>, <FrameSummary file /home/actian/Hue_server/hue/desktop/core/src/desktop/lib/rest/resource.py, line 105 in _invoke>, <FrameSummary file /home/actian/Hue_server/hue/desktop/core/src/desktop/lib/rest/http_client.py, line 229 in execute>]
[10/Dec/2020 06:26:27 -0800] cluster INFO Resource Manager not available, trying another RM: YARN RM returned a failed response: HTTPConnectionPool(host='localhost', port=8088): Max retries exceeded with url: /ws/v1/cluster/apps?doAs=admin&user.name=hue&user=admin&finalStatus=UNDEFINED&limit=1000&startedTimeBegin=1607005587000 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f98a04db5b0>: Failed to establish a new connection: [Errno 111] Connection refused')).

**Comment by Akhilsnaik** [comment]
@balajivenka  , While raising issue, Please mention the version of Hue you are using, 

also the Error message mentioned doesn't seems to be relevant .. Can you see for error related to jdbc.py in the error log.

**Comment by balajivenka** [comment]
hue version 4.8.0
please find the attached error log
[error.log](https://github.com/cloudera/hue/files/5673745/error.log)

**Comment by romainr** [comment]
```[10/Dec/2020 06:21:00 -0800] decorators   ERROR    Error running create_session
Traceback (most recent call last):
  File "/home/actian/Hue_server/hue/desktop/libs/notebook/src/notebook/decorators.py", line 114, in wrapper
    return f(*args, **kwargs)
  File "/home/actian/Hue_server/hue/desktop/libs/notebook/src/notebook/api.py", line 106, in create_session
    response['session'] = get_api(request, session).create_session(lang=session['type'], properties=properties)
  File "/home/actian/Hue_server/hue/desktop/libs/notebook/src/notebook/models.py", line 523, in get_api
    return ApiWrapper(request, snippet)
  File "/home/actian/Hue_server/hue/desktop/libs/notebook/src/notebook/models.py", line 509, in __init__
    self.api = _get_api(request, snippet)
  File "/home/actian/Hue_server/hue/desktop/libs/notebook/src/notebook/connectors/base.py", line 467, in get_api
    from notebook.connectors.jdbc import JdbcApi
  File "/home/actian/Hue_server/hue/desktop/libs/notebook/src/notebook/connectors/jdbc.py", line 47
    raise QueryError, _('%s: is the DB Proxy server running?') % message, sys.exc_info()[2]
        ```

Seems not Python 3 compatible, probably need to port the Raise exception like https://github.com/cloudera/hue/commits/master/desktop/core/src/desktop/lib/wsgiserver.py

**Comment by balajivenka** [comment]
As per the url link https://github.com/cloudera/hue/commits/master/desktop/core/src/desktop/lib/wsgiserver.py from the comments [core] Add back Python 3 compatibility to wsgiserver (#1244)
code changes are made in wsgiserver.py from line 657 to 660 but still the error exists.
if sys.version_info[0] > 2:
                    raise (exc_info[0], exc_info[1], exc_info[2])
                else:
                    raise exc_info[0], exc_info[1], exc_info[2]
getting the below error:  
Traceback (most recent call last):
  File "/home/actian/Hue_server/hue/desktop/libs/notebook/src/notebook/decorators.py", line 114, in wrapper
    return f(*args, **kwargs)
  File "/home/actian/Hue_server/hue/desktop/libs/notebook/src/notebook/api.py", line 735, in autocomplete
    autocomplete_data = get_api(request, snippet).autocomplete(snippet, database, table, column, nested, action)
  File "/home/actian/Hue_server/hue/desktop/libs/notebook/src/notebook/models.py", line 523, in get_api
    return ApiWrapper(request, snippet)
  File "/home/actian/Hue_server/hue/desktop/libs/notebook/src/notebook/models.py", line 509, in __init__
    self.api = _get_api(request, snippet)
  File "/home/actian/Hue_server/hue/desktop/libs/notebook/src/notebook/connectors/base.py", line 467, in get_api
    from notebook.connectors.jdbc import JdbcApi
  File "/home/actian/Hue_server/hue/desktop/libs/notebook/src/notebook/connectors/jdbc.py", line 47
    raise QueryError, _('%s: is the DB Proxy server running?') % message, sys.exc_info()[2]

the error mainly exists in jdbc.py file line 47 "raise QueryError, _('%s: is the DB Proxy server running?') % message, sys.exc_info()[2]"
please find the environment details.
Hue version 4.8.0
attached is the error.log 
[error.log](https://github.com/cloudera/hue/files/5702434/error.log)

**Comment by romainr** [comment]
Yes, above commits shows how to fix this line

**Comment by balajivenka** [comment]
the commits which you said its not working for me i did the changes in the file wsgiserver.py file for the codes in the line 657 to 670 and code changes also but still same issue exists as mentioned in the above comments.please provide the comments on which error exists in mentioned python files like 
decorators.py", line 114, in wrapper
return f(*args, **kwargs)
api.py", line 735, in autocomplete
autocomplete_data = get_api(request, snippet).autocomplete(snippet, database, table, column, nested, action)
models.py", line 523, in get_api
return ApiWrapper(request, snippet)
models.py", line 509, in init
self.api = _get_api(request, snippet)
base.py", line 467, in get_api
from notebook.connectors.jdbc import JdbcApi
jdbc.py", line 47
raise QueryError, _('%s: is the DB Proxy server running?') % message, sys.exc_info()[2]

it will be helpful for me to resolve the issue.

**Comment by romainr** [comment]
Could you send a pull request of your changes? (would be easier to double check there)

**Comment by balajivenka** [comment]
https://github.com/cloudera/hue/commits/master/desktop/core/src/desktop/lib/wsgiserver.py from the comments [core] Add back Python 3 compatibility to wsgiserver (#1244)

**Comment by balajivenka** [comment]
please find the error message and changes made in the code are mentioned in the above link #1244
Traceback (most recent call last):
  File "/home/actian/Hue_server/hue/desktop/libs/notebook/src/notebook/decorators.py", line 114, in wrapper
    return f(*args, **kwargs)
  File "/home/actian/Hue_server/hue/desktop/libs/notebook/src/notebook/api.py", line 735, in autocomplete
    autocomplete_data = get_api(request, snippet).autocomplete(snippet, database, table, column, nested, action)
  File "/home/actian/Hue_server/hue/desktop/libs/notebook/src/notebook/models.py", line 523, in get_api
    return ApiWrapper(request, snippet)
  File "/home/actian/Hue_server/hue/desktop/libs/notebook/src/notebook/models.py", line 509, in __init__
    self.api = _get_api(request, snippet)
  File "/home/actian/Hue_server/hue/desktop/libs/notebook/src/notebook/connectors/base.py", line 467, in get_api
    from notebook.connectors.jdbc import JdbcApi
  File "/home/actian/Hue_server/hue/desktop/libs/notebook/src/notebook/connectors/jdbc.py", line 47
    raise QueryError, _('%s: is the DB Proxy server running?') % message, sys.exc_info()[2]

**Comment by romainr** [comment]
e.g.

`QueryError, _('%s: is the DB Proxy server running?') % message, sys.exc_info()[2]`

-->

```
from future.utils import raise_

raise_(QueryError, _('%s: is the DB Proxy server running?') % message, sys.exc_info()[2])
```

+ style fixing.

And if really needed, changing to a typical `QueryError('%s: is the DB Proxy server running? Trace: %s' % (....))` could be good enough.

And side question: why do you need the old JDBC and not the new interpreters?
https://docs.gethue.com/administrator/configuration/connectors/

**Comment by balajivenka** [comment]
deploying the code in jdbc.py file in line 48 as mentioned in the above comment, But still the error persists. find the below details:
line 47:# raise QueryError, _('%s: is the DB Proxy server running?') % message, sys.exc_info()[2]
line 48: QueryError('%s: is the DB Proxy server running? Trace: %s' % (....)) 

New JDBC coonnection was added under the interpreter section by the reference of connection strings provided for sql server .

[[[Avalanche]]]
        name=Avalanche
        interface=jdbc
        options='{"url": "jdbc:ingres://av-0pq13o8h1zrp.avdev.actiandatacloud.com:27839/db", "driver": "com.ingres.jdbc.IngresDriver", "user": "*****", "password": "*****"}'

[[[mysqljdbc]]]
name=MySql JDBC
interface=jdbc
## Specific options for connecting to the server.
## The JDBC connectors, e.g. mysql.jar, need to be in the CLASSPATH environment variable.
## If 'user' and 'password' are omitted, they will be prompted in the UI.
options='{"url": "jdbc:mysql://localhost:3306/hue", "driver": "com.mysql.jdbc.Driver", "user": "root", "password": "root"}'
## options='{"url": "jdbc:mysql://localhost:3306/hue", "driver": "com.mysql.jdbc.Driver"}'
Error Message:
Traceback (most recent call last):
  File "/home/actian/Hue_server/hue/desktop/libs/notebook/src/notebook/decorators.py", line 114, in wrapper
    return f(*args, **kwargs)
  File "/home/actian/Hue_server/hue/desktop/libs/notebook/src/notebook/api.py", line 735, in autocomplete
    autocomplete_data = get_api(request, snippet).autocomplete(snippet, database, table, column, nested, action)
  File "/home/actian/Hue_server/hue/desktop/libs/notebook/src/notebook/models.py", line 523, in get_api
    return ApiWrapper(request, snippet)
  File "/home/actian/Hue_server/hue/desktop/libs/notebook/src/notebook/models.py", line 509, in __init__
    self.api = _get_api(request, snippet)
  File "/home/actian/Hue_server/hue/desktop/libs/notebook/src/notebook/connectors/base.py", line 467, in get_api
    from notebook.connectors.jdbc import JdbcApi
  File "/home/actian/Hue_server/hue/desktop/libs/notebook/src/notebook/connectors/jdbc.py", line 48
    QueryError('%s: is the DB Proxy server running? Trace: %s' % (....))
Please find the attached error log file
[error.log](https://github.com/cloudera/hue/files/5734809/error.log)

**Comment by balajivenka** [comment]
any updates on this issue?

**Comment by balajivenka** [comment]
waiting for the resolution any updates?

**Comment by detkin82** [comment]
Having same exact issue with every JDBC driver with hue-4.9.0 tarball under Kubernetes. It was built with python3.7 and throws "invalid syntax (jdbc.py, line 47)" with every JDBC driver. 
While hue-4.8.0 tarball was built with python2.7 - and it works

**Comment by romainr** [comment]
Should be a quick fix with https://github.com/cloudera/hue/issues/1483#issuecomment-749645893

**Comment by detkin82** [comment]
Thanks for quick reply! Yes, easy fix fi building - I'm not. Using docker image from repository
Switching away from jdbc drivers - yes, want to do that. How do I tell MySQL driver to use principal/keytab to authenticate though?
