### ISSUE TITLE
add database elasticsearch error

### ISSUE THREAD

**Issue by Level1Accelerator** [cloudera/hue#1492]
hue4.8

[[[es]]]
  name = Elastic Search
  interface=sqlalchemy
  options='{"url": "elasticsearch+http://localhost:9200/"}'

[11/Dec/2020 00:39:11 -0800] sql_alchemy  ERROR    Query Error
Traceback (most recent call last):
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 99, in decorator
    return func(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 345, in autocomplete
    engine = self._get_engine()
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 136, in _get_engine
    ENGINES[engine_key] = self._create_engine()
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 200, in _create_engine
    return create_engine(url, **options)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/SQLAlchemy-1.3.17-py2.7-linux-x86_64.egg/sqlalchemy/engine/__init__.py", line 488, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/SQLAlchemy-1.3.17-py2.7-linux-x86_64.egg/sqlalchemy/engine/strategies.py", line 61, in create
    entrypoint = u._get_entrypoint()
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/SQLAlchemy-1.3.17-py2.7-linux-x86_64.egg/sqlalchemy/engine/url.py", line 172, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/SQLAlchemy-1.3.17-py2.7-linux-x86_64.egg/sqlalchemy/util/langhelpers.py", line 250, in load
    return self.impls[name]()
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/es/__init__.py", line 1, in <module>
    from es.elastic.api import connect
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/es/elastic/__init__.py", line 1, in <module>
    from es.elastic.api import connect
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/es/elastic/api.py", line 22
    **kwargs,
            ^
SyntaxError: invalid syntax
[11/Dec/2020 00:39:11 -0800] decorators   ERROR    Error running autocomplete

**Comment by romainr** [comment]
It works, did you read https://docs.gethue.com/administrator/configuration/connectors/#elastic-search and installed the connector?

And starting tomorrow, the connector will be shipped in the Docker image already.

**Comment by romainr** [comment]
https://github.com/cloudera/hue/pull/1494
