### ISSUE TITLE
[docker] Hue cannot start 

### ISSUE THREAD

**Issue by penggongkui** [cloudera/hue#1562]
docker version: gethue/hue:latest

Traceback (most recent call last):
  File "/usr/share/hue/build/env/bin/hue", line 33, in <module>
    sys.exit(load_entry_point('desktop', 'console_scripts', 'hue')())
  File "/usr/share/hue/desktop/core/src/desktop/manage_entry.py", line 225, in entry
    execute_from_command_line(sys.argv)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/share/hue/desktop/core/src/desktop/management/commands/runcherrypyserver.py", line 69, in handle
    runcpserver(args)
  File "/usr/share/hue/desktop/core/src/desktop/management/commands/runcherrypyserver.py", line 131, in runcpserver
    start_server(options)
  File "/usr/share/hue/desktop/core/src/desktop/management/commands/runcherrypyserver.py", line 78, in start_server
    from desktop.lib.wsgiserver import CherryPyWSGIServer as Server
  File "/usr/share/hue/desktop/core/src/desktop/lib/wsgiserver.py", line 122, in <module>
    _fileobject_uses_str_type = isinstance(socket._fileobject(None)._rbuf, basestring)
AttributeError: module 'socket' has no attribute '_fileobject'

**Comment by romainr** [comment]
Thanks for the report!
