### ISSUE TITLE
Getting this error when I run bin/supervisor

### ISSUE THREAD

**Issue by OElesin** [cloudera/hue#159]
Traceback (most recent call last):
  File "/root/hue/build/env/bin/hue", line 8, in <module>
    load_entry_point('desktop==3.7.1', 'console_scripts', 'hue')()
  File "/root/hue/desktop/core/src/desktop/manage_entry.py", line 60, in entry
    execute_manager(settings)
  File "/root/hue/build/env/lib/python2.7/site-packages/Django-1.4.5-py2.7.egg/django/core/management/__init__.py", line 459, in execute_manager
    utility.execute()
  File "/root/hue/build/env/lib/python2.7/site-packages/Django-1.4.5-py2.7.egg/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/hue/build/env/lib/python2.7/site-packages/Django-1.4.5-py2.7.egg/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/root/hue/build/env/lib/python2.7/site-packages/Django-1.4.5-py2.7.egg/django/core/management/base.py", line 231, in execute
    self.validate()
  File "/root/hue/build/env/lib/python2.7/site-packages/Django-1.4.5-py2.7.egg/django/core/management/base.py", line 266, in validate
    num_errors = get_validation_errors(s, app)
  File "/root/hue/build/env/lib/python2.7/site-packages/Django-1.4.5-py2.7.egg/django/core/management/validation.py", line 30, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/root/hue/build/env/lib/python2.7/site-packages/Django-1.4.5-py2.7.egg/django/db/models/loading.py", line 158, in get_app_errors
    self._populate()
  File "/root/hue/build/env/lib/python2.7/site-packages/Django-1.4.5-py2.7.egg/django/db/models/loading.py", line 64, in _populate
    self.load_app(app_name, True)
  File "/root/hue/build/env/lib/python2.7/site-packages/Django-1.4.5-py2.7.egg/django/db/models/loading.py", line 88, in load_app
    models = import_module('.models', app_name)
  File "/root/hue/build/env/lib/python2.7/site-packages/Django-1.4.5-py2.7.egg/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/root/hue/apps/beeswax/src/beeswax/models.py", line 38, in <module>
    from beeswax.design import HQLdesign
  File "/root/hue/apps/beeswax/src/beeswax/design.py", line 33, in <module>
    from hadoop.cluster import get_hdfs
  File "/root/hue/desktop/libs/hadoop/src/hadoop/cluster.py", line 22, in <module>
    from hadoop.fs import webhdfs, LocalSubFileSystem
  File "/root/hue/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py", line 31, in <module>
    from desktop.lib.rest import http_client, resource
  File "/root/hue/desktop/core/src/desktop/lib/rest/http_client.py", line 19, in <module>
    import requests
  File "/root/hue/build/env/lib/python2.7/site-packages/requests-2.0.0-py2.7.egg/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/root/hue/build/env/lib/python2.7/site-packages/requests-2.0.0-py2.7.egg/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/root/hue/build/env/lib/python2.7/site-packages/requests-2.0.0-py2.7.egg/requests/packages/urllib3/__init__.py", line 16, in <module>
    from .connectionpool import (
  File "/root/hue/build/env/lib/python2.7/site-packages/requests-2.0.0-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 60, in <module>
    from .response import HTTPResponse
  File "/root/hue/build/env/lib/python2.7/site-packages/requests-2.0.0-py2.7.egg/requests/packages/urllib3/response.py", line 53, in <module>
    class HTTPResponse(io.IOBase):
  File "/root/hue/build/env/lib/python2.7/site-packages/requests-2.0.0-py2.7.egg/requests/packages/urllib3/response.py", line 77, in HTTPResponse
    REDIRECT_STATUSES = [301, 302, 303, 307, 308]
KeyboardInterrupt

**Comment by romainr** [comment]
How did you install Hue? Looks like a tarball install.
Is the 'runserver' command working?

For information http://groups.google.com/a/cloudera.org/group/hue-user is better suited for these types of problems.

**Comment by OElesin** [comment]
the 'runserver' command works. And it's a tarball install

**Comment by romainr** [comment]
Which OS?

**Comment by OElesin** [comment]
Ubuntu 14.04
