### ISSUE TITLE
Docker Image not work

### ISSUE THREAD

**Issue by pan3793** [cloudera/hue#1637]
Blocked by hello world, the experience is so bad.
```
➜  Temp docker run -it -p 8888:8888 gethue/hue:latest
[15/Jan/2021 16:12:35 ] settings     INFO     Welcome to Hue 4.8.0
Traceback (most recent call last):
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 168, in _add_installed_apps_translations
    app_configs = reversed(list(apps.get_app_configs()))
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/apps/registry.py", line 138, in get_app_configs
    self.check_apps_ready()
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/apps/registry.py", line 125, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./build/env/bin/hue", line 33, in <module>
    sys.exit(load_entry_point('desktop', 'console_scripts', 'hue')())
  File "/usr/share/hue/desktop/core/src/desktop/manage_entry.py", line 225, in entry
    execute_from_command_line(sys.argv)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/share/hue/build/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/share/hue/desktop/core/src/desktop/settings.py", line 624, in <module>
    if is_s3_enabled():
  File "/usr/share/hue/desktop/libs/aws/src/aws/conf.py", line 262, in is_enabled
    has_iam_metadata() or conf_idbroker.is_idbroker_enabled('s3a')
  File "/usr/share/hue/desktop/core/src/desktop/lib/idbroker/conf.py", line 61, in is_idbroker_enabled
    return get_cab_address(fs) is not None
  File "/usr/share/hue/desktop/core/src/desktop/lib/idbroker/conf.py", line 42, in get_cab_address
    return get_conf().get(_CNF_CAB_ADDRESS % fs) if fs else None
  File "/usr/share/hue/desktop/libs/hadoop/src/hadoop/core_site.py", line 65, in get_conf
    _parse_core_site()
  File "/usr/share/hue/desktop/libs/hadoop/src/hadoop/core_site.py", line 77, in _parse_core_site
    _CORE_SITE_PATH = get_config_root_hadoop('core-site.xml')
  File "/usr/share/hue/desktop/core/src/desktop/lib/paths.py", line 109, in get_config_root_hadoop
    return os.path.abspath(os.path.join(get_hadoop_conf_dir_default_config(), *append))
  File "/usr/share/hue/desktop/core/src/desktop/lib/paths.py", line 95, in get_hadoop_conf_dir_default_config
    yarn_site_path = HDFS_CLUSTERS[list(HDFS_CLUSTERS.keys())[0]].HADOOP_CONF_DIR.get()
  File "/usr/share/hue/desktop/core/src/desktop/lib/conf.py", line 159, in get
    return self.config.get_value(data, present=present, prefix=self.prefix, coerce_type=True)
  File "/usr/share/hue/desktop/core/src/desktop/lib/conf.py", line 273, in get_value
    return self._coerce_type(raw_val, prefix)
  File "/usr/share/hue/desktop/core/src/desktop/lib/conf.py", line 293, in _coerce_type
    return self.type(raw)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/functional.py", line 119, in __text_cast
    return func(*self.__args, **self.__kw)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/__init__.py", line 89, in ugettext
    return _trans.ugettext(message)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 338, in gettext
    return do_translate(message, 'gettext')
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 321, in do_translate
    _default = _default or translation(settings.LANGUAGE_CODE)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 228, in translation
    _translations[language] = DjangoTranslation(language)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 129, in __init__
    self._add_installed_apps_translations()
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 171, in _add_installed_apps_translations
    "The translation infrastructure cannot be initialized before the "
django.core.exceptions.AppRegistryNotReady: The translation infrastructure cannot be initialized before the apps registry is ready. Check that you don't make non-lazy gettext calls at import time.
[15/Jan/2021 16:12:36 ] supervisor   INFO     Starting process /usr/share/hue/build/env/bin/hue kt_renewer
[15/Jan/2021 16:12:36 ] supervisor   INFO     Starting process /usr/share/hue/build/env/bin/hue runcpserver
[15/Jan/2021 16:12:36 ] supervisor   INFO     Started proceses (pid 19) /usr/share/hue/build/env/bin/hue runcpserver
[15/Jan/2021 16:12:37 ] settings     INFO     Welcome to Hue 4.8.0
Traceback (most recent call last):
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 168, in _add_installed_apps_translations
    app_configs = reversed(list(apps.get_app_configs()))
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/apps/registry.py", line 138, in get_app_configs
    self.check_apps_ready()
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/apps/registry.py", line 125, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/hue/build/env/bin/hue", line 33, in <module>
    sys.exit(load_entry_point('desktop', 'console_scripts', 'hue')())
  File "/usr/share/hue/desktop/core/src/desktop/manage_entry.py", line 225, in entry
    execute_from_command_line(sys.argv)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/share/hue/build/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/share/hue/desktop/core/src/desktop/settings.py", line 624, in <module>
    if is_s3_enabled():
  File "/usr/share/hue/desktop/libs/aws/src/aws/conf.py", line 262, in is_enabled
    has_iam_metadata() or conf_idbroker.is_idbroker_enabled('s3a')
  File "/usr/share/hue/desktop/core/src/desktop/lib/idbroker/conf.py", line 61, in is_idbroker_enabled
    return get_cab_address(fs) is not None
  File "/usr/share/hue/desktop/core/src/desktop/lib/idbroker/conf.py", line 42, in get_cab_address
    return get_conf().get(_CNF_CAB_ADDRESS % fs) if fs else None
  File "/usr/share/hue/desktop/libs/hadoop/src/hadoop/core_site.py", line 65, in get_conf
    _parse_core_site()
  File "/usr/share/hue/desktop/libs/hadoop/src/hadoop/core_site.py", line 77, in _parse_core_site
    _CORE_SITE_PATH = get_config_root_hadoop('core-site.xml')
  File "/usr/share/hue/desktop/core/src/desktop/lib/paths.py", line 109, in get_config_root_hadoop
    return os.path.abspath(os.path.join(get_hadoop_conf_dir_default_config(), *append))
  File "/usr/share/hue/desktop/core/src/desktop/lib/paths.py", line 95, in get_hadoop_conf_dir_default_config
    yarn_site_path = HDFS_CLUSTERS[list(HDFS_CLUSTERS.keys())[0]].HADOOP_CONF_DIR.get()
  File "/usr/share/hue/desktop/core/src/desktop/lib/conf.py", line 159, in get
    return self.config.get_value(data, present=present, prefix=self.prefix, coerce_type=True)
  File "/usr/share/hue/desktop/core/src/desktop/lib/conf.py", line 273, in get_value
    return self._coerce_type(raw_val, prefix)
  File "/usr/share/hue/desktop/core/src/desktop/lib/conf.py", line 293, in _coerce_type
    return self.type(raw)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/functional.py", line 119, in __text_cast
    return func(*self.__args, **self.__kw)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/__init__.py", line 89, in ugettext
    return _trans.ugettext(message)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 338, in gettext
    return do_translate(message, 'gettext')
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 321, in do_translate
    _default = _default or translation(settings.LANGUAGE_CODE)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 228, in translation
    _translations[language] = DjangoTranslation(language)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 129, in __init__
    self._add_installed_apps_translations()
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 171, in _add_installed_apps_translations
    "The translation infrastructure cannot be initialized before the "
django.core.exceptions.AppRegistryNotReady: The translation infrastructure cannot be initialized before the apps registry is ready. Check that you don't make non-lazy gettext calls at import time.
[15/Jan/2021 16:12:37 ] supervisor   WARNING  Exit code for /usr/share/hue/build/env/bin/hue runcpserver: 1
[15/Jan/2021 16:12:37 ] supervisor   ERROR    Process /usr/share/hue/build/env/bin/hue runcpserver exited abnormally. Restarting it.
[15/Jan/2021 16:12:37 ] supervisor   INFO     Starting process /usr/share/hue/build/env/bin/hue runcpserver
[15/Jan/2021 16:12:37 ] supervisor   INFO     Started proceses (pid 25) /usr/share/hue/build/env/bin/hue runcpserver
[15/Jan/2021 16:12:37 ] settings     INFO     Welcome to Hue 4.8.0
Traceback (most recent call last):
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 168, in _add_installed_apps_translations
    app_configs = reversed(list(apps.get_app_configs()))
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/apps/registry.py", line 138, in get_app_configs
    self.check_apps_ready()
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/apps/registry.py", line 125, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/hue/build/env/bin/hue", line 33, in <module>
    sys.exit(load_entry_point('desktop', 'console_scripts', 'hue')())
  File "/usr/share/hue/desktop/core/src/desktop/manage_entry.py", line 225, in entry
    execute_from_command_line(sys.argv)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/share/hue/build/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/share/hue/desktop/core/src/desktop/settings.py", line 624, in <module>
    if is_s3_enabled():
  File "/usr/share/hue/desktop/libs/aws/src/aws/conf.py", line 262, in is_enabled
    has_iam_metadata() or conf_idbroker.is_idbroker_enabled('s3a')
  File "/usr/share/hue/desktop/core/src/desktop/lib/idbroker/conf.py", line 61, in is_idbroker_enabled
    return get_cab_address(fs) is not None
  File "/usr/share/hue/desktop/core/src/desktop/lib/idbroker/conf.py", line 42, in get_cab_address
    return get_conf().get(_CNF_CAB_ADDRESS % fs) if fs else None
  File "/usr/share/hue/desktop/libs/hadoop/src/hadoop/core_site.py", line 65, in get_conf
    _parse_core_site()
  File "/usr/share/hue/desktop/libs/hadoop/src/hadoop/core_site.py", line 77, in _parse_core_site
    _CORE_SITE_PATH = get_config_root_hadoop('core-site.xml')
  File "/usr/share/hue/desktop/core/src/desktop/lib/paths.py", line 109, in get_config_root_hadoop
    return os.path.abspath(os.path.join(get_hadoop_conf_dir_default_config(), *append))
  File "/usr/share/hue/desktop/core/src/desktop/lib/paths.py", line 95, in get_hadoop_conf_dir_default_config
    yarn_site_path = HDFS_CLUSTERS[list(HDFS_CLUSTERS.keys())[0]].HADOOP_CONF_DIR.get()
  File "/usr/share/hue/desktop/core/src/desktop/lib/conf.py", line 159, in get
    return self.config.get_value(data, present=present, prefix=self.prefix, coerce_type=True)
  File "/usr/share/hue/desktop/core/src/desktop/lib/conf.py", line 273, in get_value
    return self._coerce_type(raw_val, prefix)
  File "/usr/share/hue/desktop/core/src/desktop/lib/conf.py", line 293, in _coerce_type
    return self.type(raw)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/functional.py", line 119, in __text_cast
    return func(*self.__args, **self.__kw)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/__init__.py", line 89, in ugettext
    return _trans.ugettext(message)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 338, in gettext
    return do_translate(message, 'gettext')
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 321, in do_translate
    _default = _default or translation(settings.LANGUAGE_CODE)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 228, in translation
    _translations[language] = DjangoTranslation(language)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 129, in __init__
    self._add_installed_apps_translations()
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 171, in _add_installed_apps_translations
    "The translation infrastructure cannot be initialized before the "
django.core.exceptions.AppRegistryNotReady: The translation infrastructure cannot be initialized before the apps registry is ready. Check that you don't make non-lazy gettext calls at import time.
[15/Jan/2021 16:12:38 ] supervisor   WARNING  Exit code for /usr/share/hue/build/env/bin/hue runcpserver: 1
[15/Jan/2021 16:12:38 ] supervisor   ERROR    Process /usr/share/hue/build/env/bin/hue runcpserver exited abnormally. Restarting it.
[15/Jan/2021 16:12:38 ] supervisor   INFO     Starting process /usr/share/hue/build/env/bin/hue runcpserver
[15/Jan/2021 16:12:38 ] supervisor   INFO     Started proceses (pid 31) /usr/share/hue/build/env/bin/hue runcpserver
[15/Jan/2021 16:12:38 ] settings     INFO     Welcome to Hue 4.8.0
Traceback (most recent call last):
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 168, in _add_installed_apps_translations
    app_configs = reversed(list(apps.get_app_configs()))
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/apps/registry.py", line 138, in get_app_configs
    self.check_apps_ready()
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/apps/registry.py", line 125, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/hue/build/env/bin/hue", line 33, in <module>
    sys.exit(load_entry_point('desktop', 'console_scripts', 'hue')())
  File "/usr/share/hue/desktop/core/src/desktop/manage_entry.py", line 225, in entry
    execute_from_command_line(sys.argv)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/share/hue/build/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/share/hue/desktop/core/src/desktop/settings.py", line 624, in <module>
    if is_s3_enabled():
  File "/usr/share/hue/desktop/libs/aws/src/aws/conf.py", line 262, in is_enabled
    has_iam_metadata() or conf_idbroker.is_idbroker_enabled('s3a')
  File "/usr/share/hue/desktop/core/src/desktop/lib/idbroker/conf.py", line 61, in is_idbroker_enabled
    return get_cab_address(fs) is not None
  File "/usr/share/hue/desktop/core/src/desktop/lib/idbroker/conf.py", line 42, in get_cab_address
    return get_conf().get(_CNF_CAB_ADDRESS % fs) if fs else None
  File "/usr/share/hue/desktop/libs/hadoop/src/hadoop/core_site.py", line 65, in get_conf
    _parse_core_site()
  File "/usr/share/hue/desktop/libs/hadoop/src/hadoop/core_site.py", line 77, in _parse_core_site
    _CORE_SITE_PATH = get_config_root_hadoop('core-site.xml')
  File "/usr/share/hue/desktop/core/src/desktop/lib/paths.py", line 109, in get_config_root_hadoop
    return os.path.abspath(os.path.join(get_hadoop_conf_dir_default_config(), *append))
  File "/usr/share/hue/desktop/core/src/desktop/lib/paths.py", line 95, in get_hadoop_conf_dir_default_config
    yarn_site_path = HDFS_CLUSTERS[list(HDFS_CLUSTERS.keys())[0]].HADOOP_CONF_DIR.get()
  File "/usr/share/hue/desktop/core/src/desktop/lib/conf.py", line 159, in get
    return self.config.get_value(data, present=present, prefix=self.prefix, coerce_type=True)
  File "/usr/share/hue/desktop/core/src/desktop/lib/conf.py", line 273, in get_value
    return self._coerce_type(raw_val, prefix)
  File "/usr/share/hue/desktop/core/src/desktop/lib/conf.py", line 293, in _coerce_type
    return self.type(raw)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/functional.py", line 119, in __text_cast
    return func(*self.__args, **self.__kw)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/__init__.py", line 89, in ugettext
    return _trans.ugettext(message)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 338, in gettext
    return do_translate(message, 'gettext')
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 321, in do_translate
    _default = _default or translation(settings.LANGUAGE_CODE)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 228, in translation
    _translations[language] = DjangoTranslation(language)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 129, in __init__
    self._add_installed_apps_translations()
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 171, in _add_installed_apps_translations
    "The translation infrastructure cannot be initialized before the "
django.core.exceptions.AppRegistryNotReady: The translation infrastructure cannot be initialized before the apps registry is ready. Check that you don't make non-lazy gettext calls at import time.
[15/Jan/2021 16:12:39 ] supervisor   WARNING  Exit code for /usr/share/hue/build/env/bin/hue runcpserver: 1
[15/Jan/2021 16:12:39 ] supervisor   ERROR    Process /usr/share/hue/build/env/bin/hue runcpserver exited abnormally. Restarting it.
[15/Jan/2021 16:12:39 ] supervisor   INFO     Starting process /usr/share/hue/build/env/bin/hue runcpserver
[15/Jan/2021 16:12:39 ] supervisor   INFO     Started proceses (pid 37) /usr/share/hue/build/env/bin/hue runcpserver
[15/Jan/2021 16:12:39 ] settings     INFO     Welcome to Hue 4.8.0
Traceback (most recent call last):
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 168, in _add_installed_apps_translations
    app_configs = reversed(list(apps.get_app_configs()))
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/apps/registry.py", line 138, in get_app_configs
    self.check_apps_ready()
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/apps/registry.py", line 125, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/hue/build/env/bin/hue", line 33, in <module>
    sys.exit(load_entry_point('desktop', 'console_scripts', 'hue')())
  File "/usr/share/hue/desktop/core/src/desktop/manage_entry.py", line 225, in entry
    execute_from_command_line(sys.argv)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/share/hue/build/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/share/hue/desktop/core/src/desktop/settings.py", line 624, in <module>
    if is_s3_enabled():
  File "/usr/share/hue/desktop/libs/aws/src/aws/conf.py", line 262, in is_enabled
    has_iam_metadata() or conf_idbroker.is_idbroker_enabled('s3a')
  File "/usr/share/hue/desktop/core/src/desktop/lib/idbroker/conf.py", line 61, in is_idbroker_enabled
    return get_cab_address(fs) is not None
  File "/usr/share/hue/desktop/core/src/desktop/lib/idbroker/conf.py", line 42, in get_cab_address
    return get_conf().get(_CNF_CAB_ADDRESS % fs) if fs else None
  File "/usr/share/hue/desktop/libs/hadoop/src/hadoop/core_site.py", line 65, in get_conf
    _parse_core_site()
  File "/usr/share/hue/desktop/libs/hadoop/src/hadoop/core_site.py", line 77, in _parse_core_site
    _CORE_SITE_PATH = get_config_root_hadoop('core-site.xml')
  File "/usr/share/hue/desktop/core/src/desktop/lib/paths.py", line 109, in get_config_root_hadoop
    return os.path.abspath(os.path.join(get_hadoop_conf_dir_default_config(), *append))
  File "/usr/share/hue/desktop/core/src/desktop/lib/paths.py", line 95, in get_hadoop_conf_dir_default_config
    yarn_site_path = HDFS_CLUSTERS[list(HDFS_CLUSTERS.keys())[0]].HADOOP_CONF_DIR.get()
  File "/usr/share/hue/desktop/core/src/desktop/lib/conf.py", line 159, in get
    return self.config.get_value(data, present=present, prefix=self.prefix, coerce_type=True)
  File "/usr/share/hue/desktop/core/src/desktop/lib/conf.py", line 273, in get_value
    return self._coerce_type(raw_val, prefix)
  File "/usr/share/hue/desktop/core/src/desktop/lib/conf.py", line 293, in _coerce_type
    return self.type(raw)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/functional.py", line 119, in __text_cast
    return func(*self.__args, **self.__kw)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/__init__.py", line 89, in ugettext
    return _trans.ugettext(message)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 338, in gettext
    return do_translate(message, 'gettext')
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 321, in do_translate
    _default = _default or translation(settings.LANGUAGE_CODE)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 228, in translation
    _translations[language] = DjangoTranslation(language)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 129, in __init__
    self._add_installed_apps_translations()
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 171, in _add_installed_apps_translations
    "The translation infrastructure cannot be initialized before the "
django.core.exceptions.AppRegistryNotReady: The translation infrastructure cannot be initialized before the apps registry is ready. Check that you don't make non-lazy gettext calls at import time.
[15/Jan/2021 16:12:40 ] supervisor   WARNING  Exit code for /usr/share/hue/build/env/bin/hue runcpserver: 1
[15/Jan/2021 16:12:40 ] supervisor   ERROR    Process /usr/share/hue/build/env/bin/hue runcpserver has restarted more than 3 times in the last 2 seconds
[15/Jan/2021 16:12:41 ] supervisor   WARNING  Supervisor shutting down!
[15/Jan/2021 16:12:41 ] supervisor   WARNING  Waiting for children to exit for 5 seconds...
[15/Jan/2021 16:12:46 ] supervisor   WARNING  Children have not exited after 5 seconds. Killing them with SIGKILL.
[15/Jan/2021 16:12:46 ] supervisor   ERROR    Exception in supervisor main loop
Traceback (most recent call last):
  File "/usr/share/hue/desktop/core/src/desktop/supervisor.py", line 385, in main
    wait_loop(sups, options)
  File "/usr/share/hue/desktop/core/src/desktop/supervisor.py", line 402, in wait_loop
    shutdown(sups)  # shutdown() exits the process
  File "/usr/share/hue/desktop/core/src/desktop/supervisor.py", line 218, in shutdown
    sys.exit(1)
SystemExit: 1
[15/Jan/2021 16:12:46 ] supervisor   WARNING  Supervisor shutting down!
[15/Jan/2021 16:12:46 ] supervisor   WARNING  Waiting for children to exit for 5 seconds...
[15/Jan/2021 16:12:51 ] supervisor   WARNING  Children have not exited after 5 seconds. Killing them with SIGKILL.
```

**Comment by romainr** [comment]
`latest` image should have the fix
