### ISSUE TITLE
Get sharable link from Editor errors

### ISSUE THREAD

**Issue by romainr** [cloudera/hue#1661]
[2021-01-20 17:57:43 +0000] [34] [DEBUG] POST /desktop/api2/gist/create
    [20/Jan/2021 09:57:43 -0800] api2         ERROR    Error running <function gist_create at 0x7f59d715d048>
    Traceback (most recent call last):
      File "/usr/share/hue/desktop/core/src/desktop/api2.py", line 73, in decorator
        return func(*args, **kwargs)
      File "/usr/share/hue/desktop/core/src/desktop/api2.py", line 945, in gist_create
        parent_directory=Document2.objects.get_gist_directory(request.user)
      File "/usr/share/hue/desktop/core/src/desktop/models.py", line 1071, in get_gist_directory
        gist_dir, created = Directory.objects.get_or_create(name=Document2.GIST_DIR, owner=user, parent_directory=home_dir)
      File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
        return getattr(self.get_queryset(), name)(*args, **kwargs)
      File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/db/models/query.py", line 464, in get_or_create
        return self.get(**lookup), False
      File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/db/models/query.py", line 384, in get
        (self.model._meta.object_name, num)
    desktop.models.MultipleObjectsReturned: get() returned more than one Directory -- it returned 3!
    [20/Jan/2021 09:57:43 -0800] access       INFO     73.71.51.214 demo - "POST /desktop/api2/gist/create HTTP/1.0" returned in 9ms 200 85

**Comment by romainr** [comment]
Might or might not be a one off

  from desktop.models import Directory, Document2
  Directory.objects.filter(name=Document2.GIST_DIR).delete()
(153, {'desktop.Document2_dependencies': 0, 'desktop.Document_tags': 51, 'desktop.Directory': 4, 'desktop.Document2': 47, 'desktop.Document': 51})

**Comment by Akhilsnaik** [comment]
is this issue reproducable, i am not able to reproduce it on the latest master branch hue.

**Comment by romainr** [comment]
Yes same, will close and will see. It is planned to refresh it while doing the Slack integration so will keep in mind.
