### ISSUE TITLE
[Pig to Hbase] using pig to parse data and store back to hbase in kerberos environment

### ISSUE THREAD

**Issue by polingsky** [cloudera/hue#170]
We use pig to parse data from hdfs and finally store back to hbase in kerberos environment
But we encountered a problem.
If i use 'testuser' to login into the hue, and to execute the pig task

The error like this:

DFSClient_attempt_1429154075368_0059_m_000000_0_-1563104544_1] for 81 seconds.  Will retry shortly ...
org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.security.token.SecretManager$InvalidToken): token (HDFS_DELEGATION_TOKEN token 279 for testuser) can't be found in cache
     at org.apache.hadoop.ipc.Client.call(Client.java:1468)
     at org.apache.hadoop.ipc.Client.call(Client.java:1399)
     at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:232)
     at com.sun.proxy.$Proxy15.renewLease(Unknown Source)
     at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.renewLease(ClientNamenodeProtocolTranslatorPB.java:571)
     at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:606)
     at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187)
     at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
     at com.sun.proxy.$Proxy16.renewLease(Unknown Source)
     at org.apache.hadoop.hdfs.DFSClient.renewLease(DFSClient.java:879)
     at org.apache.hadoop.hdfs.LeaseRenewer.renew(LeaseRenewer.java:417)
     at org.apache.hadoop.hdfs.LeaseRenewer.run(LeaseRenewer.java:442)
     at org.apache.hadoop.hdfs.LeaseRenewer.access$700(LeaseRenewer.java:71)
     at org.apache.hadoop.hdfs.LeaseRenewer$1.run(LeaseRenewer.java:298)
     at java.lang.Thread.run(Thread.java:745)
2015-04-16 14:58:21,699 [LeaseRenewer:testuser@hostname.example.com:8020] WARN  org.apache.hadoop.ipc.Client  - Exception encountered while connecting to the server : 

I's like to know that we create hue keytab for kerberos
and I originally think that the testuser will be impersonate to be hue 
But it seems to something wrong

Does anyone has some ideas for me!~~~

thanks so much~~~~

**Comment by romainr** [comment]
Is testuser a real user? You only need a hue user keytab and Hue is going to impersonate all the other
