### ISSUE TITLE
Hue 3.8.0 Tarball issues with LDAP integration

### ISSUE THREAD

**Issue by searchwizard** [cloudera/hue#178]
It looks like a fix is not included in the tarball. apps/useradmin/src/useradmin/ldap_access.py in master branch is using a method called get_ldap_bind_password which takes an argument. But the same file in tarball is using a method called get_ldap_password()

Following is the exception I ran into:

```
[27/Apr/2015 11:33:58 -0400] middleware   INFO     Processing exception: get_ldap_password() takes no arguments (1 given): Traceback (most recent call last):
  File "/opt/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/opt/hue/apps/useradmin/src/useradmin/views.py", line 332, in add_ldap_users
    connection = ldap_access.get_connection_from_server(server)
  File "/opt/hue/apps/useradmin/src/useradmin/ldap_access.py", line 39, in get_connection_from_server
    return get_connection(ldap_config)
  File "/opt/hue/apps/useradmin/src/useradmin/ldap_access.py", line 48, in get_connection
    password = desktop.conf.get_ldap_password(ldap_config)
TypeError: get_ldap_password() takes no arguments (1 given)
```

**Comment by romainr** [comment]
Thanks, this is true, I just put the commit in https://github.com/cloudera/hue/commits/branch-3.8

Will prepare a 3.8.1 tarball release

**Comment by romainr** [comment]
3.8.1 release is out https://github.com/cloudera/hue/tree/release-3.8.1 with a tarball link in http://gethue.com/hue-3-8-with-an-oozie-editor-revamp-better-performances-improved-spark-ui-is-out/
