### ISSUE TITLE
Filebrowser xxd fails on binary files in Python 3 runtime

### ISSUE THREAD

**Issue by rickb78** [cloudera/hue#1799]
**Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?** 
- No

**Describe the bug:**

- When trying to view any binary file in the File Browser when Hue is run using Python 3.7, it is now frequently failing with the below stack trace.  This appears failing in python 3 runtime environments since Hue 4.7.  As such, users get 500 errors when trying to view any binary file.

```
Traceback (most recent call last):
  File "build/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "build/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "build/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "build/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "apps/filebrowser/src/filebrowser/views.py", line 217, in view
    return display(request, path)
  File "apps/filebrowser/src/filebrowser/views.py", line 704, in display
    xxd_out = list(xxd.xxd(offset, contents, BYTES_PER_LINE, BYTES_PER_SENTENCE))
  File "apps/filebrowser/src/filebrowser/lib/xxd.py", line 69, in xxd
    line_printable = mask_not_alphanumeric(line)[1]
  File "apps/filebrowser/src/filebrowser/lib/xxd.py", line 51, in mask_not_alphanumeric
    return mask_not_printable(data, NON_FANCY_PRINTABLE)
  File "apps/filebrowser/src/filebrowser/lib/xxd.py", line 44, in mask_not_printable
    out, cnt = mask_re.subn('.', contents)
TypeError: cannot use a string pattern on a bytes-like object
```

**Steps to reproduce it?**

- Upload any binary file to the filebrowser.  Then click on it to try and open and view it.

**Hue version or source?** 
- Any version of Hue 4.7 and newer.  Python 3.7 runtime environment, RHEL 7.

**Comment by rickb78** [comment]
A proposed possible fix:

https://github.com/cloudera/hue/pull/1810

**Comment by rickb78** [comment]
@romainr , created a new PR to address that I had added to the prior one.  See https://github.com/cloudera/hue/pull/1842

Also, which specific tool are you requiring for style checking?  Thanks...

**Comment by romainr** [comment]
Currently it is a minimal Pytlint with https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/management/commands/runpylint.py#L30

This will get easier in a few months with auto fixing of the style.

**Comment by rickb78** [comment]
@romainr I see that this issue is closed, but https://github.com/cloudera/hue/pull/1842 is not yet merged, is there anything else that needs to be done?

**Comment by romainr** [comment]
Fluke in the CI, but it should auto close after next re-run passes!
