### ISSUE TITLE
Get Sharable Link is not working on demo.gethue

### ISSUE THREAD

**Issue by Harshg999** [cloudera/hue#1809]
Describe the bug:
When trying to generate the sharable link on demo.gethue, following error pops up 

<img width="1252" alt="Screenshot 2021-02-23 at 8 42 11 PM" src="https://user-images.githubusercontent.com/42064744/108863823-9d480400-7617-11eb-8cd5-e0e5d1addf49.png">

**Comment by romainr** [comment]
```

[2021-02-23 18:17:07 +0000] [34] [DEBUG] POST /desktop/api2/gist/create
[23/Feb/2021 10:17:07 -0800] api2         ERROR    Error running <function gist_create at 0x7f406417dd90>
Traceback (most recent call last):
  File "/usr/share/hue/desktop/core/src/desktop/api2.py", line 73, in decorator
    return func(*args, **kwargs)
  File "/usr/share/hue/desktop/core/src/desktop/api2.py", line 945, in gist_create
    parent_directory=Document2.objects.get_gist_directory(request.user)
  File "/usr/share/hue/desktop/core/src/desktop/models.py", line 1071, in get_gist_directory
    gist_dir, created = Directory.objects.get_or_create(name=Document2.GIST_DIR, owner=user, parent_directory=home_dir)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/db/models/query.py", line 559, in get_or_create
    return self.get(**kwargs), False
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/db/models/query.py", line 422, in get
    num if not limit or num < limit else 'more than %s' % (limit - 1),
desktop.models.Directory.MultipleObjectsReturned: get() returned more than one Directory -- it returned 4!
[23/Feb/2021 10:17:07 -0800] access       INFO     73.71.51.214 demo - "POST /desktop/api2/gist/create HTTP/1.0" returned in 9ms 200 85
```

**Comment by romainr** [comment]
Probably better to repro and add a test then:

1. Fix root cause (where do we do a create() without checking if it exists already)
2. Fix here when we retrieve it by deleting all but one directory
