### ISSUE TITLE
Error when connecting to sparksql via hiveserver2 interface

### ISSUE THREAD

**Issue by bmv126** [cloudera/hue#1843]
Describe the bug:

I have followed the below documentation for connecting to spark sql server.
https://medium.com/data-querying/a-sparksql-editor-via-hue-and-the-spark-sql-server-f82e72bbdfc7

The spark thrift is unsecured and it connects properly using sqlalchemy interface. The spark thrift is based on spark 3.0 version.
When I try via the hiveserver2 interface to connect to spark thrift server, I get below error. Not sure if this is a known issue or if something I am missing
```
21/03/02 17:18:41 DEBUG TSaslServerTransport: transport map does not contain key
21/03/02 17:18:41 DEBUG TSaslTransport: opening transport org.apache.thrift.transport.TSaslServerTransport@4b30acf7
21/03/02 17:18:41 DEBUG TSaslTransport: SERVER: Writing message with status ERROR and payload length 19
21/03/02 17:18:41 DEBUG TSaslServerTransport: failed to open server transport
org.apache.thrift.transport.TTransportException: Invalid status -128
        at org.apache.thrift.transport.TSaslTransport.sendAndThrowMessage(TSaslTransport.java:232)
        at org.apache.thrift.transport.TSaslTransport.receiveSaslMessage(TSaslTransport.java:184)
        at org.apache.thrift.transport.TSaslServerTransport.handleSaslStartMessage(TSaslServerTransport.java:127)
        at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:271)
        at org.apache.thrift.transport.TSaslServerTransport.open(TSaslServerTransport.java:43)
        at org.apache.thrift.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:223)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

Below is the content of hue.ini file:
```
    [beeswax]
    server_conn_timeout=120
    hive_conf_dir=/mnt/hadoop
    thrift_version=7

    [spark]
    sql_server_host=10.15.121.211
    sql_server_port=30006
    use_sasl=false

    [notebook]
    show_notebooks=true
    enable_batch_execute=true
    enable_external_statements=false
    enable_query_builder=true
    enable_query_analysis=true

    [[interpreters]]
	
    [[[sparksql]]]
    name=SparkSql (via HiveServer2)
    interface=hiveserver2
```

Steps to reproduce it?
Try to access spark sql editor and below error is seen in the UI:
`TSocket read 0 bytes (code THRIFTTRANSPORT): TTransportException('TSocket read 0 bytes',)`

I am using python3 and below pip modules are installed:
```
(app-root) bash-4.2# ./build/env/bin/pip freeze | grep -i thrift
thrift==0.13.0
thrift-sasl==0.2.1
thriftpy==0.3.9
```

Hue version or source?
4.9.0

**Comment by romainr** [comment]
Would recommend to give a go via SqlAlchemy interface instead, not hiveserver2:

https://docs.gethue.com/administrator/configuration/connectors/#apache-spark-sql
https://gethue.com/blog/querying-spark-sql-with-spark-thrift-server-and-hue-editor/

**Comment by bmv126** [comment]
@romainr 
I have tried with SqlAlchemy interface and it is working.
Is there any advantage or disadvantage of using SqlAlchemy over the hiveserver2 interface ?
