### ISSUE TITLE
start error

### ISSUE THREAD

**Issue by huyang19881115** [cloudera/hue#1884]
+ /opt/cloudera/parcels/CDH-5.9.0-1.cdh5.9.0.p0.23/lib/hue/build/env/bin/hue syncdb --noinput
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Traceback (most recent call last):
  File "/opt/cloudera/parcels/CDH-5.9.0-1.cdh5.9.0.p0.23/lib/hue/build/env/bin/hue", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/opt/cloudera/parcels/CDH-5.9.0-1.cdh5.9.0.p0.23/lib/hue/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 18, in <module>
    from __future__ import absolute_import
ImportError: No module named __future__
+ '[' -z '' ']'
+ MERGE_FLAG=--merge
+ '[' 5 -ge 5 ']'
+ /opt/cloudera/parcels/CDH-5.9.0-1.cdh5.9.0.p0.23/lib/hue/build/env/bin/hue migrate --merge
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Traceback (most recent call last):
  File "/opt/cloudera/parcels/CDH-5.9.0-1.cdh5.9.0.p0.23/lib/hue/build/env/bin/hue", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/opt/cloudera/parcels/CDH-5.9.0-1.cdh5.9.0.p0.23/lib/hue/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 18, in <module>
    from __future__ import absolute_import
ImportError: No module named __future__
+ '[' dumpdata = runcpserver ']'
+ '[' syncdb = runcpserver ']'
+ exec /opt/cloudera/parcels/CDH-5.9.0-1.cdh5.9.0.p0.23/lib/hue/build/env/bin/hue runcpserver
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Traceback (most recent call last):
  File "/opt/cloudera/parcels/CDH-5.9.0-1.cdh5.9.0.p0.23/lib/hue/build/env/bin/hue", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/opt/cloudera/parcels/CDH-5.9.0-1.cdh5.9.0.p0.23/lib/hue/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 18, in <module>
    from __future__ import absolute_import
ImportError: No module named __future__

find

**Comment by romainr** [comment]
CDH-5.9.0, this is very old and Cloudera. Any luck with using `latest` upstream release/Docker instead?

PS: maybe your Python version is not >= 2.7
