### ISSUE TITLE
Failed to retrieve buckets: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by pkhadka56** [cloudera/hue#1930]
Hello,

I am trying to use minio as aws s3 alternative, but  am unable to make it work. I have the following configuration in the `hue.ini` file. 

```
    [aws]
    [[aws_accounts]]
    [[[default]]]
    access_key_id=ACCESS-KEY
    secret_access_key=SECRET-KEY
    proxy_address=10.1.1.2
    proxy_port=9000
    is_secure: true
```    

PS: I am using this in kubernetes. I have used [helm chart](https://artifacthub.io/packages/helm/hue/hue) to deploy hue. The minio is not in kubernetes cluster but in same network.

**Comment by romainr** [comment]
It would help more to share the full stack trace?

**Comment by pkhadka56** [comment]
Here is the log

```
Traceback (most recent call last):
  File "/usr/share/hue/apps/filebrowser/src/filebrowser/views.py", line 248, in view
    return listdir_paged(request, path)
  File "/usr/share/hue/apps/filebrowser/src/filebrowser/views.py", line 504, in listdir_paged
    all_stats = request.fs.do_as_user(do_as, request.fs.listdir_stats, path)
  File "/usr/share/hue/desktop/core/src/desktop/lib/fs/proxyfs.py", line 131, in do_as_user
    return fn(*args, **kwargs)
  File "/usr/share/hue/desktop/core/src/desktop/lib/fs/proxyfs.py", line 153, in listdir_stats
    return self._get_fs(path).listdir_stats(path, **kwargs)
  File "/usr/share/hue/desktop/libs/aws/src/aws/s3/__init__.py", line 54, in wrapped
    return fn(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/aws/src/aws/s3/s3fs.py", line 309, in listdir_stats
    raise S3FileSystemException(_('Failed to retrieve buckets: %s') % e)
aws.s3.s3fs.S3FileSystemException: Failed to retrieve buckets: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/share/hue/apps/filebrowser/src/filebrowser/views.py", line 259, in view
    raise PopupException(msg, detail=e)
desktop.lib.exceptions_renderable.PopupException: S3 filesystem exception.
[24/Mar/2021 07:22:25 -0700] exceptions_renderable ERROR    Potential trace: [<FrameSummary file /usr/share/hue/apps/filebrowser/src/filebrowser/views.py, line 248 in view>, <FrameSummary file /usr/share/hue/apps/filebrowser/src/filebrowser/views.py, line 504 in listdir_paged>, <FrameSummary file /usr/share/hue/desktop/core/src/desktop/lib/fs/proxyfs.py, line 131 in do_as_user>, <FrameSummary file /usr/share/hue/desktop/core/src/desktop/lib/fs/proxyfs.py, line 153 in listdir_stats>, <FrameSummary file /usr/share/hue/desktop/libs/aws/src/aws/s3/__init__.py, line 54 in wrapped>, <FrameSummary file /usr/share/hue/desktop/libs/aws/src/aws/s3/s3fs.py, line 309 in listdir_stats>]
[24/Mar/2021 07:22:25 -0700] exceptions_renderable ERROR    Potential detail: Failed to retrieve buckets: a bytes-like object is required, not 'str'
[24/Mar/2021 07:22:25 -0700] connection   DEBUG    Proxy connection: CONNECT s3.amazonaws.com:443 HTTP/1.0
[24/Mar/2021 07:22:25 -0700] connection   DEBUG    establishing HTTPS connection: host=s3.amazonaws.com, kwargs={'timeout': 60, 'port': 443}
[24/Mar/2021 07:22:25 -0700] connection   DEBUG    Params: {}
[24/Mar/2021 07:22:25 -0700] connection   DEBUG    Port: 443
[24/Mar/2021 07:22:25 -0700] connection   DEBUG    Host: s3.amazonaws.com:443
[24/Mar/2021 07:22:25 -0700] connection   DEBUG    Headers: {}
[24/Mar/2021 07:22:25 -0700] connection   DEBUG    Data: 
[24/Mar/2021 07:22:25 -0700] connection   DEBUG    Path: https://s3.amazonaws.com:443/
[24/Mar/2021 07:22:25 -0700] connection   DEBUG    Method: GET
[24/Mar/2021 07:22:25 -0700] connection   DEBUG    auth_path=/
[24/Mar/2021 07:22:25 -0700] connection   DEBUG    path=/
[24/Mar/2021 07:22:25 -0700] provider     DEBUG    Using secret key provided by client.
[24/Mar/2021 07:22:25 -0700] provider     DEBUG    Using access key provided by client.
[24/Mar/2021 07:22:25 -0700] access       INFO     10.42.3.0 admin - "GET /desktop/api2/contex
```

**Comment by romainr** [comment]
There is probably some Python3 releated issues. To check if `path` or other params need to be converted to bytes.

https://github.com/cloudera/hue/blob/master/desktop/libs/aws/src/aws/s3/s3fs.py#L294
