### ISSUE TITLE
hue helm not working

### ISSUE THREAD

**Issue by pkhadka56** [cloudera/hue#1934]
Hello,

I used the given instructon to run the helm of hue but I got CrashLoopBackOff error:

```
kubectl get po -n hue
NAME                            READY   STATUS             RESTARTS   AGE
postgres-hue-5d5ccf4f8c-cq5fz   1/1     Running            0          26m
hue-7cd544b97b-jrxsr            1/2     CrashLoopBackOff   8          26m
```

Also the log of hue container
```
kubectl logs hue-7cd544b97b-jrxsr -n hue -c hue
WARNINGS:
?: (axes.W002) You do not have 'axes.middleware.AxesMiddleware' in your settings.MIDDLEWARE.
?: (axes.W003) You do not have 'axes.backends.AxesBackend' or a subclass in your settings.AUTHENTICATION_BACKENDS.
	HINT: AxesModelBackend was renamed to AxesBackend in django-axes version 5.0.
desktop.Document2.is_trashed: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
	HINT: Use BooleanField(null=True) instead.

Error: class uri 'gevent' invalid or not found: 

[Traceback (most recent call last):
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 20, in <module>
    import gevent
ModuleNotFoundError: No module named 'gevent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/gunicorn/util.py", line 135, in load_class
    mod = import_module('.'.join(components))
  File "/usr/share/hue/build/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 22, in <module>
    raise RuntimeError("You need gevent installed to use this worker.")
RuntimeError: You need gevent installed to use this worker.
]

[24/Mar/2021 17:09:46 ] supervisor   WARNING  Exit code for /usr/share/hue/build/env/bin/hue runcpserver: 1
[24/Mar/2021 17:09:46 ] supervisor   ERROR    Process /usr/share/hue/build/env/bin/hue runcpserver exited abnormally. Restarting it.
[24/Mar/2021 17:09:46 ] supervisor   INFO     Starting process /usr/share/hue/build/env/bin/hue runcpserver
[24/Mar/2021 17:09:46 ] supervisor   INFO     Started proceses (pid 53) /usr/share/hue/build/env/bin/hue runcpserver
[24/Mar/2021 17:09:47 ] settings     INFO     Welcome to Hue 4.9.0
[24/Mar/2021 10:09:49 -0700] backend      WARNING  pam module not found
[24/Mar/2021 10:09:49 -0700] backend      WARNING  mozilla_django_oidc module not found
[24/Mar/2021 10:09:49 -0700] client       WARNING  gcs_oauth2_boto_plugin module not found
[24/Mar/2021 10:09:50 -0700] apps         INFO     AXES: BEGIN LOG
[24/Mar/2021 10:09:50 -0700] apps         INFO     AXES: Using django-axes version 5.13.0
[24/Mar/2021 10:09:50 -0700] apps         INFO     AXES: blocking by IP only.
[24/Mar/2021 10:09:50 -0700] hiveserver2  WARNING  Job Browser app is not enabled
[24/Mar/2021 10:09:50 -0700] api          WARNING  Oozie application is not enabled: Model class oozie.models.Job doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
[24/Mar/2021 10:09:50 -0700] views        WARNING  httplib2 module not found
[24/Mar/2021 10:09:50 -0700] backend      WARNING  httplib2 module not found
[24/Mar/2021 10:09:50 -0700] urls         WARNING  djangosaml2 module not found
[24/Mar/2021 10:09:50 -0700] api3         WARNING  simple_salesforce module not found
[24/Mar/2021 10:09:50 -0700] jdbc         WARNING  Failed to import py4j
[24/Mar/2021 10:09:52 -0700] settings     INFO     Welcome to Hue 4.9.0
[24/Mar/2021 10:09:53 -0700] backend      WARNING  pam module not found
[24/Mar/2021 10:09:53 -0700] backend      WARNING  mozilla_django_oidc module not found
[24/Mar/2021 10:09:54 -0700] client       WARNING  gcs_oauth2_boto_plugin module not found
```

**Comment by romainr** [comment]
Indeed, I think we need https://github.com/cloudera/hue/pull/1938
