### ISSUE TITLE
Hue 4.9 build shows distutils-related errors

### ISSUE THREAD

**Issue by elukey** [cloudera/hue#1996]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?

Not that I can see!

Describe the bug:

After building the Vanilla Hue 4.9 from its related branch-4.9.0 I noticed the following error in supervisor.log:

```
[12/Apr/2021 07:06:39 ] supervisor   ERROR    Exception in supervisor main loop
Traceback (most recent call last):
  File "/usr/lib/hue/desktop/core/src/desktop/supervisor.py", line 360, in main
    for name, supervisee in get_supervisees().items():
  File "/usr/lib/hue/desktop/core/src/desktop/supervisor.py", line 244, in get_supervisees
    return dict((ep.name, ep.load()) for ep in eps)
  File "/usr/lib/hue/desktop/core/src/desktop/supervisor.py", line 244, in <genexpr>
    return dict((ep.name, ep.load()) for ep in eps)
  File "/usr/lib/hue/build/env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/lib/hue/build/env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/hue/desktop/core/src/desktop/kt_renewer.py", line 23, in <module>
    from desktop.conf import KERBEROS as CONF
  File "/usr/lib/hue/desktop/core/src/desktop/conf.py", line 29, in <module>
    from django.db import connection
  File "/usr/lib/hue/build/env/lib/python3.7/site-packages/django/__init__.py", line 1, in <module>
    from django.utils.version import get_version
  File "/usr/lib/hue/build/env/lib/python3.7/site-packages/django/utils/version.py", line 6, in <module>
    from distutils.version import LooseVersion
  File "/usr/lib/hue/build/env/lib/python3.7/distutils/__init__.py", line 25, in <module>
    from distutils import dist, sysconfig
ImportError: cannot import name 'dist' from 'distutils' (/usr/lib/hue/build/env/lib/python3.7/distutils/__init__.py)
```

This errors clears out on Debian after installing python3-distutils, but I am wondering if anything is missing in the build process since the errors did not come up in previous releases. 

Steps to reproduce it?

Just start Hue 4.9 and check the supervisor.log, since the daemon fails to start.

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).

Open source / vanilla 4.9

**Comment by romainr** [comment]
Which OS?

**Comment by elukey** [comment]
> Which OS?

Debian 10 :)

**Comment by romainr** [comment]
Well, for Py3 we added it in the dependencies: https://docs.gethue.com/administrator/installation/dependencies/#ubuntu
