### ISSUE TITLE
HUE Oozie Error when Accessing Coordinator via Workflows -> Dashboard

### ISSUE THREAD

**Issue by sarus** [cloudera/hue#203]
We are running HUE 3.5.0

This used to work for us but all of sudden when I click on Workflows -> Editor -> Coordinators I get the following error:

```
Error!
An error occurred with Oozie.
E0603: SQL error in operation, Failed to execute query "select count(a) from CoordinatorActionBean a where a.jobId = :jobId". Check the query syntax for correctness. See nested exception for details.
 More Info   View Logs 
File Name	Line Number	Function Name
/opt/cloudera/parcels/CDH-5.0.2-1.cdh5.0.2.p0.13/lib/hue/apps/oozie/src/oozie/views/dashboard.py	88	decorate
/opt/cloudera/parcels/CDH-5.0.2-1.cdh5.0.2.p0.13/lib/hue/apps/oozie/src/oozie/views/dashboard.py	138	list_oozie_coordinators
/opt/cloudera/parcels/CDH-5.0.2-1.cdh5.0.2.p0.13/lib/hue/apps/oozie/src/oozie/views/dashboard.py	780	split_oozie_jobs
/opt/cloudera/parcels/CDH-5.0.2-1.cdh5.0.2.p0.13/lib/hue/desktop/libs/liboozie/src/liboozie/oozie_api.py	161	get_coordinator
/opt/cloudera/parcels/CDH-5.0.2-1.cdh5.0.2.p0.13/lib/hue/desktop/core/src/desktop/lib/rest/resource.py	90	get
/opt/cloudera/parcels/CDH-5.0.2-1.cdh5.0.2.p0.13/lib/hue/desktop/core/src/desktop/lib/rest/resource.py	73	invoke
/opt/cloudera/parcels/CDH-5.0.2-1.cdh5.0.2.p0.13/lib/hue/desktop/core/src/desktop/lib/rest/http_client.py	154	execute
```

The error started happening after I tried to kill a coordinator that was running.  Restarting HUE doesn't fix anything.  It looks like the database might be corrupted?  I can click on the Workflows tab without any problem but Coordinators no longer works.

Any ideas on how to fix this?

Thank you!

**Comment by sarus** [comment]
Just found the rest of the logs via Cloudera Manager for this error.  There are actually lots of other SQL errors there.  Here is the one that corresponds to the error above:

```
SERVER[hue1.xxx.local] USER[hue doAs dataloader] GROUP[-] TOKEN[-] APP[-] JOB[-] ACTION[-] XException, 
org.apache.oozie.command.CommandException: E0603: SQL error in operation, Failed to execute query "select count(a) from CoordinatorActionBean a where a.jobId = :jobId". Check the query syntax for correctness. See nested exception for details.
         at org.apache.oozie.command.coord.CoordJobXCommand.execute(CoordJobXCommand.java:146)
         at org.apache.oozie.command.coord.CoordJobXCommand.execute(CoordJobXCommand.java:40)
         at org.apache.oozie.command.XCommand.call(XCommand.java:280)
         at org.apache.oozie.CoordinatorEngine.getCoordJob(CoordinatorEngine.java:151)
         at org.apache.oozie.servlet.V1JobServlet.getCoordinatorJob(V1JobServlet.java:820)
         at org.apache.oozie.servlet.V1JobServlet.getJob(V1JobServlet.java:234)
         at org.apache.oozie.servlet.BaseJobServlet.doGet(BaseJobServlet.java:234)
         at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
         at org.apache.oozie.servlet.JsonRestServlet.service(JsonRestServlet.java:287)
         at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
         at org.apache.oozie.servlet.AuthFilter$2.doFilter(AuthFilter.java:126)
         at org.apache.hadoop.security.authentication.server.AuthenticationFilter.doFilter(AuthenticationFilter.java:384)
         at org.apache.oozie.servlet.AuthFilter.doFilter(AuthFilter.java:131)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
         at org.apache.oozie.servlet.HostnameFilter.doFilter(HostnameFilter.java:84)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
         at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
         at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:606)
         at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
         at java.lang.Thread.run(Thread.java:744)
Caused by: org.apache.oozie.executor.jpa.JPAExecutorException: E0603: SQL error in operation, Failed to execute query "select count(a) from CoordinatorActionBean a where a.jobId = :jobId". Check the query syntax for correctness. See nested exception for details.
         at org.apache.oozie.executor.jpa.CoordActionsCountForJobIdJPAExecutor.execute(CoordActionsCountForJobIdJPAExecutor.java:52)
         at org.apache.oozie.executor.jpa.CoordActionsCountForJobIdJPAExecutor.execute(CoordActionsCountForJobIdJPAExecutor.java:29)
         at org.apache.oozie.service.JPAService.execute(JPAService.java:224)
         at org.apache.oozie.command.coord.CoordJobXCommand.execute(CoordJobXCommand.java:127)
         ... 29 more
Caused by: <openjpa-2.2.2-r422266:1468616 nonfatal user error> org.apache.openjpa.persistence.ArgumentException: Failed to execute query "select count(a) from CoordinatorActionBean a where a.jobId = :jobId". Check the query syntax for correctness. See nested exception for details.
         at org.apache.openjpa.kernel.QueryImpl.execute(QueryImpl.java:872)
         at org.apache.openjpa.kernel.QueryImpl.execute(QueryImpl.java:794)
         at org.apache.openjpa.kernel.DelegatingQuery.execute(DelegatingQuery.java:542)
         at org.apache.openjpa.persistence.QueryImpl.execute(QueryImpl.java:286)
         at org.apache.openjpa.persistence.QueryImpl.getResultList(QueryImpl.java:302)
         at org.apache.openjpa.persistence.QueryImpl.getSingleResult(QueryImpl.java:330)
         at org.apache.oozie.executor.jpa.CoordActionsCountForJobIdJPAExecutor.execute(CoordActionsCountForJobIdJPAExecutor.java:48)
         ... 32 more
Caused by: java.sql.SQLTransactionRollbackException: A lock could not be obtained within the time requested
         at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
         at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
         at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
         at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
         at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
         at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
         at org.apache.derby.impl.jdbc.EmbedResultSet.closeOnTransactionError(Unknown Source)
         at org.apache.derby.impl.jdbc.EmbedResultSet.movePosition(Unknown Source)
         at org.apache.derby.impl.jdbc.EmbedResultSet.next(Unknown Source)
         at org.apache.commons.dbcp.DelegatingResultSet.next(DelegatingResultSet.java:207)
         at org.apache.commons.dbcp.DelegatingResultSet.next(DelegatingResultSet.java:207)
         at org.apache.openjpa.lib.jdbc.DelegatingResultSet.next(DelegatingResultSet.java:109)
         at org.apache.openjpa.jdbc.sql.ResultSetResult.nextInternal(ResultSetResult.java:222)
         at org.apache.openjpa.jdbc.sql.SelectImpl$SelectResult.nextInternal(SelectImpl.java:2445)
         at org.apache.openjpa.jdbc.sql.AbstractResult.next(AbstractResult.java:175)
         at org.apache.openjpa.jdbc.kernel.SelectResultObjectProvider.next(SelectResultObjectProvider.java:99)
         at org.apache.openjpa.kernel.QueryImpl$PackingResultObjectProvider.next(QueryImpl.java:2087)
         at org.apache.openjpa.kernel.QueryImpl.singleResult(QueryImpl.java:1323)
         at org.apache.openjpa.kernel.QueryImpl.toResult(QueryImpl.java:1242)
         at org.apache.openjpa.kernel.QueryImpl.execute(QueryImpl.java:1007)
         at org.apache.openjpa.kernel.QueryImpl.execute(QueryImpl.java:863)
         ... 38 more
Caused by: java.sql.SQLException: A lock could not be obtained within the time requested
         at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
         at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
         ... 59 more
Caused by: ERROR 40XL1: A lock could not be obtained within the time requested
         at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
         at org.apache.derby.impl.services.locks.ConcurrentLockSet.lockObject(Unknown Source)
         at org.apache.derby.impl.services.locks.ConcurrentLockSet.zeroDurationLockObject(Unknown Source)
         at org.apache.derby.impl.services.locks.AbstractPool.zeroDurationlockObject(Unknown Source)
         at org.apache.derby.impl.services.locks.ConcurrentPool.zeroDurationlockObject(Unknown Source)
         at org.apache.derby.impl.store.raw.xact.RowLocking2nohold.lockRecordForRead(Unknown Source)
         at org.apache.derby.impl.store.access.heap.HeapController.lockRow(Unknown Source)
         at org.apache.derby.impl.store.access.heap.HeapController.lockRow(Unknown Source)
         at org.apache.derby.impl.store.access.btree.index.B2IRowLocking3.lockRowOnPage(Unknown Source)
         at org.apache.derby.impl.store.access.btree.index.B2IRowLocking3._lockScanRow(Unknown Source)
         at org.apache.derby.impl.store.access.btree.index.B2IRowLockingRR.lockScanRow(Unknown Source)
         at org.apache.derby.impl.store.access.btree.BTreeForwardScan.fetchRows(Unknown Source)
         at org.apache.derby.impl.store.access.btree.BTreeScan.fetchNextGroup(Unknown Source)
         at org.apache.derby.impl.sql.execute.BulkTableScanResultSet.reloadArray(Unknown Source)
         at org.apache.derby.impl.sql.execute.BulkTableScanResultSet.getNextRowCore(Unknown Source)
         at org.apache.derby.impl.sql.execute.IndexRowToBaseRowResultSet.getNextRowCore(Unknown Source)
         at org.apache.derby.impl.sql.execute.ProjectRestrictResultSet.getNextRowCore(Unknown Source)
         at org.apache.derby.impl.sql.execute.ScalarAggregateResultSet.getRowFromResultSet(Unknown Source)
         at org.apache.derby.impl.sql.execute.ScalarAggregateResultSet.getNextRowCore(Unknown Source)
         at org.apache.derby.impl.sql.execute.ProjectRestrictResultSet.getNextRowCore(Unknown Source)
         at org.apache.derby.impl.sql.execute.BasicNoPutResultSetImpl.getNextRow(Unknown Source)
         ... 52 more
```

**Comment by sarus** [comment]
Not sure what fixed it but the coordinator I started ended up running and now I can view coordinators under the oozie dashboard.  Thanks!

**Comment by romainr** [comment]
Weird and that seems more like a Oozie specific issue.
