### ISSUE TITLE
" WHERE  table_name LIKE 'table%' " query could not be submitted to presto.

### ISSUE THREAD

**Issue by MagicDevilZhang** [cloudera/hue#2051]
hue 4.9.0 could not support ` LIKE '%keyword%' ` in sql with the interface of sqlachemy.
```sql
SELECT id, username, password
FROM desktop_hue_yzf.auth_user 
WHERE  username LIKE '%admin%'
LIMIT 100;
```
and it feedback the error:
```
unsupported format character 'a' (0x61) at index 85
```
in addition, the lanuguage of hue was switched  to 'zh-cn', and the log report errors:
```
[28/Apr/2021 23:13:04 +0000] access       INFO     127.0.0.1 demo - "POST /notebook/api/check_status HTTP/1.1" returned in 195ms 200 47 (mem: 205mb)
[28/Apr/2021 23:13:04 +0000] access       INFO     127.0.0.1 demo - "POST /desktop/log_analytics HTTP/1.1" - (mem: 205mb)-- PAGE: editor/showLongOperationWarning
[28/Apr/2021 23:13:04 +0000] access       INFO     127.0.0.1 demo - "POST /desktop/log_analytics HTTP/1.1" returned in 1ms 200 13 (mem: 205mb)
[28/Apr/2021 23:13:04 +0000] base         DEBUG    Selected interpreter presto_local interface=sqlalchemy compute=None
[28/Apr/2021 23:13:04 +0000] sql_alchemy  ERROR    Query Error
Traceback (most recent call last):
  File "/home/yzf/hue-master/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 100, in decorator
    return func(*args, **kwargs)
  File "/home/yzf/hue-master/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 255, in execute
    result = connection.execute(statement)
  File "/home/yzf/hue-master/build/env/local/lib/python2.7/site-packages/SQLAlchemy-1.3.17-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1012, in execute
    return self._execute_text(object_, multiparams, params)
  File "/home/yzf/hue-master/build/env/local/lib/python2.7/site-packages/SQLAlchemy-1.3.17-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1187, in _execute_text
    parameters,
  File "/home/yzf/hue-master/build/env/local/lib/python2.7/site-packages/SQLAlchemy-1.3.17-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1324, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/yzf/hue-master/build/env/local/lib/python2.7/site-packages/SQLAlchemy-1.3.17-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1521, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/home/yzf/hue-master/build/env/local/lib/python2.7/site-packages/SQLAlchemy-1.3.17-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1284, in _execute_context
    cursor, statement, parameters, context
  File "/home/yzf/hue-master/build/env/local/lib/python2.7/site-packages/SQLAlchemy-1.3.17-py2.7-linux-x86_64.egg/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "/home/yzf/hue-master/build/env/local/lib/python2.7/site-packages/pyhive/presto.py", line 259, in execute
    sql = operation % _escaper.escape_args(parameters)
ValueError: unsupported format character 'a' (0x61) at index 85
[28/Apr/2021 23:13:04 +0000] decorators   ERROR    Error running execute
Traceback (most recent call last):
  File "/home/yzf/hue-master/desktop/libs/notebook/src/notebook/decorators.py", line 119, in wrapper
    return f(*args, **kwargs)
  File "/home/yzf/hue-master/desktop/libs/notebook/src/notebook/api.py", line 236, in execute
    response = _execute_notebook(request, notebook, snippet)
  File "/home/yzf/hue-master/desktop/libs/notebook/src/notebook/api.py", line 211, in _execute_notebook
    raise ex
QueryError: unsupported format character 'a' (0x61) at index 85
```

**Comment by MagicDevilZhang** [comment]
when i change the sql like ('%' -> '%%') :
```sql
SELECT id, username, password
FROM desktop_hue_yzf.auth_user 
WHERE  username LIKE '%%admin%%'
LIMIT 100;
```
SQLAlchemy should change the '%' to '%%'

**Comment by forrestlmj** [comment]
@romainr  is this sqlachemy some compatibility problem ？

**Comment by romainr** [comment]
This should be handled by the dialect itself indeed, e.g. https://github.com/googleapis/python-bigquery-sqlalchemy/issues/72

Have you checked in the Pyhive github if there is already an issue/fix about this?
https://github.com/dropbox/PyHive

(it might be "fixable" on the Hue side but would need to properly parse the SQL statements and it is not trivial)
