### ISSUE TITLE
Could not complete build in MacOS 10.14.6

### ISSUE THREAD

**Issue by chan71** [cloudera/hue#2092]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com? No

**Nature of the issue**:
Tried to build hue using `make apps` after following the steps described in the installation section (link given below) but got an error.
```
"PYTHON_VER is python3.7."
"Python 3 module install via pip"
"SYS_PYTHON is /Users/ckit/.virtualenvs/hue/bin/python3.7."
"ENV_PYTHON is /Users/ckit/platforms/hue/build/env/bin/python3.7."
./build/env/bin/hue collectstatic --noinput
[10/May/2021 21:49:14 +1000] settings     DEBUG    DESKTOP_DB_TEST_NAME SET: /Users/ckit/platforms/hue/desktop/desktop-test.db
[10/May/2021 21:49:14 +1000] settings     DEBUG    DESKTOP_DB_TEST_USER SET: hue_test
Traceback (most recent call last):
  File "./build/env/bin/hue", line 33, in <module>
    sys.exit(load_entry_point('desktop', 'console_scripts', 'hue')())
  File "/Users/ckit/platforms/hue/desktop/core/src/desktop/manage_entry.py", line 230, in entry
    execute_from_command_line(sys.argv)
  File "/Users/ckit/platforms/hue/build/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/ckit/platforms/hue/build/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/Users/ckit/platforms/hue/build/env/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/ckit/platforms/hue/build/env/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/ckit/platforms/hue/build/env/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/ckit/platforms/hue/build/env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/ckit/platforms/hue/desktop/core/src/desktop/models.py", line 46, in <module>
    from useradmin.models import User, Group, get_organization
  File "/Users/ckit/platforms/hue/apps/useradmin/src/useradmin/models.py", line 56, in <module>
    from desktop.lib.connectors.models import _get_installed_connectors, Connector
  File "/Users/ckit/platforms/hue/desktop/core/src/desktop/lib/connectors/models.py", line 29, in <module>
    from desktop.lib.connectors.types import get_connectors_types
  File "/Users/ckit/platforms/hue/desktop/core/src/desktop/lib/connectors/types.py", line 23, in <module>
    from desktop.lib.exceptions_renderable import PopupException
  File "/Users/ckit/platforms/hue/desktop/core/src/desktop/lib/exceptions_renderable.py", line 31, in <module>
    import desktop.lib.django_util
  File "/Users/ckit/platforms/hue/desktop/core/src/desktop/lib/django_util.py", line 44, in <module>
    import desktop.lib.thrift_util
  File "/Users/ckit/platforms/hue/desktop/core/src/desktop/lib/thrift_util.py", line 33, in <module>
    import sasl
  File "/Users/ckit/platforms/hue/build/env/lib/python3.7/site-packages/sasl/__init__.py", line 15, in <module>
    from sasl.saslwrapper import *
ImportError: dlopen(/Users/ckit/platforms/hue/build/env/lib/python3.7/site-packages/sasl/saslwrapper.cpython-37m-darwin.so, 2): Symbol not found: _PyString_Type
  Referenced from: /Users/ckit/platforms/hue/build/env/lib/python3.7/site-packages/sasl/saslwrapper.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/ckit/platforms/hue/build/env/lib/python3.7/site-packages/sasl/saslwrapper.cpython-37m-darwin.so
make[1]: *** [create-static] Error 1
make: *** [apps] Error 2
```

**Steps to reproduce it?**
Followed the steps described under 'macOS Big Sur on M1 or Intel with Python 3' as I couldn't find instructions for Mojave.
https://docs.gethue.com/administrator/installation/dependencies/

**Environment**
Hue version: git clone https://github.com/cloudera/hue.git
OS: MacOS 10.14.6
Python: 3.7.9
Pip - 21.0.1
Node - 12.4.0

**Comment by chan71** [comment]
This error could be boiled down to the following import issue. And it looks like to me that saslwrapper.cpython-37m-darwin.so library is not the right one for the platform I am building hue on which is MacOS 10.14.6. Hope someone would know more about this and help to solve this.
```
hue$ python
Python 3.7.9 (v3.7.9:13c94747c7, Aug 15 2020, 01:31:08)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from sasl.saslwrapper import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ckit/.virtualenvs/hue/lib/python3.7/site-packages/sasl/__init__.py", line 15, in <module>
    from sasl.saslwrapper import *
ImportError: dlopen(/Users/ckit/.virtualenvs/hue/lib/python3.7/site-packages/sasl/saslwrapper.cpython-37m-darwin.so, 2): Symbol not found: _PyString_Type
  Referenced from: /Users/ckit/.virtualenvs/hue/lib/python3.7/site-packages/sasl/saslwrapper.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/ckit/.virtualenvs/hue/lib/python3.7/site-packages/sasl/saslwrapper.cpython-37m-darwin.so
```
