### ISSUE TITLE
Unable to use HDFS if Oozie is blacklisted

### ISSUE THREAD

**Issue by grozeille** [cloudera/hue#214]
Hi,

I worked for someone who is using a cluster without Oozie.
So we added to the blacklist of HUE: oozie, jobsub and pig
But then, we can't use filebrowser anymore:
```
u'oozie' is not a registered namespace
```
Why the FileBrowser has a dependency on Oozie ?

Full log:
```
[28/Jul/2015 07:57:40 +0200] middleware   INFO     Processing exception: u'oozie' is not a registered namespace: Traceback (most recent call last):
  File "/media/data/hadoop/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/data/hadoop/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/media/data/hadoop/hue/apps/filebrowser/src/filebrowser/views.py", line 105, in index
    return view(request, path)
  File "/media/data/hadoop/hue/apps/filebrowser/src/filebrowser/views.py", line 167, in view
    return listdir_paged(request, path)
  File "/media/data/hadoop/hue/apps/filebrowser/src/filebrowser/views.py", line 448, in listdir_paged
    return render('listdir.mako', request, data)
  File "/media/data/hadoop/hue/desktop/core/src/desktop/lib/django_util.py", line 225, in render
    **kwargs)
  File "/media/data/hadoop/hue/desktop/core/src/desktop/lib/django_util.py", line 146, in _render_to_response
    return django_mako.render_to_response(template, *args, **kwargs)
  File "/media/data/hadoop/hue/desktop/core/src/desktop/lib/django_mako.py", line 125, in render_to_response
    return HttpResponse(render_to_string(template_name, data_dictionary), **kwargs)
  File "/media/data/hadoop/hue/desktop/core/src/desktop/lib/django_mako.py", line 114, in render_to_string_normal
    result = template.render(**data_dict)
  File "/media/data/hadoop/hue/build/env/lib/python2.6/site-packages/Mako-0.8.1-py2.6.egg/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/media/data/hadoop/hue/build/env/lib/python2.6/site-packages/Mako-0.8.1-py2.6.egg/mako/runtime.py", line 786, in _render
    **_kwargs_for_callable(callable_, data))
  File "/media/data/hadoop/hue/build/env/lib/python2.6/site-packages/Mako-0.8.1-py2.6.egg/mako/runtime.py", line 818, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/media/data/hadoop/hue/build/env/lib/python2.6/site-packages/Mako-0.8.1-py2.6.egg/mako/runtime.py", line 844, in _exec_template
    callable_(context, *args, **kwargs)
  File "/tmp/tmpBZ9xhA/filebrowser/listdir.mako.py", line 242, in render_body
    __M_writer(escape(unicode(dir.list_table_browser(files, path_enc, current_request_path, cwd_set))))
  File "/tmp/tmpBZ9xhA/filebrowser/listdir_components.mako.py", line 86, in render_list_table_browser
    __M_writer(escape(unicode(_table(files, path, current_request_path, 'view'))))
  File "/tmp/tmpBZ9xhA/filebrowser/listdir_components.mako.py", line 81, in _table
    return render__table(context,files,path,current_request_path,view)
  File "/tmp/tmpBZ9xhA/filebrowser/listdir_components.mako.py", line 574, in render__table
    __M_writer(escape(unicode( url('oozie:submit_external_job', application_path='/') )))
  File "/media/data/hadoop/hue/desktop/core/src/desktop/lib/django_mako.py", line 131, in url
    return reverse(view_name, args=args, kwargs=view_args)
  File "/media/data/hadoop/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/urlresolvers.py", line 532, in reverse
    key)
NoReverseMatch: u'oozie' is not a registered namespace
```

**Comment by romainr** [comment]
Good catch indeed, here is a fix for that: https://review.cloudera.org/r/5654/

And this is about this feature http://gethue.com/hadoop-tutorial-submit-any-oozie-jobs-directly-from/ that was not designed to work without Oozie

**Comment by romainr** [comment]
And even prettier with:
https://github.com/cloudera/hue/commit/a315d60cd105713502ca389032a1d4e9566f2491
