### ISSUE TITLE
SSL setup error between browser and Hue

### ISSUE THREAD

**Issue by chuingggg** [cloudera/hue#2266]
Hi, my name is chu

Today, I tried setting ssl at hue

So, i did the following on the server where I installed Hue.
 edge]$ cd /fsdata/ssl/
 edge]$ openssl genrsa 4096 > server.key
 edge]$ openssl req -new -x509 -nodes -sha1 -key server.key > server.cert

and set it up hue.ini
 - hue.ini
[desktop]
ssl_certificate=/fsdata/test_ssl/server.cert
ssl_private_key=/fsdata/test_ssl/server.key
[[session]]
secure=true

But I get the following error(kt_renewer:kerberos key tab??) :
 - hue.log
[24/Jun/2021 16:31:19 +0900] supervisor   WARNING  Exit code for /usr/share/hue/build/env/bin/hue kt_renewer: 1
[24/Jun/2021 16:31:19 +0900] supervisor   ERROR    Process /usr/share/hue/build/env/bin/hue **kt_renewer** has restarted more than 3 times in the last 2 seconds
[24/Jun/2021 16:31:19 +0900] supervisor   WARNING  Exit code for /usr/share/hue/build/env/bin/hue runcpserver: 1
[24/Jun/2021 16:31:19 +0900] supervisor   ERROR    Process /usr/share/hue/build/env/bin/hue runcpserver has restarted more than 3 times in the last 2 seconds
[24/Jun/2021 16:31:20 +0900] supervisor   WARNING  Supervisor shutting down!
[24/Jun/2021 16:31:20 +0900] supervisor   WARNING  Waiting for children to exit for 5 seconds...
[24/Jun/2021 16:31:20 +0900] supervisor   ERROR    Exception in supervisor main loop
Traceback (most recent call last):
  File "/usr/share/hue/desktop/core/src/desktop/supervisor.py", line 385, in main
    wait_loop(sups, options)
  File "/usr/share/hue/desktop/core/src/desktop/supervisor.py", line 402, in wait_loop
    shutdown(sups)  # shutdown() exits the process
  File "/usr/share/hue/desktop/core/src/desktop/supervisor.py", line 218, in shutdown
    sys.exit(1)
SystemExit: 1
[24/Jun/2021 16:31:20 +0900] supervisor   WARNING  Supervisor shutting down!
[24/Jun/2021 16:31:20 +0900] supervisor   WARNING  Waiting for children to exit for 5 seconds...

I set it up like the link below
https://docs.cloudera.com/documentation/enterprise/6/6.3/topics/cm_sg_ssl_hue.html
https://hadoop429.rssing.com/chan-36239927/all_p2.html

Please let me know if there are any settings(conf) I have missed.

thanks

**Comment by chuingggg** [comment]
Hi, my name is chu.

For a few days, I checked the frontend log.
So, I checked the log that the ssl file could not be found,
and after including the log in the docker container,
I set the config again.

As a result, it was applied normally.
[hue.ini]
# Filename of SSL Certificate
ssl_certificate=/usr/share/hue/ssl/host.cert

# Filename of SSL RSA Private Key
ssl_private_key=/usr/share/hue/ssl/host.key

**I have one question.
Is there any flag setting?
whether to configure ssl or not in the Hue config?**

**Comment by romainr** [comment]
If you rebuild the image and specify these 2 ini properties in https://github.com/cloudera/hue/blob/master/tools/docker/hue/conf3/z-hue-overrides.ini it will be on.

Most of the time people run Hue Docker image in Kubernetes and get the SSL via the Ingress.
