### ISSUE TITLE
In sqlalchemy connection, LIKE '%' statement doens't work.

### ISSUE THREAD

**Issue by hoon-e** [cloudera/hue#2308]
# Bug
When execute SQL Query like below, error occurs.
```
SELECT * FROM <database>.<table> WHERE <column name> LIKE 'D%';
or
SELECT * FROM <database>.<table> WHERE <column name> LIKE "D%";
```

Hue server error log shows like below.
```
Traceback (most recent call last):
File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 100, in decorator
return func(*args, **kwargs)
File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 255, in execute
result = connection.execute(statement)
File "/usr/share/hue/build/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 982, in execute
return self._execute_text(object_, multiparams, params)
File "/usr/share/hue/build/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1155, in _execute_text
parameters,
File "/usr/share/hue/build/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
e, statement, parameters, cursor, context
File "/usr/share/hue/build/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
util.raise_from_cause(sqlalchemy_exception, exc_info)
File "/usr/share/hue/build/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "/usr/share/hue/build/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
raise value.with_traceback(tb)
File "/usr/share/hue/build/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
cursor, statement, parameters, context
File "/usr/share/hue/build/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
cursor.execute(statement, parameters)
File "/usr/share/hue/build/env/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
raise ProgrammingError(str(m))
sqlalchemy.exc.ProgrammingError: (MySQLdb._exceptions.ProgrammingError) not enough arguments for format string
```

# How to reproduce it
https://demo.gethue.com/hue/home

In hue demo application, you can reproduce error.
Using Query:
```sql
use information_schema;

show tables;

DESC Ages;

select * from name from Ages where name like 'd%';
```
Screenshot:
![Screen Shot 2021-07-08 at 6 41 16 PM](https://user-images.githubusercontent.com/32868349/124900508-16228800-e01c-11eb-8a2f-9b10e5ea62ea.png)

# Hue version
Opensource 4.9.0 version.
Using mysql notebook with sqlalchemy connection.

**Comment by romainr** [comment]
It depends on the dialect itself not Bue, and doubling the % should work

**Comment by hoon-e** [comment]
@romainr Yes, There was similar issue before. I solved the problem with doubling %. Thanks for the comment.
