### ISSUE TITLE
Session Creation doesn't work connecting to hue through custom UI; The hue UI works fine

### ISSUE THREAD

**Issue by AweltyBelv** [cloudera/hue#2343]
We're trying to use the sql-scratchpad component to connect to a hue service, and are unable to execute queries since the POST to create_session returns `{
    "status": -1,
    "message": "'User' object has no attribute 'has_hue_permission'"
}`. When connecting to hue through chrome, everything works fine and this POST returns no errors. We've ensured the users have the correct permissions, and also received the same issue when logging in with the superuser account.

We're using the sql-scratchpad webcomponent imported as 'gethue/lib/components/SqlScratchpadWebComponent', and display it with 
 ```
<sql-scratchpad
        api-url={HUE_URL}
        username={HUE_USERNAME}
        password={HUE_PASSWORD}
        dialect='flink'
        />
```

Additionally, we notice python segfaulting when we try to create this session. Here's the stack trace that we're seeing:
```
Traceback (most recent call last):
File "git/hue/desktop/libs/notebook/src/notebook/decorators.py", line 119, in wrapper
return f(*args, **kwargs)
File "git/hue/desktop/libs/notebook/src/notebook/api.py", line 117, in create_session
response['session'] = get_api(request, session).create_session(lang=session['type'], properties=properties)
File "git/hue/desktop/libs/notebook/src/notebook/models.py", line 586, in get_api
return ApiWrapper(request, snippet)
File "git/hue/desktop/libs/notebook/src/notebook/models.py", line 570, in __init__
self.api = _get_api(request, snippet)
File "git/hue/desktop/libs/notebook/src/notebook/connectors/base.py", line 424, in get_api
interpreter = get_interpreter(connector_type=connector_name, user=request.user)
File "git/hue/desktop/libs/notebook/src/notebook/connectors/base.py", line 360, in get_interpreter
interpreter for interpreter in get_ordered_interpreters(user) if connector_type == interpreter['type']
File "git/hue/desktop/libs/notebook/src/notebook/conf.py", line 104, in get_ordered_interpreters
user_apps = appmanager.get_apps_dict(user)
File "git/hue/desktop/core/src/desktop/appmanager.py", line 225, in get_apps_dict
apps = get_apps(user)
File "git/hue/desktop/core/src/desktop/appmanager.py", line 220, in get_apps
if user.has_hue_permission(action="access", app=app.display_name)
AttributeError: 'User' object has no attribute 'has_hue_permission'
```

Any help is appreciated, thanks!

**Comment by romainr** [comment]
Is it the very latest Hue from the master branch? (and npm package too)
(it should already have been fixed a few weeks ago)

**Comment by AweltyBelv** [comment]
Yep! We're running the latest off master, and our npm version is 4.6.10, which matches the latest.

**Comment by romainr** [comment]
Weird, in the Chrome console XHR tab, do you see a create_session call that does not start with /api/...?


https://docs.gethue.com/developer/components/scratchpad/

![image](https://user-images.githubusercontent.com/17945/125844472-d0a291fe-9e0e-4797-9448-5773b6210771.png)

**Comment by AweltyBelv** [comment]
Our create session call hits /api/editor/create_session and has all the same headers as what you've shown in the image. Our calls hit the auth endpoint, then get_config, then flink, then create_session, then autocomplete, which is a different process than what you have in the image though.

**Comment by romainr** [comment]
Hum, please share the Chrome more logs/traces, it looks like it works for me with gethue 4.10.6:

![image](https://user-images.githubusercontent.com/17945/126042313-5e317c12-ea9c-422e-a124-61d5dc55b042.png)

`

Line wrap
--
  | <!DOCTYPE html>
  | <html>
  |  
  | <head>
  | <title>SQL Scratchpad</title>
  | <script type="text/javascript" src="./node_modules/gethue/lib/components/SqlScratchpadWebComponent.js"></script>
  | </head>
  |  
  | <body>
  | <div style="position: absolute; height: 100%; width: 100%">
  |  
  | <sql-scratchpad api-url="https://demo.gethue.com" username="demo" password="demo" dialect="flink" />
  |  
  | </div>
  | </body>
  |  
  | </html>
  |  

`

**Comment by AweltyBelv** [comment]
We have no issue in connecting to the demo instance -- the issue lies with connecting to our own instance for some strange reason. In the event that our config is the issue, I've included that in addition to the network information.

[HueConfig.txt](https://github.com/cloudera/hue/files/6843990/HueConfig.txt)
![Auth](https://user-images.githubusercontent.com/87493397/126229461-adb07e6c-c65b-44a8-b807-2057c2a444de.PNG)
![Autocomplete](https://user-images.githubusercontent.com/87493397/126229473-d2cddc89-5b66-4b16-b000-9fc0161b7c63.PNG)
![CreateSession](https://user-images.githubusercontent.com/87493397/126229483-c952f898-1c30-4b3c-8bb1-3a2f8ae9cf6c.PNG)
![Flink](https://user-images.githubusercontent.com/87493397/126229490-9df30b2a-9a3b-4a66-8334-bf9a992b980f.PNG)
![GetConfig](https://user-images.githubusercontent.com/87493397/126229495-bdbe25e7-cc43-49a9-bab8-80dbb19e9633.PNG)
![HasHuePermission](https://user-images.githubusercontent.com/87493397/126229506-51d13529-a20a-4f65-83e5-922c60991479.PNG)
![NetworkRequests](https://user-images.githubusercontent.com/87493397/126229520-4d7930a4-39bc-47a5-9b1f-1050a2a325c8.PNG)
[CreateSession.txt](https://github.com/cloudera/hue/files/6844012/CreateSession.txt)
[FlinkResponse.txt](https://github.com/cloudera/hue/files/6844013/FlinkResponse.txt)
[GetConfigResponse.txt](https://github.com/cloudera/hue/files/6844014/GetConfigResponse.txt)
[AutocompleteResponse.txt](https://github.com/cloudera/hue/files/6844015/AutocompleteResponse.txt)

**Comment by romainr** [comment]
Do you have?

```
[notebook]
enable_notebook_2=true

```

**Comment by AweltyBelv** [comment]
We did not. However, after adding that line to the config file we continue to have the issue.

**Comment by AweltyBelv** [comment]
In an attempt to continue debugging the issue, could we see the config for the demo instance? I can't seem to find it in this repo

**Comment by romainr** [comment]
Let me see how to get it, in the meantime, make sure you have below. Also this is something that we are going to make cleaner/works with flag combination in August.

```
[desktop]
enable_connectors=true

[notebook]
enable_notebook_2=true
```

**Comment by AweltyBelv** [comment]
We've enabled these 2 flags and have a different error this time, which might be some progress! I'll paste the server logs below, the frontend console logs show a 401 UNAUTHORIZED error as well as calling out the `useradmin_huepermission.connector_id`  issue.

```
[27/Jul/2021 10:22:18 -0700] views        WARNING  Not creating home directory of root as no file system connector is configured
[27/Jul/2021 10:22:18 -0700] access       WARNING  127.0.0.1 root - "POST /hue/accounts/login HTTP/1.1" - (mem: 138mb)-- Successful login for user: root
[27/Jul/2021 10:22:18 -0700] access       INFO     127.0.0.1 root - "POST /hue/accounts/login HTTP/1.1" returned in 68ms 302 0 (mem: 138mb)
[27/Jul/2021 10:22:18 -0700] middleware   ERROR    Could not audit the request: [Errno 2] No such file or directory: '/var/log/hue/audit.log'
[27/Jul/2021 10:22:18 -0700] access       INFO     127.0.0.1 root - "GET / HTTP/1.1" returned in 2ms 302 0 (mem: 138mb)
[27/Jul/2021 10:22:18 -0700] middleware   INFO     Processing exception: (1054, "Unknown column 'useradmin_huepermission.connector_id' in 'field list'"): Traceback (most recent call last):
  File "/Users/yababer/git/hue/build/env/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yababer/git/hue/build/env/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/Users/yababer/git/hue/desktop/core/src/desktop/views.py", line 117, in hue
    current_app, other_apps, apps_list = _get_apps(request.user, '')
  File "/Users/yababer/git/hue/desktop/core/src/desktop/models.py", line 2212, in _get_apps
    apps_list = appmanager.get_apps_dict(user)
  File "/Users/yababer/git/hue/desktop/core/src/desktop/appmanager.py", line 225, in get_apps_dict
    apps = get_apps(user)
  File "/Users/yababer/git/hue/desktop/core/src/desktop/appmanager.py", line 220, in get_apps
    if user.has_hue_permission(action="access", app=app.display_name)
  File "/Users/yababer/git/hue/desktop/core/src/desktop/auth/backend.py", line 176, in has_hue_permission
    return self._get_profile().has_hue_permission(action=action, app=app)
  File "/Users/yababer/git/hue/apps/useradmin/src/useradmin/models.py", line 112, in has_hue_permission
    perm = self._lookup_permission(app, action)
  File "/Users/yababer/git/hue/apps/useradmin/src/useradmin/models.py", line 105, in _lookup_permission
    perms = dict([('%s:%s' % (p.app, p.action), p) for p in HuePermission.objects.all()])
  File "/Users/yababer/git/hue/build/env/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/Users/yababer/git/hue/build/env/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/db/models/query.py", line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/yababer/git/hue/build/env/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/Users/yababer/git/hue/build/env/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
OperationalError: (1054, "Unknown column 'useradmin_huepermission.connector_id' in 'field list'")
```

**Comment by romainr** [comment]
If you are missing the column, you would need

```
./build/env/bin/hue migrate
```

(note: it is recommended to backup your DB beforehand)

Then you will need to add DB connectors via the admin page https://docs.gethue.com/administrator/configuration/connectors/#connectors-ui

**Comment by AweltyBelv** [comment]
```
 hue % ./build/env/bin/hue migrate
[27/Jul/2021 12:36:21 -0500] settings     DEBUG    DESKTOP_DB_TEST_NAME SET: /git/hue/desktop/desktop-test.db
[27/Jul/2021 12:36:21 -0500] settings     DEBUG    DESKTOP_DB_TEST_USER SET: hue_test
/git/hue/build/env/lib/python2.7/site-packages/requests_kerberos-0.12.0-py2.7.egg/requests_kerberos/kerberos_.py:11: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import x509
[27/Jul/2021 10:36:22 -0700] sslcompat    DEBUG    ipaddress module is available
[27/Jul/2021 10:36:22 -0700] sslcompat    WARNING  backports.ssl_match_hostname is unavailable
[27/Jul/2021 10:36:22 -0700] sslcompat    DEBUG    ssl.match_hostname is available
[27/Jul/2021 10:36:23 -0700] decorators   INFO     AXES: BEGIN LOG
[27/Jul/2021 10:36:23 -0700] decorators   INFO     AXES: Using django-axes 4.5.4
[27/Jul/2021 10:36:23 -0700] decorators   INFO     AXES: blocking by IP only.
[27/Jul/2021 10:36:24 -0700] __init__     INFO     Couldn't import snappy. Support for snappy compression disabled.
System check identified some issues:

 

WARNINGS:
jobbrowser.DagDetails.dag_info: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
    HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
jobbrowser.QueryDetails.hive_query: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
    HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
Operations to perform:
  Apply all migrations: auth, authtoken, axes, beeswax, contenttypes, desktop, jobsub, oozie, pig, search, sessions, sites, useradmin
Running migrations:
  No migrations to apply.
```

**Comment by Harshg999** [comment]
Hi @AweltyBelv, 
Since you are getting the `OperationalError: (1054, "Unknown column 'useradmin_huepermission.connector_id' in 'field list'")` error, you. might need to do some extra steps mentioned as a `Note` on the page.

Then you can add connectors via the UI following https://docs.gethue.com/administrator/configuration/connectors/#connectors-ui

Hope it helps!

**Comment by Harshg999** [comment]
Hi @AweltyBelv,
Looks like this error was not related to connectors and it has been fixed in https://github.com/cloudera/hue/pull/2406.
It should work out the box now (whether connectors are enabled or not).

Hope it helps!
