### ISSUE TITLE
Oozie kill from job browser in Python 3 environment leads to JSON serializable error.

### ISSUE THREAD

**Issue by rickb78** [cloudera/hue#2379]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?

No

Describe the bug:

When trying to kill an Oozie workflow/coordinator/bundle from the Job Browser in a Python 3 runtime environment, it fails with the following stack trace:

api2         ERROR    Error running <function action at 0x7f95ae2429e0>                             
Traceback (most recent call last):
  File "apps/jobbrowser/src/jobbrowser/api2.py", line 48, in decorator
    return func(*args, **kwargs)
  File "apps/jobbrowser/src/jobbrowser/api2.py", line 127, in action
    get_api(request.user, interface, cluster=cluster).action(app_ids, operation)
  File "apps/jobbrowser/src/jobbrowser/apis/workflow_api.py", line 108, in action
    return _manage_oozie_job(self.user, action, app_ids)
  File "apps/jobbrowser/src/jobbrowser/apis/workflow_api.py", line 196, in _manage_oozie_job
    response = manage_oozie_jobs(request, app_ids[0], action['action'])
  File "apps/oozie/src/oozie/views/dashboard.py", line 157, in manage_oozie_jobs
    return JsonResponse(response)
  File "desktop/core/src/desktop/lib/django_util.py", line 503, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "ppython3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "ppython3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "build/env/lib/python3.7/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable

Steps to reproduce it?

- Enable job kill for the job browser.
- Launch an Oozie workflow.
- Try to kill the workflow from the job browser.

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).

- Hue 4.10
- Python 3.7

**Comment by rickb78** [comment]
PR for fix:  https://github.com/cloudera/hue/pull/2380
