### ISSUE TITLE
how to add more than one presto connector 

### ISSUE THREAD

**Issue by szsuyuji** [cloudera/hue#2395]
after add config like this ,hue start failed
![image](https://user-images.githubusercontent.com/1931764/127452009-700eef7a-ac51-4996-9383-8b373fb7f334.png)

+ /opt/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hue/build/env/bin/hue makemigrations --noinput
Traceback (most recent call last):
  File "/opt/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hue/build/env/bin/hue", line 11, in <module>
    load_entry_point('desktop', 'console_scripts', 'hue')()
  File "/opt/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hue/desktop/core/src/desktop/manage_entry.py", line 230, in entry
    execute_from_command_line(sys.argv)
  File "/opt/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/opt/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/opt/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hue/desktop/core/src/desktop/settings.py", line 318, in <module>
    conf.initialize(_desktop_conf_modules, _config_dir)
  File "/opt/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hue/desktop/core/src/desktop/lib/conf.py", line 605, in initialize
    conf_data = load_confs(_configs_from_dir(config_dir))
  File "/opt/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hue/desktop/core/src/desktop/lib/conf.py", line 537, in load_confs
    for in_conf in conf_source:
  File "/opt/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hue/desktop/core/src/desktop/lib/conf.py", line 518, in _configs_from_dir
    conf = ConfigObj(os.path.join(conf_dir, filename))
  File "/opt/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hue/build/env/lib/python2.7/site-packages/configobj-5.0.6-py2.7.egg/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/opt/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hue/build/env/lib/python2.7/site-packages/configobj-5.0.6-py2.7.egg/configobj.py", line 1318, in _load
    raise error

**Comment by romainr** [comment]
Rename the second one `[presto]` --> `[prestohive]`?

This will be easier when using the connectors feature https://docs.gethue.com/administrator/configuration/connectors/#connectors-ui

**Comment by szsuyuji** [comment]
> Rename the second one `[presto]` --> `[prestohive]`?
> 
> This will be easier when using the connectors feature https://docs.gethue.com/administrator/configuration/connectors/#connectors-ui

it works ,i thought [presto] means the connector type.
