### ISSUE TITLE
Getting python syntax errors while building with PYTHON_VER=python3.6

### ISSUE THREAD

**Issue by byungnam** [cloudera/hue#2413]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
No.

Describe the bug:
I see many incompatible python2 python3 syntax errors while running `make install` command. Most of the errors are coming from `desktop/core/ext-py/`. 

Error snippets below:

1. python2-style `print 'xxx'` function
```
[deploy@infra-hadoop-build1 hue]$ INSTALL_DIR=/home/deploy/brandon/hue make install
"PYTHON_VER is python3.6."
"Python 3 module install via pip"
"SYS_PYTHON is /usr/bin/python3.6."
"ENV_PYTHON is /home/deploy/brandon/khp-package-clean/repositories/hadoopeng/hue/build/env/bin/python3.6."
--- Installing core source structure...
--- Installing Desktop core...
INSTALL_DIR=/home/deploy/brandon/hue make -C desktop install
"PYTHON_VER is python3.6."
"Python 3 module install via pip"
"SYS_PYTHON is /usr/bin/python3.6."
"ENV_PYTHON is /home/deploy/brandon/khp-package-clean/repositories/hadoopeng/hue/build/env/bin/python3.6."
"----------------> ENV_INSTALL_TARGETS: .recursive-env-install/core .recursive-env-install/libs/aws .recursive-env-install/libs/azure .recursive-env-install/libs/hadoop .recursive-env-install/libs/indexer .recursive-env-install/libs/libanalyze .recursive-env-install/libs/liboauth .recursive-env-install/libs/liboozie .recursive-env-install/libs/librdbms .recursive-env-install/libs/libsaml .recursive-env-install/libs/libsentry .recursive-env-install/libs/libsolr .recursive-env-install/libs/libzookeeper .recursive-env-install/libs/metadata .recursive-env-install/libs/notebook .recursive-env-install/libs/dashboard .recursive-env-install/libs/kafka"
make[1]: Entering directory `/home/deploy/brandon/khp-package-clean/repositories/hadoopeng/hue/desktop'
INSTALL_DIR=/home/deploy/brandon/hue/desktop/core \
	INSTALL_CONF_DIR=/home/deploy/brandon/hue/desktop/conf \
	make -C core install-bdist
"PYTHON_VER is python3.6."
"Python 3 module install via pip"
"SYS_PYTHON is /usr/bin/python3.6."
"ENV_PYTHON is /home/deploy/brandon/khp-package-clean/repositories/hadoopeng/hue/build/env/bin/python3.6."
make[2]: Entering directory `/home/deploy/brandon/khp-package-clean/repositories/hadoopeng/hue/desktop/core'
--- Building egg for urllib2_kerberos-0.1.6
Traceback (most recent call last):
  File "/home/deploy/brandon/khp-package-clean/repositories/hadoopeng/hue/build/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/home/deploy/brandon/khp-package-clean/repositories/hadoopeng/hue/build/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/home/deploy/brandon/khp-package-clean/repositories/hadoopeng/hue/build/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/home/deploy/brandon/khp-package-clean/repositories/hadoopeng/hue/build/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 43, in _execfile
    exec(code, globals, locals)
  File "setup.py", line 17, in <module>
    import hgvers
  File "/home/deploy/brandon/khp-package-clean/repositories/hadoopeng/hue/desktop/core/ext-py/urllib2_kerberos-0.1.6/hgvers.py", line 47
    print version
                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(version)?
```

2. Importing python2-style PascalCase packages
```
--- Building egg for MySQL-python-1.2.5
Traceback (most recent call last):
  File "/home/deploy/brandon/khp-package-clean/repositories/hadoopeng/hue/build/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/home/deploy/brandon/khp-package-clean/repositories/hadoopeng/hue/build/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/home/deploy/brandon/khp-package-clean/repositories/hadoopeng/hue/build/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/home/deploy/brandon/khp-package-clean/repositories/hadoopeng/hue/build/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 43, in _execfile
    exec(code, globals, locals)
  File "setup.py", line 13, in <module>
    from setup_posix import get_config
  File "/home/deploy/brandon/khp-package-clean/repositories/hadoopeng/hue/desktop/core/ext-py/MySQL-python-1.2.5/setup_posix.py", line 2, in <module>
    from ConfigParser import SafeConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
```

Steps to reproduce it?
1. Get hue-4.10.0 source code from git
2. Run `export PYTHON_VER=python3.6`
3. Run `make clean apps`
2. Run `INSTALL_DIR=/path/to/install/hue make install`

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).
- Source: open source hue release-4.10.0
- OS: Centos 7
- kernel: 3.10.0-1062.18.1.el7.x86_64

**Comment by byungnam** [comment]
Well. I found [this comment](https://github.com/cloudera/hue/issues/1493#issuecomment-743203841) can help my problem.

**Comment by byungnam** [comment]
I finally found the problem. In short, `ext-py` directory must be removed when you are building with python3.

From [lines](https://github.com/cloudera/hue/blob/master/Makefile.sdk#L95-L96) in `Makefile.sdk`, it scans `desktop/core/ext-py` directory (which contains python2 libraries) and if it exists, then [here](https://github.com/cloudera/hue/blob/master/Makefile.sdk#L129-L136) it runs the setup.py codes in there with python3 interpreter. So the error happens.

But when you build it with `docker build` command, the error is not showing up. Why? Because there is a hidden `.dockerignore` file in the root directory and it prevents `ext-py` directory be skipped when copying the whole project files into the docker image.

So I decided to remove the `ext-py` directory because the hue docker is also doing that. After that, I was able to finish hue installation correctly.

I see this is very important for local build process but I cannot find any instructions about this. We need to state this somewhere in the document.

**Comment by romainr** [comment]
Yes, you need a fresh clone or a bit clean if you tried to compile with py2
before and now are switching to py3

**Comment by byungnam** [comment]
@romainr 
> Yes, you need a fresh clone or a bit clean if you tried to compile with py2 before and now are switching to py3

No. I checked it with both fresh cloned directory and `make clean` before running install. The error happens because hue project itself already has `ext-py` directory.
