### ISSUE TITLE
3.9  - Oracle migration getting ORA-00904 in oozie:0026_set_default_data_values

### ISSUE THREAD

**Issue by JRman** [cloudera/hue#247]
Have 3.9 running fine.  Trying to migrate it to an external Oracle DB.

The "syncdb" works perfectly fine and creates all tables.  

When we run the "migrate" we are getting an error on the oozie:0026_set_default_data_values step.  Have tried dropping all Oracle tables and re-run.  Same results:

```
Running migrations for oozie:
 - Migrating forwards to 0026_set_default_data_values.
 > oozie:0026_set_default_data_values
 - Migration 'oozie:0026_set_default_data_values' is marked for no-dry-run.
 ! Error found during real run of migration! Aborting.

 ! Since you have a database that does not support running
 ! schema-altering statements in transactions, we have had
 ! to leave it in an interim state between migrations.

! You *might* be able to recover with:   (migration cannot be dry-run; cannot discover commands)
 ! The South developers regret this has happened, and would
 ! like to gently persuade you to consider a slightly
 ! easier-to-deal-with DBMS (one that supports DDL transactions)
 ! NOTE: The error which caused the migration to fail is further up.
Error in migration: oozie:0026_set_default_data_values
Traceback (most recent call last):
  File "/home/hue/hue3/hue/build/env/bin/hue", line 9, in <module>
    load_entry_point('desktop==3.9.0', 'console_scripts', 'hue')()
  File "/home/hue/hue3/hue/desktop/core/src/desktop/manage_entry.py", line 57, in entry
    execute_from_command_line(sys.argv)
  File "/home/hue/hue3/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/hue/hue3/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/hue/hue3/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/hue/hue3/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/hue/hue3/hue/build/env/lib/python2.6/site-packages/South-1.0.2-py2.6.egg/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/home/hue/hue3/hue/build/env/lib/python2.6/site-packages/South-1.0.2-py2.6.egg/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/home/hue/hue3/hue/build/env/lib/python2.6/site-packages/South-1.0.2-py2.6.egg/south/migration/migrators.py", line 256, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/home/hue/hue3/hue/build/env/lib/python2.6/site-packages/South-1.0.2-py2.6.egg/south/migration/migrators.py", line 331, in migrate_many
    result = self.migrate(migration, database)
  File "/home/hue/hue3/hue/build/env/lib/python2.6/site-packages/South-1.0.2-py2.6.egg/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/home/hue/hue3/hue/build/env/lib/python2.6/site-packages/South-1.0.2-py2.6.egg/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/home/hue/hue3/hue/build/env/lib/python2.6/site-packages/South-1.0.2-py2.6.egg/south/migration/migrators.py", line 84, in run_migration
    migration_function()
  File "/home/hue/hue3/hue/build/env/lib/python2.6/site-packages/South-1.0.2-py2.6.egg/south/migration/migrators.py", line 60, in <lambda>
    return (lambda: direction(orm))
  File "/home/hue/hue3/hue/apps/oozie/src/oozie/migrations/0026_set_default_data_values.py", line 11, in forwards
    orm.Job.objects.filter(data='').update(data='{}')
  File "/home/hue/hue3/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/models/query.py", line 493, in update
    rows = query.get_compiler(self.db).execute_sql(None)
  File "/home/hue/hue3/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/models/sql/compiler.py", line 980, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/hue/hue3/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/home/hue/hue3/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/hue/hue3/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/hue/hue3/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/hue/hue3/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/backends/oracle/base.py", line 845, in execute
    return self.cursor.execute(query, self._param_generator(params))
django.db.utils.DatabaseError: ORA-00904: : invalid identifier``

```

**Comment by romainr** [comment]
@sai-krish @spaztic1215 is it the one we fixed or grant issue on the Oracle DB?

**Comment by sai-krish** [comment]
fixed with - https://issues.cloudera.org/browse/HUE-3395
