### ISSUE TITLE
Issue when activating saml backend with hue 4.10.0 inside a docker container

### ISSUE THREAD

**Issue by max-l-f** [cloudera/hue#2501]
Hello,
I have a hue version 4.8.0 working properly using the official hue docker image and I'm trying to bump the version to 4.10.0 but I've encounterd the following problem:

**Describe the bug:**
When I activate and configure hue with a saml backend as it was with version 4.8.0 I get the following error:

Traceback (most recent call last):
File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 600, in url_patterns
iter(patterns)
TypeError: 'module' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "./build/env/bin/hue", line 33, in <module>
sys.exit(load_entry_point('desktop', 'console_scripts', 'hue')())
File "/usr/share/hue/desktop/core/src/desktop/manage_entry.py", line 236, in entry
raise e
File "/usr/share/hue/desktop/core/src/desktop/manage_entry.py", line 230, in entry
execute_from_command_line(sys.argv)
File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/management/_init_.py", line 419, in execute_from_command_line
utility.execute()
File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/management/_init_.py", line 413, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/management/base.py", line 354, in run_from_argv
self.execute(*args, **cmd_options)
File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/management/base.py", line 398, in execute
output = self.handle(*args, **options)
File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/management/base.py", line 89, in wrapped
res = handle_func(*args, **kwargs)
File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 75, in handle
self.check(databases=[database])
File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/management/base.py", line 423, in check
databases=databases,
File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 76, in run_checks
new_errors = check(app_configs=app_configs, databases=databases)
File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
return check_resolver(resolver)
File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
return check_method()
File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 413, in check
messages.extend(check_resolver(pattern))
File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
return check_method()
File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 412, in check
for pattern in self.url_patterns:
File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in _get_
res = instance._dict_[self.name] = self.func(instance)
File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 607, in url_patterns
raise ImproperlyConfigured(msg.format(name=self.urlconf_name)) from e
django.core.exceptions.ImproperlyConfigured: The included URLconf '<module 'libsaml.urls' from '/usr/share/hue/desktop/libs/libsaml/src/libsaml/urls.py'>' does not appear to have any patterns in it. If you see valid patterns in the file then the issue is probably caused by a circular import.

**Steps to reproduce it:**
Use the default configuration file,
activate the saml backend
 and configure it this way:
[libsaml]

base_url="https://..."

create_users_on_login=false

metadata_file="/opt/application/hue/current/security/saml/metadata.xml"

key_file="/opt/application/hue/current/security/saml/key.pem"

cert_file="/opt/application/hue/current/security/saml/certificate.pem"

username_source=attributes
name_id_format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"

user_attribute_mapping='{"uid":"username"}'

logout_requests_signed=true

logout_enabled=true

Hue version: 4.10.0 inside a docker container

Can you help me ?

**Comment by InvalidPointer** [comment]
Same issue here. @max-l-f have you found a way to deal with it?

**Comment by max-l-f** [comment]
No I haven't, for now I'm still using hue version 4.8.0 but I was hoping to get some help here

**Comment by InvalidPointer** [comment]
@romainr please, could you provide any help here?

**Comment by InvalidPointer** [comment]
@max-l-f fixed this by adding `djangosaml2==0.18.1` into `desktop/core/requirements.txt`.

**Comment by max-l-f** [comment]
@InvalidPointer thank you I'll test that

**Comment by InvalidPointer** [comment]
I think there are some other fixes should be made in Dockerfile, I'll test them and will also post here.

**Comment by InvalidPointer** [comment]
Also needed to add `xmlsec1` and `libxmlsec1-openssl` to `apt-get install` section at the beginning of Dockerfile.
