### ISSUE TITLE
Build issue - No such file : en_US.pot

### ISSUE THREAD

**Issue by syepes** [cloudera/hue#253]
Hello,

Is anyone else having this build issue from master bbaec8d4?

```
# make prod
..
..
`compiling catalog '/opt/apps/src/hue/desktop/core/src/desktop/locale/zh_CN/LC_MESSAGES/django.po' to '/opt/apps/src/hue/desktop/core/src/desktop/locale/zh_CN/LC_MESSAGES/django.mo'
make[2]: Leaving directory `/opt/apps/src/hue/desktop/core'
make[2]: Entering directory `/opt/apps/src/hue/desktop/libs/aws'
/opt/apps/src/hue/build/env/bin/pybabel extract . -F babel.cfg -k _ -k _t -o /opt/apps/src/hue/desktop/libs/aws/src/aws/locale/en_US.pot --copyright-holder="Cloudera, Inc" --project="Hue" --version=""
Traceback (most recent call last):
  File "/opt/apps/src/hue/build/env/bin/pybabel", line 9, in <module>
    load_entry_point('Babel==0.9.6', 'console_scripts', 'pybabel')()
  File "/opt/apps/src/hue/build/env/lib/python2.7/site-packages/Babel-0.9.6-py2.7.egg/babel/messages/frontend.py", line 1107, in main
    return CommandLineInterface().run(sys.argv)
  File "/opt/apps/src/hue/build/env/lib/python2.7/site-packages/Babel-0.9.6-py2.7.egg/babel/messages/frontend.py", line 651, in run
    return getattr(self, cmdname)(args[1:])
  File "/opt/apps/src/hue/build/env/lib/python2.7/site-packages/Babel-0.9.6-py2.7.egg/babel/messages/frontend.py", line 853, in extract
    outfile = open(options.output, 'w')
IOError: [Errno 2] No such file or directory: '/opt/apps/src/hue/desktop/libs/aws/src/aws/locale/en_US.pot'
make[2]: *** [compile-locale] Error 1
make[2]: Leaving directory `/opt/apps/src/hue/desktop/libs/aws'
make[1]: *** [.recursive-compile-locales/libs/aws] Error 2
make[1]: Leaving directory `/opt/apps/src/hue/desktop'
make: *** [locales] Error 2
```

**Comment by romainr** [comment]
https://review.cloudera.org/r/6270/

**Comment by romainr** [comment]
https://github.com/cloudera/hue/commit/996ee535d0a3415079a98e91a4fd3c593645725e

**Comment by syepes** [comment]
@romainr Thanks
