### ISSUE TITLE
HUE connect Phoenix Error

### ISSUE THREAD

**Issue by stancycowen** [cloudera/hue#2535]
HUE 4.10.0 (run with helm)
Phoenix 4.5.2-1.clabs_phoenix1.1.0.p0.687(on CDH 5.4.7)
I start phoenix queryserver on 8765
then add interpreters config 

[[[phoenix]]]
    name=HBase Phoenix
    interface=sqlalchemy
    options='{"url": "phoenix://xxxx:8765"}'

Finally I got error on queryserver  
21/09/07 15:52:07 WARN server.HttpChannel: /
java.lang.NullPointerException
        at java.io.StringReader.<init>(StringReader.java:50)
        at com.fasterxml.jackson.core.JsonFactory.createJsonParser(JsonFactory.java:917)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1942)
        at org.apache.calcite.avatica.remote.JsonHandler.decode(JsonHandler.java:51)
        at org.apache.calcite.avatica.remote.JsonHandler.apply(JsonHandler.java:42)
        at org.apache.calcite.avatica.server.AvaticaHandler.handle(AvaticaHandler.java:55)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:245)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedTh

Dose anybody know why ?

**Comment by romainr** [comment]
Hum, probably worth upgrading to a much more recent Phoenix and give a try :)

**Comment by stancycowen** [comment]
> Hum, probably worth upgrading to a much more recent Phoenix and give a try :)

I upgrade Phoenix to 5.0, it works, Thanks for your help! LOL!
