### ISSUE TITLE
Centos7 build fails with webpack error

### ISSUE THREAD

**Issue by hindmasj** [cloudera/hue#2625]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
No

Describe the bug:
When running "make apps" I get the following webpack error. Reading around suggests it is incompatibilty with the version of NodeJS.

````
npm run webpack

> gethue@4.10.0 webpack /home/foo/workspace/beam-hue-build/rpmbuild/BUILD/hue-4.10.0
> webpack --config webpack.config.js

/home/foo/workspace/beam-hue-build/rpmbuild/BUILD/hue-4.10.0/node_modules/import-local/node_modules/pkg-dir/index.js:5
const pkgDir = async cwd => {
                     ^^^

SyntaxError: Unexpected identifier
    at NativeCompileCache._moduleCompile (/home/foo/workspace/beam-hue-build/rpmbuild/BUILD/hue-4.10.0/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/home/foo/workspace/beam-hue-build/rpmbuild/BUILD/hue-4.10.0/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/home/foo/workspace/beam-hue-build/rpmbuild/BUILD/hue-4.10.0/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/foo/workspace/beam-hue-build/rpmbuild/BUILD/hue-4.10.0/node_modules/import-local/index.js:4:16)
    at Module._compile (/home/foo/workspace/beam-hue-build/rpmbuild/BUILD/hue-4.10.0/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
````

Steps to reproduce it?

On CentOS 7.9

1. download and unpack hue-4.10.0 from cdn.gethue.com
2. sudo yum install nodejs npm
2. cd hue
3. make desktop
4. make apps

Without installing npm and node the build fails earlier when it checks for npm.
````
$ rpm -q nodejs npm
nodejs-6.17.1-1.el7.x86_64
npm-3.10.10-1.6.17.1.1.el7.x86_64
````

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).

Tarball 4.10.0.

**Comment by hindmasj** [comment]
OK, I have managed to answer my own question, the dependency is on a later version of Node and I need to install the RPMs from Node Source.

It is not clear which versions of node and npm I need. Would it be a good idea include tests for minimum versions during the build?
