### ISSUE TITLE
KeyError: "Couldn't get user id for user hue"

### ISSUE THREAD

**Issue by gavenpeng** [cloudera/hue#27]
[root@hbase2 hue]# build/env/bin/supervisor
Traceback (most recent call last):
  File "build/env/bin/supervisor", line 8, in <module>
    load_entry_point('desktop==2.3.0', 'console_scripts', 'supervisor')()
  File "/home/chamago/hue/desktop/core/src/desktop/supervisor.py", line 312, in main
    setup_user_info()
  File "/home/chamago/hue/desktop/core/src/desktop/supervisor.py", line 253, in setup_user_info
    desktop.lib.daemon_utils.get_uid_gid(SETUID_USER, SETGID_GROUP)
  File "/home/chamago/hue/desktop/core/src/desktop/lib/daemon_utils.py", line 45, in get_uid_gid
    raise KeyError("Couldn't get user id for user %s" % (username,))
KeyError: "Couldn't get user id for user hue"

**Comment by Erko85** [comment]
That worked for me. Do not forget to create the Hue user. It was just so that the Hue user didn't have read rights to the db
