### ISSUE TITLE
Hue 4.10.0 GUI blank and errors in log

### ISSUE THREAD

**Issue by recourse** [cloudera/hue#2760]
Hi did the latest git clone after following the build instructions when I run the supervisor and browse to the main screen i get a blank page with this is the terminal running the server

[21/Mar/2022 09:31:23 -0700] base         WARNING  Session data corrupted
[21/Mar/2022 09:31:23 -0700] access       DEBUG    172.17.19.137 -anon- - "GET /hue/accounts/login HTTP/1.1" - (mem: 141mb)
[21/Mar/2022 09:31:23 -0700] middleware   WARNING  request.fs was not set for anonymous user
[21/Mar/2022 09:31:23 -0700] models       INFO     Sample user found with username "hue" and User ID: 1100713
[21/Mar/2022 09:31:23 -0700] http_client  DEBUG    Setting request Session
[21/Mar/2022 09:31:23 -0700] http_client  DEBUG    Setting session adapter for http://dfwhadoop-master.aninetworks.net:9870
[21/Mar/2022 09:31:23 -0700] webhdfs      DEBUG    Initializing Hadoop WebHdfs: http://dfwhadoop-master.aninetworks.net:9870/webhdfs/v1 (security: False, superuser: None)
[21/Mar/2022 09:31:23 -0700] resource     DEBUG    GET None http://dfwhadoop-master.aninetworks.net:9870/webhdfs/v1?user.name=hue&doas=hue&op=GETHOMEDIRECTORY  returned in 13ms 200 20 {"Path":"/user/hue"}
[21/Mar/2022 09:31:23 -0700] models       INFO     Home directory already exists for user: hue
[21/Mar/2022 09:31:23 -0700] access       INFO     172.17.19.137 -anon- - "GET /hue/accounts/login HTTP/1.1" returned in 292ms 200 117922 (mem: 149mb)
172.17.19.137 - - [21/Mar/2022:09:31:23 -0700] "GET /hue/accounts/login?next=/ HTTP/1.1" 200 117922 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
[21/Mar/2022 09:31:23 -0700] access       DEBUG    172.17.19.137 -anon- - "GET /static/desktop/css/hue3-extra.css HTTP/1.1" - (mem: 149mb)
[21/Mar/2022 09:31:23 -0700] middleware   WARNING  request.fs was not set for anonymous user
[21/Mar/2022 09:31:23 -0700] access       INFO     172.17.19.137 -anon- - "GET /static/desktop/css/hue3-extra.css HTTP/1.1" returned in 2ms 200 - (mem: 149mb)
[2022-03-21 09:31:23 -0700] [9977] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/usr/local/hue/build/env/lib/python3.8/site-packages/gunicorn/workers/base_async.py", line 66, in handle
    six.reraise(*sys.exc_info())
  File "/usr/local/hue/build/env/lib/python3.8/site-packages/gunicorn/six.py", line 625, in reraise
    raise value
  File "/usr/local/hue/build/env/lib/python3.8/site-packages/gunicorn/workers/base_async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/hue/build/env/lib/python3.8/site-packages/gunicorn/workers/base_async.py", line 129, in handle_request
    six.reraise(*sys.exc_info())
  File "/usr/local/hue/build/env/lib/python3.8/site-packages/gunicorn/six.py", line 625, in reraise
    raise value
  File "/usr/local/hue/build/env/lib/python3.8/site-packages/gunicorn/workers/base_async.py", line 112, in handle_request
    resp.write_file(respiter)
  File "/usr/local/hue/build/env/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 403, in write_file
    if not self.sendfile(respiter):
  File "/usr/local/hue/build/env/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 393, in sendfile
    sent += sendfile(sockno, fileno, offset + sent, count)
BlockingIOError: [Errno 11] Resource temporarily unavailable

**Comment by Arcadia822** [comment]
same problem here. 

open gui show blank and cause this:

```
[2022-04-17 19:46:45 -0700] [49] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/gunicorn/workers/base_async.py", line 66, in handle
    six.reraise(*sys.exc_info())
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/gunicorn/six.py", line 625, in reraise
    raise value
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/gunicorn/workers/base_async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/gunicorn/workers/base_async.py", line 129, in handle_request
    six.reraise(*sys.exc_info())
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/gunicorn/six.py", line 625, in reraise
    raise value
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/gunicorn/workers/base_async.py", line 112, in handle_request
    resp.write_file(respiter)
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 403, in write_file
    if not self.sendfile(respiter):
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 393, in sendfile
    sent += sendfile(sockno, fileno, offset + sent, count)
BlockingIOError: [Errno 11] Resource temporarily unavailable
```

**Comment by Akhilsnaik** [comment]
@Arcadia822  @recourse  an BlockingIOError means a socket to which hue is running is blocked for some reason kindly check the hue.ini file and make sure the port assigned to hue is open and ready to be binded by hue process.

**Comment by recourse** [comment]
It appears to be something with ubuntu 20.04LTS.  I installed Hue on debian 11 and it worked without issue

**Comment by wilker7ribeiro** [comment]
Having the same issue with docker image `gethue/4.10.0` when deployed in a kubernetes cluster.

It happens when serving files with size higher than 326K (login bundle js).

Version 4.7.1 works.

**Comment by KeithTt** [comment]
@wilker7ribeiro Same problem here, but I found `sendfile` option is `None` in `rungunicornserver.py`.

**Comment by gudari** [comment]
@KeithTt I had the same issue. I don't know the reason, but even the ```sendfile``` option has ```None``` value in the ```rungunicornserver.py``` configuration file, it still runs the sendfile. I fixed it, setting the ```SENDFILE=None``` env variable, and now it's working behind the nginx ingress controller in kubernetes with the last release of hue, the 4.11.
