### ISSUE TITLE
Get render_to_string() error when change default new HUE application

### ISSUE THREAD

**Issue by jie8357IOII** [cloudera/hue#277]
OS: ubuntu 14.04 LTS
hue: 3.9
python: 2.7.6

I already installed [HUE][1]'s pre-requisites & built up HUE 3.9.

And I follow the [sdk document][2], type `"./build/env/bin/python tools/app_reg/app_reg.py --install calculator"` to new a application. 

It'a all work and fine.

cuz I want to change default mako template engine to django,I change default index page's filename, from '.mako' to '.html' and got the following problem.

    Traceback (most recent call last):
      File "/home/ubuntu/Desktop/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/contrib/staticfiles/handlers.py", line 67, in __call__
        return self.application(environ, start_response)
      File "/home/ubuntu/Desktop/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/wsgi.py", line 206, in __call__
        response = self.get_response(request)
      File "/home/ubuntu/Desktop/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/base.py", line 194, in get_response
        response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
      File "/home/ubuntu/Desktop/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/base.py", line 229, in handle_uncaught_exception
        return debug.technical_500_response(request, *exc_info)
      File "/home/ubuntu/Desktop/hue/build/env/lib/python2.7/site-packages/django_extensions-1.5.0-py2.7.egg/django_extensions/management/technical_response.py", line 5, in null_technical_500_response
        six.reraise(exc_type, exc_value, tb)
      File "/home/ubuntu/Desktop/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/base.py", line 112, in get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/home/ubuntu/Desktop/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/transaction.py", line 371, in inner
        return func(*args, **kwargs)
      File "/home/ubuntu/Desktop/hue/hello/src/hello/views.py", line 25, in hello
        return render('hello.html',request,{})
      File "/home/ubuntu/Desktop/hue/desktop/core/src/desktop/lib/django_util.py", line 227, in render
        **kwargs)
      File "/home/ubuntu/Desktop/hue/desktop/core/src/desktop/lib/django_util.py", line 146, in _render_to_response
        return django_render_to_response(template, *args, **kwargs)
      File "/home/ubuntu/Desktop/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/shortcuts/__init__.py", line 29, in render_to_response
        return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
    TypeError: render_to_string() got an unexpected keyword argument 'status'

What's wrong with this?

  [1]: https://github.com/cloudera/hue
  [2]: http://cloudera.github.io/hue/docs-3.5.0/sdk/sdk.html#install-sdk-application

**Comment by sai-krish** [comment]
@jie8357IOII 
I tried to do this locally and it worked fine. Did you make sure that your html file has no mako related content in it.

**Comment by jie8357IOII** [comment]
I'm sure I didn't put any mako content in html file.
The problem happens even I did not put the html file, in the template dir

below is my "view.py" code

```
from desktop.lib.django_util import render
import datetime

def index(request):
  return render('index.mako', request, dict(date=datetime.datetime.now()))

def hello(request):
  return render('hello.html',request,dict())
```

"urls.py"

```
from django.conf.urls import patterns, url

urlpatterns = patterns('hello',
  url(r'^$', 'views.index'),
  url(r'^hello$', 'views.hello'),
)
```

**Comment by romainr** [comment]
What is the content of hello.html and what is its full path?

**Comment by jie8357IOII** [comment]
I think I find the problem!
It's seem desktop.lib.django_util's method "render" doesn't support html 

I change the app/views.py from 
```
from desktop.lib.django_util import render
import datetime

def index(request):
  return render('index.mako', request, dict(date=datetime.datetime.now()))
```
to
```
from django.shortcuts import render
import datetime

def index(request):
  return render(request,'index.html', dict(date=datetime.datetime.now()))
```

and it work!

**Comment by sai-krish** [comment]
ah ! glad it's fixed. Closing this.
