### ISSUE TITLE
Hue 4.10 Docker image doesn't work with Kerberos authentication

### ISSUE THREAD

**Issue by pietrogentile** [cloudera/hue#2778]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com/?

Yes, the issue already present [here](https://github.com/cloudera/hue/issues/2249#issue-920162567).

Describe the bug:

Hue Docker image fails trying to interact with kerberized Hadoop cluster. It seems that _krb5-*_ client libraries are not installed.

They were removed, if I correctly understood, in [this commit](https://github.com/cloudera/hue/commit/003855714392b8ad5781c236d0e71dedb19198df)

Steps to reproduce it:

Have a cluster (Hadoop) that has Kerberos authentication enabled.

In the _hue-ini_ file, add _kerberos_ section configured as below:

```
[[kerberos]]
    hue_keytab = /etc/hue.keytab
    hue_principal = hue/***@***
    keytab_reinit_frequency=3600
    ccache_path=/var/run/hue/hue_krb5_ccache
    kinit_path = /usr/bin/kinit
```

When restarted, it tries to perform Kerberos authentication, but it crashes with the error:

```
Traceback (most recent call last):
  File "/usr/share/hue/build/env/bin/hue", line 33, in <module>
    sys.exit(load_entry_point('desktop', 'console_scripts', 'hue')())
  File "/usr/share/hue/desktop/core/src/desktop/manage_entry.py", line 230, in entry
    execute_from_command_line(sys.argv)
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/share/hue/desktop/core/src/desktop/management/commands/kt_renewer.py", line 25, in handle
    desktop.kt_renewer.run()
  File "/usr/share/hue/desktop/core/src/desktop/kt_renewer.py", line 119, in run
    renew_from_kt()
  File "/usr/share/hue/desktop/core/src/desktop/kt_renewer.py", line 41, in renew_from_kt
    subp = subprocess.Popen(cmdv, stdout=subprocess.PIPE,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/kinit' 
```
See full log in the [attachement ](https://github.com/cloudera/hue/files/8402020/logs.log)

Hue version or source:

Helm Chart Version: _1.0.3_
Hue version: _4.10.0_

**Comment by Harshg999** [comment]
Hi @pietrogentile, thanks for reporting this issue!
Added the `krb5-config`, `krb5-user` packages via https://github.com/cloudera/hue/pull/2797.
