### ISSUE TITLE
HUE ignore impala_principal

### ISSUE THREAD

**Issue by adrenasxxx** [cloudera/hue#2832]
Describe the bug: [impala] Ignoring hostname from configured "impala_principal" while getting Service Ticket for Impala

Steps to reproduce it?

Add a LB on the node1, e.g: c5356-node1.coelab.cloudera.com and configure it in the Impala/Configuraiton/load_balancer

Add in the HUE ini safety valve the below (to try to bypass the LB connecting straight to the ImpalaD using the TGS of the LB as it should be)

[impala]
server_host=c5356-node3.coelab.cloudera.com
server_port=21050
impala_principal=impala/c5356-node1.coelab.cloudera.com@COELAB.CLOUDERA.COM
use_sasl=true  ##(with and without the issue is reproducible)

On the HUE Logs:
```
[02/May/2022 08:23:06 -0700] dbms         DEBUG    Query Server: {'SESSION_TIMEOUT_S': 1800, 'QUERY_TIMEOUT_S': 600, 'server_name': 'impala', 'server_host': 'c5356-node3.coelab.cloudera.com', 'querycache_rows': 100000, 'server_port': 21050, 'auth_password_used': False, 'impersonation_enabled': False, 'auth_username': 'hue', 'principal': 'impala/c5356-node1.coelab.cloudera.com@COELAB.CLOUDERA.COM'}
[02/May/2022 08:23:13 -0700] thrift_util  INFO     Thrift exception; retrying: TSocket read 0 bytes
[02/May/2022 08:23:13 -0700] thrift_util  INFO     Thrift exception; retrying: TSocket read 0 bytes
[02/May/2022 08:23:13 -0700] thrift_util  WARNING  Out of retries for thrift call: ExecuteStatement
[02/May/2022 08:23:13 -0700] thrift_util  INFO     Thrift saw a transport exception: TSocket read 0 bytes
[02/May/2022 08:23:13 -0700] decorators   ERROR    Error running execute
Traceback (most recent call last):
  File "/opt/cloudera/parcels/CDH-5.16.1-1.cdh5.16.1.p0.3/lib/hue/desktop/libs/notebook/src/notebook/decorators.py", line 97, in decorator
    return func(*args, **kwargs)
  File "/opt/cloudera/parcels/CDH-5.16.1-1.cdh5.16.1.p0.3/lib/hue/desktop/libs/notebook/src/notebook/api.py", line 167, in execute
    response = _execute_notebook(request, notebook, snippet)
  File "/opt/cloudera/parcels/CDH-5.16.1-1.cdh5.16.1.p0.3/lib/hue/desktop/libs/notebook/src/notebook/api.py", line 149, in _execute_notebook
    raise ex
QueryError
```

On the ImpalaD logs:
```
E0502 15:23:11.830476 126230 authentication.cc:176] SASL message (Kerberos (external)): GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Request ticket server impala/c5356-node3.coelab.cloud
era.com@COELAB.CLOUDERA.COM found in keytab but does not match server principal impala/c5356-node1.coelab.cloudera.com@)
I0502 15:23:11.830724 126230 thrift-util.cc:113] TAcceptQueueServer: Caught TException: SASL(-13): authentication failure: GSSAPI Failure: gss_accept_sec_context
E0502 15:23:11.834539 126230 authentication.cc:176] SASL message (Kerberos (external)): GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Request ticket server impala/c5356-node3.coelab.cloud
era.com@COELAB.CLOUDERA.COM found in keytab but does not match server principal impala/c5356-node1.coelab.cloudera.com@)
I0502 15:23:11.834766 126230 thrift-util.cc:113] TAcceptQueueServer: Caught TException: SASL(-13): authentication failure: GSSAPI Failure: gss_accept_sec_context
E0502 15:23:11.837899 126230 authentication.cc:176] SASL message (Kerberos (external)): GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Request ticket server impala/c5356-node3.coelab.cloud
era.com@COELAB.CLOUDERA.COM found in keytab but does not match server principal impala/c5356-node1.coelab.cloudera.com@)
I0502 15:23:11.838115 126230 thrift-util.cc:113] TAcceptQueueServer: Caught TException: SASL(-13): authentication failure: GSSAPI Failure: gss_accept_sec_context
```

Hue version or source? reproduced on 5.16, 6.3.x, most likely all the versions are affected.
It is also advertised on [HUE-6775](https://issues.cloudera.org/browse/HUE-6775) however Jira is not used anymore, so revamping this issue here also. In HUE the error shown is:

> TSocket read 0 bytes (code THRIFTTRANSPORT): TTransportException('TSocket read 0 bytes',)

**Comment by quadoss** [comment]
I dont see this as an issue, but an issue with the config.  Note that impala_principal only takes <principal_name>/<hostname> and not <principal_name>/<hostname>@REALM.COM

In this case, I see the hostname to be fine but since there is @REALM mentioned as well, the information being passed in has "impala/c5356-node1.coelab.cloudera.com@".  

Modify the impala_principal to remove @REALM.COM and then see if you have an issue.

**Comment by adrenasxxx** [comment]
@quadoss 
Apart from the fact that for the Kerberos standard the Principal is divided into three parts: the primary, the instance, and the realm. The format of a typical Kerberos V5 principal is primary/instance@REALM.

Of course, you are free to implement your principal definition that does not observe the Kerberos standard, BUT yes, this observation leaves the time it takes as also specifying the configuration you recommended it does not work and impala_principal is ignored during the TGS request:


in `Hue Service Advanced Configuration Snippet (Safety Valve) for hue_safety_valve.ini`

```
[impala]
server_host=c5356-node3.coelab.cloudera.com
server_port=21050
impala_principal=impala/c5356-node1.coelab.cloudera.com
```




[HUE runcpserver.log]
```
[03/May/2022 00:11:40 -0700] dbms         DEBUG    Query Server: {'SESSION_TIMEOUT_S': 1800, 'QUERY_TIMEOUT_S': 600, 'server_name': 'impala', 'server_host': 'c5356-node3.coelab.cloudera.com', 'querycache_rows': 100000, 'server_port': 21050, 'auth_password_used': False, 'impersonation_enabled': False, 'auth_username': 'hue', 'principal': 'impala/c5356-node1.coelab.cloudera.com'}
[03/May/2022 00:11:40 -0700] dbms         DEBUG    Query Server: {'SESSION_TIMEOUT_S': 1800, 'QUERY_TIMEOUT_S': 600, 'server_name': 'impala', 'server_host': 'c5356-node3.coelab.cloudera.com', 'querycache_rows': 100000, 'server_port': 21050, 'auth_password_used': False, 'impersonation_enabled': False, 'auth_username': 'hue', 'principal': 'impala/c5356-node1.coelab.cloudera.com'}
[03/May/2022 00:11:40 -0700] access       INFO     10.19.18.169 admin - "POST /notebook/api/close_statement HTTP/1.1" returned in 163ms (mem: 138mb)
[03/May/2022 00:11:40 -0700] dbms         DEBUG    Query Server: {'SESSION_TIMEOUT_S': 1800, 'QUERY_TIMEOUT_S': 600, 'server_name': 'impala', 'server_host': 'c5356-node3.coelab.cloudera.com', 'querycache_rows': 100000, 'server_port': 21050, 'auth_password_used': False, 'impersonation_enabled': False, 'auth_username': 'hue', 'principal': 'impala/c5356-node1.coelab.cloudera.com'}
[03/May/2022 00:11:40 -0700] dbms         DEBUG    Query Server: {'SESSION_TIMEOUT_S': 1800, 'QUERY_TIMEOUT_S': 600, 'server_name': 'impala', 'server_host': 'c5356-node3.coelab.cloudera.com', 'querycache_rows': 100000, 'server_port': 21050, 'auth_password_used': False, 'impersonation_enabled': False, 'auth_username': 'hue', 'principal': 'impala/c5356-node1.coelab.cloudera.com'}
[03/May/2022 00:11:41 -0700] access       DEBUG    10.19.18.169 admin - "GET /static/desktop/js/sqlFunctions.js HTTP/1.1" (mem: 138mb)
[03/May/2022 00:11:41 -0700] access       INFO     10.19.18.169 admin - "GET /static/desktop/js/sqlFunctions.js HTTP/1.1" returned in 1ms (mem: 138mb)
[03/May/2022 00:11:42 -0700] access       INFO     10.19.18.169 admin - "POST /desktop/log_analytics HTTP/1.1" (mem: 138mb)-- PAGE: editor/showLongOperationWarning
[03/May/2022 00:11:42 -0700] access       INFO     10.19.18.169 admin - "POST /desktop/log_analytics HTTP/1.1" returned in 1ms (mem: 138mb)
[03/May/2022 00:11:46 -0700] thrift_util  INFO     Thrift exception; retrying: TSocket read 0 bytes
[03/May/2022 00:11:46 -0700] thrift_util  INFO     Thrift exception; retrying: TSocket read 0 bytes
[03/May/2022 00:11:46 -0700] thrift_util  WARNING  Out of retries for thrift call: ExecuteStatement
[03/May/2022 00:11:46 -0700] thrift_util  INFO     Thrift saw a transport exception: TSocket read 0 bytes
[03/May/2022 00:11:46 -0700] decorators   ERROR    Error running execute
Traceback (most recent call last):
  File "/opt/cloudera/parcels/CDH-5.16.1-1.cdh5.16.1.p0.3/lib/hue/desktop/libs/notebook/src/notebook/decorators.py", line 97, in decorator
    return func(*args, **kwargs)
  File "/opt/cloudera/parcels/CDH-5.16.1-1.cdh5.16.1.p0.3/lib/hue/desktop/libs/notebook/src/notebook/api.py", line 167, in execute
    response = _execute_notebook(request, notebook, snippet)
  File "/opt/cloudera/parcels/CDH-5.16.1-1.cdh5.16.1.p0.3/lib/hue/desktop/libs/notebook/src/notebook/api.py", line 149, in _execute_notebook
    raise ex
QueryError
```

[impalaD node3 logs]
```
E0503 07:11:47.907485 12409 authentication.cc:176] SASL message (Kerberos (external)): GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Request ticket server impala/c5356-node3.coelab.cloude
ra.com@COELAB.CLOUDERA.COM found in keytab but does not match server principal impala/c5356-node1.coelab.cloudera.com@)
I0503 07:11:47.907613 12409 thrift-util.cc:113] TAcceptQueueServer: Caught TException: SASL(-13): authentication failure: GSSAPI Failure: gss_accept_sec_context
E0503 07:11:47.911752 12409 authentication.cc:176] SASL message (Kerberos (external)): GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Request ticket server impala/c5356-node3.coelab.cloude
ra.com@COELAB.CLOUDERA.COM found in keytab but does not match server principal impala/c5356-node1.coelab.cloudera.com@)
I0503 07:11:47.911866 12409 thrift-util.cc:113] TAcceptQueueServer: Caught TException: SASL(-13): authentication failure: GSSAPI Failure: gss_accept_sec_context
E0503 07:11:47.915659 12409 authentication.cc:176] SASL message (Kerberos (external)): GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Request ticket server impala/c5356-node3.coelab.cloude
ra.com@COELAB.CLOUDERA.COM found in keytab but does not match server principal impala/c5356-node1.coelab.cloudera.com@)
I0503 07:11:47.915787 12409 thrift-util.cc:113] TAcceptQueueServer: Caught TException: SASL(-13): authentication failure: GSSAPI Failure: gss_accept_sec_context
```

So the issue still exists and it is true.
