### ISSUE TITLE
Connect with S3 ( minio ) 

### ISSUE THREAD

**Issue by achraf-bouaouda** [cloudera/hue#2919]
Unable to connect to minio  object store : 
configuration : 
`      [aws]
        [[aws_accounts]]
          # Default AWS account
          [[[default]]]
            # AWS credentials
              access_key_id=XXXXXXXXXXXXX
              secret_access_key=YYYYYYYYYYYY
              region=us-east-1
              host=INTERNAL_IP
              is_secure=false`
on UI , I get this error : 
  S3 filesystem exception.
  Failed to retrieve buckets: Bad Request

Logs : 
`[07/Jul/2022 03:35:26 -0700] exceptions_renderable ERROR    Potential trace: [<FrameSummary file /usr/share/hue/apps/filebrowser/src/filebrowser/views.py, line 267 in view>, <FrameSummary file /usr/share/hue/apps/filebrowser/src/filebrowser/views.py, line 519 in listdir_paged>, <FrameSummary file /usr/share/hue/desktop/core/src/desktop/lib/fs/proxyfs.py, line 132 in do_as_user>, <FrameSummary file /usr/share/hue/desktop/core/src/desktop/lib/fs/proxyfs.py, line 154 in listdir_stats>, <FrameSummary file /usr/share/hue/desktop/libs/aws/src/aws/s3/__init__.py, line 54 in wrapped>, <FrameSummary file /usr/share/hue/desktop/libs/aws/src/aws/s3/s3fs.py, line 323 in listdir_stats>]
[07/Jul/2022 03:35:26 -0700] middleware   INFO     Processing exception: S3 filesystem exception.: Traceback (most recent call last):
  File "/usr/share/hue/desktop/libs/aws/src/aws/s3/s3fs.py", line 315, in listdir_stats
    [S3Stat.from_bucket(b, self.fs) for b in self._s3_connection.get_all_buckets(headers=self.header_values)], key=lambda x: x.name)
  File "/usr/share/hue/desktop/core/ext-py3/boto-2.49.0/boto/s3/connection.py", line 462, in get_all_buckets
    raise self.provider.storage_response_error(
boto.exception.S3ResponseError: S3ResponseError: 400 Bad Request
<?xml version="1.0" encoding="utf-8"?>
<Error><Code>IllegalLocationConstraintException</Code><Message>Attempting to access a bucket from a different region than where the bucket exists.</Message><Resource>/</Resource><LocationConstraint/><ConfiguredRegion>us-east-1</ConfiguredRegion></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/hue/apps/filebrowser/src/filebrowser/views.py", line 267, in view
    return listdir_paged(request, path)
  File "/usr/share/hue/apps/filebrowser/src/filebrowser/views.py", line 519, in listdir_paged
    all_stats = request.fs.do_as_user(do_as, request.fs.listdir_stats, path)
  File "/usr/share/hue/desktop/core/src/desktop/lib/fs/proxyfs.py", line 132, in do_as_user
    return fn(*args, **kwargs)
  File "/usr/share/hue/desktop/core/src/desktop/lib/fs/proxyfs.py", line 154, in listdir_stats
    return self._get_fs(path).listdir_stats(path, **kwargs)
  File "/usr/share/hue/desktop/libs/aws/src/aws/s3/__init__.py", line 54, in wrapped
    return fn(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/aws/src/aws/s3/s3fs.py", line 323, in listdir_stats
    raise S3FileSystemException(_('Failed to retrieve buckets: %s') % e.reason)
aws.s3.s3fs.S3FileSystemException: Failed to retrieve buckets: Bad Request`

default region is 'us-east-1' ( ref https://docs.min.io/docs/how-to-use-aws-sdk-for-python-with-minio-server.html  )

ENV : 
kubernetes with helm chart 
docker image : https://hub.docker.com/layers/hue/gethue/hue/20220706-140101/images/sha256-eebb81c63debfe125f91b09d43b9a2e120a503baa52bddbb5e91bb56ee34328c?context=explore

**Comment by achraf-bouaouda** [comment]
unblocked using : 
adding 
   hostAliases:
  - ip: "internal_server_ip"
    hostnames:
    - "**us-east-1**.minio.com"
when an IP or DNS NAME  is specified , normally the API should connect using region from : 
  [[aws_accounts]]
    # Default AWS account
    ## [[[default]]]
      ......
# AWS region to use, if no region is specified, will attempt to connect to standard s3.amazonaws.com endpoint
      **region=us-east-1**
