### ISSUE TITLE
Make apps compile errors

### ISSUE THREAD

**Issue by 1356469429** [cloudera/hue#295]
CenOS6.5 Maven 3.0.5 oracle jdk 1.7.0_79 hue-master
Error is as follows:
[WARNING] The POM for org.apache.maven.plugins:maven-enforcer-plugin:jar:1.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] Total time: 0.228s
[INFO] Finished at: Wed Jan 13 17:37:38 PST 2016
[INFO] Final Memory: 4M/43M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to parse plugin descriptor for org.apache.maven.plugins:maven-enforcer-plugin:1.0 (/root/.m2/repository/org/apache/maven/plugins/maven-enforcer-plugin/1.0/maven-enforcer-plugin-1.0.jar): error in opening zip file -> [Help 1]

**Comment by 1356469429** [comment]
When I switched system solved the problem
but ,When I was using the supervisor command to start server .Start failure
The following information:
Traceback (most recent call last):
  File "/home/hadoop/branch-3.7.1/build/env/bin/hue", line 9, in <module>
    load_entry_point('desktop==3.9.0', 'console_scripts', 'hue')()
  File "/home/hadoop/branch-3.7.1/desktop/core/src/desktop/manage_entry.py", line 57, in entry
    execute_from_command_line(sys.argv)
  File "/home/hadoop/branch-3.7.1/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/hadoop/branch-3.7.1/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/hadoop/branch-3.7.1/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/__init__.py", line 261, in fetch_command
    commands = get_commands()
  File "/home/hadoop/branch-3.7.1/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/__init__.py", line 107, in get_commands
    apps = settings.INSTALLED_APPS
  File "/home/hadoop/branch-3.7.1/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/hadoop/branch-3.7.1/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/hadoop/branch-3.7.1/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/hadoop/branch-3.7.1/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/hadoop/branch-3.7.1/desktop/core/src/desktop/settings.py", line 236, in <module>
    appmanager.load_libs()
  File "/home/hadoop/branch-3.7.1/desktop/core/src/desktop/appmanager.py", line 218, in load_libs
    m = lib.load()
  File "/home/hadoop/branch-3.7.1/build/env/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2310, in load
    return self.resolve()
  File "/home/hadoop/branch-3.7.1/build/env/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/hadoop/branch-3.7.1/desktop/libs/aws/src/aws/__init__.py", line 18, in <module>
    import aws.s3
  File "/home/hadoop/branch-3.7.1/desktop/libs/aws/src/aws/s3/__init__.py", line 28, in <module>
    from boto.exception import S3ResponseError
  File "/home/hadoop/branch-3.7.1/build/env/lib/python2.6/site-packages/boto-2.38.0-py2.6.egg/boto/__init__.py", line 27, in <module>
    from boto.pyami.config import Config, BotoConfigLocations
  File "/home/hadoop/branch-3.7.1/build/env/lib/python2.6/site-packages/boto-2.38.0-py2.6.egg/boto/pyami/config.py", line 29, in <module>
    from boto.compat import expanduser, ConfigParser, StringIO
  File "/home/hadoop/branch-3.7.1/build/env/lib/python2.6/site-packages/boto-2.38.0-py2.6.egg/boto/compat.py", line 54, in <module>
    from boto.vendored.six.moves.queue import Queue
  File "/home/hadoop/branch-3.7.1/build/env/lib/python2.6/site-packages/boto-2.38.0-py2.6.egg/boto/vendored/six.py", line 192, in load_module
    mod = mod._resolve()
  File "/home/hadoop/branch-3.7.1/build/env/lib/python2.6/site-packages/boto-2.38.0-py2.6.egg/boto/vendored/six.py", line 106, in _resolve
    return _import_module(self.mod)
  File "/home/hadoop/branch-3.7.1/build/env/lib/python2.6/site-packages/boto-2.38.0-py2.6.egg/boto/vendored/six.py", line 77, in _import_module
    __import__(name)
  File "/usr/lib64/python2.6/Queue.py", line 1, in <module>
    """A multi-producer, multi-consumer queue."""
KeyboardInterrupt

**Comment by romainr** [comment]
Is  
./build/env/bin/hue runserver

working at least?

**Comment by 1356469429** [comment]
Yes
