### ISSUE TITLE
After rollback to 5.4.3 from cdh 5.5.1, ldap login failed!

### ISSUE THREAD

**Issue by baibaichen** [cloudera/hue#298]
After rollback to 5.4.3 from cdh 5.5.1, **ldap login backend** is broken, and we **get server error(500)**. 

The full stack trace
*Processing exception: 'NoneType' object has no attribute 'creation_method': Traceback (most recent call last):*
>>      File "/opt/cloudera/parcels/CDH-5.4.3-1.cdh5.4.3.p0.6/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/handlers/base.py", line 112, in get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/opt/cloudera/parcels/CDH-5.4.3-1.cdh5.4.3.p0.6/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/transaction.py", line 371, in inner
        return func(*args, **kwargs)
      File "/opt/cloudera/parcels/CDH-5.4.3-1.cdh5.4.3.p0.6/lib/hue/desktop/core/src/desktop/auth/views.py", line 105, in dt_login
        if auth_form.is_valid():
      File "/opt/cloudera/parcels/CDH-5.4.3-1.cdh5.4.3.p0.6/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/forms/forms.py", line 129, in is_valid
        return self.is_bound and not bool(self.errors)
      File "/opt/cloudera/parcels/CDH-5.4.3-1.cdh5.4.3.p0.6/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/forms/forms.py", line 121, in errors
        self.full_clean()
      File "/opt/cloudera/parcels/CDH-5.4.3-1.cdh5.4.3.p0.6/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/forms/forms.py", line 274, in full_clean
        self._clean_form()
      File "/opt/cloudera/parcels/CDH-5.4.3-1.cdh5.4.3.p0.6/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/forms/forms.py", line 300, in _clean_form
        self.cleaned_data = self.clean()
      File "/opt/cloudera/parcels/CDH-5.4.3-1.cdh5.4.3.p0.6/lib/hue/desktop/core/src/desktop/auth/forms.py", line 79, in clean
        return self.authenticate()
      File "/opt/cloudera/parcels/CDH-5.4.3-1.cdh5.4.3.p0.6/lib/hue/desktop/core/src/desktop/auth/forms.py", line 52, in authenticate
        return super(AuthenticationForm, self).clean()
      File "/opt/cloudera/parcels/CDH-5.4.3-1.cdh5.4.3.p0.6/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/contrib/auth/forms.py", line 189, in clean
        password=password)
      File "/opt/cloudera/parcels/CDH-5.4.3-1.cdh5.4.3.p0.6/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/contrib/auth/__init__.py", line 49, in authenticate
        user = backend.authenticate(**credentials)
      File "/opt/cloudera/parcels/CDH-5.4.3-1.cdh5.4.3.p0.6/lib/hue/desktop/core/src/desktop/auth/backend.py", line 436, in authenticate
        profile.creation_method = UserProfile.CreationMethod.EXTERNAL
    AttributeError: 'NoneType' object has no attribute 'creation_method'

I guess there are something wrong in database, how could i fix it?

**Comment by romainr** [comment]
It seems like the user profile of the user is not present. 
Do you have the same error with all the users?

Did you restart Hue? Could be just a caching issue: https://github.com/cloudera/hue/blob/master/apps/useradmin/src/useradmin/models.py#L144

**Comment by baibaichen** [comment]
Yes, we even re-installed the hue on the same host, the issue is still existed, we could reproduce this issue in three clusters. The most important step is we changed login back-end from AllowAllBackend to LdapBackend after rolling-back.

The current workaround is re-installed the hue on the different host.

**Comment by romainr** [comment]
Which database are you using? The default sqlite? 
Re-installing on a different host means that you probably lose all the Hue data (users, queries... etc)

**Comment by baibaichen** [comment]
we use **mysql**,  it looks like there is something related with environment.
