### ISSUE TITLE
"Results have expired, rerun the query if needed"

### ISSUE THREAD

**Issue by jerryleooo** [cloudera/hue#3164]
### Describe the bug:

Global variables are not shared between different gunicorn workers. https://github.com/cloudera/hue/blob/b5d126ea651d76e982a13c7da3661dac9a939246/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py#L90

### Steps to reproduce it?

1. Use the docker-compose to up the service, with following configurations:
```
gunicorn_work_class=eventlet
gunicorn_number_of_workers=8
```
2. configure an interpreter with Athena/Trino/Presto + sqlalchemy
3. use 2 different browser tabs to submit queries in editor, and you may see the ` Results have expired, rerun the query if needed.` error

### Hue version or source? 
open source 4.10.0

**Comment by jerryleooo** [comment]
I guess it's better to use https://docs.djangoproject.com/en/dev/topics/http/sessions/ ?

**Comment by sbbagal13** [comment]
I too observed similar with Trino

**Comment by bjornalm** [comment]
Hi @jerryleooo, thanks for reporting this. Do you know if this happens with other interpreters as well? 

@Harshg999 can you have a look?

**Comment by jerryleooo** [comment]
Hi @bjornalm I haven't tried other interpreters, later i may try jdbc and update here

**Comment by vpattar** [comment]
I too observed similar issue with Trino, which is connected through a VPC endpoint.

Is there a known workaround to this?

**Comment by jerryleooo** [comment]
@vpattar now I use `gunicorn_work_class=sync` and `gunicorn_number_of_workers=1`, I started 3 instances behind a LB

**Comment by Harshg999** [comment]
With Gunicorn now, we need to relook and scope how to share global variable state. I've created an internal roadmap item for this issue and will take it up for subsequent releases. 
Thanks for flagging this @jerryleooo.

**Comment by hackeryang** [comment]
I also met this error using StarRocks(compatible with mysql protocol), and when i used the mysql JDBC configuration way, it worked and returned query results. Maybe the sqlalchemy way has some session or connection bugs.

You can also try the JDBC way(need to upload JDK and execute `$HUE_HOME/build/env/bin/pip install py4j` ahead): https://docs.gethue.com/administrator/configuration/connectors/#mysql

**Comment by Alterrien** [comment]
I am getting similar issues, that seems to be fixed when relying on the default Gunicorn settings (1 thread and using gthreads).
Also for reference, I have similar issues using hive/beeswax, with the following traceback this time:
```
Traceback (most recent call last):
  File "/opt/hue/desktop/libs/notebook/src/notebook/decorators.py", line 120, in wrapper
    return f(*args, **kwargs)
  File "/opt/hue/desktop/libs/notebook/src/notebook/api.py", line 248, in check_status
    response = _check_status(request, notebook=notebook, snippet=snippet, operation_id=operation_id)
  File "/opt/hue/desktop/libs/notebook/src/notebook/api.py", line 272, in _check_status
    status = response['query_status']['status']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by MonsterChenzhuo** [comment]
@Harshg999 Has this problem been solved? I also encountered this problem when I used spark and hive to submit sql.
