### ISSUE TITLE
Error when connecting to Hive

### ISSUE THREAD

**Issue by kratorr** [cloudera/hue#3183]
I get an error when trying to connect to HiveServer2 (3.1.1) in a Hadoop cluster with SSL and Kerberos.

Traceback:
```
[29/Jan/2023 13:47:55 +0300] hive_server2_lib INFO     beeswax: server_host=hivehost.test.example, use_sasl=True, mechanism=GSSAPI, kerberos_principal_short_name=hive, impersonation_enabled=False, auth_username=hue
[29/Jan/2023 13:47:55 +0300] hive_server2_lib INFO     Session b'=\xa8$Q\x99)Iq\xb5\xc4u\x0b;\xbe\x0f)' opened
[29/Jan/2023 13:47:55 +0300] hive_server2_lib INFO     Session b'A\xdc\xa5\xdbj\xaeH;\x93\xd6\xc24\x01X\xbd\xe3' opened
[29/Jan/2023 13:47:55 +0300] thrift_util  ERROR    Thrift saw exception (this may be expected).
Traceback (most recent call last):
  File "/usr/share/hue/desktop/core/src/desktop/lib/thrift_util.py", line 515, in wrapper
    if not self.transport.isOpen():
  File "/usr/share/hue/desktop/core/src/desktop/lib/thrift_sasl.py", line 61, in isOpen
    return self._trans.isOpen()
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/thrift/transport/TSocket.py", line 92, in isOpen
    peeked_bytes = self.handle.recv(1, socket.MSG_PEEK)
  File "/usr/lib/python3.8/ssl.py", line 1223, in recv
    raise ValueError(
ValueError: non-zero flags not allowed in calls to recv() on <class 'ssl.SSLSocket'>
[29/Jan/2023 13:47:55 +0300] thrift_util  ERROR    Thrift saw exception (this may be expected).
Traceback (most recent call last):
  File "/usr/share/hue/desktop/core/src/desktop/lib/thrift_util.py", line 515, in wrapper
    if not self.transport.isOpen():
  File "/usr/share/hue/desktop/core/src/desktop/lib/thrift_sasl.py", line 61, in isOpen
    return self._trans.isOpen()
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/thrift/transport/TSocket.py", line 92, in isOpen
    peeked_bytes = self.handle.recv(1, socket.MSG_PEEK)
  File "/usr/lib/python3.8/ssl.py", line 1223, in recv
    raise ValueError(
ValueError: non-zero flags not allowed in calls to recv() on <class 'ssl.SSLSocket'>
[29/Jan/2023 13:47:55 +0300] thrift_util  INFO     Thrift saw exception: non-zero flags not allowed in calls to recv() on <class 'ssl.SSLSocket'>
[29/Jan/2023 13:47:55 +0300] decorators   ERROR    Error running describe
Traceback (most recent call last):
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/decorators.py", line 119, in wrapper
    return f(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/api.py", line 1041, in describe
    describe = get_api(request, snippet).describe(notebook, snippet, database, table, column=column)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/base.py", line 647, in describe
    describe_database = self.describe_database(notebook, snippet, database)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/hiveserver2.py", line 976, in describe_database
    return db.get_database(database)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/dbms.py", line 395, in get_database
    return self.client.get_database(database)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 1525, in get_database
    return self._client.get_database(database)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 844, in get_database
    desc_results, desc_schema, operation_handle, session = self.execute_statement(
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 1022, in execute_statement
    (res, session) = self.call(self._client.ExecuteStatement, req, session=session)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 742, in call
    return self.call_return_result_and_session(fn, req, status, session=session)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 779, in call_return_result_and_session
    session = self.open_session(self.user)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 733, in open_session
    configuration = self.get_configuration(session=session)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 1211, in get_configuration
    results = self.execute_query_statement(
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 979, in execute_query_statement
    results, schema, operation_handle, session = self.execute_statement(
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 1022, in execute_statement
    (res, session) = self.call(self._client.ExecuteStatement, req, session=session)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 742, in call
    return self.call_return_result_and_session(fn, req, status, session=session)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 756, in call_return_result_and_session
    return self._call_return_result_and_session(fn, req, status=status, session=session)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 788, in _call_return_result_and_session
    res = fn(req)
  File "/usr/share/hue/desktop/core/src/desktop/lib/thrift_util.py", line 453, in wrapper
    return attr(*args, **kwargs)
  File "/usr/share/hue/desktop/core/src/desktop/lib/thrift_util.py", line 515, in wrapper
    if not self.transport.isOpen():
  File "/usr/share/hue/desktop/core/src/desktop/lib/thrift_sasl.py", line 61, in isOpen
    return self._trans.isOpen()
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/thrift/transport/TSocket.py", line 92, in isOpen
    peeked_bytes = self.handle.recv(1, socket.MSG_PEEK)
  File "/usr/lib/python3.8/ssl.py", line 1223, in recv
    raise ValueError(
ValueError: non-zero flags not allowed in calls to recv() on <class 'ssl.SSLSocket'>
[29/Jan/2023 13:47:55 +0300] thrift_util  INFO     Thrift saw exception: non-zero flags not allowed in calls to recv() on <class 'ssl.SSLSocket'>
[29/Jan/2023 13:47:55 +0300] api          ERROR    Autocomplete data fetching error
Traceback (most recent call last):
  File "/usr/share/hue/apps/beeswax/src/beeswax/api.py", line 122, in _autocomplete
    tables_meta = db.get_tables_meta(database=database)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/dbms.py", line 427, in get_tables_meta
    tables = self.client.get_tables_meta(database, identifier)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 1529, in get_tables_meta
    tables = self._client.get_tables_meta(database, table_names, table_types)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 867, in get_tables_meta
    (res, session) = self.call(self._client.GetTables, req)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 742, in call
    return self.call_return_result_and_session(fn, req, status, session=session)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 779, in call_return_result_and_session
    session = self.open_session(self.user)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 733, in open_session
    configuration = self.get_configuration(session=session)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 1211, in get_configuration
    results = self.execute_query_statement(
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 979, in execute_query_statement
    results, schema, operation_handle, session = self.execute_statement(
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 1022, in execute_statement
    (res, session) = self.call(self._client.ExecuteStatement, req, session=session)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 742, in call
    return self.call_return_result_and_session(fn, req, status, session=session)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 756, in call_return_result_and_session
    return self._call_return_result_and_session(fn, req, status=status, session=session)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 788, in _call_return_result_and_session
    res = fn(req)
  File "/usr/share/hue/desktop/core/src/desktop/lib/thrift_util.py", line 453, in wrapper
    return attr(*args, **kwargs)
  File "/usr/share/hue/desktop/core/src/desktop/lib/thrift_util.py", line 515, in wrapper
    if not self.transport.isOpen():
  File "/usr/share/hue/desktop/core/src/desktop/lib/thrift_sasl.py", line 61, in isOpen
    return self._trans.isOpen()
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/thrift/transport/TSocket.py", line 92, in isOpen
    peeked_bytes = self.handle.recv(1, socket.MSG_PEEK)
  File "/usr/lib/python3.8/ssl.py", line 1223, in recv
    raise ValueError(
ValueError: non-zero flags not allowed in calls to recv() on <class 'ssl.SSLSocket'>
```
Configuration:
Run in Docker, image: gethue/hue:20230127-140101
```
[desktop]
# Path to default Certificate Authority certificates.
ssl_cacerts=/usr/share/hue/desktop/conf/hue_truststore.pem
# Choose whether Hue should validate certificates received from the server.
ssl_validate=true

[hadoop]
[[hdfs_clusters]]
[[[default]]]
# Change this if your HDFS cluster is Kerberos-secured
security_enabled=true
hadoop_conf_dir='/etc/hadoop/conf'
is_enabled=true

[beeswax]
hive_server_host=hivehost.test.example
hive_server_port=10000
use_sasl=true
[[ssl]]
enabled=true
cacerts=/usr/share/hue/desktop/conf/hue_truststore.pem
validate=true
```

At the same time, the HDFS browser and YARN jobs browser work fine.

For testing, I made a connection to HiveServer2 to another Hadoop without SSL, only with Kerberos and everything worked fine, tables were visible and requests were executed.
Any ideas? Is it a problem with the settings or an SSL bug?

**Comment by bjornalm** [comment]
Hi @kratorr, thanks for reporting. @ranade1 can you take a look?

**Comment by kratorr** [comment]
I decided to check docker image 4.9.0 and 4.8.0 , with 4.9.0 the same error, but on 4.8.0 Hue was able to read the tables from Hive. But now I get another error related to Cyrillic characters in LDAP groups, which has been fixed in fresh versions.

**Comment by bjornalm** [comment]
I see, so do you need any further help with this particular config issue, or can we close?

**Comment by kratorr** [comment]
The error with SSL on fresh versions of Hue still persists, I would like to use the latest version of the software. Could it be related to the supported encryption types in versions 4.8.0 and 4.11?

**Comment by kratorr** [comment]
UPD
I tried adding lines of code from this [#3260](https://github.com/cloudera/hue/pull/3260) and the error does not appear, the connection to Hive works. Waiting for PR to confirm)

**Comment by kratorr** [comment]
@bjornalm  I saw that https://github.com/cloudera/hue/pull/3260 is closed and the fix is in another PR https://github.com/cloudera/hue/pull/3291 .  Can I find out how long it will take for these changes to appear in the docker image on hub.docker.com?

**Comment by bjornalm** [comment]
@kratorr We are normally updating the docker images with the latest code from master, meaning that the image would have the code the day after the PR is merged. But we have been having some issues with this flow lately and the docker images have been based on an older version instead. We are looking to fix the problem. @agl29 can you leave a small comment when the docker images are properly updated again?

**Comment by agl29** [comment]
Hi @kratorr, @bjornalm 
We have triggered the script for the new docker image. You will be able to see that image in couple of hours.

**Comment by Harshg999** [comment]
The latest Hue image should be ready for use @kratorr. Try pulling it now and check.
