### ISSUE TITLE
invalid syntax?

### ISSUE THREAD

**Issue by mzq1312117926** [cloudera/hue#3199]
[17/Feb/2023 00:48:56 -0800] decorators   ERROR    Error running create_session
Traceback (most recent call last):
  File "/data02/hue-release-4.11.0/desktop/libs/notebook/src/notebook/decorators.py", line 119, in wrapper
    return f(*args, **kwargs)
  File "/data02/hue-release-4.11.0/desktop/libs/notebook/src/notebook/api.py", line 115, in create_session
    response['session'] = get_api(request, session).create_session(lang=session['type'], properties=properties)
  File "/data02/hue-release-4.11.0/desktop/libs/notebook/src/notebook/models.py", line 586, in get_api
    return ApiWrapper(request, snippet)
  File "/data02/hue-release-4.11.0/desktop/libs/notebook/src/notebook/models.py", line 570, in __init__
    self.api = _get_api(request, snippet)
  File "/data02/hue-release-4.11.0/desktop/libs/notebook/src/notebook/connectors/base.py", line 476, in get_api
    from notebook.connectors.jdbc import JdbcApi
  File "/data02/hue-release-4.11.0/desktop/libs/notebook/src/notebook/connectors/jdbc.py", line 54
    raise AuthenticationRequired, '', sys.exc_info()[2]
                                ^
SyntaxError: invalid syntax

hue 4.11
python 3.8.16

**Comment by bjornalm** [comment]
Hi @mzq1312117926, thanks for reporting. Can you describe how to reproduce this issue?

**Comment by mzq1312117926** [comment]
> Hi @mzq1312117926, thanks for reporting. Can you describe how to reproduce this issue?

Error reporting of starting the hue log after configuring the jdbc link clickhouse

**Comment by bjornalm** [comment]
> > Hi @mzq1312117926, thanks for reporting. Can you describe how to reproduce this issue?
> 
> Error reporting of starting the hue log after configuring the jdbc link clickhouse

Thanks, can you share the configuration as well?

**Comment by Harshg999** [comment]
Good catch @mzq1312117926! Thanks for reporting this.
This syntax is for python2 and is not supported in python3. Would you like to fix this issue via a PR contribution?

**Comment by bjornalm** [comment]
> Hi @Harshg999, I would like to work on the issue. Would you assign it to me?

Hi @Madhukar98 I've assigned this issue to you. We are very happy that you want to become a committer, let us know if you need any help. See https://github.com/cloudera/hue/blob/master/CONTRIBUTING.md to get started :-)

**Comment by Madhukar98** [comment]
Hi @bjornalm Thanks for the documentation, it was quite helpful while building Hue. I had raised a PR for this -https://github.com/cloudera/hue/pull/3344
