### ISSUE TITLE
Imported gets in stuck state in 4.10.0

### ISSUE THREAD

**Issue by divincode** [cloudera/hue#3219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This issue happens when we import documents , which are json in type . The json consists queries , which when we click in Hue 4.9.0 opens up the editor but in Hue 4.10.0 , it gets stuck in the reloading state.

The error shown here is 

```
[23/Feb/2023 10:53:01 -0800] access       ERROR    10.75.185.233 raviax - "POST /desktop/log_js_error HTTP/1.1" --- JS ERROR: {"msg":"Uncaught TypeError: Cannot read properties of undefined (reading 'dialect')","url":"[http://10.242.92.216:8888/static/desktop/js/bundles/hue/hue-5fffb0b9-bundle-b1e482f4e9a6a404921a.ff69ac51086e.js","line":16304,"column":31,"stack":"TypeError](http://10.242.92.216:8888/static/desktop/js/bundles/hue/hue-5fffb0b9-bundle-b1e482f4e9a6a404921a.ff69ac51086e.js%22,%22line%22:16304,%22column%22:31,%22stack%22:%22TypeError) : Cannot read properties of undefined (reading 'dialect')\n    at [http://10.242.92.216:8888/static/desktop/js/bundles/hue/hue-5fffb0b9-bundle-b1e482f4e9a6a404921a.ff69ac51086e.js:16304:31\n](http://10.242.92.216:8888/static/desktop/js/bundles/hue/hue-5fffb0b9-bundle-b1e482f4e9a6a404921a.ff69ac51086e.js:16304:31/n)     at Function.yd (http://10.242.92.216:8888/static/desktop/js/bundles/hue/defaultVendors~hue-9241dc7c-bundle-b1e482f4e9a6a404921a.e5976413527a.js:3231:359)\n     at Function.zd (http://10.242.92.216:8888/static/desktop/js/bundles/hue/defaultVendors~hue-9241dc7c-bundle-b1e482f4e9a6a404921a.e5976413527a.js:3231:45)\n     at Function.ha (http://10.242.92.216:8888/static/desktop/js/bundles/hue/defaultVendors~hue-9241dc7c-bundle-b1e482f4e9a6a404921a.e5976413527a.js:3230:384)\n     at [Function.Qa](http://function.qa/)  (http://10.242.92.216:8888/static/desktop/js/bundles/hue/defaultVendors~hue-9241dc7c-bundle-b1e482f4e9a6a404921a.e5976413527a.js:3233:5)\n     at Function.subscribe (http://10.242.92.216:8888/static/desktop/js/bundles/hue/defaultVendors~hue-9241dc7c-bundle-b1e482f4e9a6a404921a.e5976413527a.js:3214:223)\n     at Function.$c (http://10.242.92.216:8888/static/desktop/js/bundles/hue/defaultVendors~hue-9241dc7c-bundle-b1e482f4e9a6a404921a.e5976413527a.js:3229:487)\n     at [Object.ba](http://object.ba/)  (http://10.242.92.216:8888/static/desktop/js/bundles/hue/defaultVendors~hue-9241dc7c-bundle-b1e482f4e9a6a404921a.e5976413527a.js:3184:292)\n     at [Object.cc](http://object.cc/)  (http://10.242.92.216:8888/static/desktop/js/bundles/hue/defaultVendors~hue-9241dc7c-bundle-b1e482f4e9a6a404921a.e5976413527a.js:3217:391)\n     at Snippet.e [as dialect] (http://10.242.92.216:8888/static/desktop/js/bundles/hue/defaultVendors~hue-9241dc7c-bundle-b1e482f4e9a6a404921a.e5976413527a.js:3227:5 )"}
```

This error is brought up by this commit - @Harshg999 

>https://github.com/cloudera/hue/commit/e65379dd37120cc1a93c709553cc7fe7ceb58010

I still dont understand why this commit is brought up as u can see the defination of connector.dialect is removed hence when the code flows the error comes.

<img width="1440" alt="Screenshot 2023-03-07 at 9 38 18 AM" src="https://user-images.githubusercontent.com/35135348/223322913-5ef90ae8-8446-4b6c-af37-7282dd3c7bfa.png">

### Steps To Reproduce

1) open the HUE UI
2) Click of documents.
3) upload the .json file (screenshot is attached ) 
4) click on the any of the document which is imported 

### Logs

[23/Feb/2023 10:53:01 -0800] access       ERROR    10.75.185.233 raviax - "POST /desktop/log_js_error HTTP/1.1" --- JS ERROR: {"msg":"Uncaught TypeError: Cannot read properties of undefined (reading 'dialect')","url":"[http://10.242.92.216:8888/static/desktop/js/bundles/hue/hue-5fffb0b9-bundle-b1e482f4e9a6a404921a.ff69ac51086e.js","line":16304,"column":31,"stack":"TypeError](http://10.242.92.216:8888/static/desktop/js/bundles/hue/hue-5fffb0b9-bundle-b1e482f4e9a6a404921a.ff69ac51086e.js%22,%22line%22:16304,%22column%22:31,%22stack%22:%22TypeError) : Cannot read properties of undefined (reading 'dialect')\n    at [http://10.242.92.216:8888/static/desktop/js/bundles/hue/hue-5fffb0b9-bundle-b1e482f4e9a6a404921a.ff69ac51086e.js:16304:31\n](http://10.242.92.216:8888/static/desktop/js/bundles/hue/hue-5fffb0b9-bundle-b1e482f4e9a6a404921a.ff69ac51086e.js:16304:31/n)     at Function.yd (http://10.242.92.216:8888/static/desktop/js/bundles/hue/defaultVendors~hue-9241dc7c-bundle-b1e482f4e9a6a404921a.e5976413527a.js:3231:359)\n     at Function.zd (http://10.242.92.216:8888/static/desktop/js/bundles/hue/defaultVendors~hue-9241dc7c-bundle-b1e482f4e9a6a404921a.e5976413527a.js:3231:45)\n     at Function.ha (http://10.242.92.216:8888/static/desktop/js/bundles/hue/defaultVendors~hue-9241dc7c-bundle-b1e482f4e9a6a404921a.e5976413527a.js:3230:384)\n     at [Function.Qa](http://function.qa/)  (http://10.242.92.216:8888/static/desktop/js/bundles/hue/defaultVendors~hue-9241dc7c-bundle-b1e482f4e9a6a404921a.e5976413527a.js:3233:5)\n     at Function.subscribe (http://10.242.92.216:8888/static/desktop/js/bundles/hue/defaultVendors~hue-9241dc7c-bundle-b1e482f4e9a6a404921a.e5976413527a.js:3214:223)\n     at Function.$c (http://10.242.92.216:8888/static/desktop/js/bundles/hue/defaultVendors~hue-9241dc7c-bundle-b1e482f4e9a6a404921a.e5976413527a.js:3229:487)\n     at [Object.ba](http://object.ba/)  (http://10.242.92.216:8888/static/desktop/js/bundles/hue/defaultVendors~hue-9241dc7c-bundle-b1e482f4e9a6a404921a.e5976413527a.js:3184:292)\n     at [Object.cc](http://object.cc/)  (http://10.242.92.216:8888/static/desktop/js/bundles/hue/defaultVendors~hue-9241dc7c-bundle-b1e482f4e9a6a404921a.e5976413527a.js:3217:391)\n     at Snippet.e [as dialect] (http://10.242.92.216:8888/static/desktop/js/bundles/hue/defaultVendors~hue-9241dc7c-bundle-b1e482f4e9a6a404921a.e5976413527a.js:3227:5 )"}

### Hue version

Open Source 4.10

**Comment by Harshg999** [comment]
Hey @divincode, thanks for the detailed description.
@agl29 - Can you take a look? Why we had to introduce this commit when adding direct upload feature in importer?

**Comment by bjornalm** [comment]
@agl29 any ideas?
