### ISSUE TITLE
Docker logging config error

### ISSUE THREAD

**Issue by Aakcht** [cloudera/hue#3269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello, in the latest hue docker image(gethue/hue:20230403-140101) I'm getting the following error:
```
[05/Apr/2023 21:35:36 -0700] rungunicornserver INFO     Welcome to Hue from Gunicorn server 4.11.0
Error: Error: log config '/etc/hue/conf/log.conf' not found
[06/Apr/2023 04:35:36 ] supervisor   WARNING  Exit code for /usr/share/hue/build/env/bin/hue runcpserver: 1
[06/Apr/2023 04:35:36 ] supervisor   ERROR    Process /usr/share/hue/build/env/bin/hue runcpserver has restarted more than 3 times in the last 20 seconds
[06/Apr/2023 04:35:37 ] supervisor   WARNING  Supervisor shutting down!
[06/Apr/2023 04:35:37 ] supervisor   WARNING  Waiting for children to exit for 5 seconds...
Traceback (most recent call last):
  File "/usr/share/hue/build/env/bin/hue", line 33, in <module>
    sys.exit(load_entry_point('desktop', 'console_scripts', 'hue')())
  File "/usr/share/hue/desktop/core/src/desktop/manage_entry.py", line 233, in entry
    execute_from_command_line(sys.argv)
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/share/hue/desktop/core/src/desktop/management/commands/kt_renewer.py", line 25, in handle
    desktop.kt_renewer.run()
  File "/usr/share/hue/desktop/core/src/desktop/kt_renewer.py", line 120, in run
    time.sleep(CONF.REINIT_FREQUENCY.get())
KeyboardInterrupt
```

I suspect this happens because of #3234, see the change regarding `/etc/hue/conf/log.conf` file https://github.com/cloudera/hue/pull/3234/files#diff-f5e4a4c46ccb3948baaac9f4a2278ce72d436583fb1920e53145b7219600bfb2R164 . As a WA it's possible to create custom dockerfile with the following additional command:

```bash
RUN mkdir -p /etc/hue/conf \
    && ln -s /usr/share/hue/desktop/conf/log.conf /etc/hue/conf/log.conf
```

But shouldn't this logging config issue be fixed in the base dockerfile?

### Steps To Reproduce

Try ro run gethue/hue:20230403-140101 docker image in kubernetes

### Hue version

4.11, docker image gethue/hue:20230403-140101

**Comment by bjornalm** [comment]
Hi @Aakcht & @Aakcht, thanks for reporting and being part of our community. 
@ranade1 Can you have a look at this?

**Comment by Aakcht** [comment]
Looks like in the latest version(gethue/hue:20230518-140101) the issue is no longer present, `docker run -it -p 8888:8888 gethue/hue:20230518-140101` also executes successfully.
