### ISSUE TITLE
when i make apps on mac book(m1-12.5,python3.8.10)(hue-4.11.0),it shows ModuleNotFoundError: No module named 'future'

### ISSUE THREAD

**Issue by baiying319** [cloudera/hue#3272]
1. when i make apps on mac book(m1-12.5,python3.8.10)(hue-4.11.0),it shows ModuleNotFoundError: No module named 'future'
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/38554352/230425790-edb6f0ee-b183-4d0a-8a38-6d4a3299725d.png">
I use Python to create three files in the following image：
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/38554352/230426715-7248ca95-9dd4-4c9e-a23f-3fc204866f81.png">
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/38554352/230426814-9374b891-4f7a-41bc-b400-ee773ff2c7d9.png">
I tried installing desktop and future, but it didn't work.

2. when i get docker in (mac m1 ) centos-9 (CentOS-Stream-9-latest-aarch64-dvd1),it shows 
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/38554352/230427693-eba95741-fc45-4405-aaa4-6c2045b5264b.png">

Can you give me a helping hand?
thank you！

**Comment by baiying319** [comment]
=== zookeeper v.4.11.0 is already installed
=== Saved registry at /Users/ningjianwen/docker-contain/hue/app.reg
=== Saved /Users/ningjianwen/docker-contain/hue/build/env/lib/python3.8/site-packages/hue.pth
Running '/Users/ningjianwen/docker-contain/hue/build/env/bin/python /Users/ningjianwen/docker-contain/hue/build/env/bin/hue makemigrations --noinput' with None
Traceback (most recent call last):
  File "/Users/ningjianwen/docker-contain/hue/build/env/bin/hue", line 33, in <module>
    sys.exit(load_entry_point('desktop', 'console_scripts', 'hue')())
  File "/Users/ningjianwen/docker-contain/hue/build/env/bin/hue", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/ningjianwen/docker-contain/hue/desktop/core/src/desktop/__init__.py", line 19, in <module>
    import desktop.signal_handlers
  File "/Users/ningjianwen/docker-contain/hue/desktop/core/src/desktop/signal_handlers.py", line 20, in <module>
    from desktop.lib.thread_util import dump_traceback
  File "/Users/ningjianwen/docker-contain/hue/desktop/core/src/desktop/lib/thread_util.py", line 19, in <module>
    from future import standard_library
ModuleNotFoundError: No module named 'future'
Running '/Users/ningjianwen/docker-contain/hue/build/env/bin/python /Users/ningjianwen/docker-contain/hue/build/env/bin/hue migrate --fake-initial' with None
Traceback (most recent call last):
  File "/Users/ningjianwen/docker-contain/hue/build/env/bin/hue", line 33, in <module>
    sys.exit(load_entry_point('desktop', 'console_scripts', 'hue')())
  File "/Users/ningjianwen/docker-contain/hue/build/env/bin/hue", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/ningjianwen/docker-contain/hue/desktop/core/src/desktop/__init__.py", line 19, in <module>
    import desktop.signal_handlers
  File "/Users/ningjianwen/docker-contain/hue/desktop/core/src/desktop/signal_handlers.py", line 20, in <module>
    from desktop.lib.thread_util import dump_traceback
  File "/Users/ningjianwen/docker-contain/hue/desktop/core/src/desktop/lib/thread_util.py", line 19, in <module>
    from future import standard_library
ModuleNotFoundError: No module named 'future'
Running '/Users/ningjianwen/docker-contain/hue/build/env/bin/python /Users/ningjianwen/docker-contain/hue/build/env/bin/hue collectstatic --noinput' with None
Traceback (most recent call last):
  File "/Users/ningjianwen/docker-contain/hue/build/env/bin/hue", line 33, in <module>
    sys.exit(load_entry_point('desktop', 'console_scripts', 'hue')())
  File "/Users/ningjianwen/docker-contain/hue/build/env/bin/hue", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/ningjianwen/docker-contain/hue/desktop/core/src/desktop/__init__.py", line 19, in <module>
    import desktop.signal_handlers
  File "/Users/ningjianwen/docker-contain/hue/desktop/core/src/desktop/signal_handlers.py", line 20, in <module>
    from desktop.lib.thread_util import dump_traceback
  File "/Users/ningjianwen/docker-contain/hue/desktop/core/src/desktop/lib/thread_util.py", line 19, in <module>
    from future import standard_library
ModuleNotFoundError: No module named 'future'
"PYTHON_VER is python3.8."
"SYS_PYTHON is /usr/local/bin/python3.8."
"ENV_PYTHON is /Users/ningjianwen/docker-contain/hue/build/env/bin/python3.8."
"SYS_PIP is /usr/local/bin/pip3.8."
"ENV_PIP is /Users/ningjianwen/docker-contain/hue/build/env/bin/python3.8 /Users/ningjianwen/docker-contain/hue/build/env/bin/pip."
./build/env/bin/python ./build/env/bin/hue collectstatic --noinput
Traceback (most recent call last):
  File "./build/env/bin/hue", line 33, in <module>
    sys.exit(load_entry_point('desktop', 'console_scripts', 'hue')())
  File "./build/env/bin/hue", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/ningjianwen/docker-contain/hue/desktop/core/src/desktop/__init__.py", line 19, in <module>
    import desktop.signal_handlers
  File "/Users/ningjianwen/docker-contain/hue/desktop/core/src/desktop/signal_handlers.py", line 20, in <module>
    from desktop.lib.thread_util import dump_traceback
  File "/Users/ningjianwen/docker-contain/hue/desktop/core/src/desktop/lib/thread_util.py", line 19, in <module>
    from future import standard_library
ModuleNotFoundError: No module named 'future'
make[1]: *** [create-static] Error 1
make: *** [apps] Error 2

**Comment by bjornalm** [comment]
Hi @baiying319 and thanks for reporting. We have seen the same build issue in some of our own build systems as well. We are working to have this fixed.

**Comment by agl29** [comment]
@baiying319 can you please try the following steps and see if you are still facing the issue?
```
make clean
rm -rf build
export ROOT="path/to/hue/directory"
export PYTHON_VER=python3.8
make apps
```

**Comment by ericbrow** [comment]
I've encountered the same bug installing on a VM.  After lots of digging, I found an error early in the `make apps` process that pointed to a file ${ROOT}/desktop/core/requirements.txt.  After a short list of pip packages, the requirements file points to base_requirements.txt, which includes the future package among many others.  The error is requirements.txt somehow giving a double path.  My ${ROOT} is /opt/hue.  The error points to /opt/hue/desktop/core/${ROOT}/desktop/core/base_requirements.txt.  None of the packages in requirements or base requirements are present in the working virtual environment.

I also edited requirements.txt to point to the absolute path of base_requirements.txt, but this resulted in no errors, as well as none of the listed python packages being installed in the virtual environment.

Here's the snippet with the actual error.  My guess is that since the path to base_requirements.txt fails, no python packages get installed.  I'm not experienced enough with makefiles to assist in further troubleshooting.

```
--- Installing /opt/hue/desktop/core/requirements.txt into virtual-env via /opt/hue/build/env/bin/python3.9 /opt/hue/build/env/bin/pip
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/opt/hue/desktop/core/${ROOT}/desktop/core/base_requirements.txt'
--- Finished /opt/hue/desktop/core/requirements.txt into virtual-env
```

Any suggestions would be greatly apricated.

**Comment by jackso-a** [comment]
Same here ericbrow with the added fun of Python3.9 not being referenced in the MakeFile. I couldn't work out why the literal wasn't still there, so hard coded it and onto the next issue.

**Comment by Harshg999** [comment]
@ranade1 @wing2fly @athithyaaselvam - Can someone take a look?

**Comment by agl29** [comment]
> 

Hi @ericbrow 
Looks like you have not defined the value of ROOT. 
`export ROOT = <path_to_hue_directory>`
in your case it is `/opt/hue`
Please see the point 9 in this [doc](https://docs.gethue.com/administrator/installation/dependencies/#macos).

**Comment by ericbrow** [comment]
Thanks @agl29 .  That was the fix.

Since step 9 was under the section for installing on a Mac, and I'm not installing on a Mac, I hope it stands to reason that we would skip that section.

Maybe setting the ROOT environment variable should be at the top of the document.

**Comment by bjornalm** [comment]
also see https://github.com/cloudera/hue/pull/3311
