### ISSUE TITLE
 <s3 connector>Failed to retrieve buckets: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by zhangzhaohuazai** [cloudera/hue#3392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After the s3 cluster parameters are configured and customized by hue and the s3 module is restarted, the S3 module is opened on the hue page, and the error message Failed to retrieve buckets:

```
S3 filesystem exception.
Failed to retrieve buckets: [Errno -2] Name or service not known
```
![image](https://github.com/cloudera/hue/assets/28680957/5629c4fe-b3be-40af-844b-69810bd468ff)

### Steps To Reproduce

hue s3 connector config:
`[aws]
[[aws_accounts]]
[[[default]]]
access_key_id=******
secret_access_key=******
allow_environment_credentials=false
host=http://*.*.*.*:9000
`

### Logs

`[12/Jul/2023 18:54:09 -0700] exceptions_renderable ERROR    Potential detail: Failed to retrieve buckets: [Errno -2] Name or service not known
[12/Jul/2023 18:54:09 -0700] exceptions_renderable ERROR    Potential trace: [<FrameSummary file /usr/share/hue/apps/filebrowser/src/filebrowser/views.py, line 291 in view>, <FrameSummary file /usr/share/hue/apps/filebrowser/src/filebrowser/views.py, line 545 in listdir_paged>, <FrameSummary file /usr/share/hue/desktop/core/src/desktop/lib/fs/proxyfs.py, line 140 in do_as_user>, <FrameSummary file /usr/share/hue/desktop/core/src/desktop/lib/fs/proxyfs.py, line 162 in listdir_stats>, <FrameSummary file /usr/share/hue/desktop/libs/aws/src/aws/s3/__init__.py, line 54 in wrapped>, <FrameSummary file /usr/share/hue/desktop/libs/aws/src/aws/s3/s3fs.py, line 329 in listdir_stats>]
[12/Jul/2023 18:54:09 -0700] middleware   INFO     Processing exception: S3 filesystem exception.: Traceback (most recent call last):
  File "/usr/share/hue/desktop/libs/aws/src/aws/s3/s3fs.py", line 319, in listdir_stats
    [S3Stat.from_bucket(b, self.fs) for b in self._s3_connection.get_all_buckets(headers=self.header_values)], key=lambda x: x.name)
  File "/usr/share/hue/desktop/core/ext-py3/boto-2.49.0/boto/s3/connection.py", line 459, in get_all_buckets
    response = self.make_request('GET', headers=headers)
  File "/usr/share/hue/desktop/core/ext-py3/boto-2.49.0/boto/s3/connection.py", line 683, in make_request
    return super(S3Connection, self).make_request(
  File "/usr/share/hue/desktop/core/ext-py3/boto-2.49.0/boto/connection.py", line 1071, in make_request
    return self._mexe(http_request, sender, override_num_retries,
  File "/usr/share/hue/desktop/core/ext-py3/boto-2.49.0/boto/connection.py", line 1031, in _mexe
    raise ex
  File "/usr/share/hue/desktop/core/ext-py3/boto-2.49.0/boto/connection.py", line 943, in _mexe
    connection.request(request.method, request.path,
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/hue/apps/filebrowser/src/filebrowser/views.py", line 291, in view
    return listdir_paged(request, path)
  File "/usr/share/hue/apps/filebrowser/src/filebrowser/views.py", line 545, in listdir_paged
    all_stats = request.fs.do_as_user(do_as, request.fs.listdir_stats, path)
  File "/usr/share/hue/desktop/core/src/desktop/lib/fs/proxyfs.py", line 140, in do_as_user
    return fn(*args, **kwargs)
  File "/usr/share/hue/desktop/core/src/desktop/lib/fs/proxyfs.py", line 162, in listdir_stats
    return self._get_fs(path).listdir_stats(path, **kwargs)
  File "/usr/share/hue/desktop/libs/aws/src/aws/s3/__init__.py", line 54, in wrapped
    return fn(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/aws/src/aws/s3/s3fs.py", line 329, in listdir_stats
    raise S3FileSystemException(_('Failed to retrieve buckets: %s') % e)
aws.s3.s3fs.S3FileSystemException: Failed to retrieve buckets: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/share/hue/apps/filebrowser/src/filebrowser/views.py", line 302, in view
    raise PopupException(msg, detail=e)
desktop.lib.exceptions_renderable.PopupException: S3 filesystem exception.
`

### Hue version

gethue/hue:latest

**Comment by bjornalm** [comment]
Hi @zhangzhaohuazai and thanks for reporting. @Harshg999 can you have a quick look to see if this is a configuration issue or a bug?

**Comment by Harshg999** [comment]
Hey @zhangzhaohuazai, this feels like a config issue or something network related. Hue is not able to connect to S3 with the config provided.

Can you once try populating the value in the sample config below and use it in your setup?
```
[aws]
[[aws_accounts]]
[[[default]]]
access_key_id=xxxx
secret_access_key=xxxx
allow_environment_credentials=yes

# Your S3 bucket region
region=us-west-2
```
