### ISSUE TITLE
 <hue connect to hdfs error>an error occurs when a file is uploaded or created

### ISSUE THREAD

**Issue by zhangzhaohuazai** [cloudera/hue#3393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After hue configures parameters related to hdfs and restarts, the hdfs module is opened on the hue page. Directories and files are displayed normally, and a new directory is created on the hue page. However, an error occurs when a file is uploaded or created.
1、Upload error:
![image](https://github.com/cloudera/hue/assets/28680957/3441912c-44fa-4378-af3b-af2be42280ea)
2、Create file error:
![image](https://github.com/cloudera/hue/assets/28680957/72096e34-843f-4592-8019-f957a39d5bbb)

### Steps To Reproduce

1、config hue.ini with hdfs：
> [hadoop]
> [[hdfs_clusters]]
> [[[default]]]
> fs_defaultfs=hdfs://*.*.*.*:9000
> webhdfs_url=http://*.*.*.*:50070/webhdfs/v1
2、restart hue docker container
3、open hue web，open hdfs page
4、press 'Upload' or 'Create file'

### Logs

1、When I upload file,I get this error log:
`[12/Jul/2023 19:04:21 -0700] upload       ERROR    Not using HDFS upload handler: HTTPConnectionPool(host='szfyd-lake02', port=9864): Max retries exceeded with url: /webhdfs/v1/hue/A.txt.tmp?op=CREATE&doas=root&user.name=root&namenoderpcaddress=szfyd-lake01:9000&createflag=&createparent=true&overwrite=false&permission=644 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcddc61b9d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[12/Jul/2023 19:04:21 -0700] views        WARNING  User root is using Hue 3 UI`
2、When I create file,I get this error log:
`[12/Jul/2023 19:23:56 -0700] exceptions_renderable ERROR    Potential detail: HTTPConnectionPool(host='szfyd-lake02', port=9864): Max retries exceeded with url: /webhdfs/v1/test/input/1.txt?op=CREATE&doas=root&user.name=root&namenoderpcaddress=szfyd-lake01:9000&createflag=&createparent=true&overwrite=false&permission=644 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcddc6bedf0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[12/Jul/2023 19:23:56 -0700] exceptions_renderable ERROR    Potential trace: [<FrameSummary file /usr/share/hue/apps/filebrowser/src/filebrowser/views.py, line 1196 in generic_op>, <FrameSummary file /usr/share/hue/apps/filebrowser/src/filebrowser/views.py, line 1279 in smart_touch>, <FrameSummary file /usr/share/hue/desktop/core/src/desktop/lib/fs/proxyfs.py, line 207 in create>, <FrameSummary file /usr/share/hue/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py, line 637 in create>, <FrameSummary file /usr/share/hue/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py, line 880 in _invoke_with_redirect>, <FrameSummary file /usr/share/hue/desktop/core/src/desktop/lib/rest/resource.py, line 78 in invoke>, <FrameSummary file /usr/share/hue/desktop/core/src/desktop/lib/rest/resource.py, line 105 in _invoke>, <FrameSummary file /usr/share/hue/desktop/core/src/desktop/lib/rest/http_client.py, line 244 in execute>]
[12/Jul/2023 19:23:56 -0700] middleware   INFO     Processing exception: Cannot perform operation.: Traceback (most recent call last):
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fcddc6bedf0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/hue/desktop/core/ext-py3/requests-2.27.1/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='szfyd-lake02', port=9864): Max retries exceeded with url: /webhdfs/v1/test/input/1.txt?op=CREATE&doas=root&user.name=root&namenoderpcaddress=szfyd-lake01:9000&createflag=&createparent=true&overwrite=false&permission=644 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcddc6bedf0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/hue/desktop/core/src/desktop/lib/rest/http_client.py", line 233, in execute
    resp = getattr(self._session, http_method.lower())(url, **request_kwargs)
  File "/usr/share/hue/desktop/core/ext-py3/requests-2.27.1/requests/sessions.py", line 589, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/usr/share/hue/desktop/core/ext-py3/requests-2.27.1/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/hue/desktop/core/ext-py3/requests-2.27.1/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/hue/desktop/core/ext-py3/requests-2.27.1/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='szfyd-lake02', port=9864): Max retries exceeded with url: /webhdfs/v1/test/input/1.txt?op=CREATE&doas=root&user.name=root&namenoderpcaddress=szfyd-lake01:9000&createflag=&createparent=true&overwrite=false&permission=644 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcddc6bedf0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/hue/apps/filebrowser/src/filebrowser/views.py", line 1196, in generic_op
    op(*args)
  File "/usr/share/hue/apps/filebrowser/src/filebrowser/views.py", line 1279, in smart_touch
    request.fs.create(
  File "/usr/share/hue/desktop/core/src/desktop/lib/fs/proxyfs.py", line 207, in create
    self._get_fs(path).create(path, *args, **kwargs)
  File "/usr/share/hue/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py", line 637, in create
    self._invoke_with_redirect('PUT', path, params, data, headers)
  File "/usr/share/hue/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py", line 880, in _invoke_with_redirect
    return resource.Resource(client).invoke(method, data=data, headers=headers)
  File "/usr/share/hue/desktop/core/src/desktop/lib/rest/resource.py", line 78, in invoke
    resp = self._invoke(
  File "/usr/share/hue/desktop/core/src/desktop/lib/rest/resource.py", line 105, in _invoke
    resp = self._client.execute(
  File "/usr/share/hue/desktop/core/src/desktop/lib/rest/http_client.py", line 244, in execute
    raise self._exc_class(ex)
hadoop.fs.exceptions.WebHdfsException: HTTPConnectionPool(host='szfyd-lake02', port=9864): Max retries exceeded with url: /webhdfs/v1/test/input/1.txt?op=CREATE&doas=root&user.name=root&namenoderpcaddress=szfyd-lake01:9000&createflag=&createparent=true&overwrite=false&permission=644 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcddc6bedf0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/hue/build/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/share/hue/apps/filebrowser/src/filebrowser/views.py", line 1286, in touch
    return generic_op(TouchForm, request, smart_touch, ["path", "name"], "path")
  File "/usr/share/hue/apps/filebrowser/src/filebrowser/views.py", line 1199, in generic_op
    raise PopupException(msg, detail=e)
desktop.lib.exceptions_renderable.PopupException: Cannot perform operation.
`

### Hue version

gethue/hue:latest

**Comment by zhangzhaohuazai** [comment]
any ideas?

**Comment by bjornalm** [comment]
@zhangzhaohuazai thanks for reporting. @tabraiz12 can you take a look?
