### ISSUE TITLE
 <hue connect to yarn error>YARN RM returned a failed response: 401 Client Error: Unauthorized access for url:

### ISSUE THREAD

**Issue by zhangzhaohuazai** [cloudera/hue#3394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Symptom After hue configures yarn parameters and restarts, an error occurs when the jobs module is opened on the hue page:
![image](https://github.com/cloudera/hue/assets/28680957/8857fc37-fc67-401a-8734-56f6a08bd79a)

### Steps To Reproduce

1、config hue.ini with yarn：
> [[yarn_clusters]]
> [[[default]]]
> [[[default]]]
> resourcemanager_host=10.101.12.142
> resourcemanager_port=8032
> submit_to=True
> resourcemanager_api_url=http://*.*.*.*:8088
> history_server_api_url=http://*.*.*.*:19888

2、restart hue docker container
3、open hue web，open Jobs page

### Logs

`[12/Jul/2023 22:50:28 -0700] exceptions_renderable ERROR    Potential trace: [<FrameSummary file /usr/share/hue/desktop/libs/hadoop/src/hadoop/yarn/resource_manager_api.py, line 176 in _execute>, <FrameSummary file /usr/share/hue/desktop/core/src/desktop/lib/rest/resource.py, line 157 in get>, <FrameSummary file /usr/share/hue/desktop/core/src/desktop/lib/rest/resource.py, line 78 in invoke>, <FrameSummary file /usr/share/hue/desktop/core/src/desktop/lib/rest/resource.py, line 105 in _invoke>, <FrameSummary file /usr/share/hue/desktop/core/src/desktop/lib/rest/http_client.py, line 244 in execute>]
[12/Jul/2023 22:50:28 -0700] api2         ERROR    Error running <function jobs at 0x7f07fd850940>
Traceback (most recent call last):
  File "/usr/share/hue/desktop/core/src/desktop/lib/rest/http_client.py", line 235, in execute
    resp.raise_for_status()
  File "/usr/share/hue/desktop/core/ext-py3/requests-2.27.1/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized access for url: http://10.101.12.142:8088/ws/v1/cluster/apps?user=root&limit=500&startedTimeBegin=1688622628000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/hue/desktop/libs/hadoop/src/hadoop/yarn/resource_manager_api.py", line 176, in _execute
    response = function(*args, **kwargs)
  File "/usr/share/hue/desktop/core/src/desktop/lib/rest/resource.py", line 157, in get
    return self.invoke("GET", relpath, params, headers=headers, allow_redirects=True, clear_cookies=clear_cookies)
  File "/usr/share/hue/desktop/core/src/desktop/lib/rest/resource.py", line 78, in invoke
    resp = self._invoke(
  File "/usr/share/hue/desktop/core/src/desktop/lib/rest/resource.py", line 105, in _invoke
    resp = self._client.execute(
  File "/usr/share/hue/desktop/core/src/desktop/lib/rest/http_client.py", line 244, in execute
    raise self._exc_class(ex)
desktop.lib.rest.http_client.RestException: 401 Client Error: Unauthorized access for url: http://10.101.12.142:8088/ws/v1/cluster/apps?user=root&limit=500&startedTimeBegin=1688622628000
{
"servlet":"org.eclipse.jetty.servlet.DefaultServlet-2e6a5539",
"message":"Unauthorized access",
"url":"/ws/v1/cluster/apps",
"status":"401"
} (error 401)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/hue/apps/jobbrowser/src/jobbrowser/api2.py", line 48, in decorator
    return func(*args, **kwargs)
  File "/usr/share/hue/apps/jobbrowser/src/jobbrowser/api2.py", line 73, in jobs
    jobs = get_api(request.user, interface, cluster=cluster).apps(filters)
  File "/usr/share/hue/apps/jobbrowser/src/jobbrowser/apis/job_api.py", line 58, in apps
    return self.yarn_api.apps(filters)
  File "/usr/share/hue/apps/jobbrowser/src/jobbrowser/apis/job_api.py", line 116, in apps
    jobs = NativeYarnApi(self.user).get_jobs(**filter_params)
  File "/usr/share/hue/desktop/libs/hadoop/src/hadoop/cluster.py", line 58, in decorate
    raise ex
  File "/usr/share/hue/desktop/libs/hadoop/src/hadoop/cluster.py", line 46, in decorate
    return funct(api, *args, **kwargs)
  File "/usr/share/hue/apps/jobbrowser/src/jobbrowser/api.py", line 112, in get_jobs
    json = self.resource_manager_api.apps(**filters)
  File "/usr/share/hue/desktop/libs/hadoop/src/hadoop/yarn/resource_manager_api.py", line 126, in apps
    return self._execute(self._root.get, 'cluster/apps', params=params, headers={'Accept': _JSON_CONTENT_TYPE})
  File "/usr/share/hue/desktop/libs/hadoop/src/hadoop/yarn/resource_manager_api.py", line 178, in _execute
    raise PopupException(_('YARN RM returned a failed response: %s') % e)
desktop.lib.exceptions_renderable.PopupException: YARN RM returned a failed response: 401 Client Error: Unauthorized access for url: http://10.101.12.142:8088/ws/v1/cluster/apps?user=root&limit=500&startedTimeBegin=1688622628000
{
"servlet":"org.eclipse.jetty.servlet.DefaultServlet-2e6a5539",
"message":"Unauthorized access",
"url":"/ws/v1/cluster/apps",
"status":"401"
} (error 401)
[12/Jul/2023 22:50:28 -0700] access       INFO     10.11.14.115 root - "POST /jobbrowser/api/jobs/jobs HTTP/1.1" returned in 5ms 200 385
[12/Jul/2023 22:50:28 -0700] access       INFO     10.11.14.115 root - "POST /jobbrowser/api/jobs/jobs HTTP/1.1" returned in 5ms 200 385
- 10.11.14.115 - - [12/Jul/2023:22:50:28 -0700] 'POST /jobbrowser/api/jobs/jobs HTTP/1.1' 200 385 'http://10.101.12.141:8880/hue/jobbrowser/' 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'
[12/Jul/2023 22:50:28 -0700] exceptions_renderable ERROR    Potential trace: [<FrameSummary file /usr/share/hue/desktop/libs/hadoop/src/hadoop/yarn/resource_manager_api.py, line 176 in _execute>, <FrameSummary file /usr/share/hue/desktop/core/src/desktop/lib/rest/resource.py, line 157 in get>, <FrameSummary file /usr/share/hue/desktop/core/src/desktop/lib/rest/resource.py, line 78 in invoke>, <FrameSummary file /usr/share/hue/desktop/core/src/desktop/lib/rest/resource.py, line 105 in _invoke>, <FrameSummary file /usr/share/hue/desktop/core/src/desktop/lib/rest/http_client.py, line 244 in execute>]
[12/Jul/2023 22:50:28 -0700] api2         ERROR    Error running <function jobs at 0x7f07fd850940>
Traceback (most recent call last):
  File "/usr/share/hue/desktop/core/src/desktop/lib/rest/http_client.py", line 235, in execute
    resp.raise_for_status()
  File "/usr/share/hue/desktop/core/ext-py3/requests-2.27.1/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized access for url: http://10.101.12.142:8088/ws/v1/cluster/apps?user=root&limit=500&startedTimeBegin=1688622628000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/hue/desktop/libs/hadoop/src/hadoop/yarn/resource_manager_api.py", line 176, in _execute
    response = function(*args, **kwargs)
  File "/usr/share/hue/desktop/core/src/desktop/lib/rest/resource.py", line 157, in get
    return self.invoke("GET", relpath, params, headers=headers, allow_redirects=True, clear_cookies=clear_cookies)
  File "/usr/share/hue/desktop/core/src/desktop/lib/rest/resource.py", line 78, in invoke
    resp = self._invoke(
  File "/usr/share/hue/desktop/core/src/desktop/lib/rest/resource.py", line 105, in _invoke
    resp = self._client.execute(
  File "/usr/share/hue/desktop/core/src/desktop/lib/rest/http_client.py", line 244, in execute
    raise self._exc_class(ex)
desktop.lib.rest.http_client.RestException: 401 Client Error: Unauthorized access for url: http://10.101.12.142:8088/ws/v1/cluster/apps?user=root&limit=500&startedTimeBegin=1688622628000
{
"servlet":"org.eclipse.jetty.servlet.DefaultServlet-2e6a5539",
"message":"Unauthorized access",
"url":"/ws/v1/cluster/apps",
"status":"401"
} (error 401)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/hue/apps/jobbrowser/src/jobbrowser/api2.py", line 48, in decorator
    return func(*args, **kwargs)
  File "/usr/share/hue/apps/jobbrowser/src/jobbrowser/api2.py", line 73, in jobs
    jobs = get_api(request.user, interface, cluster=cluster).apps(filters)
  File "/usr/share/hue/apps/jobbrowser/src/jobbrowser/apis/job_api.py", line 58, in apps
    return self.yarn_api.apps(filters)
  File "/usr/share/hue/apps/jobbrowser/src/jobbrowser/apis/job_api.py", line 116, in apps
    jobs = NativeYarnApi(self.user).get_jobs(**filter_params)
  File "/usr/share/hue/desktop/libs/hadoop/src/hadoop/cluster.py", line 58, in decorate
    raise ex
  File "/usr/share/hue/desktop/libs/hadoop/src/hadoop/cluster.py", line 46, in decorate
    return funct(api, *args, **kwargs)
  File "/usr/share/hue/apps/jobbrowser/src/jobbrowser/api.py", line 112, in get_jobs
    json = self.resource_manager_api.apps(**filters)
  File "/usr/share/hue/desktop/libs/hadoop/src/hadoop/yarn/resource_manager_api.py", line 126, in apps
    return self._execute(self._root.get, 'cluster/apps', params=params, headers={'Accept': _JSON_CONTENT_TYPE})
  File "/usr/share/hue/desktop/libs/hadoop/src/hadoop/yarn/resource_manager_api.py", line 178, in _execute
    raise PopupException(_('YARN RM returned a failed response: %s') % e)
desktop.lib.exceptions_renderable.PopupException: YARN RM returned a failed response: 401 Client Error: Unauthorized access for url: http://10.101.12.142:8088/ws/v1/cluster/apps?user=root&limit=500&startedTimeBegin=1688622628000
{
"servlet":"org.eclipse.jetty.servlet.DefaultServlet-2e6a5539",
"message":"Unauthorized access",
"url":"/ws/v1/cluster/apps",
"status":"401"
} (error 401)
[12/Jul/2023 22:50:28 -0700] access       INFO     10.11.14.115 root - "POST /jobbrowser/api/jobs/jobs HTTP/1.1" returned in 4ms 200 385
[12/Jul/2023 22:50:28 -0700] access       INFO     10.11.14.115 root - "POST /jobbrowser/api/jobs/jobs HTTP/1.1" returned in 4ms 200 385
- 10.11.14.115 - - [12/Jul/2023:22:50:28 -0700] 'POST /jobbrowser/api/jobs/jobs HTTP/1.1' 200 385 'http://10.101.12.141:8880/hue/jobbrowser/' 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'`

### Hue version

gethue/hue:latest

**Comment by bjornalm** [comment]
Hi @zhangzhaohuazai and thank you for reporting. We will try to have someone take a look shortly. @wing2fly can you have a look?

**Comment by wing2fly** [comment]
@zhangzhaohuazai is your Yarn a Kerberos-secured?
From your STR, I don't see such config:
https://github.com/cloudera/hue/blob/master/desktop/conf/pseudo-distributed.ini.tmpl#L1280-L1281
