### ISSUE TITLE
 <hive query error>Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask

### ISSUE THREAD

**Issue by zhangzhaohuazai** [cloudera/hue#3417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If hue executes the select statement for a hive table, the result can be displayed normally. However, if select count is executed, an error message is displayed:
```Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask```
![image](https://github.com/cloudera/hue/assets/28680957/cddbf3be-c5dd-4c0b-9aef-9fa4c80f187c)

### Steps To Reproduce

0、hive config in hue:
```
 [[[hive]]]
   name=Hive
   interface=hiveserver2

[beeswax]
# Host where HiveServer2 is running.
# If Kerberos security is enabled, use fully-qualified domain name (FQDN).
hive_server_host=***
# Binary thrift port for HiveServer2.
hive_server_port=10000
```
1、open a hive table's sql console
2、inset sql:SELECT count(*) FROM `metadata_hudi32`.`metadata_hudi_32_rt`;
3、run the sql

### Logs

```- 10.11.14.115 - - [27/Jul/2023:01:14:46 -0700] 'POST /notebook/api/get_logs HTTP/1.1' 200 260 'http://10.101.12.141:8880/hue/editor?editor=84' 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.33'
[27/Jul/2023 01:14:47 -0700] decorators   ERROR    Error running check_status
Traceback (most recent call last):
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/decorators.py", line 120, in wrapper
    return f(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/api.py", line 260, in check_status
    response = _check_status(request, notebook=notebook, snippet=snippet, operation_id=operation_id)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/api.py", line 274, in _check_status
    response['query_status'] = get_api(request, snippet).check_status(notebook, snippet)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/hiveserver2.py", line 99, in decorator
    return func(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/hiveserver2.py", line 373, in check_status
    raise QueryError(operation.errorMessage)
notebook.connectors.base.QueryError: Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
[27/Jul/2023 01:14:47 -0700] access       INFO     10.11.14.115 hong - "POST /notebook/api/check_status HTTP/1.1" returned in 1198ms 200 150
[27/Jul/2023 01:14:47 -0700] access       INFO     10.11.14.115 hong - "POST /notebook/api/check_status HTTP/1.1" returned in 1198ms 200 150
- 10.11.14.115 - - [27/Jul/2023:01:14:47 -0700] 'POST /notebook/api/check_status HTTP/1.1' 200 150 'http://10.101.12.141:8880/hue/editor?editor=84' 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.33'
[27/Jul/2023 01:14:48 -0700] access       INFO     10.11.14.115 hong - "POST /notebook/api/get_logs HTTP/1.1" returned in 257ms 200 702
[27/Jul/2023 01:14:48 -0700] access       INFO     10.11.14.115 hong - "POST /notebook/api/get_logs HTTP/1.1" returned in 257ms 200 702
- 10.11.14.115 - - [27/Jul/2023:01:14:48 -0700] 'POST /notebook/api/get_logs HTTP/1.1' 200 702 'http://10.101.12.141:8880/hue/editor?editor=84' 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.33'
[27/Jul/2023 01:14:49 -0700] access       INFO     10.11.14.115 hong - "POST /notebook/api/get_logs HTTP/1.1" returned in 247ms 200 193
[27/Jul/2023 01:14:49 -0700] access       INFO     10.11.14.115 hong - "POST /notebook/api/get_logs HTTP/1.1" returned in 247ms 200 193
- 10.11.14.115 - - [27/Jul/2023:01:14:49 -0700] 'POST /notebook/api/get_logs HTTP/1.1' 200 193 'http://10.101.12.141:8880/hue/editor?editor=84' 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.33'
[27/Jul/2023 01:14:56 -0700] decorators   ERROR    Error running check_status
Traceback (most recent call last):
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/decorators.py", line 120, in wrapper
    return f(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/api.py", line 260, in check_status
    response = _check_status(request, notebook=notebook, snippet=snippet, operation_id=operation_id)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/api.py", line 274, in _check_status
    response['query_status'] = get_api(request, snippet).check_status(notebook, snippet)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/hiveserver2.py", line 99, in decorator
    return func(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/hiveserver2.py", line 373, in check_status
    raise QueryError(operation.errorMessage)
notebook.connectors.base.QueryError: Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
```

### Hue version

gethue/hue:latest

**Comment by wachoo** [comment]
this error comes from the hiveserver2, is it better to set parallelism in the SQL?
