### ISSUE TITLE
[Dockerfile ] Error to use the provided Dockerfile file to build an image，https://github.com/cloudera/hue/blob/release-4.11.0/tools/docker/hue/Dockerfile

### ISSUE THREAD

**Issue by wachoo** [cloudera/hue#3425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 I am not able to use the provided Dockerfile file to build an image，https://github.com/cloudera/hue/blob/release-4.11.0/tools/docker/hue/Dockerfile

### Steps To Reproduce

1. clone the code on my desktop ( https://github.com/cloudera/hue/tree/release-4.11.0 )
2. run the command `docker build . -t gethue/hue -f tools/docker/hue/Dockerfile `
3.  An error message has occurred, "Exception: Can not find valid pkg-config name. Specify MYSQLCLIENT_CFLAGS and MYSQLCLIENT_LDFLAGS env vars manually"
![image](https://github.com/cloudera/hue/assets/13916787/23919af8-f120-45bc-bd9b-e6373ae5a609)
4. even if I have  specified relevant configurations, like this:
```
 MYSQLCLIENT_CFLAGS="-I/usr/include/mysql" \
  MYSQLCLIENT_LDFLAGS="-L/usr/lib64/mysql"\
  PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python \
  PREFIX=/usr/share ROOT=/usr/share/hue PYTHON_VER=python3.8 ROOT=/hue \
  SYS_PYTHON=/usr/bin/python3.8 SYS_PIP=/usr/local/bin/pip3.8 make apps install
```

### Logs

17.46   ERROR: Command errored out with exit status 1:
17.46    command: /usr/bin/python3 /tmp/tmpo7rexup0 get_requires_for_build_wheel /tmp/tmpjpp7wwvw
17.46        cwd: /tmp/pip-install-hjifanxi/mysqlclient
17.46   Complete output (24 lines):
17.46   /bin/sh: 1: pkg-config: not found
17.46   /bin/sh: 1: pkg-config: not found
17.46   Trying pkg-config --exists mysqlclient
17.46   Command 'pkg-config --exists mysqlclient' returned non-zero exit status 127.
17.46   Trying pkg-config --exists mariadb
17.46   Command 'pkg-config --exists mariadb' returned non-zero exit status 127.
17.46   Traceback (most recent call last):
17.46     File "/tmp/tmpo7rexup0", line 280, in <module>
17.46       main()
17.46     File "/tmp/tmpo7rexup0", line 263, in main
17.46       json_out['return_val'] = hook(**hook_input['kwargs'])
17.46     File "/tmp/tmpo7rexup0", line 114, in get_requires_for_build_wheel
17.46       return hook(config_settings)
17.46     File "/tmp/pip-build-env-p_zn_6g5/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
17.46       return self._get_build_requires(config_settings, requirements=['wheel'])
17.46     File "/tmp/pip-build-env-p_zn_6g5/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
17.46       self.run_setup()
17.46     File "/tmp/pip-build-env-p_zn_6g5/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
17.46       exec(code, locals())
17.46     File "<string>", line 154, in <module>
17.46     File "<string>", line 48, in get_config_posix
17.46     File "<string>", line 27, in find_package_name
17.46   Exception: Can not find valid pkg-config name.
17.46   Specify MYSQLCLIENT_CFLAGS and MYSQLCLIENT_LDFLAGS env vars manually
17.46   ----------------------------------------
17.55 ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpo7rexup0 get_requires_for_build_wheel /tmp/tmpjpp7wwvw Check the logs for full command output.

### Hue version

4.11.0

**Comment by wachoo** [comment]
> I think you should check your Dockfile,because as far as I know Python has the setuptools library but not the setuptool library. ![image](https://user-images.githubusercontent.com/63089130/258039633-60402963-ca40-494c-a1ec-b792c73da007.png)

sorry, I encountered another anomaly
