### ISSUE TITLE
no app for view func : submit_schedule

### ISSUE THREAD

**Issue by jallyQ** [cloudera/hue#3433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi, I want to submit a hive scheduler task from a  saved queries , but it show me a error about :
no app for view func: <function submit_schedule at 0x7f821d67c6e0> in 
<module 'desktop.lib.scheduler.api' from '/opt/hue/desktop/core/src/desktop/lib/scheduler/api.pyc'>

### Steps To Reproduce

1.In hue-4.10.0 version;
2.call the interface in the hive editor : scheduler/api/schedule/submit/62731011-d556-1263-d798-4791c71a3f38?format=json&_=1691571409408;
3.show the error;
4.If I modify the method of \desktop\core\src\desktop\lib\apputil.py to :

def get_app_for_module(module):
  for app in settings.INSTALLED_APPS:
    if module.__name__.startswith('desktop.lib.metrics.views'):
      return app
    elif module.__name__.startswith('desktop.lib.analytics.views'):
      return app
    elif module.__name__.startswith('desktop.lib.connectors'):
      return app
    elif module.__name__.startswith('desktop.lib.scheduler'):
      return app
    elif module.__name__.startswith(app) and not module.__name__.startswith("desktop.lib"):
      return app
  return None
the error will be resolved;

### Logs

[10/Aug/2023 00:07:37 +0000] middleware   DEBUG    no app for view func: <function submit_schedule at 0x7f821d67c6e0> in 
<module 'desktop.lib.scheduler.api' from '/opt/hue/desktop/core/src/desktop/lib/scheduler/api.pyc'>
[10/Aug/2023 00:07:37 +0000] middleware   INFO     Processing exception: no app!: Traceback (most recent call last):
  File "/opt/hue/build/env/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/core/handlers/bas
e.py", line 185, in _get_response    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/hue/build/env/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/utils/decorators.
py", line 185, in inner    return func(*args, **kwargs)
  File "/opt/hue/desktop/core/src/desktop/lib/scheduler/api.py", line 105, in submit_schedule
    force_template=True
  File "/opt/hue/desktop/core/src/desktop/lib/django_util.py", line 248, in render
    **kwargs
  File "/opt/hue/desktop/core/src/desktop/lib/django_util.py", line 161, in _render_to_response
    return django_mako.render_to_response(template, *args, **kwargs)
  File "/opt/hue/desktop/core/src/desktop/lib/django_mako.py", line 127, in render_to_response
    return HttpResponse(render_to_string(template_name, data_dictionary), **kwargs)
  File "/opt/hue/desktop/core/src/desktop/lib/django_mako.py", line 114, in render_to_string_normal
    template = lookup.get_template(template_name)
  File "/opt/hue/desktop/core/src/desktop/lib/django_mako.py", line 86, in get_template
    raise Exception("no app!")
Exception: no app!

### Hue version

hue-4.10.0

**Comment by bjornalm** [comment]
Hi @jallyQ thanks for reporting. It looks like you also might have found the fix for the issue. Would you like to create a pull request with your changes and become a Hue committer?

See https://github.com/cloudera/hue/blob/master/CONTRIBUTING.md
