### ISSUE TITLE
Export query results to s3 is not working 

### ISSUE THREAD

**Issue by satvik1992** [cloudera/hue#3434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hue export query results to s3 is not working and throws NotImplementedError . From the network tab it is observed that  the api 'notebook/api/notebook/export_result' returns -1

<img width="452" alt="ExportTos3" src="https://github.com/cloudera/hue/assets/66056033/0d656609-7a18-48a2-a563-e572b55acc10">

The version of hue used is 4.7.1

We are currently using Hue presto with hive meta-store and Mariadb on a Kubernetes Environment with following configuration

      [[[hive]]]
      name = Hive
      interface=hiveserver2

      [[[mysql]]]
      name = Mariadb
      interface=sqlalchemy
      options='{"url": "mysql://hue:hue@XXX-presto-mariadb:3306/hue"}'

      [[[presto]]]
      name = Presto
      interface=sqlalchemy
      options='{"url": "presto://XXX-presto-coordinator:80/hive/default"}'

### Steps To Reproduce

1. Run a query in presto editor
2. Click export the results to s3 

### Logs

 

  
ERROR    Error running export_result

Traceback (most recent call last):

  File "/usr/share/hue/desktop/libs/notebook/src/notebook/decorators.py", line 114, in wrapper
    return f(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/api.py", line 848, in export_result
    sql, success_url = api.export_large_data_to_hdfs(notebook, snippet, destination)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/base.py", line 572, in export_large_data_to_hdfs
    raise NotImplementedError()
NotImplementedError

### Hue version

4.7.1

**Comment by satvik1992** [comment]
@bjornalm  yes I see the same behaviour even on hue 4.11.0 version and below is the stack trace :-  [25/Aug/2023 05:31:05 -0700] access       INFO     10.223.205.9 -anon- - "GET /desktop/debug/is_alive HTTP/1.1" returned in 18ms 200 0
10.223.205.9 - - [25/Aug/2023:05:31:05 -0700] "GET /desktop/debug/is_alive HTTP/1.1" 200 0 "-" "kube-probe/1.24"
[25/Aug/2023 05:31:05 -0700] decorators   ERROR    Error running export_result
Traceback (most recent call last):
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/decorators.py", line 119, in wrapper
    return f(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/api.py", line 837, in export_result
    response['watch_url'] = api.export_data_as_hdfs_file(snippet, destination, overwrite)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/base.py", line 586, in export_data_as_hdfs_file
    raise NotImplementedError()
NotImplementedError

**Comment by bjornalm** [comment]
@satvik1992 ok thanks. We will have to look into it. @Harshg999 Can you take a quick look? Have we tested this before?

**Comment by bjornalm** [comment]
@Harshg999
