### ISSUE TITLE
Access Trino protected with oauth 2.0 from Hue

### ISSUE THREAD

**Issue by hafizmujadidKhalid** [cloudera/hue#3509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hey everyone!

We have oauth 2.0 (OIDC) protected Trino cluster. Hue also has Oauth 2.0 (OIDC) as an authentication method. We would like to access Trino from Hue. In order to access that, we need to set authentication to JWTAuthentication or OauthAuthentication. In SqlAlchemy we can do so as below:

JWT Authentication
```
from sqlalchemy import create_engine

engine = create_engine("trino://<username>@<host>:<port>/<catalog>/<schema>?access_token=<jwt_token>")

# or as connect_args
from trino.auth import JWTAuthentication
engine = create_engine(
    "trino://<username>@<host>:<port>/<catalog>",
    connect_args={
        "auth": JWTAuthentication("<jwt_token>"),
        "http_scheme": "https",
    }
)
```

OAuth2Authentication to pop up a browser window to authenticate users

```
from sqlalchemy import create_engine
from trino.auth import OAuth2Authentication

engine = create_engine(
"trino://<username>@<host>:<port>/<catalog>",
    connect_args={
        "auth": OAuth2Authentication(),
        "http_scheme": "https",
    }
)
```

I do see these settings are not possible in Hue. I tried setting connector like below:
```
[[[trino]]]
    name=Trino
    interface=sqlalchemy
    options='{"url": "trino://trinoserver.k8s.aws.cloud:443/hive?access_token=${ACCESS_TOKEN}","connect_args":"{\"http_scheme\": \"https\"}"}'
```
I tried without access_token as well but I always receive 401.

> (trino.exceptions.HttpError) error 401: b'Unauthorized' [SQL: SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1]

### Steps To Reproduce

1. Setup hue and Trino with OIDC
2. Setup Trino connector in Hue.ini as above
3. Open trino connector page
4. You will receive error while connectingan 
5. Ideally, we should be able to pass oidc access token of current logged in user to data connector. 

### Logs

[22/Oct/2023 23:06:48 -0700] access       INFO     127.0.0.1 user@example.com - "POST /jobbrowser/jobs/ HTTP/1.1" returned in 923ms 200 82 (mem: 190mb)
[22/Oct/2023 23:06:48 -0700] middleware   DEBUG    id token is still valid (1698042105.0221848 > 1698041208.741997)
[22/Oct/2023 23:06:49 -0700] utils        DEBUG    Found a TZ environment: America/Los_Angeles
[22/Oct/2023 23:06:49 -0700] sql_alchemy  ERROR    Query Error
Traceback (most recent call last):
  File "/hue/build/env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1321, in _cursor_execute
    self.dialect.do_execute(cursor, statement, parameters, context)
  File "/hue/build/env/lib/python3.9/site-packages/trino/sqlalchemy/dialect.py", line 399, in do_execute
    cursor.execute(statement, parameters)
  File "/hue/build/env/lib/python3.9/site-packages/trino/dbapi.py", line 592, in execute
    self._iterator = iter(self._query.execute())
  File "/hue/build/env/lib/python3.9/site-packages/trino/client.py", line 796, in execute
    status = self._request.process(response)
  File "/hue/build/env/lib/python3.9/site-packages/trino/client.py", line 603, in process
    self.raise_response_error(http_response)
  File "//hue/build/env/lib/python3.9/site-packages/trino/client.py", line 594, in raise_response_error
    raise exceptions.HttpError(
trino.exceptions.HttpError: error 401: b'Invalid credentials'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 101, in decorator
    return func(*args, **kwargs)
  File "/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 446, in autocomplete
    inspector = inspect(engine)
  File "/hue/build/env/lib/python3.9/site-packages/sqlalchemy/inspection.py", line 63, in inspect
    ret = reg(subject)
  File "/hue/build/env/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 141, in _insp
    return Inspector.from_engine(bind)

### Hue version

Open source current master

**Comment by bjornalm** [comment]
Hi @hafizmujadidKhalid and thanks for reporting. @wing2fly Can you have look and see if this is a configuration issue or not?
