### ISSUE TITLE
Livy Spark Server: Unable to determing spark-submit version [1]

### ISSUE THREAD

**Issue by xinwu246810** [cloudera/hue#362]
I installed hue 3.9 on a cluster of 3 hosts with HDP 2.3. My Ambari version is 2.1.2.

The problem is that the Hue initial setup screen displays:

**Spark The app will not work without a running Livy Spark Server**

Following this thread [Error in running livy spark server in hue](url) and this web  [http://gethue.com/new-notebook-application-for-spark](url) , I tried several things, but when I start livy-spark with root user I get the following error:

```
[root@master bin]# ./hue livy_server 
SLF4J: Class path contains multiple SLF4J bindings. 
SLF4J: Found binding in [jar:file:/usr/hdp/2.3.2.0-2950/hue/apps/spark/java-lib/livy-assembly.jar!/org/slf4j/impl/StaticLoggerBinder.class] 
SLF4J: Found binding in [jar:file:/usr/hdp/2.3.2.0-2950/hadoop/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class] 
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation. 
Failed to run spark-submit executable: java.io.IOException: Unable to determing spark-submit version [1]: 
```
 And I execute `spark-submit --version` command displays spark's version correctly (1.4.1). 

```
[root@master bin]# spark-submit --version 
Welcome to 
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 1.4.1
      /_/

Type --help for more information.
```

Someone could help me?

Thank you and regards

**Comment by romainr** [comment]
It is possible that you might need to use a more recent Livy, where this check was removed https://github.com/cloudera/livy

**Comment by xinwu246810** [comment]
Thank you for your reply! I solved this problem with the recent Livy[https://github.com/cloudera/livy](url)
But I have a new problem ! When I submit a python file through the Hue Web (Spark Notbook), and excute the python file, have some erros:
```
16/05/05 22:56:44 ERROR SessionServlet$: internal error
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of scala.collection.immutable.List out of VALUE_STRING token
 at [Source: HttpInputOverHTTP@63e8873d; line: 1, column: 19] (through reference chain: com.cloudera.livy.server.batch.CreateBatchRequest["pyFiles"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:762)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:758)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:275)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:216)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:206)
	at com.fasterxml.jackson.module.scala.deser.SeqDeserializer.deserialize(SeqDeserializerModule.scala:76)
	at com.fasterxml.jackson.module.scala.deser.SeqDeserializer.deserialize(SeqDeserializerModule.scala:59)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:238)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3066)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2207)
	at com.cloudera.livy.server.JsonServlet.bodyAs(JsonServlet.scala:102)
	at com.cloudera.livy.server.JsonServlet.bodyAs(JsonServlet.scala:98)
	at com.cloudera.livy.server.batch.BatchSessionServlet.createSession(BatchSessionServlet.scala:33)
	at com.cloudera.livy.server.batch.BatchSessionServlet.createSession(BatchSessionServlet.scala:28)
	at com.cloudera.livy.server.SessionServlet$$anonfun$17$$anon$2$$anonfun$18.apply(SessionServlet.scala:127)
	at com.cloudera.livy.server.SessionServlet$$anonfun$17$$anon$2$$anonfun$18.apply(SessionServlet.scala:126)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
Could you help me ?

**Comment by romainr** [comment]
For Livy specify questions, I would recommend to ask on the project list:
http://groups.google.com/a/cloudera.org/group/livy-user

**Comment by yamyamyuo** [comment]
@xinwu246810 did you solve your problem? I also encounter same problems like yours, upload a file to hue notebook spark python file

**Comment by xinwu246810** [comment]
No, I still have this problems! If you solved, please tell me! Thank You!

**Comment by yamyamyuo** [comment]
Actually I have already know why this occurs. https://groups.google.com/a/cloudera.org/forum/#!topic/livy-user/4m0y1VEXXVA

**Comment by romainr** [comment]
This is the jira: https://issues.cloudera.org/browse/HUE-4761

**Comment by JaryZhen** [comment]
@xinwu246810 @yamyamyuo @romainr  sorry to disturb you guys. Did u fixed this problem?

`16/12/19 15:53:20 ERROR SessionServlet$: internal error
java.lang.NullPointerException
	at com.cloudera.livy.sessions.Session.resolveURIs(Session.scala:150)
	at com.cloudera.livy.sessions.Session$$anonfun$5.apply(Session.scala:217)
	at com.cloudera.livy.sessions.Session$$anonfun$5.apply(Session.scala:211)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:224)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:403)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at com.cloudera.livy.sessions.Session.prepareConf(Session.scala:211)
	at com.cloudera.livy.server.batch.BatchSession.<init>(BatchSession.scala:38)
	at com.cloudera.livy.server.batch.BatchSessionServlet.createSession(BatchSessionServlet.scala:35)
	at com.cloudera.livy.server.batch.BatchSessionServlet.createSession(BatchSessionServlet.scala:28)
	at com.cloudera.livy.server.SessionServlet$$anonfun$17$$anon$2$$anonfun$18.apply(SessionServlet.scala:122)
	at com.cloudera.livy.server.SessionServlet$$anonfun$17$$anon$2$$anonfun$18.apply(SessionServlet.scala:121)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)`
