### ISSUE TITLE
when beeswax use spark thrift instead of hiveserver2 ,error : Autocomplete data fetching error: list index out of range

### ISSUE THREAD

**Issue by lemontreeshy** [cloudera/hue#364]
![image](https://cloud.githubusercontent.com/assets/6259741/15010178/5d8c83b2-121d-11e6-84a7-390c4d806e74.png)

I started spark-sql thriftserver :
/opt/spark/sbin/start-thriftserver.sh --hiveconf hive.server2.thrift.port=12000 --master yarn

[beeswax]

  # Host where HiveServer2 is running.
  # If Kerberos security is enabled, use fully-qualified domain name (FQDN).
  hive_server_host=analysis

  # Port where HiveServer2 Thrift server runs on.
  hive_server_port=12000

and I can run spark-sql in beeswax

**Comment by romainr** [comment]
There are some missing parts in the Spark SQL API that we are tracking  in https://issues.cloudera.org/browse/HUE-2985

**Comment by romainr** [comment]
Which Spark version are you using? On 1.6.1 I can't even list the tables

**Comment by lemontreeshy** [comment]
I'm using spark 1.6.0

**Comment by simonvanderveldt** [comment]
@romainr Was anything fixed/changed for this and was that the reason you closed this issue?
We're still seeing the same message in the Table browser
![image](https://user-images.githubusercontent.com/204286/125931480-2ec68071-8b67-4c01-ab7e-29b93111d8d0.png)

Logs from Hue:
```
[16/Jul/2021 12:02:53 +0200] decorators   ERROR    Error running describe
Traceback (most recent call last):
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/decorators.py", line 119, in wrapper
    return f(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/api.py", line 1039, in describe
    describe = get_api(request, snippet).describe(notebook, snippet, database, table, column=column)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/base.py", line 646, in describe
    describe_database = self.describe_database(notebook, snippet, database)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/hiveserver2.py", line 950, in describe_database
    return db.get_database(database)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/dbms.py", line 346, in get_database
    return self.client.get_database(database)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 1510, in get_database
    return self._client.get_database(database)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 850, in get_database
    return HiveServerTRowSet(desc_results.results, desc_schema.schema).cols(cols)[0]  # Should only contain one row
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 268, in cols
    cols = [rs.full_col(name) for name in col_names]
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 268, in <listcomp>
    cols = [rs.full_col(name) for name in col_names]
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 299, in full_col
    pos = self._get_col_position(colName)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 303, in _get_col_position
    return list(filter(lambda i_col1: i_col1[1].columnName == column_name, enumerate(self.schema.columns)))[0][0]
IndexError: list index out of range
```
We're using the Spark thriftserver running Spark 3.1.1 and Hue 4.10.0

**Comment by romainr** [comment]
https://github.com/cloudera/hue/blob/master/tools/docker/hue/Dockerfile#L61

**Comment by simonvanderveldt** [comment]
@romainr hmm, we're using that image/the upstream Hue image and still seeing this error.
Should I create a new issue?

**Comment by romainr** [comment]
You can, but would recommend to use the SQL Alchemy interface and not Hue's HiveServer2 as it should work out of the box https://gethue.com/blog/querying-spark-sql-with-spark-thrift-server-and-hue-editor/
