### ISSUE TITLE
hue  xxx.gz file Open in Brower Failed to decompress file.

### ISSUE THREAD

**Issue by liwei2916** [cloudera/hue#3692]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

I want to view the content of the gz file in HDFS through hue, but unfortunately, hue reported an error. The error message is Failed to decompress file
![image](https://github.com/cloudera/hue/assets/107097980/57ce1da9-3b31-4594-8a1a-d7eeeb8732ed)

### Steps To Reproduce

python 3.8 

### Logs

[11/Apr/2024 22:10:25 -0700] views        ERROR    Could not decompress file at "/datawarehouse/alpha/temp/base_obj_fulltext/part-00002.gz": Compressed file ended before the end-of-stream marker was reached
Traceback (most recent call last):
  File "/usr/share/hue/apps/filebrowser/src/filebrowser/views.py", line 1007, in _read_gzip
    contents = decompress_gzip(fhandle.read())
  File "/usr/lib/python3.8/gzip.py", line 548, in decompress
    return f.read()
  File "/usr/lib/python3.8/gzip.py", line 292, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.8/gzip.py", line 498, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
[11/Apr/2024 22:10:25 -0700] exceptions_renderable ERROR    Potential trace: [<FrameSummary file /usr/share/hue/apps/filebrowser/src/filebrowser/views.py, line 1007 in _read_gzip>, <FrameSummary file /usr/lib/python3.8/gzip.py, line 548 in decompress>, <FrameSummary file /usr/lib/python3.8/gzip.py, line 292 in read>, <FrameSummary file /usr/lib/python3.8/gzip.py, line 498 in read>]
[11/Apr/2024 22:10:25 -0700] middleware   INFO     Processing exception: Failed to decompress file.: Traceback (most recent call last):
  File "/usr/share/hue/apps/filebrowser/src/filebrowser/views.py", line 1007, in _read_gzip
    contents = decompress_gzip(fhandle.read())
  File "/usr/lib/python3.8/gzip.py", line 548, in decompress
    return f.read()
  File "/usr/lib/python3.8/gzip.py", line 292, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.8/gzip.py", line 498, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached

During handling of the above exception, another exception occurred:

### Hue version

hue 4.11

**Comment by liwei2916** [comment]
After verification, gz files larger than 1MB are not allowed, while files smaller than 1MB can be browsed for their content

What is the reason for this? Can someone help answer it

**Comment by liwei2916** [comment]
If compiling Hue with Python 3, opening a compressed file larger than 1MB triggers an error. I'll temporarily revert to version 4.8.0 and use Python 2.7

anyone has encountered the same problem？

**Comment by athithyaaselvam** [comment]
Hi @liwei2916, I tried to reproduce this but seems like its working for me (built on the master branch). I opened a 17mb .tgz file. Although there is a config in filebrowser, which might prevent it 
```
[filebrowser]
  # A limit on a file size (bytes) that can be uploaded to a filesystem.
  # A value of -1 means there will be no limit.
  max_file_size_upload_limit=-1 
```
<img width="1292" alt="Screenshot 2024-04-16 at 3 19 40 PM" src="https://github.com/cloudera/hue/assets/33496652/42aba0c2-93e0-4070-b0cd-29cd90003b46">

**Comment by liwei2916** [comment]
Hi @athithyaaselvam May I ask if you are using Python 3 or Python 2 for compilation? My environment is Releases 4.11.0 and Python 3.8. I have added the max_file_size_upload_limit=-1 configuration, but it still doesn't work

I still have the same error when using the gethue/hue: 4.11.0 image

I am currently using version 4.8.0, compiled through Python 2.7, and there are no restrictions on opening compressed files

**Comment by athithyaaselvam** [comment]
Hi @liwei2916, I'm using Python3.8 for compilation. Opening the file fails only for ".gz" format, as a quick workaround, try to change the compression format. I tried with ".tgz, .zip" files (It works). There is a restriction on the decompression for ".gz" files in Py3 Hue, Looking into it.

**Comment by liwei2916** [comment]
Okay, thank you @athithyaaselvam ， Will future versions be supported?
