### ISSUE TITLE
permission denied, mkdir '/usr/local/hue/node_modules/node-sass/vendor

### ISSUE THREAD

**Issue by liwei2916** [cloudera/hue#3697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

> deasync@0.1.29 install /usr/local/hue/node_modules/deasync
> node ./build.js

`linux-x64-node-14` exists; testing
Binary is fine; exiting

> node-sass@4.14.1 install /usr/local/hue/node_modules/node-sass
> node scripts/install.js

Unable to save binary /usr/local/hue/node_modules/node-sass/vendor/linux-x64-83 : Error: EACCES: permission denied, mkdir '/usr/local/hue/node_modules/node-sass/vendor'
    at Object.mkdirSync (fs.js:1014:3)
    at sync (/usr/local/hue/node_modules/mkdirp/index.js:74:13)
    at Function.sync (/usr/local/hue/node_modules/mkdirp/index.js:80:24)
    at checkAndDownloadBinary (/usr/local/hue/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/usr/local/hue/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/usr/local/hue/node_modules/node-sass/vendor'
}

### Steps To Reproduce

Centos 7.9
python 2.9

### Hue version

hue 4.8

**Comment by bjornalm** [comment]
@liwei2916 Thanks for reporting. Do you have the same issue i the latest 4.11 version?

**Comment by liwei2916** [comment]
chown -R hue:hue hue-4.8.0
su - hue
cd hue-4.8.0
make apps

Do not compile with root @bjornalm
