### ISSUE TITLE
Error while accessing Solr

### ISSUE THREAD

**Issue by JMetai** [cloudera/hue#370]
Heatmaps issue.
After adding heatmaps widget and selecting a date field, it throws following error:

{ "message": "'facets'", "traceback": [ [ "/root/Hue/apps/search/src/search/views.py", 145, "search", "response = SolrApi(SOLR_URL.get(), request.user).query(collection, query)" ], [ "/root/Hue/desktop/libs/libsolr/src/libsolr/api.py", 359, "query", "if facet['properties']['facets'] or facet['widgetType'] == 'map-widget':" ] ], "detail": "None", "title": "Error while accessing Solr" }

Also, there are no null values or zeros in the selected date field. 

I'm using Hue 3.9 and Solr 5.5

Any help is appreciated.

**Comment by romainr** [comment]
What do you have on the /logs page?

I just tried on Hue master and Solr 4 from CDH5.8 and it was good (date field and string for field 2)

**Comment by JMetai** [comment]
Here is what I have on /logs page:

ze=1000 HTTP/1.1" 200 None
[16/May/2016 09:05:58 -0700] resource     DEBUG    GET Got response: {"responseHeader":{"status":0,"Q...
[16/May/2016 09:05:58 -0700] _internal    INFO     ESC[m10.219.24.43 - - [16/May/2016 09:05:58] "POST /search/search HTTP/1.1" 200 -ESC[0m
[16/May/2016 09:06:05 -0700] access       INFO     10.219.24.43 admin - "POST /search/template/new_facet HTTP/1.1"
[16/May/2016 09:06:05 -0700] _internal    INFO     ESC[m10.219.24.43 - - [16/May/2016 09:06:05] "POST /search/template/new_facet HTTP/1.1" 200 -ESC[0m
[16/May/2016 09:06:05 -0700] access       INFO     10.219.24.43 admin - "POST /search/search HTTP/1.1"
[16/May/2016 09:06:05 -0700] middleware   INFO     Processing exception: 'facets': Traceback (most recent call last):
  File "/root/Hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/Hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/root/Hue/apps/search/src/search/decorators.py", line 44, in decorate
    return view_func(request, *args, **kwargs)
  File "/root/Hue/apps/search/src/search/views.py", line 154, in search
    raise PopupException(e, title=_('Error while accessing Solr'))
PopupException: 'facets'

**Comment by romainr** [comment]
In the chrome network tab, what do you have for the header and response of the '/search/template/new_facet' call?

**Comment by JMetai** [comment]
There was some indentation issue in views.py file, after fixing identation, issue went away. Thanks!
