### ISSUE TITLE
importlib.metadata.PackageNotFoundError: desktop

### ISSUE THREAD

**Issue by helifee** [cloudera/hue#3750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I get this error when I do it by https://gethue.com/quick-start-a-hue-development-environment-in-3-minutes-with-docker/

root@zhangdaoqiang-pxb:/mnt/d/projects/data-platform/code/hue-master# sudo docker run -it -u root --privileged=true -v $PWD/desktop:/usr/share/hue/desktop -v $PWD/apps:/usr/share/hue/apps  -v $PWD/desktop/conf/pseudo-distributed.ini:/usr/share/hue/desktop/conf/z-hue.ini gethue/hue

thank you!

### Steps To Reproduce

my os is window wsl2

### Logs

Traceback (most recent call last):
  File "./build/env/bin/hue", line 33, in <module>
    sys.exit(load_entry_point('desktop', 'console_scripts', 'hue')())
  File "./build/env/bin/hue", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: desktop
Traceback (most recent call last):
  File "./build/env/bin/supervisor", line 33, in <module>
    sys.exit(load_entry_point('desktop', 'console_scripts', 'supervisor')())
  File "./build/env/bin/supervisor", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: desktop

### Hue version

4.11 and master

**Comment by helifee** [comment]
both the source version and the docker image version are 4.11
