### ISSUE TITLE
postgres and docker container does not work

### ISSUE THREAD

**Issue by SergeyParamoshkin** [cloudera/hue#392]
Hi, I'm using Docker container Hue and want to use an external database. but attempts to do that get error 

```
Error loading psycopg2 module: No module named psycopg2.
```

```
engine = postgresql_psycopg2
```

```
$ sudo docker run -ti -p 8888:8888 -v /opt/hue/desktop/conf:/hue/desktop/conf  gethue/hue:latest
INFO:root:Welcome to Hue 3.10.0
DEBUG:desktop.appmanager:Loaded Desktop Libraries: aws, hadoop, liboauth, liboozie, libopenid, librdbms, libsaml, libsentry, libsolr, libzookeeper
DEBUG:desktop.lib.conf:Loading configuration from: hue.ini
DEBUG:desktop.appmanager:Loaded Desktop Applications: about, beeswax, filebrowser, hbase, help, impala, jobbrowser, jobsub, metastore, oozie, pig, proxy, rdbms, search, security, spark, sqoop, useradmin, zookeeper, indexer, metadata, notebook
DEBUG:root:Installed Django modules: DesktopModule(aws: aws),DesktopModule(hadoop: hadoop),DesktopModule(liboauth: liboauth),DesktopModule(liboozie: liboozie),DesktopModule(libopenid: libopenid),DesktopModule(librdbms: librdbms),DesktopModule(libsaml: libsaml),DesktopModule(libsentry: libsentry),DesktopModule(libsolr: libsolr),DesktopModule(libzookeeper: libzookeeper),DesktopModule(Hue: desktop),DesktopModule(About: about),DesktopModule(Hive: beeswax),DesktopModule(File Browser: filebrowser),DesktopModule(HBase Browser: hbase),DesktopModule(Help: help),DesktopModule(Impala: impala),DesktopModule(Job Browser: jobbrowser),DesktopModule(Job Designer: jobsub),DesktopModule(Metastore Manager: metastore),DesktopModule(Oozie Editor/Dashboard: oozie),DesktopModule(Pig Editor: pig),DesktopModule(Proxy: proxy),DesktopModule(RDBMS UI: rdbms),DesktopModule(Solr Search: search),DesktopModule(Hadoop Security: security),DesktopModule(Spark: spark),DesktopModule(Sqoop: sqoop),DesktopModule(User Admin: useradmin),DesktopModule(ZooKeeper Browser: zookeeper),DesktopModule(Solr Indexer: indexer),DesktopModule(Metadata: metadata),DesktopModule(Notebook: notebook)
WARNING:desktop.lib.conf:enable_dbproxy_server is of type bool. Resetting it as type 'coerce_bool'. Please fix it permanently
WARNING:desktop.lib.conf:enable_query_builder is of type bool. Resetting it as type 'coerce_bool'. Please fix it permanently
WARNING:desktop.lib.conf:enable_query_scheduling is of type bool. Resetting it as type 'coerce_bool'. Please fix it permanently
DEBUG:desktop.lib.conf:Loading configuration from: hue.ini
DEBUG:desktop.lib.conf:Loading configuration from: hue.ini
DEBUG:root:DESKTOP_DB_TEST_NAME SET: /hue/desktop/desktop-test.db
DEBUG:root:DESKTOP_DB_TEST_USER SET: hue_test
Traceback (most recent call last):
  File "build/env/bin/hue", line 9, in <module>
    load_entry_point('desktop==3.10.0', 'console_scripts', 'hue')()
  File "/hue/desktop/core/src/desktop/manage_entry.py", line 64, in entry
    raise e
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named psycopg2
```

```
root@5e37ecaa582c:/hue/build/env/bin# find / -name "*psycopg*"
/hue/build/env/lib/python2.7/site-packages/South-1.0.2-py2.7.egg/south/db/postgresql_psycopg2.pyc
/hue/build/env/lib/python2.7/site-packages/South-1.0.2-py2.7.egg/south/db/postgresql_psycopg2.py
/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/backends/postgresql_psycopg2
/hue/desktop/core/ext-py/South-1.0.2/build/lib.linux-x86_64-2.7/south/db/postgresql_psycopg2.py
/hue/desktop/core/ext-py/South-1.0.2/south/db/postgresql_psycopg2.py
/hue/desktop/core/ext-py/Django-1.6.10/build/lib.linux-x86_64-2.7/django/db/backends/postgresql_psycopg2
/hue/desktop/core/ext-py/Django-1.6.10/django/db/backends/postgresql_psycopg2
```

**Comment by romainr** [comment]
Did you install the postgresql connectors?

http://www.cloudera.com/documentation/enterprise/latest/topics/cdh_ig_hue_database.html#cdh_ig_hue_database_postgresql

**Comment by SergeyParamoshkin** [comment]
Hi. i`m use docker image 
https://github.com/cloudera/hue/tree/master/tools/docker

**Comment by SergeyParamoshkin** [comment]
I installed psycopg2 inside the container, but now I get this error

```
Traceback (most recent call last):
  File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/wsgi.py", line 206, in __call__
    response = self.get_response(request)
  File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/base.py", line 194, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/base.py", line 236, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/hue/desktop/core/src/desktop/views.py", line 335, in serve_500_error
    return render("500.mako", request, {'traceback': traceback.extract_tb(exc_info[2])})
  File "/hue/desktop/core/src/desktop/lib/django_util.py", line 227, in render
    **kwargs)
  File "/hue/desktop/core/src/desktop/lib/django_util.py", line 148, in _render_to_response
    return django_mako.render_to_response(template, *args, **kwargs)
  File "/hue/desktop/core/src/desktop/lib/django_mako.py", line 125, in render_to_response
    return HttpResponse(render_to_string(template_name, data_dictionary), **kwargs)
  File "/hue/desktop/core/src/desktop/lib/django_mako.py", line 114, in render_to_string_normal
    result = template.render(**data_dict)
  File "/hue/build/env/lib/python2.7/site-packages/Mako-0.8.1-py2.7.egg/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/hue/build/env/lib/python2.7/site-packages/Mako-0.8.1-py2.7.egg/mako/runtime.py", line 786, in _render
    **_kwargs_for_callable(callable_, data))
  File "/hue/build/env/lib/python2.7/site-packages/Mako-0.8.1-py2.7.egg/mako/runtime.py", line 818, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/hue/build/env/lib/python2.7/site-packages/Mako-0.8.1-py2.7.egg/mako/runtime.py", line 844, in _exec_template
    callable_(context, *args, **kwargs)
  File "/tmp/tmp9Tcgtq/desktop/500.mako.py", line 40, in render_body
    __M_writer(unicode( commonheader(_('500 - Server error'), "", user) ))
  File "/hue/desktop/core/src/desktop/views.py", line 385, in commonheader
    if user.is_authenticated():
  File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/utils/functional.py", line 213, in inner
    self._setup()
  File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/utils/functional.py", line 298, in _setup
    self._wrapped = self._setupfunc()
  File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/contrib/auth/middleware.py", line 18, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/contrib/auth/middleware.py", line 10, in get_user
    request._cached_user = auth.get_user(request)
  File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/contrib/auth/__init__.py", line 140, in get_user
    user_id = request.session[SESSION_KEY]
  File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/contrib/sessions/backends/base.py", line 47, in __getitem__
    return self._session[key]
  File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/contrib/sessions/backends/base.py", line 173, in _get_session
    self._session_cache = self.load()
  File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=timezone.now()
  File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
```

**Comment by romainr** [comment]
Could you drop the DB and do 'syncdb' then 'migrate'?

**Comment by SergeyParamoshkin** [comment]
hi. thx, I removed the sceme, delete the database, and then create the database and everything was ok
