### ISSUE TITLE
Oozie Editor/Dashboard:	The app won't work without a running Oozie server

### ISSUE THREAD

**Issue by rogeriobiondi** [cloudera/hue#393]
Hello,

I've built hue, configured and it's almost fine except for oozie. When starting Hue, in the checks, the following messages appear:

Oozie Editor/Dashboard:	The app won't work without a running Oozie server
Pig Editor	: The app won't work without a running Oozie server

In my configuration, **[liboozie]** session, the property **oozie_url** seems to be correct:

oozie_url=http://h7.domain:11000/oozie

If I try to connect this url in the browser or using curl, it seems to be ok. For some reason, the check isn't passing.

In my oozie configuration, **oozie-site.xml**, I've added the following properties:

```
<property>
      <name>oozie.service.ProxyUserService.proxyuser.hue.groups</name>
      <value>*</value>
    </property>

    <property>
      <name>oozie.service.ProxyUserService.proxyuser.hue.hosts</name>
      <value>*</value>
    </property>
```

Do you know how should I debug better this issue? Any tip or suggestion?

Thank you very much for your help.

Best regards,
Rogerio Biondi

**Comment by romainr** [comment]
What do you see in the Hue logs just after? (/logs page) 
You can check the property in the /dump_config page, maybe you modified the wrong one?

**Comment by rogeriobiondi** [comment]
Hello,

I've checked the dump_config page and the configuration is correct.
I'm taking a look at logs now...

Thanks,
Rogerio

**Comment by rogeriobiondi** [comment]
Some oozie errors here...

HTTP 401 (unauthorized).

In hue my superuser is "discover" and not "hue". I've tried with hue and the result is the same...

```
[17/Jun/2016 09:16:17 +0000] connectionpool INFO     Starting new HTTP connection (1): hdp7.discover.com.br
[17/Jun/2016 09:16:17 +0000] connectionpool DEBUG    "GET /oozie/v1/admin/status?timezone=America%2FLos_Angeles&user.name=hdfs&doAs=discover HTTP/1.1" 401 951
[17/Jun/2016 09:16:17 +0000] connectionpool INFO     Starting new HTTP connection (1): hdp7.discover.com.br
[17/Jun/2016 09:16:17 +0000] connectionpool DEBUG    "GET /oozie/v2/admin/configuration?timezone=America%2FLos_Angeles&user.name=hdfs&doAs=discover HTTP/1.1" 401 951
[17/Jun/2016 09:16:17 +0000] views        ERROR    Error in config validation by liboozie: <html><head><title>Apache Tomcat/6.0.44 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 401 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>This request requires HTTP authentication.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/6.0.44</h3></body></html> (error 401)
Traceback (most recent call last):
  File "/home/discover/hue-3.8.1/hue/desktop/core/src/desktop/views.py", line 484, in _get_config_errors
    for confvar, error in validator(request.user):
  File "/home/discover/hue-3.8.1/hue/desktop/libs/liboozie/src/liboozie/conf.py", line 87, in config_validator
    configuration = api.get_configuration()
  File "/home/discover/hue-3.8.1/hue/desktop/libs/liboozie/src/liboozie/oozie_api.py", line 317, in get_configuration
    resp = self._root.get('admin/configuration', params)
  File "/home/discover/hue-3.8.1/hue/desktop/core/src/desktop/lib/rest/resource.py", line 98, in get
    return self.invoke("GET", relpath, params, headers=headers, allow_redirects=True)
  File "/home/discover/hue-3.8.1/hue/desktop/core/src/desktop/lib/rest/resource.py", line 79, in invoke
    urlencode=self._urlencode)
  File "/home/discover/hue-3.8.1/hue/desktop/core/src/desktop/lib/rest/http_client.py", line 163, in execute
    raise self._exc_class(ex)
RestException: <html><head><title>Apache Tomcat/6.0.44 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 401 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>This request requires HTTP authentication.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/6.0.44</h3></body></html> (error 401)
```

**Comment by rogeriobiondi** [comment]
In oozie-site.xml, the authentication is set to "simple". I'm trying to figure out where should I configure the users... 
 
```
<property>
      <name>oozie.authentication.type</name>
      <value>simple</value>
    </property>
```

Thanks,
Rogério

**Comment by rogeriobiondi** [comment]
I've configured the following properties:

```
# Webserver runs as this user
server_user=hdfs
server_group=hdfs

# This should be the Hue admin and proxy user
default_user=discover

# This should be the hadoop cluster admin
default_hdfs_superuser=hdfs
```

And now it's working great!
