### ISSUE TITLE
Failed to dump data as JSON

### ISSUE THREAD

**Issue by shartoo** [cloudera/hue#397]
My hue cannot display any log(Cloudera Manager version 5.7.1).Then i enter the master machine, check log file ```/var/log/hue/error.log``` and get the error below:
```
[04/Jul/2016 19:13:29 -0700] views        ERROR    Failed to dump data as JSON
Traceback (most recent call last):
  File "/opt/cloudera/parcels/CDH-5.7.0-1.cdh5.7.0.p0.45/lib/hue/apps/hbase/src/hbase/views.py", line 86, in clean
    json.dumps(data)
  File "/usr/lib64/python2.6/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python2.6/json/encoder.py", line 367, in encode
    chunks = list(self.iterencode(o))
  File "/usr/lib64/python2.6/json/encoder.py", line 317, in _iterencode
    for chunk in self._iterencode_default(o, markers):
  File "/usr/lib64/python2.6/json/encoder.py", line 323, in _iterencode_default
    newobj = self.default(o)
  File "/usr/lib64/python2.6/json/encoder.py", line 344, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: TCell(timestamp=0, value='\x01\x00\x02\x00\x03\x00\x00\x00\x00\x00\x02\x01\x01\x02\x00\x03\x01\x04\x00\x00\x01\x00\x03\x01\x00\x01\x01\x01\x00\x00\x00\x04\x00\x00\x03\x01\x00\x00\x04\x00\x01\x01\x04\x01\x00\x02\x08\x00\x00\x00\x01\x01\x00\x01\x02\x00\x01\x00\x01\x00\x01\x03\x00\x00\x01\x07\x01\x00\x00\x01\x02\x00\x01\x00\x01\x00\x00\x03\x02\x00\x01\x00\x02\x00\x00\x00\x00\x03\x00\x01\x00\x03\x01\x02\x01\x01\x01\x01\x01\x00\x00\x00\x00\x05\x00\x0b\x05\x03\x00\x02\x00\x00\x04\x00\x00\x00\x01\x00\x04\x02\x00\x00\x00\x02\x02\x00\x00\x00\x00\x00\x00\x00\x01\x00\x03\x00\x03\x04\x01\x01\x00\x03\x02\x00\x00\x03\x03\x06\x01\x01\x02\x00\x03\x00\x03\x00\x00\x00\x00\x01\x00\x01\x00\x00\x00\x01\x05\x00\x07\x02\x00\x01\x02\x01\x01\x02\x01\x00\x07\x03\x00\x00\x02\x01\x01\x02\x02\x00\x02\x02\x01\x00\x00\x00\x00\x00\x02\x00\x01\x00\x01\x01\x01\x00\x02\x00\x00\x02\x00\x00\x02\x00\x02\x01\x00\x02\x01\x00\x03\x00\x00\x06\x04\x05\x03\x00\x00\x00\x00\x01\x02\x01\x01\x00\x00\x00\x01\x02\x07\x00\x02\x02\x00\x03\x00\x02\x06\x03\x04\x01\x00\x00\x02\x00\x04\x00\x05\x00\x00\x02\x00\x02\x01\x00\x01\x00\x03\x01\x00\x03\x03\x00\x06\x04\x03\x01\x00\x00\x01\x01\x00\x03\x03\x04\x02\x00\x00\x00\x01\x01\x00\x00\x00\x01\x02\x05\x00\x01\x00\x01\x00\x03\x00\x00\x00\x02\x01\x01\x00\x00\x04\x00\x02\x00\x00\x00\x00\x01\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x01\x01\x00\x03\x00\x00\x00\x00\x00\x03\x00\x00\x00\x02\x00\x02\x00\x00\x00\x01\x01\x00\x02\x04\x00\x01\x01\x01\x00\x00\x00\x00\x07\x02\x03\x01\x05\x04\x03\x02\x01\x00\x01\x01\x02\x01\x01\x00\x03\x03\x04\x00\x01\x00\x00\x02\x00\x04\x00\x03\x00\x04\x03\x00\x01\x02\x05\x00\x00\x04\x02\x02\x01\x03\x01\x01\x02\x00\x00\x03\x01\x00\x00\x02\x00\x00\x05\x01\x03\x03\x01\x02\x00\x02\x02\x01\x00\x01\x01\x00\x02\x00\x02\x02\x00\x01\x01\x00\x04\x00\x00\x01\x02\x03\x00\x00\x00\x00\x02\x01\x00\x01\x02\x01\x01\x03\x00\x01\x00\x00\x00\x00\x01\x00\x02\x02\x01\x00\x00\x04\x00\x00\x01\x00\x00\x03\x01\x00\x01\x00\x00\x00\x01\x00\x00\x02\x02\x00\x01\x00\x01\x01\x00\x02\x00\x00\x02\x01\x02\x04\x00\x03\x03\x02\x01\x02\x01\x00\x01\x06\x00\x01\x01\x04\x00\x02\x01\x00\x02\x01\x03\x00\x03\x01\x00\x01\x01\x00\x02\x04\x06\x04\x00\x07\x01\x00\x00\x01\x01\x04\x00\x01\x01\x00\x01\x00\x02\x00\x00\x03\x0b\x00\x03\x00\x02\x04\x02\x01\x00\x02\x00\x00\x00\x04\x01\x02\x01\x06\x00\x02\x01\x02\x00\x00\x00\x01\x04\x01\x00\x01\x00\x01\x02\x00\x03\x00\x00\x00\x01\x00\x01\x05\x00\x01\x02\x03\x02\x04\x00\x00\x01\x02\x04\x01\x02\x01\x02\x01\x04\x00\x00\x03\x00\x00\x02\x01\x02\x00\x02\x01\x00\x02\x02\x00\x00\x00\x00\x00\x00\x01\x06\x00\x01\x03\x01\x01\x05\x01\x01\x01\x00\x00\x00\x00\x04\x04\x02\x00\x00\x00\x00\x00\x00\x01\x00\x00\x03\x00\x01\x05\x02\x00\x00\x02\x00\x00\x01\x00\x00\x03\x00\x01\x01\x03\x00\x00\x00\x00\x01\x00\x00\x03\x00\x01\x02\x00\x04\x00\x02\x03\x02\x04\x01\x01\x00\x01\x01\x00\x04\x00\x00\x04\x04\x00\x00\x06\x00\x00\x00\x03\x03\x02\x01\x02\x02\x00\x03\x03\x00\x00\x00\x01\x00\x04\x02\x02\x00\x00\x01\x08\x06\x00\x02\x03\x00\x03\x00\x00\x00\x01\x01\x06\x04\x03\x02\x02\x02\x00\x00\x00\x00\x01\x00\x00\x00\x03\x07\x01\x01\x00\x00\x03\x00\x03\x00\x03\x00\x00\x06\x00\x02\x02\x07\x00\x00\x02\x04\x00\x00\x03\x02\x02\x00\x00\x01\x04\x00\x00\x00\x02\x01\x00\x02\x01\x00\x04\x01\x00\x02\x01\x00\x00\x00\x01\x00\x01\x01\x01\x03\x01\x00\x03\x00\x00\x00\x00\x00\x00\x01\x00\x00\x04\x00\x02\x06\x01\x00\x00\x00\x00\x00\x00\x02\x02\x00\x00\x01\x00\x00\x00\x00\x01\x02\x00\x00\x01\x02\x02\x00\x00\x05\x00\x00\x01\x05\x03\x00\x02\x01\x02\x00\x00\x03\x00\x00\x00\x00\x03\x02\x00\x03\x00\x01\x00\x05\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x01\x02\x01\x00\x02\x01\x02\x00\x00\x00\x00\x00\x00\x04\x01\x00\x00\x02\x00\x03\x00\x02\x00\x01\x01\x00\x02\x03\x00\x01\x00\x00\x02\x00\x00\x01\x01\x00\x03\x00\x02\x00\x02\x04\x00\x00\x01\x00\x00\x01\x04\x01\x01\x01\x02\x02\x00\x00\x01\x01\x05\x02\x00\x01\x03\x02\x02\x02\x00\x00\x01\x03\x01\x00\x04\x00\x00\x01\x00\x02\x01\x00\x02\x02\x00\x04\x02\x02\x02\x00\x00\x03\x01\x07\x03\x00\x00\x00\x00\x00\x01\x01\x02\x01\x03\x01\x00\x01\x01\x01\x00\x00\x01\x00\x01\x02\x02\x01\x00\x00\x00\x01\x00\x05\x03\x04\x00\x01\x01\x00\x05\x02\x00\x02\x01\x00\x00\x01\x00\x01\x01\x00\x00\x13\x88\x00\x00\x03W\x00\x00\x00\x02g\x80\x03W\x00\x00\x00\x00\x00\x00\x00\x01\x002\x00\xec\n\xf82`B\x80\x08\x80Y\x82\x1e\n\xb8\x00p\x03\x90T\xf0\x06\xa0\x13\x01\x14\x00\xd9\x00\x12\x03\xc0\x1b\xf0&PP\x80\x8a\x008\x01\xa0\x00\xb8\x00\x98\x0c\xd8\x11\x90\x10\x00E\x00\xe2\x81\x15\x03\x04\x08p\n\xe8\x0f\xb0A\xe0\x06@\xfa\x01\x17\x00\xd8\x01\xac\x04\xd0\x01@\x08@\xcd\x80\x02\x80(\x00\xcc\x01\xa8\x1b\xa8\x08\xb0Z\xe06\xc0V\x00\xc4\x01\xb4\x04\xb4\x00\x88\x05\x80\x0c\xc06@\x02\x00\xc3\x00\xb4\x07\x14\x0b\xe0\x010\n`\xcaC\xa8\x00z\x03\x10\x04\x08\x05\x10 \x10\x01\x00!\x00\x15\x00\xd5\x00\x9a\x02\x08\x02\x98\x04\xf0\x13\x802\x81\x18\x81\x8f\x00\xd4\t\x00\x01X\x0b\xd0\x03\x80$@0\x006\x00z\x030\x08\xd0\x14@\x1c\xa0\x12@[\x81\xae\x02\x88\x02\x18\x08\x08\x010\x18 \x16\xc0\x1f\x00\xcd\x02&\t\xe4\x01\x00\x06\xf0\x13\xa0z\x01\xd4\x01\x81\x00^\x08\x18\x008\x04`$ \x05\x80\x16\x80u\x06\x1c\x08\x84\r\xd8\x0f\x80\x08\x00&\x013\x80\x03\x02^\x05\xe4\x07\xd0\x0e\xd0\x03\xc0\x03A\xcd\x00\xda\x00\xfa\x04t\n\xc8"\xb0\x14@\x14\xc0\x03\x80\xf0\x01"\x0c\x14\x01\x18&0\x11`+\xc1-\x82\xc8\x01:\x018\x00\xf0\x01@#\xc00@\x88\x81|\x01\xfe\x00@\x040\r\xd0\x04 e\xc1\x13\x00\xe5\x00\xca\x00\xf4\x0c\xa8\x05`=`\x1e\x00q\x00\x18\x00\xe8\t\xc0\x10\x80W0\x04\x80\x17\x80y\x80\x1d\x014\x00,\x07(\x08 \x0b`\x02\xc1\xa0\x80v\x02\xa0\x02\x90\x03\xa8\x0b@\r@\x0b\x80v\x00\xa2\x00j\x05\xf0\x07\xb8\x0e\xc0\x06\x00\x15\xc01\x00N\x03\xc4\x04\xf8\x01\x80#\xb0L\xe0\x15\x00w\x81_\x01(\x00\x0c\x010\n0\x07 8@\x0b\x80\xeb\x02(\x02,\x06\xc8\x1e\xf0\t\xa0\x1a@\xbf\x00\xaf\x00\n\x02\x94\x15h\x0c\x10\x15 1\xc02\x00\x94\x00\xf0\x01\xd0\x06\x90\x02@\t f\x80!\x00`\x00\xfc\x00<\x110\n\xa0\x01`6\x80\x03\x80Z\x00\x82\x02\xcc\x08h!\xe0)`\x9a\xc0\x1c\x00\x0f\x01\xa8\x02X\x01(\x14\x00\r\xa0\x1c\x00\x08\x00H\x00<\x07\x84\x01\xf8\x15\xd0\x08`l@N\x80\x0e\x00\xbe\x03\x98\x0f\x08\x03 \x18`G@\xd8\x80\xc2\x01\x06\x004\x00\xa8$p\x11`R\xc0i\x80T\x00\x1c\x02p\x01x\x01\xf0\x0b\xa0%@"\x00\x8b\x04\xa2\x00`\x00(\x04\xf0\x1f\xc0*\x80P\x80\x9e\x018\x01\xf4\x15\x80\x02p\x02 \x1c\x00i\x82\x82\x00d\r\xc8\x0c\xc0\x07\x80\x0f\xc0H\x00\xa2\x80C\x02T\x02X\x02hB@\x08\xa0\x1d@\xa4\x80$\x00\x06\x01 \x03\x98\x00P.\xe0\x02\x80\x12\x80\x12\x07\x02\x00 \x06\x98\x14 \x04`\x10\x80\x02\x80\x88\x01b\x01X\x01\xd8\n\x80\x07@G\xc0\xbd\x80\x8e\x01\xb8\x04H\x02H\rP\'\xe0?\x00\x00\x80\xa6\x00*\x02\x18\x03 \t\xc0\x14 \x15\x80\r\x01\x0e\x01\xb0\x00\xec\x0b\xa09\xc0\x01\x80\x03@J\x008\x00\x1e\x01\xa8\x02\xb8\x01@\x06`\x07\x80b\x00?\x00\xfa\x07\xc4\x05\x10\x03\xf0(\xc0g\x805\x01\xef\x00 \x02<\x02 \x13\xf0\x0e\xe0\x08@\x05\x80u\x00\x8a\x02`\x05\xf0\x01 \x04 \x17\x00d\x00\x08\x00"\x02\x1c\x05\x88+\xa0(\x80"\x80\x91\x80\xb6\x00x\x03T\x01\xf8L\x90\x03@\xb2@\x1f\x808\x00\xf2\x00\xa0\x04\x18\x08\xe0\x05 \x05\x80c\x00/\x00\xe4\x03x\x020\x14 0 \x1c\xc03\x81E\x00\xb2\x03\xc8\x02\xf0\x05\x80\x0f@\x00@b\x00\x06\x00\xa0\x02\xb4\x01p\x02`%`~\xc0\xba\x007\x01V\x07\xec\x00\xf8\x01`\x0b \x1b\x80X\x04\x8c\x04.\x04\xac\x12\x88\x04 F \x82\xc0\x02\x00\xbf\x00\x1e\x00\x0c \xf0\x010\x0f@\x11@\xa5\x01\x04\x02 \x05|\x00\xe8#\xb0\x07@\xcd\x80\x8b\x008\x00\x96\x0f\\\x01`\x17\xf0;\x00a\x80p\x00\xb6\x01*\x03\x04\x04\xc0A\xc0\t\xe0\x12@\x97\x00\xf4\x05\xbc\x03\xac\r 1\x00\x02\xc0\x91\x80\x90\x80Y\x004\x04`\x0eP\x18\xd0\x10\x00\xb0@\x87\x01]\x02\xb6\x05\xf0\x02\x88\x10P\x06 \x16\x80)\x81\xe4\x01\x9c\x0b\xe4\x16\xd8\x16@"@\xf5@\xa9\x80\x90\x03\x94\x03L\x00\x08\x07\x900\xe0\x85@!\x00\xa8\x03\x82\x0c\xec&\x88\x01\xc0\x1d`8\x801\x80`\x01\x80\x0b\x98\x04\x18\x08`\x14\xa0B\xc1&\x00t\x00\xd0\x01\x10\x04\xa8\x03\x90\x14\xa0\t\x80!\x01\x01\x02\x04\x01L\x00\xf0\n\xd0\x11@\\\x80\x18\x00\x13\x01|\x05\x0c\x02\xa8\x10\xa0\x0c`\xec@\xe2\x80\x95\x008\tL\x0b\xe01P\x07\xa0\x18\xc01\x00\x12\x00~\x00H\t\xc8\t\xb0! f\x804\x81\n\x01`\x02@ \x90\t\xc0\x12\xc09@\xc6\x80\\\x01\xbc\x05\xd4\x13\x88!0\x08\x00=\x00\x13\x80\xa5\x01\x16\x01L\x03 \x080\x05@#\xc0q\x82H\x00\xac\x02\xd4\x05x\x00\xb0\x06\xa0\x15\x01\x97\x80\xa8\x00\xfc\x10\xf8\x01@\\ \x02\xe0PAD\x04H\x00\xc4\x02\xec\x04p\x1a ;!\x92\x00\n\x00]\x02\\\x04\xa0\tx\x02\x10\n\xe18\x80\x10\x00J\x05\x16\x03\xc8\x14\x88\x12@V@\x0f\x00t\x00\x0f\x00\xa4\x06\x18\x0b\x88\x00\x90M\xa02\x004\x80\xc5\x02\x16\x04\xac\x01H,\x00\t\xc0(\xc0\xc5\x81\xba\x00`\x02 \n\xd8\x0e\xf0\x7f\xc0\x06\x00\x8f\x81g\x06\x00\x00\x08\x14(\x1a\xa0\x89\xc0V\x80\x99\x83\x1f\x00p\x08\xb0\x01\xd0<p\x15\xe0I\x01;\x00L\x02\\\x04\xa0\x01x\x10\xb07 K\x82\x07\x80-\x02\x0c\x08\xdc# I\xa0\'\x809\x02\xdb\x85\x89\x06\xf4\x02\x14\x0f0"@\x01@{\x834\x81s\x01\xb0\x1e|&\xd0\x18\xc0:\x803\xc0G\x81\x1c\x05\xd0\x03\x1c\x03\xa0\n\x105B\x06\x043\x803\x03\xde\x0f\x18\x100\x041)\xc13\x80\xa8\x03\xcd\x05\x14\x03\xac\x00p=\x10\x02\x00\xb2C>\x00D\x0cb\x04<\t\x08$\xc0u \x85\xc0j\x80\xd5\x01\xaa\x03\x10\x05\x904\xb0\t\xe1\xb5@\xae\x83\x10\x01\x9c\x05t\x0b\xf8\x04\x91_\xa1)\x021\x03.\x01\x8a\x08\xc8\x82H?@\xa1 \x9a@\x07\x83#\x05l\t\x84\x17\xf8\xd4\xd0;\xe0\x07@z\x0c\xb0\x0c\x9c\x0f\xa0\t0D\xa0} \xb9\x83\x18\x81\x0b\x11\xded\xc0P\x80\\\x90\x02\x84\xba\x82x\x81\xec\x00\xf4\x88\xd0\x86\xc0\xd1P\xb2 \x0fA_\x84\xa6I\x144D\x088f@s\xa3\xe6Px\x86\xf4\x068g<\x0c\xa0QJ\xa2aw\xc0\x00\x00\x00\x00\x00\x00\x007\x013\x01\x17\x02\x7f\x01P\x00X\x02Y\x01\x1b\x01\xfc\x031\x03\x9c\x03B\x02:\x02\xd6\x02K\x02j\x01\x83\x02\x01\x03o\x03\x81\x01\x10\x03\xde\x03\xca\x01\x80\x00\xc4\x01\xdc\x00\xbf\x03\x13\x01;\x00*\x02?\x00P\x03!\x01\x98\x00\xd1\x02\x0e\x01\xf4\x02\x0b\x03\t\x03\x0f\x02D\x01\xfa\x03\xba\x00j\x01V\x02n\x00\x17\x03\xdc\x01\xd4\x01\xc6\x02/\x00\xb2\x01\x03\x03\xb1\x00\x01\x03S\x02\xfa\x03x\x034\x00\x1c\x02w\x02\xde\x00\x03\x00&\x03\xce\x03p\x01\x92\x001\x00\'\x02W\x02\xcf\x01\xfb\x01\x93\x02&\x03\x08\x03\xb9\x03\x8d\x00\x89\x02+\x03Z\x02Z\x02\x14\x02\xbf\x01\x12\x03\xc3\x00\x1d\x00\x85\x01\x18\x02\xf5\x03\x89\x03?\x00=\x02\xac\x02}\x02\xbe\x03\xb6\x03V\x00)\x03\xd0\x01\xa5\x01-\x00\xdf\x00K\x01B\x03u\x006\x01\xc4\x03\x9d\x01I\x02\x07\x02\xa3\x03F\x03&\x00\xf5\x03\xbd\x02\xcd\x01<\x02\xd8\x00q\x01p\x00\xe7\x00\x00\x02\xb6\x01\x8a\x00\xa7\x00\x96\x01\xb8\x00,\x00\xff\x01\xaa\x02\t\x02P\x02\x9e\x01\xe7\x01\x19\x03\x95\x03<\x02\xf6\x01\n\x03\x02\x02\x9c\x03\x14\x015\x01u\x01,\x01Y\x02N\x01\x89\x01\xab\x00H\x00:\x01\x8c\x02\x82\x00\xa3\x01?\x00e\x00\x9b\x02b\x01\t\x03@\x01)\x03\xc0\x02\x8a\x00~\x01\x88\x00\\\x00A\x02\xb3\x02\xea\x00{\x03\x80\x02\xba\x03z\x00\x15\x03\xc6\x00F\x02o\x01^\x02\x89\x032\x00+\x03#\x03~\x00M\x01/\x03\xa9\x024\x01\xe4\x00\x0f\x01.\x01\xdb\x00\xf2\x02\x97\x03\x05\x03\x19\x00\x07\x02S\x02\x03\x01}\x03:\x01\xc8\x01\x13\x00\x93\x02<\x01\x86\x00W\x02\xed\x00#\x02\xf3\x02\xd3\x01[\x02H\x02\xd2\x00 \x00\xef\x03\x0c\x017\x03\xcb\x00N\x02\xe9\x00"\x02\x18\x02]\x02\xb8\x038\x03\x83\x00O\x02\xf0\x02\x8f\x00\xa6\x02\xa6\x01\x8b\x02X\x01D\x00\x88\x00d\x02\x91\x01\x05\x00\xd6\x01\xbc\x01\xfd\x021\x00\xac\x00]\x00\xc5\x01S\x03\xcf\x00\x86\x03\xd2\x01\xe6\x03\xd6\x01M\x01\xd6\x01\xea\x00\x98\x00\xe8\x03C\x02\xe1\x00\x8d\x02\xdd\x03\xb0\x02\xdc\x00Y\x01\xdf\x037\x01\xc1\x01z\x03G\x03\xb2\x00>\x01\xb6\x02[\x03 \x00\x04\x01\xeb\x02\x81\x00\x12\x00\xee\x02\xc6\x03\xe2\x01\x0b\x02\x1f\x00R\x02\xa5\x01\xd8\x01\x9c\x00\xd7\x03j\x01\xee\x02u\x03W\x00\xc2\x01\x87\x01H\x02c\x02F\x00u\x00\xcb\x03K\x02{\x00T\x00\xa1\x01\xa0\x01\xa9\x02\xef\x008\x01\x81\x03\xc8\x02R\x03\x88\x02\xfb\x03\xd7\x02\xe5\x02h\x01\xa3\x01w\x00\xc9\x00L\x01A\x02\xeb\x00\xe1\x03=\x00\xf3\x01\xbf\x00I\x01i\x02|\x01\xe1\x03\x96\x02\x1a\x03>\x02%\x03\xd5\x030\x01\x95\x01\x9a\x00\x81\x00\xed\x03\xa6\x03\xa8\x01G\x03\xcc\x00\x8a\x02\xb7\x03e\x02\xc1\x00$\x00\xe3\x01\xb5\x00\xc3\x02\xbc\x00\xc7\x02t\x00\xd2\x02,\x00\xb5\x02\xad\x02\xc0\x02k\x03\xbb\x02\xb4\x02\r\x03-\x03\x8a\x00;\x03A\x003\x00}\x00b\x03\xb5\x01\xcc\x02)\x00\xea\x03\x97\x02\xca\x00\xdc\x02"\x00\xf8\x01+\x03\x1a\x00\x8c\x00\xda\x02\x85\x01\x85\x00\x90\x00\xb4\x00\xb8\x03\xdd\x00\xbb\x02g\x00\x8b\x029\x02\xe4\x03\xdf\x02\xe2\x02i\x02e\x03\xe6\x03)\x027\x01\xca\x03\xe7\x00\x08\x00o\x02\xc8\x02A\x02\xff\x01f\x03\x12\x03\x98\x02\x80\x02\x9f\x00\xe2\x02L\x00\x92\x02\x94\x02\xce\x03\xe1\x01\r\x02C\x00g\x03\x91\x01\xbb\x00\x14\x00\x1e\x02\x87\x02\xa8\x00^\x01\xf5\x02\xc5\x01\x06\x00k\x02\xc4\x011\x00\xdb\x03v\x03[\x03E\x02\xfc\x00\x16\x02\x17\x02\xae\x03\\\x02\xbb\x02\n\x00?\x02\x8e\x03\xda\x03|\x03\r\x00\xe5\x03\xe3\x01m\x03\x1e\x02\x05\x01\x84\x02.\x02\xfd\x00\xcc\x01\xa4\x01\xec\x02\xd9\x00\x9e\x03\x9a\x00\x95\x03\x1b\x01C\x01\xff\x03H\x00\xb9\x03r\x00\x7f\x01\x1d\x00\xd3\x03{\x01\x9f\x02;\x02\xa4\x01\xed\x02V\x03(\x00y\x01\xa1\x014\x01\x08\x01\xfe\x03t\x00\xad\x01\x94\x01>\x03\xab\x00w\x00\xd8\x02\x15\x02\x12\x02\x06\x00\xca\x01\xe5\x03"\x02\xee\x03N\x01\xd5\x03\x06\x00\xc6\x02\xfe\x01\xb9\x03L\x00\xd9\x01\xad\x03Q\x02\xf8\x00\xec\x03%\x01J\x01R\x02y\x00\xd5\x03\xcd\x00B\x00\x9a\x026\x01\xd2\x02\x96\x00\xde\x03$\x00\x02\x00E\x03/\x03\xd3\x02(\x02\xdf\x01\xb2\x02\xc3\x00\xae\x00\t\x00\x9d\x02\x8d\x01\xc5\x02>\x01(\x02\x13\x00D\x00\x0e\x02@\x00\x99\x01\x1a\x03f\x02s\x00_\x02\x02\x01\x1f\x00\xb7\x00c\x00-\x03\n\x02!\x005\x03\x10\x01\xd9\x00\x1b\x03\xa3\x03\x9f\x02\x04\x02\xda\x01\xf0\x00%\x01\x14\x01\x04\x02\xc7\x00l\x02I\x033\x03\xac\x03\'\x00t\x002\x03`\x01\xe2\x01\x96\x02\xab\x00\xeb\x03\x94\x00\xb3\x01|\x01v\x03n\x01\xbe\x01K\x01*\x03\xb4\x01\x0e\x00\x1f\x01\'\x01\xe9\x01\x82\x02\xf2\x00\xfa\x00a\x01\x01\x00\xbe\x01\xcf\x00\x97\x03\xa4\x01U\x02\xf9\x03\xc2\x02v\x01\xf6\x00\xf4\x02f\x00@\x00\x91\x03_\x03\xc4\x02\xa1\x03\x87\x01=\x01\xf9\x00\xfe\x03\x15\x02\xb9\x01j\x01d\x02\xb0\x02\xc2\x01\xf8\x03k\x01 \x00v\x01\\\x028\x00\r\x01a\x03I\x00\xbd\x00\x0b\x00\xfb\x01\xf1\x02\xec\x02\xd0\x00Z\x01\xcd\x01\xf2\x01\x91\x03w\x02\x90\x00J\x02\xb1\x03c\x02\xe6\x02 \x03]\x01"\x02\xaa\x03P\x01\x1c\x02\x11\x01T\x03\xc7\x00\x10\x01_\x01o\x000\x00\xa5\x02G\x00m\x03\x0e\x00\x83\x00\xaf\x00\x84\x01l\x01\x07\x02\xcb\x03g\x01t\x01\xb3\x01{\x03d\x02\x00\x01b\x00\x8f\x00|\x00s\x03\x93\x02\x83\x00\xe4\x03\x82\x03;\x02q\x01y\x01\xa7\x00U\x020\x02\x1b\x018\x03\x1c\x01\xda\x02\xa9\x00S\x02\xdb\x02-\x02\x84\x00\xa4\x02\xf1\x01\xa2\x02r\x01\xa8\x03R\x02B\x00[\x02\xe7\x00\xaa\x01r\x02\x1e\x01\x00\x01\x97\x01\xc9\x03\x85\x02\x1c\x00\xe9\x03\x7f\x03\xdb\x02\xd7\x025\x012\x03\x9e\x00\x05\x01\x9d\x00\x13\x03\xbc\x01X\x01`\x02\x93\x00i\x03\x8c\x03U\x02\xd4\x02\x9d\x02\'\x01\x8f\x00\n\x00x\x00\x9c\x01~\x03\x00\x01&\x02\x19\x02\x8b\x00\x18\x01g\x03O\x01h\x01%\x03X\x03\xad\x02\x8c\x01\xd0\x02m\x01\x8e\x02\x9b\x00C\x02*\x00p\x01\xaf\x004\x03Y\x02^\x02J\x03\x07\x01e\x02~\x00\xab\x02\x98\x03\x01\x03\x16\x00\x8e\x02\xb2\x00\x0c\x02\xcc\x00\x06\x00z\x01\x9b\x03\xc1\x03b\x01\xb7\x00\x94\x01F\x00\x82\x00\xdd\x01N\x03\xb3\x023\x02\x86\x01\x15\x03\xb7\x01\xf7\x03\x1d\x03\xd1\x03\xa1\x01\x9e\x01\xb1\x01\x1e\x01:\x03i\x02M\x02z\x01\xef\x00Q\x03\xa0\x02\x16\x03\xbf\x00\x11\x03,\x03\xc9\x010\x03*\x01\x11\x02E\x01s\x03\xe0\x00\xa0\x00\xc8\x03\xe5\x03q\x00\xa8\x02\xbd\x03+\x00.\x01\x0f\x00\xa2\x02\x0c\x039\x00\xba\x03D\x00\xce\x00\xfd\x00\xb0\x00!\x009\x01k\x03m\x00f\x02a\x035\x03\x04\x03}\x01\xe8\x01n\x01x\x03\xb8\x03\xd9\x03\xd8\x03\x99\x01#\x00\xcf') is not JSON serializable
[04/Jul/2016 19:13:29 -0700] views        ERROR    Failed to dump data as JSON
Traceback (most recent call last):
  File "/opt/cloudera/parcels/CDH-5.7.0-1.cdh5.7.0.p0.45/lib/hue/apps/hbase/src/hbase/views.py", line 86, in clean
    json.dumps(data)
  File "/usr/lib64/python2.6/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python2.6/json/encoder.py", line 361, in encode
    return encode_basestring_ascii(o)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x88 in position 1033: invalid start byte
```

**Comment by romainr** [comment]
Something like this was fixed in 5.8, but I also believe there are some similar issues not fixed yet (cf. conversation here or on the hue user list)
