### ISSUE TITLE
NOT NULL constraint failed: desktop_document2.is_managed

### ISSUE THREAD

**Issue by qiulp** [cloudera/hue#407]
hi,

my hue version is branch-3.10 ,I got this exception after I excuted a query:
[03/Aug/2016 21:33:44 -0700] access       INFO     127.0.0.1 hue - "POST /notebook/api/execute HTTP/1.1"
[03/Aug/2016 21:33:44 -0700] dbms         DEBUG    Query Server: {'server_name': 'beeswax', 'transport_mode': 'socket', 'server_host': 'cs02', 'server_port': 10000, 'auth_password_used': True, 'http_url': 'http://cs02:10001/cliservice', 'auth_username': 'hue', 'principal': None}
[03/Aug/2016 21:33:44 -0700] thrift_util  DEBUG    Thrift call: <class 'TCLIService.TCLIService.Client'>.ExecuteStatement(args=(TExecuteStatementReq(confOverlay={}, sessionHandle=TSessionHandle(sessionId=THandleIdentifier(secret='\xe0\x1bU\x96x\xc8L\xb5\xbfH\xf4\x04^\xc0*^', guid='\x9e\xe3\x0f\xb6\xcf\x1eO\xa2\x80\x90A\x1c\xf9E\x89\xa0')), runAsync=False, statement='USE `quilp`'),), kwargs={})
[03/Aug/2016 21:33:44 -0700] thrift_util  DEBUG    Thrift call <class 'TCLIService.TCLIService.Client'>.ExecuteStatement returned in 99ms: TExecuteStatementResp(status=TStatus(errorCode=None, errorMessage=None, sqlState=None, infoMessages=None, statusCode=0), operationHandle=TOperationHandle(hasResultSet=False, modifiedRowCount=None, operationType=0, operationId=THandleIdentifier(secret='mBO\x1c\xa7<B\xe1\x86\xd8x\xfa\xc3\xa4\x1c\xe0', guid='w\xfe\xc2\xc3\xaeYCJ\xbb\xe7\x91h\xce\xe6&\xed')))
[03/Aug/2016 21:33:44 -0700] thrift_util  DEBUG    Thrift call: <class 'TCLIService.TCLIService.Client'>.CloseOperation(args=(TCloseOperationReq(operationHandle=TOperationHandle(hasResultSet=False, modifiedRowCount=None, operationType=0, operationId=THandleIdentifier(secret='mBO\x1c\xa7<B\xe1\x86\xd8x\xfa\xc3\xa4\x1c\xe0', guid='w\xfe\xc2\xc3\xaeYCJ\xbb\xe7\x91h\xce\xe6&\xed'))),), kwargs={})
[03/Aug/2016 21:33:44 -0700] thrift_util  DEBUG    Thrift call <class 'TCLIService.TCLIService.Client'>.CloseOperation returned in 25ms: TCloseOperationResp(status=TStatus(errorCode=None, errorMessage=None, sqlState=None, infoMessages=None, statusCode=0))
[03/Aug/2016 21:33:44 -0700] thrift_util  DEBUG    Thrift call: <class 'TCLIService.TCLIService.Client'>.ExecuteStatement(args=(TExecuteStatementReq(confOverlay={}, sessionHandle=TSessionHandle(sessionId=THandleIdentifier(secret='\xe0\x1bU\x96x\xc8L\xb5\xbfH\xf4\x04^\xc0*^', guid='\x9e\xe3\x0f\xb6\xcf\x1eO\xa2\x80\x90A\x1c\xf9E\x89\xa0')), runAsync=True, statement='select * from users'),), kwargs={})
[03/Aug/2016 21:33:44 -0700] thrift_util  DEBUG    Thrift call <class 'TCLIService.TCLIService.Client'>.ExecuteStatement returned in 192ms: TExecuteStatementResp(status=TStatus(errorCode=40000, errorMessage='Error while compiling statement: FAILED: SemanticException org.apache.hadoop.hive.ql.metadata.HiveException: Error in loading storage handler.com.cloudera.kudu.hive.KuduStorageHandler', sqlState='42000', infoMessages=['*org.apache.hive.service.cli.HiveSQLException:Error while compiling statement: FAILED: SemanticException org.apache.hadoop.hive.ql.metadata.HiveException: Error in loading storage handler.com.cloudera.kudu.hive.KuduStorageHandler:17:16', 'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:326', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:102', 'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:171', 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:268', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:410', 'org.apache.hive.service.cli.session.Hi...
[03/Aug/2016 21:33:44 -0700] decorators   ERROR    error running <function execute at 0x7fcda28b1758>
Traceback (most recent call last):
  File "/home/rube/cloudera/hue/desktop/libs/notebook/src/notebook/decorators.py", line 81, in decorator
    return func(*args, **kwargs)
  File "/home/rube/cloudera/hue/desktop/libs/notebook/src/notebook/api.py", line 124, in execute
    history = _historify(notebook, request.user)
  File "/home/rube/cloudera/hue/desktop/libs/notebook/src/notebook/api.py", line 319, in _historify
    is_history=True
  File "/home/rube/cloudera/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/models/manager.py", line 157, in create
    return self.get_queryset().create(**kwargs)
  File "/home/rube/cloudera/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/models/query.py", line 322, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/rube/cloudera/hue/desktop/core/src/desktop/models.py", line 1138, in save
    home_dir = Document2.objects.get_home_directory(self.owner)
  File "/home/rube/cloudera/hue/desktop/core/src/desktop/models.py", line 937, in get_home_directory
    return self.create_user_directories(user)
  File "/home/rube/cloudera/hue/desktop/core/src/desktop/models.py", line 969, in create_user_directories
    home_dir, created = Directory.objects.get_or_create(name=Document2.HOME_DIR, owner=user)
  File "/home/rube/cloudera/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/models/manager.py", line 154, in get_or_create
    return self.get_queryset().get_or_create(**kwargs)
  File "/home/rube/cloudera/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/models/query.py", line 391, in get_or_create
    six.reraise(*exc_info)
  File "/home/rube/cloudera/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/models/query.py", line 383, in get_or_create
    obj.save(force_insert=True, using=self.db)
  File "/home/rube/cloudera/hue/desktop/core/src/desktop/models.py", line 1353, in save
    super(Directory, self).save(*args, **kwargs)
  File "/home/rube/cloudera/hue/desktop/core/src/desktop/models.py", line 1147, in save
    super(Document2, self).save(*args, **kwargs)
  File "/home/rube/cloudera/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/rube/cloudera/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/rube/cloudera/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/rube/cloudera/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/home/rube/cloudera/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/home/rube/cloudera/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/rube/cloudera/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/models/sql/compiler.py", line 903, in execute_sql
    cursor.execute(sql, params)
  File "/home/rube/cloudera/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/rube/cloudera/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/rube/cloudera/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/rube/cloudera/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/backends/sqlite3/base.py", line 452, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: NOT NULL constraint failed: desktop_document2.is_managed
[03/Aug/2016 21:33:46 -0700] access       INFO     127.0.0.1 hue - "GET /jobbrowser/ HTTP/1.1"
[03/Aug/2016 21:33:46 -0700] connectionpool DEBUG    "GET /ws/v1/cluster/apps?limit=10000&user=hue&finalStatus=UNDEFINED HTTP/1.1" 200 None
[03/Aug/2016 21:33:46 -0700] resource     DEBUG    GET Got response: {"apps":null}

Have I missed some configurations?

Regards,
rube.q

**Comment by qiulp** [comment]
aha~~.replaced the default sqlite3  with mysql and solved the problem.
