### ISSUE TITLE
Error at *make apps*

### ISSUE THREAD

**Issue by damiencarol** [cloudera/hue#423]
I have this error when compiling the notebook app
```
Installed /home/hduser/hue-3.11.0/desktop/libs/metadata/src
make[2]: Leaving directory `/home/hduser/hue-3.11.0/desktop/libs/metadata'
make -C libs/notebook env-install
make[2]: Entering directory `/home/hduser/hue-3.11.0/desktop/libs/notebook'
--- Installing notebook into virtual-env
running develop
running egg_info
/home/hduser/hue-3.11.0/build/env/lib/python2.6/site-packages/setuptools/command/egg_info.py:171: DeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  writer = ep.load(installer=installer)
writing requirements to src/notebook.egg-info/requires.txt
writing src/notebook.egg-info/PKG-INFO
writing top-level names to src/notebook.egg-info/top_level.txt
writing dependency_links to src/notebook.egg-info/dependency_links.txt
writing entry points to src/notebook.egg-info/entry_points.txt
writing requirements to src/notebook.egg-info/requires.txt
writing src/notebook.egg-info/PKG-INFO
writing top-level names to src/notebook.egg-info/top_level.txt
writing dependency_links to src/notebook.egg-info/dependency_links.txt
writing entry points to src/notebook.egg-info/entry_points.txt
reading manifest file 'src/notebook.egg-info/SOURCES.txt'
writing manifest file 'src/notebook.egg-info/SOURCES.txt'
running build_ext
Creating /home/hduser/hue-3.11.0/build/env/lib/python2.6/site-packages/notebook.egg-link (link to src)
notebook 3.11.0 is already the active version in easy-install.pth

Installed /home/hduser/hue-3.11.0/desktop/libs/notebook/src
make[2]: Leaving directory `/home/hduser/hue-3.11.0/desktop/libs/notebook'
--- Regenerating database at /home/hduser/hue-3.11.0/desktop/desktop.db
--- Syncing/updating database at /home/hduser/hue-3.11.0/desktop/desktop.db
Traceback (most recent call last):
  File "/home/hduser/hue-3.11.0/build/env/bin/hue", line 9, in <module>
    load_entry_point('desktop==3.11.0', 'console_scripts', 'hue')()
  File "/home/hduser/hue-3.11.0/desktop/core/src/desktop/manage_entry.py", line 59, in entry
    execute_from_command_line(sys.argv)
  File "/home/hduser/hue-3.11.0/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/hduser/hue-3.11.0/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/hduser/hue-3.11.0/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/__init__.py", line 261, in fetch_command
    commands = get_commands()
  File "/home/hduser/hue-3.11.0/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/__init__.py", line 107, in get_commands
    apps = settings.INSTALLED_APPS
  File "/home/hduser/hue-3.11.0/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/hduser/hue-3.11.0/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/hduser/hue-3.11.0/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/hduser/hue-3.11.0/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/hduser/hue-3.11.0/desktop/core/src/desktop/settings.py", line 249, in <module>
    conf.initialize(_desktop_conf_modules, _config_dir)
  File "/home/hduser/hue-3.11.0/desktop/core/src/desktop/lib/conf.py", line 591, in initialize
    conf_data = load_confs(_configs_from_dir(config_dir))
  File "/home/hduser/hue-3.11.0/desktop/core/src/desktop/lib/conf.py", line 523, in load_confs
    for in_conf in conf_source:
  File "/home/hduser/hue-3.11.0/desktop/core/src/desktop/lib/conf.py", line 504, in _configs_from_dir
    conf = configobj.ConfigObj(os.path.join(conf_dir, filename))
  File "/home/hduser/hue-3.11.0/build/env/lib/python2.6/site-packages/configobj-4.6.0-py2.6.egg/configobj.py", line 1219, in __init__
    self._load(infile, configspec)
  File "/home/hduser/hue-3.11.0/build/env/lib/python2.6/site-packages/configobj-4.6.0-py2.6.egg/configobj.py", line 1302, in _load
    raise error
configobj.DuplicateError: Duplicate keyword name at line 806.
make[1]: *** [/home/hduser/hue-3.11.0/desktop/desktop.db] Error 1
make[1]: Leaving directory `/home/hduser/hue-3.11.0/desktop'
make: *** [desktop] Error 2

```

**Comment by damiencarol** [comment]
seems to bee 2 identical keys in hue.ini

=> https://community.mapr.com/docs/DOC-1403
