### ISSUE TITLE
Hue 3.11 Notebook and CSRF

### ISSUE THREAD

**Issue by vishalvpv** [cloudera/hue#428]
Hi,

Installed Hue 3.11 on HDP 2.5. 

Created a notebook and added below spark snippet.
print 1+1+1

On running below error is thrown.
<html> <head> <meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/> <title>Error 400 </title> </head> <body> <h2>HTTP ERROR: 400</h2> <p>Problem accessing /sessions. Reason: <pre> Missing Required Header for CSRF protection.</pre></p> <hr /><i><small>Powered by Jetty://</small></i> </body> </html> (error 400)

Below is the stack trace from the logs
Error running <function create_session at 0x7f73d8d907d0>
Traceback (most recent call last):
  File "/usr/local/hue/desktop/libs/notebook/src/notebook/decorators.py", line 81, in decorator
    return func(_args, *_kwargs)
  File "/usr/local/hue/desktop/libs/notebook/src/notebook/api.py", line 79, in create_session
    response['session'] = get_api(request, session).create_session(lang=session['type'], properties=properties)
  File "/usr/local/hue/desktop/libs/notebook/src/notebook/connectors/spark_shell.py", line 163, in create_session
    response = api.create_session(**props)
  File "/usr/local/hue/apps/spark/src/spark/job_server_api.py", line 101, in create_session
    return self._root.post('sessions', data=json.dumps(properties), contenttype=_JSON_CONTENT_TYPE)
  File "/usr/local/hue/desktop/core/src/desktop/lib/rest/resource.py", line 132, in post
    allow_redirects=allow_redirects, clear_cookies=clear_cookies)
  File "/usr/local/hue/desktop/core/src/desktop/lib/rest/resource.py", line 81, in invoke
    clear_cookies=clear_cookies)
  File "/usr/local/hue/desktop/core/src/desktop/lib/rest/http_client.py", line 173, in execute
    raise self._exc_class(ex)
RestException: <html>
<head>

Had a quick look at the source code. In getapi function in notebook/connectors/base.py original request object is lost.

Any workarounds?

Best Regards,
Vishal

**Comment by vishalvpv** [comment]
Workaround is to disable csrf for livy via ambari.

Best Regards,
Vishal
