### ISSUE TITLE
HUE Installation Error: [ipython[0.10]] Error 1, hue/build/.devtools] Error 2

### ISSUE THREAD

**Issue by kevinguard** [cloudera/hue#453]
I'm trying to build HUE on my laptop and am getting the following error (for make apps):

Note: I have ipython already installed on my computer.

```
--- Installing development tool: ipython[0.10]
/Users/kaveh/Development/hue/build/env/bin/python2.7 /Users/kaveh/Development/hue/build/env/bin/easy_install -f http://archive.cloudera.com/desktop-sdk-python-packages/ \
	   -H pypi.python.org,archive.cloudera.com -qq ipython==0.10
Traceback (most recent call last):
  File "/Users/kaveh/Development/hue/build/env/bin/easy_install", line 9, in <module>
    load_entry_point('setuptools==30.0.0', 'console_scripts', 'easy_install')()
  File "build/bdist.macosx-10.6-intel/egg/setuptools/command/easy_install.py", line 2265, in main
    
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.macosx-10.6-intel/egg/setuptools/command/easy_install.py", line 410, in run
    
  File "build/bdist.macosx-10.6-intel/egg/setuptools/command/easy_install.py", line 665, in easy_install
    
  File "build/bdist.macosx-10.6-intel/egg/setuptools/command/easy_install.py", line 695, in install_item
    
  File "build/bdist.macosx-10.6-intel/egg/setuptools/command/easy_install.py", line 876, in install_eggs
    
  File "build/bdist.macosx-10.6-intel/egg/setuptools/command/easy_install.py", line 1115, in build_and_install
    
  File "build/bdist.macosx-10.6-intel/egg/setuptools/command/easy_install.py", line 1101, in run_setup
    
  File "build/bdist.macosx-10.6-intel/egg/setuptools/sandbox.py", line 251, in run_setup
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.macosx-10.6-intel/egg/setuptools/sandbox.py", line 198, in setup_context
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.macosx-10.6-intel/egg/setuptools/sandbox.py", line 169, in save_modules
  File "build/bdist.macosx-10.6-intel/egg/setuptools/sandbox.py", line 144, in resume
  File "build/bdist.macosx-10.6-intel/egg/setuptools/sandbox.py", line 157, in save_modules
  File "build/bdist.macosx-10.6-intel/egg/setuptools/sandbox.py", line 198, in setup_context
  File "build/bdist.macosx-10.6-intel/egg/setuptools/sandbox.py", line 248, in run_setup
  File "build/bdist.macosx-10.6-intel/egg/setuptools/sandbox.py", line 278, in run
  File "build/bdist.macosx-10.6-intel/egg/setuptools/sandbox.py", line 246, in runner
  File "build/bdist.macosx-10.6-intel/egg/setuptools/sandbox.py", line 47, in _execfile
  File "/var/folders/qx/6xwsdfq14yd536xyz6yg9ytw0000gn/T/easy_install-ffqgX_/ipython-0.10/setup.py", line 213, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.macosx-10.6-intel/egg/setuptools/command/bdist_egg.py", line 152, in run
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.macosx-10.6-intel/egg/setuptools/command/egg_info.py", line 279, in run
  File "build/bdist.macosx-10.6-intel/egg/setuptools/command/egg_info.py", line 306, in find_sources
  File "build/bdist.macosx-10.6-intel/egg/setuptools/command/egg_info.py", line 533, in run
  File "build/bdist.macosx-10.6-intel/egg/setuptools/command/egg_info.py", line 569, in add_defaults
  File "build/bdist.macosx-10.6-intel/egg/setuptools/command/py36compat.py", line 35, in add_defaults
  File "build/bdist.macosx-10.6-intel/egg/setuptools/command/sdist.py", line 147, in _add_defaults_data_files
  File "build/bdist.macosx-10.6-intel/egg/setuptools/command/py36compat.py", line 111, in _add_defaults_data_files
ValueError: too many values to unpack
make[2]: *** [ipython[0.10]] Error 1
make[1]: *** [/Users/kaveh/Development/hue/build/.devtools] Error 2
make: *** [desktop] Error 2
```

**Comment by romainr** [comment]
Do you have the Python 2 dev libs installed?

**Comment by chozee** [comment]
I also had this problem. And I installed 3.8-dev by pyenv

**Comment by attomos** [comment]
@chozee how did you solve it?

**Comment by linbaicome** [comment]
I solved it, use "PREFIX=/data/soft/test/ make install" not "make apps"
