### ISSUE TITLE
Cannot execute hive sql include chinese characters in CDH-5.9.0-1.cdh5.9.0.p0.23

### ISSUE THREAD

**Issue by binyan17** [cloudera/hue#470]
hi,buddy,
We found the same bug in CDH-5.9.0-1.cdh5.9.0.p0.23.
We cannot execute sql in hue.
Can you tell me any solution ,thanks!

Error logs as follow:

[05/Jan/2017 20:16:08 +0800] decorators ERROR Error running <function get_logs at 0x7fa85d805320>
Traceback (most recent call last):
File "/opt/cloudera/parcels/CDH-5.9.0-1.cdh5.9.0.p0.23/lib/hue/desktop/libs/notebook/src/notebook/decorators.py", line 81, in decorator
try:
File "/opt/cloudera/parcels/CDH-5.9.0-1.cdh5.9.0.p0.23/lib/hue/desktop/libs/notebook/src/notebook/api.py", line 276, in get_logs

UnicodeEncodeError: 'ascii' codec can't encode characters in position 147-148: ordinal not in range(128)

**Comment by romainr** [comment]
Please, could you share your query so that we can try ti reproduce it?

**Comment by wemersoncesar** [comment]
Hi guys,

I'm getting the same error with portuguese caracters :

ERROR:

select * from product p  where p.name = "CAPITALIZAÇÃO" limit 100;
decorators   ERROR    Error running <function get_logs at 0x7fb80571ce60>
Traceback (most recent call last):
  File "/opt/cloudera/parcels/CDH-5.9.0-1.cdh5.9.0.p0.23/lib/hue/desktop/libs/notebook/src/notebook/decorators.py", line 81, in decorator
    return func(*args, **kwargs)
  File "/opt/cloudera/parcels/CDH-5.9.0-1.cdh5.9.0.p0.23/lib/hue/desktop/libs/notebook/src/notebook/api.py", line 276, in get_logs
    full_log = str(request.POST.get('full_log', ''))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 162-163: ordinal not in range(128)

**Comment by romainr** [comment]
https://issues.cloudera.org/browse/HUE-4815 Fixed in Hue 3.12 or CDH5.10

**Comment by wemersoncesar** [comment]
Hi!
If you are using CDH-5.9.0, to avoid this problem just click on Cloudera Manager => Hue => Configuration, type default_site_encoding and change to UTF-8 or another.
Romainr, Thanks!
