### ISSUE TITLE
Hue make apps failing to complete due to desktop.db error

### ISSUE THREAD

**Issue by maffsojah** [cloudera/hue#471]
I am using Ubuntu 16.04 amd64 and after using the command _make apps_ in the **hue** directory, I am getting the following error. 

`Installed /home/maffsojah/hue/desktop/libs/notebook/src
make[2]: Leaving directory '/home/maffsojah/hue/desktop/libs/notebook'
--- Regenerating database at /home/maffsojah/hue/desktop/desktop.db
--- Syncing/updating database at /home/maffsojah/hue/desktop/desktop.db
[09/Jan/2017 12:10:24 +0000] settings     DEBUG    DESKTOP_DB_TEST_NAME SET: /home/maffsojah/hue/desktop/desktop-test.db
[09/Jan/2017 12:10:24 +0000] settings     DEBUG    DESKTOP_DB_TEST_USER SET: hue_test
Traceback (most recent call last):
  File "/home/maffsojah/hue/build/env/bin/hue", line 9, in <module>
    load_entry_point('desktop==3.11.0', 'console_scripts', 'hue')()
  File "/home/maffsojah/hue/desktop/core/src/desktop/manage_entry.py", line 59, in entry
    execute_from_command_line(sys.argv)
  File "/home/maffsojah/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/maffsojah/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/maffsojah/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/maffsojah/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/management/base.py", line 284, in execute
    self.validate()
  File "/home/maffsojah/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/management/base.py", line 310, in validate
    num_errors = get_validation_errors(s, app)
  File "/home/maffsojah/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/management/validation.py", line 34, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/home/maffsojah/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/models/loading.py", line 196, in get_app_errors
    self._populate()
  File "/home/maffsojah/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/models/loading.py", line 78, in _populate
    self.load_app(app_name)
  File "/home/maffsojah/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/home/maffsojah/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/maffsojah/hue/desktop/core/src/desktop/models.py", line 42, in <module>
    from desktop.lib.exceptions_renderable import PopupException
  File "/home/maffsojah/hue/desktop/core/src/desktop/lib/exceptions_renderable.py", line 28, in <module>
    import desktop.lib.django_util
  File "/home/maffsojah/hue/desktop/core/src/desktop/lib/django_util.py", line 40, in <module>
    import desktop.lib.thrift_util
  File "/home/maffsojah/hue/desktop/core/src/desktop/lib/thrift_util.py", line 25, in <module>
    import sasl
  File "/home/maffsojah/hue/build/env/lib/python2.7/site-packages/sasl-0.1.1-py2.7-linux-x86_64.egg/sasl/__init__.py", line 1, in <module>
    from sasl.saslwrapper import *
  File "/home/maffsojah/hue/build/env/lib/python2.7/site-packages/sasl-0.1.1-py2.7-linux-x86_64.egg/sasl/saslwrapper.py", line 7, in <module>
    import _saslwrapper
ImportError: /home/maffsojah/hue/build/env/lib/python2.7/site-packages/sasl-0.1.1-py2.7-linux-x86_64.egg/_saslwrapper.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE
Makefile:93: recipe for target '/home/maffsojah/hue/desktop/desktop.db' failed
make[1]: *** [/home/maffsojah/hue/desktop/desktop.db] Error 1
make[1]: Leaving directory '/home/maffsojah/hue/desktop'
Makefile:149: recipe for target 'desktop' failed
make: *** [desktop] Error 2
`

**Comment by romainr** [comment]
Did you install all the dev packages? https://github.com/cloudera/hue#development-prerequisites

**Comment by cpgonzal** [comment]
I also have the same error in make apps under Ubuntu 16....and I have checked all development requisites.
However, in Ubuntu 14 there is no problem...Is this a bug?

**Comment by maffsojah** [comment]
sorry for replying late @romainr , I installed all the packages but nothing is working. I had since continued using the terminal instead of Hue

**Comment by drag0nglass** [comment]
Finally figure this out. 
That is, to `make apps`, the ini configuration file in desktop/conf/ shall be the same as the default template.
Simply run `rm -f desktop/conf/*.ini && cp desktop/conf/pseudo-distributed.ini.tmpl desktop/conf/pseudo-distributed.ini` before `make apps` will do the job.

**Comment by maffsojah** [comment]
Hi @drag0nglass, I have failed to reproduce the issue since I am no longer using that setup. If this has worked for you on the same issue then your solution should close the issue. I'll wait for your update before proceeding.
