### ISSUE TITLE
JA009 Oozie error

### ISSUE THREAD

**Issue by roymwickham** [cloudera/hue#477]
I am trying to run a basic hiveQL script through the Hue Oozie  GUI. I keep running into this error:

JA009: Cannot initialize Cluster. Please check your configuration for mapreduce.framework.name and the correspond server addresses.

Research suggests that this could be due to bad format of nameNode in the job.properties file.
Mine looks like this:
oozie.use.system.libpath=True
security_enabled=False
dryrun=True
jobTracker=servername.domainname:8032
nameNode=DEVNNHA

My question is how do I change the way the nameNode is being generated in the job.properties file when running Ozzie through Hue?

**Comment by romainr** [comment]
Same as https://community.cloudera.com/t5/Batch-Processing-and-Workflow/CDH-5-1-2-Oozie-cannot-initialize-cluster-error-JA009/td-p/21678?

**Comment by jomach** [comment]
I have the same problem. I think this is a HUE Bug. because I can start the job over the command line and changing it to hdfs://namenode...

**Comment by romainr** [comment]
Did you set the [hadoop] section in the hue.ini?

**Comment by jomach** [comment]
Yes, like this : 

 [[[default]]]
      # Enter the filesystem uri
      fs_defaultfs=hdfs://SOMENAME

      # NameNode logical name.
      logical_name=SOMENAME

Can it be that it is picking up the logical_name instead of fs_defaultfs ? I'm getting exactly that exception: `2017-07-25 09:14:33,887  WARN FileSystem:343 - SERVER[xxx] "SOMENAME" is a deprecated filesystem name. Use "hdfs://SOMENAME/" instead.
2017-07-25 09:14:33,891  INFO Cluster:113 - SERVER[xxx] Failed to use org.apache.hadoop.mapred.YarnClientProtocolProvider due to error:
java.lang.RuntimeException: Error in instantiating YarnClient
        at org.apache.hadoop.mapred.YARNRunner.<init>(YARNRunner.java:140)
        at org.apache.hadoop.mapred.YARNRunner.<init>(YARNRunner.java:122)
        at org.apache.hadoop.mapred.YARNRunner.<init>(YARNRunner.java:112)
        at org.apache.hadoop.mapred.YarnClientProtocolProvider.create(YarnClientProtocolProvider.java:34)
        at org.apache.hadoop.mapreduce.Cluster.initialize(Cluster.java:95)
        at org.apache.hadoop.mapreduce.Cluster.<init>(Cluster.java:82)
        at org.apache.hadoop.mapreduce.Cluster.<init>(Cluster.java:75)
        at org.apache.hadoop.mapred.JobClient.init(JobClient.java:475)
        at org.apache.hadoop.mapred.JobClient.<init>(JobClient.java:454)
        at org.apache.oozie.service.HadoopAccessorService$3.run(HadoopAccessorService.java:526)
        at org.apache.oozie.service.HadoopAccessorService$3.run(HadoopAccessorService.java:524)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1724)
        at org.apache.oozie.service.HadoopAccessorService.createJobClient(HadoopAccessorService.java:524)
        at org.apache.oozie.action.hadoop.JavaActionExecutor.createJobClient(JavaActionExecutor.java:1416)
        at org.apache.oozie.action.hadoop.JavaActionExecutor.submitLauncher(JavaActionExecutor.java:1137)
        at org.apache.oozie.action.hadoop.JavaActionExecutor.start(JavaActionExecutor.java:1373)
        at org.apache.oozie.command.wf.ActionStartXCommand.execute(ActionStartXCommand.java:232)
        at org.apache.oozie.command.wf.ActionStartXCommand.execute(ActionStartXCommand.java:63)
        at org.apache.oozie.command.XCommand.call(XCommand.java:287)
        at org.apache.oozie.service.CallableQueueService$CompositeCallable.call(CallableQueueService.java:331)
        at org.apache.oozie.service.CallableQueueService$CompositeCallable.call(CallableQueueService.java:260)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.oozie.service.CallableQueueService$CallableWrapper.run(CallableQueueService.java:178)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.fs.UnsupportedFileSystemException: DBAHNHDP1: URI configured via fs.defaultFS carries no scheme
        at org.apache.hadoop.fs.FileContext.getFileContext(FileContext.java:478)
        at org.apache.hadoop.mapred.YARNRunner.<init>(YARNRunner.java:138)
        ... 27 more`

**Comment by jomach** [comment]
So I just tested it and it is a bug imho
My cluster has the following config:
HDP 2.5
Kerberos active
hue 3.12

if logical name does not have logical_name=hdfs://DBAHNHDP1 it does not work.
