### ISSUE TITLE
Problem installing Hue on Mac OS Sierra 10.12.3

### ISSUE THREAD

**Issue by roman-burdakov** [cloudera/hue#481]
I'm getting an error during dashboard installation. It starts with ipdb, but even if I comment it out from desktop/devtools.mk I get the same error with next dependency. Removing version also doesn't help. Partial stack trace.

```
...
/Applications/Xcode.app/Contents/Developer/usr/bin/make ipython[0.10] nose[0.11.3] coverage[3.7.1] nosetty[0.4] werkzeug[0.6] windmill[1.3] pylint[0.28.0]
--- Installing development tool: ipython[0.10]
/other/javaDev/tools/hue/build/env/bin/python2.7 /other/javaDev/tools/hue/build/env/bin/easy_install -f http://archive.cloudera.com/desktop-sdk-python-packages/ \
	   -H pypi.python.org,archive.cloudera.com -qq ipython==0.10
Traceback (most recent call last):
  File "/other/javaDev/tools/hue/build/env/bin/easy_install", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 2265, in main
    **kw
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 410, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 665, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 695, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 876, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1115, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1101, in run_setup
    run_setup(setup_script, args)
  File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 251, in run_setup
    raise
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 144, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 248, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 278, in run
    return func()
  File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 246, in runner
    _execfile(setup_script, ns)
  File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/var/folders/fb/h_sz_lsn4j11dbz4svd3p1f5sf1b7x/T/easy_install-Ed27Ik/ipython-0.10/setup.py", line 213, in <module>
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 152, in run
    self.run_command("egg_info")
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 279, in run
    self.find_sources()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 306, in find_sources
    mm.run()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 533, in run
    self.add_defaults()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 569, in add_defaults
    sdist.add_defaults(self)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 35, in add_defaults
    self._add_defaults_data_files()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/sdist.py", line 147, in _add_defaults_data_files
    sdist_add_defaults._add_defaults_data_files(self)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 111, in _add_defaults_data_files
    dirname, filenames = item
ValueError: too many values to unpack
make[2]: *** [ipython[0.10]] Error 1
make[1]: *** [/other/javaDev/tools/hue/build/.devtools] Error 2
make: *** [desktop] Error 2
```
notice i don't have ipdb in the list. I removed it to see if I get the same error with next dependency and I did. Please advise on solution.

**Comment by romainr** [comment]
To be sure, you are trying on a Mac? ( Yosemite (10.10) or El Capitan (10.11))

http://gethue.com/start-developing-hue-on-a-mac-in-a-few-minutes/

**Comment by roman-burdakov** [comment]
Yes, I'm using Mac, but I'm on Sierra 10.12.3. I have all required libraries installed. Also, I have completed installation by excluding desktop/devtools.mk from build steps, by means of commenting out corresponding parts in desktop/Makefile file. It does start, but I see some configuration errors which I'm now going through. I'm not sure if excluding devtools can affect my work.

**Comment by romainr** [comment]
Latest http://cloudera.github.io/hue/latest/admin-manual/manual.html#dependencies

**Comment by cryptoe** [comment]
build/env/bin/python -m pip install setuptools==28.6.1

Try this. Looks like a bug in easy install.
