### ISSUE TITLE
In Hue3.9 Shell Action argument, single quote was transferred

### ISSUE THREAD

**Issue by xinghalo** [cloudera/hue#484]
I drag the shell action , bug countered an error!

my workflow like this!
```
<workflow-app name="My_Workflow" xmlns="uri:oozie:workflow:0.5">
    <start to="shell-6eb7"/>
    <kill name="Kill">
        <message>操作失败，错误消息[${wf:errorMessage(wf:lastErrorNode())}]</message>
    </kill>
    <action name="shell-958f">
        <shell xmlns="uri:oozie:shell-action:0.1">
            <job-tracker>${jobTracker}</job-tracker>
            <name-node>${nameNode}</name-node>
            <exec>echo</exec>
              <argument>${wf:actionData(shell-6eb7).time}</argument>
              <capture-output/>
        </shell>
        <ok to="End"/>
        <error to="Kill"/>
    </action>
    <action name="shell-6eb7">
        <shell xmlns="uri:oozie:shell-action:0.1">
            <job-tracker>${jobTracker}</job-tracker>
            <name-node>${nameNode}</name-node>
            <exec>property.sh</exec>
            <file>/xhl/property.sh#property.sh</file>
              <capture-output/>
        </shell>
        <ok to="shell-958f"/>
        <error to="Kill"/>
    </action>
    <end name="End"/>
</workflow-app>
```
can i rename the first action to resolve this problerm.
```
javax.servlet.jsp.el.ELException: Encountered "eb7", expected one of [".", ">", "gt", "<", "lt", "==", "eq", "<=", "le", ">=", "ge", "!=", "ne", ")", ",", "[", "+", "-", "*", "/", "div", "%", "mod", "and", "&&", "or", "||", "?"]
	at org.apache.commons.el.ExpressionEvaluatorImpl.parseExpressionString(ExpressionEvaluatorImpl.java:320)
	at org.apache.commons.el.ExpressionEvaluatorImpl.evaluate(ExpressionEvaluatorImpl.java:250)
	at org.apache.commons.el.ExpressionEvaluatorImpl.evaluate(ExpressionEvaluatorImpl.java:190)
	at org.apache.oozie.util.ELEvaluator.evaluate(ELEvaluator.java:204)
	at org.apache.oozie.command.wf.ActionStartXCommand.execute(ActionStartXCommand.java:192)
	at org.apache.oozie.command.wf.ActionStartXCommand.execute(ActionStartXCommand.java:63)
	at org.apache.oozie.command.XCommand.call(XCommand.java:286)
	at org.apache.oozie.command.XCommand.call(XCommand.java:356)
	at org.apache.oozie.command.wf.SignalXCommand.execute(SignalXCommand.java:459)
	at org.apache.oozie.command.wf.SignalXCommand.execute(SignalXCommand.java:82)
	at org.apache.oozie.command.XCommand.call(XCommand.java:286)
	at org.apache.oozie.command.XCommand.call(XCommand.java:356)
	at org.apache.oozie.command.wf.ActionEndXCommand.execute(ActionEndXCommand.java:280)
	at org.apache.oozie.command.wf.ActionEndXCommand.execute(ActionEndXCommand.java:61)
	at org.apache.oozie.command.XCommand.call(XCommand.java:286)
	at org.apache.oozie.command.XCommand.call(XCommand.java:356)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:244)
	at org.apache.oozie.command.wf.ActionCheckXCommand.execute(ActionCheckXCommand.java:56)
	at org.apache.oozie.command.XCommand.call(XCommand.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.oozie.service.CallableQueueService$CallableWrapper.run(CallableQueueService.java:178)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by romainr** [comment]
${wf:actionData('shell-6eb7').time} does not work?

**Comment by xinghalo** [comment]
when I use this `${wf:actionData('shell-6eb7').time}` , bug the `'` was transffered too, like this  ： 
```
<argument>${wf:actionData(&#39;shell-6eb7&#39;).time}</argument>
```

**Comment by xinghalo** [comment]
my hue version is 3.9

**Comment by xinghalo** [comment]
@romainr aha! the `&#39;` doesn't matter, it won't make a mistake. My failed is other reason.

Thanks for your reply!
