### ISSUE TITLE
Export CSV in Hue 3.12

### ISSUE THREAD

**Issue by sanketplus** [cloudera/hue#485]
Hi, I am using Hue 3.12 built from source. while executing queries using notebook, there is no option to save/export results as CSV. I modified HTML and make the export button visible but it says:

```
[01/Mar/2017 05:51:55 -0800] middleware   INFO     Processing exception: Downloading is not supported yet: Traceback (most recent call last):
  File "/usr/local/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/usr/local/hue/desktop/libs/notebook/src/notebook/decorators.py", line 55, in decorate
    return view_func(request, *args, **kwargs)
  File "/usr/local/hue/desktop/libs/notebook/src/notebook/views.py", line 271, in download
    return get_api(request, snippet).download(notebook, snippet, file_format)
  File "/usr/local/hue/desktop/libs/notebook/src/notebook/connectors/jdbc.py", line 123, in download
    raise PopupException('Downloading is not supported yet')
PopupException: Downloading is not supported yet
```

What can be done for this? Do I have to install older version? I am executing Phoenix.queries.

**Comment by sanketplus** [comment]
I tried same with 3.10 and it says he same. Looks like there is no Downloading support for JDBC api (https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/connectors/jdbc.py#L122). When can we expect that? 

And also is there a way around this? I want to get results out in CSV format. 

Thanks.

**Comment by romainr** [comment]
Same as the other answers: https://issues.cloudera.org/browse/HUE-3996

**Comment by sanketplus** [comment]
thanks @romainr it'll be great if you could tell me estimated ETA for that.

**Comment by sanketplus** [comment]
https://twitter.com/gethue/status/837333447504863232
Thanks!

**Comment by rohit-nsit08** [comment]
This applies to only rdbms interface right? and not the jdbc interface as I can still see not implemented message in Hue 4+

**Comment by romainr** [comment]
Yes, JDBC is not implemented yet 
https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/connectors/jdbc.py#L122

https://github.com/cloudera/hue/issues/623
