### ISSUE TITLE
Hue connect to hive GetSchemas error

### ISSUE THREAD

**Issue by JasonBian** [cloudera/hue#515]
when I use Hue master branch to connect Hiveserver2, the GetSchemas request get error.
My env Info: HDP 2.5.0 + Hive1.2，
The error message for the Hiveserver2 as below:
`2017-04-13 04:30:04,796 WARN  [HiveServer2-Handler-Pool: Thread-316]: thrift.ThriftCLIService (ThriftCLIService.java:GetSchemas(555)) - Error getting schemas: 
org.apache.hive.service.cli.HiveSQLException: Invalid SessionHandle: SessionHandle [64912dd3-e3a1-496f-a82a-4abcf04301d6]
	at org.apache.hive.service.cli.session.SessionManager.getSession(SessionManager.java:341)
	at org.apache.hive.service.cli.CLIService.getSchemas(CLIService.java:336)
	at org.apache.hive.service.cli.thrift.ThriftCLIService.GetSchemas(ThriftCLIService.java:550)
	at org.apache.hive.service.cli.thrift.TCLIService$Processor$GetSchemas.getResult(TCLIService.java:1377)
	at org.apache.hive.service.cli.thrift.TCLIService$Processor$GetSchemas.getResult(TCLIService.java:1362)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
	at org.apache.hive.service.auth.TSetIpAddressProcessor.process(TSetIpAddressProcessor.java:56)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by romainr** [comment]
Note about Hive and HDP 2.5+: Since at least HDP 2.5, the default Hive shipped won’t work with Hue unless you change the property:

hive.server2.parallel.ops.in.session=true

**Comment by JasonBian** [comment]
THX,got it

**Comment by hminle** [comment]
@romainr @JasonBian  So when we set hive.server2.parallel.ops.in.session=true, and using tez engine --> it will run multiple DAG in one DAG App Master, right? (Assume I submit multiple queries, one query / one DAG)
