### ISSUE TITLE
Meet 'cffi.api.CDefError: parse error' when make apps

### ISSUE THREAD

**Issue by WangKB** [cloudera/hue#519]
hello:
      when I make 3.12 version project ,I met the follow error:

make[1]: Entering directory `/home/sheshou/hue-3.12.0/desktop'
make -C core env-install
make[2]: Entering directory `/home/sheshou/hue-3.12.0/desktop/core'
--- Building egg for cryptography-1.3.1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/sheshou/hue-3.12.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 238, in run_setup
    raise
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/sheshou/hue-3.12.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 191, in setup_context
    yield
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/sheshou/hue-3.12.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 162, in save_modules
    saved_exc.resume()
  File "/home/sheshou/hue-3.12.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 137, in resume
    compat.reraise(type, exc, self._tb)
  File "/home/sheshou/hue-3.12.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 150, in save_modules
    yield saved
  File "/home/sheshou/hue-3.12.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 191, in setup_context
    yield
  File "/home/sheshou/hue-3.12.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 235, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/home/sheshou/hue-3.12.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 265, in run
    return func()
  File "/home/sheshou/hue-3.12.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 234, in runner
    _execfile(setup_script, ns)
  File "/home/sheshou/hue-3.12.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "setup.py", line 335, in <module>
    **keywords_with_side_effects(sys.argv)
  File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/sheshou/hue-3.12.0/build/env/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/home/sheshou/hue-3.12.0/build/env/lib/python2.7/site-packages/setuptools/dist.py", line 325, in finalize_options
    ep.load()(self, ep.name, value)
  File "/usr/lib64/python2.7/site-packages/cffi/setuptools_ext.py", line 187, in cffi_modules
    add_cffi_module(dist, cffi_module)
  File "/usr/lib64/python2.7/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
    execfile(build_file_name, mod_vars)
  File "/usr/lib64/python2.7/site-packages/cffi/setuptools_ext.py", line 25, in execfile
    exec(code, glob, glob)
  File "src/_cffi_src/build_constant_time.py", line 26, in <module>
    extra_link_args=extra_link_args(compiler_type()),
  File "src/_cffi_src/utils.py", line 73, in build_ffi
    ffi.cdef(cdef_source)
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 105, in cdef
    self._cdef(csource, override=override, packed=packed)
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 119, in _cdef
    self._parser.parse(csource, override=override, **options)
  File "/usr/lib64/python2.7/site-packages/cffi/cparser.py", line 299, in parse
    self._internal_parse(csource)
  File "/usr/lib64/python2.7/site-packages/cffi/cparser.py", line 304, in _internal_parse
    ast, macros, csource = self._parse(csource)
  File "/usr/lib64/python2.7/site-packages/cffi/cparser.py", line 262, in _parse
    self.convert_pycparser_error(e, csource)
  File "/usr/lib64/python2.7/site-packages/cffi/cparser.py", line 291, in convert_pycparser_error
    raise api.CDefError(msg)
cffi.api.CDefError: parse error
:7:1: Illegal character '\r'

I'm using centos 7.2.
Waiting for your help ,thanks.

**Comment by WangKB** [comment]
Problem solved, it is caused by difference between win's and unix's line feed. I edit some file in hue-3.12.0/desktop/core and the file's line feed style turn to win's style, just change it back and everything is ok.
