### ISSUE TITLE
TFetchResultsResp(status=TStatus(errorCode=0, errorMessage='Expected state FINISHED, but found RUNNING', sqlState=None, in

### ISSUE THREAD

**Issue by escapeCarthage** [cloudera/hue#535]
when i fetch result ,I got this error:

[17/May/2017 06:28:10 +0000] middleware   INFO     Processing exception: Bad status for request TFetchResultsReq(fetchType=0, operationHandle=TOperationHandle(hasResultSet=True, modifiedRowCount=None, operationType=0, operationId=THandleIdentifier(secret='-\xe9\xae-\xa1\xb1B\x8f\x85\xa4\xf3T\xc7\x99*\x9d', guid='{\xb7\xb0;\xc5\xd3F\x7f\x95\x1c\x0b\x1e%\xf6K\xf5')), orientation=0, maxRows=100):
TFetchResultsResp(status=TStatus(errorCode=0, errorMessage='Expected state FINISHED, but found RUNNING', sqlState=None, infoMessages=['*org.apache.hive.service.cli.HiveSQLException:Expected state FINISHED, but found RUNNING:26:25', 'org.apache.hive.service.cli.operation.Operation:assertState:Operation.java:189', 'org.apache.hive.service.cli.operation.SQLOperation:getNextRowSet:SQLOperation.java:348', 'org.apache.hive.service.cli.operation.OperationManager:getOperationNextRowSet:OperationManager.java:275', 'org.apache.hive.service.cli.session.HiveSessionImpl:fetchResults:HiveSessionImpl.java:751', 'sun.reflect.GeneratedMethodAccessor16:invoke::-1', 'sun.reflect.DelegatingMethodAccessorImpl:invoke:DelegatingMethodAccessorImpl.java:43', 'java.lang.reflect.Method:invoke:Method.java:606', 'org.apache.hive.service.cli.session.HiveSessionProxy:invoke:HiveSessionProxy.java:78', 'org.apache.hive.service.cli.session.HiveSessionProxy:access$000:HiveSessionProxy.java:36', 'org.apache.hive.service.cli.session.HiveSessionProxy$1:run:HiveSessionProxy.java:63', 'java.security.AccessController:doPrivileged:AccessController.java:-2', 'javax.security.auth.Subject:doAs:Subject.java:415', 'org.apache.hadoop.security.UserGroupInformation:doAs:UserGroupInformation.java:1693', 'org.apache.hive.service.cli.session.HiveSessionProxy:invoke:HiveSessionProxy.java:59', 'com.sun.proxy.$Proxy25:fetchResults::-1', 'org.apache.hive.service.cli.CLIService:fetchResults:CLIService.java:438', 'org.apache.hive.service.cli.thrift.ThriftCLIService:FetchResults:ThriftCLIService.java:689', 'org.apache.hive.service.cli.thrift.TCLIService$Processor$FetchResults:getResult:TCLIService.java:1553', 'org.apache.hive.service.cli.thrift.TCLIService$Processor$FetchResults:getResult:TCLIService.java:1538', 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:285', 'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1145', 'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:615', 'java.lang.Thread:run:Thread.java:745'], statusCode=3), results=None, hasMoreRows=None): Traceback (most recent call last):
  File "/home/test/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/test/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/test/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/home/test/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/test/hue/desktop/libs/notebook/src/notebook/api.py", line 171, in fetch_result_data_no
    response['result'] = get_api(request, snippet).fetch_result(notebook, snippet, rows, start_over)
  File "/home/test/hue/desktop/libs/notebook/src/notebook/connectors/hiveserver2.py", line 81, in decorator
    return func(*args, **kwargs)
  File "/home/test/hue/desktop/libs/notebook/src/notebook/connectors/hiveserver2.py", line 290, in fetch_result
    raise QueryError(ex)
QueryError

And I find the code errror is located at here(hive_server2_lib.py):

def fetch_result(self, operation_handle, orientation=TFetchOrientation.FETCH_FIRST, max_rows=1000):
    if operation_handle.hasResultSet :
      fetch_req = TFetchResultsReq(operationHandle=operation_handle, orientation=orientation, maxRows=max_rows)
      res = self.call(self._client.FetchResults, fetch_req)
   
 So,Can you tell me why?

**Comment by romainr** [comment]
Note about Hive and HDP 2.5+: Since at least HDP 2.5, the default Hive shipped won’t work with Hue unless you change the property:

hive.server2.parallel.ops.in.session=true

?

**Comment by caengcjd** [comment]
Oh no,it doesn't work at all!.
Can you give me more hints?
