### ISSUE TITLE
No module named setuptools_ext

### ISSUE THREAD

**Issue by maxiulin** [cloudera/hue#537]
hi,when i make apps,I find errors ! please help me
Installed /hue-release-3.12.0/desktop/core/ext-py/cryptography-1.3.1/.eggs/cffi-1.10.0-py2.7-linux-x86_64.egg
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/hue-release-3.12.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 238, in run_setup
    raise
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/hue-release-3.12.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 191, in setup_context
    yield
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/hue-release-3.12.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 162, in save_modules
    saved_exc.resume()
  File "/hue-release-3.12.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 137, in resume
    compat.reraise(type, exc, self._tb)
  File "/hue-release-3.12.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 150, in save_modules
    yield saved
  File "/hue-release-3.12.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 191, in setup_context
    yield
  File "/hue-release-3.12.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 235, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/hue-release-3.12.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 265, in run
    return func()
  File "/hue-release-3.12.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 234, in runner
    _execfile(setup_script, ns)
  File "/hue-release-3.12.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "setup.py", line 335, in <module>
    **keywords_with_side_effects(sys.argv)
  File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
    _setup_distribution = dist = klass(attrs)
  File "/hue-release-3.12.0/build/env/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/hue-release-3.12.0/build/env/lib/python2.7/site-packages/setuptools/dist.py", line 325, in finalize_options
    ep.load()(self, ep.name, value)
  File "/hue-release-3.12.0/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2310, in load
    return self.resolve()
  File "/hue-release-3.12.0/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named setuptools_ext
make[2]: *** [/hue-release-3.12.0/desktop/core/build/cryptography-1.3.1/egg.stamp] Error 1
make[2]: Leaving directory `/hue-release-3.12.0/desktop/core'
make[1]: *** [.recursive-env-install/core] Error 2
make[1]: Leaving directory `/hue-release-3.12.0/desktop'
make: *** [desktop] Error 2

**Comment by romainr** [comment]
Did you install the python-dev packages? https://github.com/cloudera/hue#development-prerequisites

**Comment by maxiulin** [comment]
Hello，the version of my Linux  is centos7.2，the  python-dev packages is not available，I installed the python-devel，is this？

**Comment by romainr** [comment]
Yes, should be good, look at the 'CentOS/RHEL' section

**Comment by fishermancome** [comment]
you can use pip install cffi == 1.10.0  and it will ok. In my opiniom ,when some wrong like this, we can pip install dependencies at local and then make apps  , it will success.
