### ISSUE TITLE
Operation timed when running hive query

### ISSUE THREAD

**Issue by jai2605** [cloudera/hue#539]
Hi,

Environment Hue-3.11 HiveServer2-2.1 Amazon EMR cluster

I'm able to run a query via hive cli without any issue, but when i run using hue UI facing operation timed out error. Seeing below error in hive logs when timed out occurs. 

2017-05-23T06:59:26,732 WARN  [HiveServer2-Handler-Pool: Thread-57([])]: thrift.ThriftCLIService (ThriftCLIService.java:GetOperationStatus(647)) - Error getting operation status:
org.apache.hive.service.cli.HiveSQLException: Invalid OperationHandle: OperationHandle [opType=EXECUTE_STATEMENT, getHandleIdentifier()=4daab882-dbee-494e-98ea-7d80da1cae23]
        at org.apache.hive.service.cli.operation.OperationManager.getOperation(OperationManager.java:193) ~[hive-service-2.1.1-amzn-0.jar:2.1.1-amzn-0]
        at org.apache.hive.service.cli.CLIService.getOperationStatus(CLIService.java:425) ~[hive-service-2.1.1-amzn-0.jar:2.1.1-amzn-0]
        at org.apache.hive.service.cli.thrift.ThriftCLIService.GetOperationStatus(ThriftCLIService.java:633) [hive-service-2.1.1-amzn-0.jar:2.1.1-amzn-0]
        at org.apache.hive.service.rpc.thrift.TCLIService$Processor$GetOperationStatus.getResult(TCLIService.java:1637) [hive-exec-2.1.1-amzn-0.jar:2.1.1-amzn-0]
        at org.apache.hive.service.rpc.thrift.TCLIService$Processor$GetOperationStatus.getResult(TCLIService.java:1622) [hive-exec-2.1.1-amzn-0.jar:2.1.1-amzn-0]
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39) [hive-exec-2.1.1-amzn-0.jar:2.1.1-amzn-0]
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39) [hive-exec-2.1.1-amzn-0.jar:2.1.1-amzn-0]
        at org.apache.hive.service.auth.TSetIpAddressProcessor.process(TSetIpAddressProcessor.java:56) [hive-service-2.1.1-amzn-0.jar:2.1.1-amzn-0]
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286) [hive-exec-2.1.1-amzn-0.jar:2.1.1-amzn-0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

Thank you,
Jai

**Comment by cricket007** [comment]
Hello @jai2605 

The Hive CLI does not touch HiveServer2 Thrift Server, please retry your query from the terminal using the Beeline CLI.
