### ISSUE TITLE
Api Error: Invalid method name: 'getTableNames'

### ISSUE THREAD

**Issue by maxiulin** [cloudera/hue#540]
hello,teacher
when i use the hbase on HUE,i make mistakes。please help me ,thanks!
for  exmple
[24/May/2017 11:08:55 +0800] middleware   INFO     Processing exception: Api Error: Invalid method name: 'getTableNames': Traceback (most recent call last):
  File "/hue-release-3.6.0/build/env/lib/python2.7/site-packages/Django-1.4.5-py2.7.egg/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/hue-release-3.6.0/apps/hbase/src/hbase/views.py", line 77, in api_router
    return api_dump(HbaseApi().query(*url_params))
  File "/hue-release-3.6.0/apps/hbase/src/hbase/api.py", line 50, in query
    raise PopupException(_("Api Error: %s") % e.message)
PopupException: Api Error: Invalid method name: 'getTableNames'
[24/May/2017 11:08:55 +0800] thrift_util  INFO     Thrift saw an application exception: Invalid method name: 'getTableNames'
[24/May/2017 11:08:55 +0800] thrift_util  ERROR    Thrift saw exception (this may be expected).
Traceback (most recent call last):
  File "/hue-release-3.6.0/desktop/core/src/desktop/lib/thrift_util.py", line 371, in wrapper
    ret = res(*args, **kwargs)
  File "/hue-release-3.6.0/apps/hbase/src/hbase/server/../../../gen-py/hbased/Hbase.py", line 788, in getTableNames
    return self.recv_getTableNames()
  File "/hue-release-3.6.0/apps/hbase/src/hbase/server/../../../gen-py/hbased/Hbase.py", line 803, in recv_getTableNames
    raise x
TApplicationException: Invalid method name: 'getTableNames'
[24/May/2017 11:08:55 +0800] thrift_util  DEBUG    Thrift call: hbased.Hbase.Client.getTableNames(args=(), kwargs={})

**Comment by romainr** [comment]
Any change you use a more recent Hue?

**Comment by maxiulin** [comment]
sorry，my Hue is 3.6，because 3.12 not make apps correctly on centos 7.2，so i use the 3.6
