### ISSUE TITLE
dbproxy CLASSPATH still not set in Hue 3.12

### ISSUE THREAD

**Issue by foscraig** [cloudera/hue#549]
I'm getting the same issue as described in PR #458 with the updated code. hue.ini has the correct setting: 
```[notebook]
  dbproxy_extra_classpath = /usr/lib/presto/presto-jdbc/*
```
But this is the error log I'm seeing:

```
decorators   ERROR    Error running <function create_session at 0x7f689c025668>
Traceback (most recent call last):
  File "/usr/lib/hue/desktop/libs/notebook/src/notebook/decorators.py", line 82, in decorator
    return func(*args, **kwargs)
  File "/usr/lib/hue/desktop/libs/notebook/src/notebook/api.py", line 81, in create_session
    response['session'] = get_api(request, session).create_session(lang=session['type'], properties=properties)
  File "/usr/lib/hue/desktop/libs/notebook/src/notebook/connectors/base.py", line 225, in get_api
    return JdbcApi(request.user, interpreter=interpreter)
  File "/usr/lib/hue/desktop/libs/notebook/src/notebook/connectors/jdbc.py", line 64, in __init__
    self.db = API_CACHE[self.cache_key] = Jdbc(self.options['driver'], self.options['url'], username, self.options['password'])
  File "/usr/lib/hue/desktop/libs/librdbms/src/librdbms/jdbc.py", line 54, in __init__
    self.gateway = JavaGateway.launch_gateway(classpath=os.environ['CLASSPATH'])
  File "/usr/lib/hue/build/env/lib64/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'CLASSPATH'
```
I'm also getting that same "CLASSPATH" notification. I took a look at this PR but I don't see a bug in the code yet. Are we setting/getting CLASSPATH in the proper shell?

**Comment by ChrisMcPherson** [comment]
I can confirm that I am receiving the same error on Hue 3.12 when attempting to reference the Presto JDBC driver with the dbproxy_extra_classpath configuration.

**Comment by romainr** [comment]
Above error means you did not

> export CLASSPATH=/.... 

in the environment (shell) of Hue.

**Comment by cricket007** [comment]
I've noticed that despite `/home/hue/.bash_profile` or `/etc/profile.d/hue.sh` having `export CLASSPATH=/...`, the jar files are not getting picked up. 

The `dbproxy_extra_classpath` does want to load them, though
