### ISSUE TITLE
'make apps' got a error <configobj.ParseError: Invalid line at line "908">

### ISSUE THREAD

**Issue by Danier-Evens** [cloudera/hue#561]
> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

**when I `make apps`,  got a error，Ask for your help. thanks....**

make[2]: Leaving directory '/usr/local/hue-3.12.0/desktop/libs/notebook'
--- Regenerating database at /usr/local/hue-3.12.0/desktop/desktop.db
--- Syncing/updating database at /usr/local/hue-3.12.0/desktop/desktop.db
Traceback (most recent call last):
  File "/usr/local/hue-3.12.0/build/env/bin/hue", line 9, in <module>
    load_entry_point('desktop==3.12.0', 'console_scripts', 'hue')()
  File "/usr/local/hue-3.12.0/desktop/core/src/desktop/manage_entry.py", line 59, in entry
    execute_from_command_line(sys.argv)
  File "/usr/local/hue-3.12.0/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/hue-3.12.0/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/hue-3.12.0/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/management/__init__.py", line 261, in fetch_command
    commands = get_commands()
  File "/usr/local/hue-3.12.0/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/management/__init__.py", line 107, in get_commands
    apps = settings.INSTALLED_APPS
  File "/usr/local/hue-3.12.0/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/local/hue-3.12.0/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/hue-3.12.0/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/hue-3.12.0/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/local/hue-3.12.0/desktop/core/src/desktop/settings.py", line 250, in <module>
    conf.initialize(_desktop_conf_modules, _config_dir)
  File "/usr/local/hue-3.12.0/desktop/core/src/desktop/lib/conf.py", line 591, in initialize
    conf_data = load_confs(_configs_from_dir(config_dir))
  File "/usr/local/hue-3.12.0/desktop/core/src/desktop/lib/conf.py", line 523, in load_confs
    for in_conf in conf_source:
  File "/usr/local/hue-3.12.0/desktop/core/src/desktop/lib/conf.py", line 504, in _configs_from_dir
    conf = configobj.ConfigObj(os.path.join(conf_dir, filename))
  File "/usr/local/hue-3.12.0/build/env/local/lib/python2.7/site-packages/configobj-4.6.0-py2.7.egg/configobj.py", line 1219, in __init__
    self._load(infile, configspec)
  File "/usr/local/hue-3.12.0/build/env/local/lib/python2.7/site-packages/configobj-4.6.0-py2.7.egg/configobj.py", line 1302, in _load
    raise error
configobj.ParseError: Invalid line at line "908".
Makefile:56: recipe for target '/usr/local/hue-3.12.0/desktop/desktop.db' failed
make[1]: *** [/usr/local/hue-3.12.0/desktop/desktop.db] Error 1
make[1]: Leaving directory '/usr/local/hue-3.12.0/desktop'
Makefile:73: recipe for target 'desktop' failed
make: *** [desktop] Error 2

**Comment by Danier-Evens** [comment]
This error have already been solved.  https://community.hortonworks.com/questions/44145/error-start-hue-39.html
