### ISSUE TITLE
blacklisting is broken for impala and beeswax in hue 4.0

### ISSUE THREAD

**Issue by antonkulaga** [cloudera/hue#562]
When I try to use gethue/hue docker container with blacklisted impala and beeswax it still tries to load them!
Here is the error list:
```
AttributeError
AttributeError: 'Config' object has no attribute 'get'

Traceback (most recent call last)
File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/wsgi.py", line 206, in __call__
response = self.get_response(request)
File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/base.py", line 194, in get_response
response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/base.py", line 236, in handle_uncaught_exception
return callback(request, **param_dict)
File "/hue/desktop/core/src/desktop/views.py", line 375, in serve_500_error
return django.views.debug.technical_500_response(request, *exc_info)
File "/hue/build/env/lib/python2.7/site-packages/django_extensions-1.5.0-py2.7.egg/django_extensions/management/technical_response.py", line 5, in null_technical_500_response
six.reraise(exc_type, exc_value, tb)
File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/base.py", line 112, in get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/transaction.py", line 371, in inner
return func(*args, **kwargs)
File "/hue/build/env/lib/python2.7/site-packages/django_axes-1.5.0-py2.7.egg/axes/decorators.py", line 296, in decorated_login
response = func(request, *args, **kwargs)
File "/hue/desktop/core/src/desktop/auth/views.py", line 171, in dt_login
'action': urlresolvers.reverse('desktop.auth.views.dt_login'),
File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/urlresolvers.py", line 536, in reverse
return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/urlresolvers.py", line 403, in _reverse_with_prefix
self._populate()
File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/urlresolvers.py", line 303, in _populate
lookups.appendlist(pattern.callback, (bits, p_pattern, pattern.default_args))
File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/urlresolvers.py", line 230, in callback
self._callback = get_callable(self._callback_str)
File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/utils/functional.py", line 32, in wrapper
result = func(*args)
File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/urlresolvers.py", line 97, in get_callable
mod = import_module(mod_name)
File "/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/utils/importlib.py", line 40, in import_module
__import__(name)
File "/hue/desktop/core/src/desktop/configuration/api.py", line 32, in <module>
from notebook.connectors.hiveserver2 import HiveConfiguration, ImpalaConfiguration
File "/hue/desktop/libs/notebook/src/notebook/connectors/hiveserver2.py", line 64, in <module>
from impala.server import get_api as get_impalad_api, ImpalaDaemonApiException
File "/hue/apps/impala/src/impala/server.py", line 26, in <module>
from beeswax.server.hive_server2_lib import HiveServerClient
File "/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 362, in <module>
if beeswax_conf.THRIFT_VERSION.get() >= 7:
AttributeError: 'Config' object has no attribute 'get'
```
And here is a config file:
[hue.ini.tar.gz](https://github.com/cloudera/hue/files/1155385/hue.ini.tar.gz)

**Comment by romainr** [comment]
Added a patch to https://issues.cloudera.org/browse/HUE-6884
