### ISSUE TITLE
Hue startup failed

### ISSUE THREAD

**Issue by guogithut** [cloudera/hue#581]
Traceback (most recent call last):
  File "/home/hadoop/hue-3.9.0-cdh5.5.2/build/env/bin/hue", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/hadoop/hue-3.9.0-cdh5.5.2/build/env/lib/python2.6/site-packages/pkg_resources/__init__.py", line 15, in <module>
    """
KeyboardInterrupt

**Comment by guogithut** [comment]
[17/Aug/2017 17:03:00 ] supervisor   ERROR    Uncaught exception. Supervisor exiting.
Traceback (most recent call last):
  File "/home/hadoop/hue-3.9.0-cdh5.5.2/desktop/core/src/desktop/supervisor.py", line 150, in run
    **self.popen_kwargs)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1234, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
[17/Aug/2017 17:03:01 ] supervisor   ERROR    Exception in supervisor main loop
Traceback (most recent call last):
  File "/home/hadoop/hue-3.9.0-cdh5.5.2/desktop/core/src/desktop/supervisor.py", line 386, in main
    wait_loop(sups, options)
  File "/home/hadoop/hue-3.9.0-cdh5.5.2/desktop/core/src/desktop/supervisor.py", line 403, in wait_loop
    shutdown(sups)        # shutdown() exits the process
  File "/home/hadoop/hue-3.9.0-cdh5.5.2/desktop/core/src/desktop/supervisor.py", line 215, in shutdown
    sys.exit(1)
SystemExit: 1

**Comment by guogithut** [comment]
[17/Aug/2017 17:03:00 ] supervisor   INFO     Starting process /home/hadoop/hue-3.9.0-cdh5.5.2/build/env/bin/hue kt_renewer
[17/Aug/2017 17:03:00 ] supervisor   INFO     Starting process /home/hadoop/hue-3.9.0-cdh5.5.2/build/env/bin/hue runcpserver
[17/Aug/2017 17:03:00 ] supervisor   ERROR    Uncaught exception. Supervisor exiting.
Traceback (most recent call last):
  File "/home/hadoop/hue-3.9.0-cdh5.5.2/desktop/core/src/desktop/supervisor.py", line 150, in run
    **self.popen_kwargs)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1234, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
[17/Aug/2017 17:03:00 ] supervisor   INFO     Started proceses (pid 16027) /home/hadoop/hue-3.9.0-cdh5.5.2/build/env/bin/hue runcpserver
[17/Aug/2017 17:03:01 ] supervisor   WARNING  Supervisor shutting down!
[17/Aug/2017 17:03:01 ] supervisor   WARNING  Waiting for children to exit for 5 seconds...
[17/Aug/2017 17:03:01 ] supervisor   WARNING  Exit code for /home/hadoop/hue-3.9.0-cdh5.5.2/build/env/bin/hue runcpserver: 1
[17/Aug/2017 17:03:01 ] supervisor   INFO     Stopping /home/hadoop/hue-3.9.0-cdh5.5.2/build/env/bin/hue runcpserver because supervisor exiting
[17/Aug/2017 17:03:01 ] supervisor   ERROR    Exception in supervisor main loop
Traceback (most recent call last):
  File "/home/hadoop/hue-3.9.0-cdh5.5.2/desktop/core/src/desktop/supervisor.py", line 386, in main
    wait_loop(sups, options)
  File "/home/hadoop/hue-3.9.0-cdh5.5.2/desktop/core/src/desktop/supervisor.py", line 403, in wait_loop
    shutdown(sups)        # shutdown() exits the process
  File "/home/hadoop/hue-3.9.0-cdh5.5.2/desktop/core/src/desktop/supervisor.py", line 215, in shutdown
    sys.exit(1)
SystemExit: 1
[17/Aug/2017 17:03:01 ] supervisor   WARNING  Supervisor shutting down!
[17/Aug/2017 17:03:01 ] supervisor   WARNING  Waiting for children to exit for 5 seconds...

**Comment by enricoberti** [comment]
Hi! That's a super old version of Hue, any reason why you are using that?

OSError: [Errno 13] Permission denied -> there's an old thread about this [here](https://groups.google.com/a/cloudera.org/forum/#!topic/hue-user/yiFiH1E0LM4)

**Comment by guogithut** [comment]
Thank you!

**Comment by guogithut** [comment]
@enricoberti  
Thank you!
