### ISSUE TITLE
Traceback (most recent call last):   File "/home/hadoop/bigdataApp/hue-3.9.0-cdh5.5.2/build/env/bin/hue", line 5, in <module>     from pkg_resources import load_entry_point   File "/home/hadoop/bigdataApp/hue-3.9.0-cdh5.5.2/build/env/lib/python2.6/site-packages/pkg_resources/__init__.py", line 951, in <module>     class Environment(object):   File "/home/hadoop/bigdataApp/hue-3.9.0-cdh5.5.2/build/env/lib/python2.6/site-packages/pkg_resources/__init__.py", line 954, in Environment     def __init__(self, search_path=None, platform=get_supported_platform(),   File "/home/hadoop/bigdataApp/hue-3.9.0-cdh5.5.2/build/env/lib/python2.6/site-packages/pkg_resources/__init__.py", line 259, in get_supported_platform     plat = get_build_platform()   File "/home/hadoop/bigdataApp/hue-3.9.0-cdh5.5.2/build/env/lib/python2.6/site-packages/pkg_resources/__init__.py", line 427, in get_build_platform     from sysconfig import get_platform KeyboardInterrupt

### ISSUE THREAD

**Issue by guogithut** [cloudera/hue#582]
Traceback (most recent call last):
  File "/home/hadoop/bigdataApp/hue-3.9.0-cdh5.5.2/build/env/bin/hue", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/hadoop/bigdataApp/hue-3.9.0-cdh5.5.2/build/env/lib/python2.6/site-packages/pkg_resources/__init__.py", line 951, in <module>
    class Environment(object):
  File "/home/hadoop/bigdataApp/hue-3.9.0-cdh5.5.2/build/env/lib/python2.6/site-packages/pkg_resources/__init__.py", line 954, in Environment
    def __init__(self, search_path=None, platform=get_supported_platform(),
  File "/home/hadoop/bigdataApp/hue-3.9.0-cdh5.5.2/build/env/lib/python2.6/site-packages/pkg_resources/__init__.py", line 259, in get_supported_platform
    plat = get_build_platform()
  File "/home/hadoop/bigdataApp/hue-3.9.0-cdh5.5.2/build/env/lib/python2.6/site-packages/pkg_resources/__init__.py", line 427, in get_build_platform
    from sysconfig import get_platform
KeyboardInterrupt

**Comment by enricoberti** [comment]
For stacktraces and general help please post either on our [Google Group](https://groups.google.com/a/cloudera.org/forum/#!forum/hue-user) or on the [Hue Forum](http://community.cloudera.com/t5/Web-UI-Hue-Beeswax/bd-p/Hue)
