### ISSUE TITLE
Error while building Hue-4.1.0

### ISSUE THREAD

**Issue by analog76** [cloudera/hue#602]
It stopped at `ls: cannot access /mnt/data/apps/hue-4.1.0/binary/hue/desktop/desktop.db: No such file or directory 
`

Here is the full stack error. What is required to to at my end?

`Post-processed 'dashboard/help/index.html' as 'dashboard/help/index.e505932c5f0c.html'
Post-processed 'dashboard/js/create-collections.ko.js' as 'dashboard/js/create-collections.ko.bc1110aa4344.js'
Post-processed 'dashboard/js/search.ko.js' as 'dashboard/js/search.ko.08e0e0a1f999.js'
Post-processed 'dashboard/js/collections.ko.js' as 'dashboard/js/collections.ko.f5c3d5a4901f.js'
Post-processed 'dashboard/js/search.utils.js' as 'dashboard/js/search.utils.85783f1cc171.js'

1401 static files copied to '/mnt/data/apps/hue-4.1.0/binary/hue/build/static', 1401 post-processed.
make[1]: Leaving directory `/mnt/data/apps/hue-4.1.0/binary/hue/apps'
--- Setting up Desktop database
make -C /mnt/data/apps/hue-4.1.0/binary/hue/desktop syncdb
make[1]: Entering directory `/mnt/data/apps/hue-4.1.0/binary/hue/desktop'
--- Regenerating database at /mnt/data/apps/hue-4.1.0/binary/hue/desktop/desktop.db
--- Syncing/updating database at /mnt/data/apps/hue-4.1.0/binary/hue/desktop/desktop.db
/mnt/data/apps/hue-4.1.0/binary/hue/build/env/lib/python2.6/site-packages/cryptography-1.3.1-py2.6-linux-x86_64.egg/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning
Syncing...
Traceback (most recent call last):
  File "/mnt/data/apps/hue-4.1.0/binary/hue/build/env/bin/hue", line 11, in <module>
    load_entry_point('desktop', 'console_scripts', 'hue')()
  File "/mnt/data/apps/hue-4.1.0/binary/hue/desktop/core/src/desktop/manage_entry.py", line 59, in entry
    execute_from_command_line(sys.argv)
  File "/mnt/data/apps/hue-4.1.0/binary/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/mnt/data/apps/hue-4.1.0/binary/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/mnt/data/apps/hue-4.1.0/binary/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/mnt/data/apps/hue-4.1.0/binary/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/mnt/data/apps/hue-4.1.0/binary/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/mnt/data/apps/hue-4.1.0/binary/hue/build/env/lib/python2.6/site-packages/South-1.0.2-py2.6.egg/south/management/commands/syncdb.py", line 92, in handle_noargs
    syncdb.Command().execute(**options)
  File "/mnt/data/apps/hue-4.1.0/binary/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/mnt/data/apps/hue-4.1.0/binary/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/mnt/data/apps/hue-4.1.0/binary/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/commands/syncdb.py", line 57, in handle_noargs
    cursor = connection.cursor()
  File "/mnt/data/apps/hue-4.1.0/binary/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/backends/__init__.py", line 162, in cursor
    cursor = util.CursorWrapper(self._cursor(), self)
  File "/mnt/data/apps/hue-4.1.0/binary/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/backends/__init__.py", line 132, in _cursor
    self.ensure_connection()
  File "/mnt/data/apps/hue-4.1.0/binary/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/backends/__init__.py", line 127, in ensure_connection
    self.connect()
  File "/mnt/data/apps/hue-4.1.0/binary/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/mnt/data/apps/hue-4.1.0/binary/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/backends/__init__.py", line 127, in ensure_connection
    self.connect()
  File "/mnt/data/apps/hue-4.1.0/binary/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/backends/__init__.py", line 115, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/mnt/data/apps/hue-4.1.0/binary/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/backends/sqlite3/base.py", line 347, in get_new_connection
    conn = Database.connect(**conn_params)
django.db.utils.OperationalError: unable to open database file
make[1]: *** [/mnt/data/apps/hue-4.1.0/binary/hue/desktop/desktop.db] Error 1
make[1]: Leaving directory `/mnt/data/apps/hue-4.1.0/binary/hue/desktop'
make: *** [install-env] Error 2`

**Comment by analog76** [comment]
Forgot to update.  I downloaded the tar file and tried to build.

**Comment by romainr** [comment]
Seems like the 'hue syncdb' command was not ran when doing the 'make' (it will just create the SQLLite DB)
