### ISSUE TITLE
Hue 4 fails to show oozie workflows/schedules

### ISSUE THREAD

**Issue by botchniaque** [cloudera/hue#606]
I use hue 4 in EMR cluster version 5.9.0 together with oozie (4.3.0). Old hue 3 UI works just fine. 

This error appears only it I click around a little while - which means initially the UI works, but after a while I start getting errors from oozie api. 

somehow hue is calling oozie api with filter `text` set ([apparently text is considered one of the valid job filters](https://github.com/cloudera/hue/blob/master/desktop/libs/liboozie/src/liboozie/oozie_api.py#L92)), but [oozie does not know filter `text`](https://github.com/apache/oozie/blob/release-4.3.0/core/src/main/java/org/apache/oozie/CoordinatorEngine.java#L603). 

hue log: 
```
[19/Oct/2017 14:48:35 +0200] api2         ERROR    Error running <function jobs at 0x7f7bbc028488>
Traceback (most recent call last):
  File "/usr/lib/hue/apps/jobbrowser/src/jobbrowser/api2.py", line 36, in decorator
    return func(*args, **kwargs)
  File "/usr/lib/hue/apps/jobbrowser/src/jobbrowser/api2.py", line 55, in jobs
    jobs = get_api(request.user, interface).apps(filters)
  File "/usr/lib/hue/apps/jobbrowser/src/jobbrowser/apis/workflow_api.py", line 46, in apps
    wf_list = oozie_api.get_workflows(**kwargs)
  File "/usr/lib/hue/desktop/libs/liboozie/src/liboozie/oozie_api.py", line 129, in get_workflows
    return self.get_jobs('wf', offset, cnt, filters)
  File "/usr/lib/hue/desktop/libs/liboozie/src/liboozie/oozie_api.py", line 119, in get_jobs
    resp = self._root.get('jobs', params)
  File "/usr/lib/hue/desktop/core/src/desktop/lib/rest/resource.py", line 100, in get
    return self.invoke("GET", relpath, params, headers=headers, allow_redirects=True, clear_cookies=clear_cookies)
  File "/usr/lib/hue/desktop/core/src/desktop/lib/rest/resource.py", line 80, in invoke
    clear_cookies=clear_cookies)
  File "/usr/lib/hue/desktop/core/src/desktop/lib/rest/http_client.py", line 197, in execute
    raise self._exc_class(ex)
RestException: <html><head><title>Apache Tomcat/6.0.45 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 400 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>The request sent by the client was syntactically incorrect.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/6.0.45</h3></body></html> (error 400)

```

Oozie log:
```
2017-10-19 12:48:55,303  WARN V1JobsServlet:523 - SERVER[MY_AWS_PRIVATE_IP] USER[-] GROUP[-] TOKEN[-] APP[-] JOB[-] ACTION[-] URL[GET MY_AWS_PRIVATE_IP:11000/oozie/v1/jobs?len=100&doAs=szymonbochniakzalandode&filter=startcreatedtime%3D-1d%3Btext%3D+&user.name=hue&offset=1&timezone=Europe%2FBerlin&jobtype=wf] error[E0420], E0420: Invalid jobs filter [startcreatedtime=-1d;text= ], invalid name [text]
org.apache.oozie.servlet.XServletException: E0420: Invalid jobs filter [startcreatedtime=-1d;text= ], invalid name [text]
        at org.apache.oozie.servlet.V1JobsServlet.getWorkflowJobs(V1JobsServlet.java:332)
        at org.apache.oozie.servlet.V1JobsServlet.getJobs(V1JobsServlet.java:153)
        at org.apache.oozie.servlet.BaseJobsServlet.doGet(BaseJobsServlet.java:123)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.apache.oozie.servlet.JsonRestServlet.service(JsonRestServlet.java:304)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.oozie.servlet.AuthFilter$2.doFilter(AuthFilter.java:171)
        at org.apache.hadoop.security.authentication.server.AuthenticationFilter.doFilter(AuthenticationFilter.java:594)
        at org.apache.hadoop.security.authentication.server.AuthenticationFilter.doFilter(AuthenticationFilter.java:553)
        at org.apache.oozie.servlet.AuthFilter.doFilter(AuthFilter.java:176)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.oozie.servlet.HostnameFilter.doFilter(HostnameFilter.java:86)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:234)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:612)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:503)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.oozie.DagEngineException: E0420: Invalid jobs filter [startcreatedtime=-1d;text= ], invalid name [text]
        at org.apache.oozie.DagEngine.parseFilter(DagEngine.java:502)
        at org.apache.oozie.DagEngine.getJobs(DagEngine.java:539)
        at org.apache.oozie.servlet.V1JobsServlet.getWorkflowJobs(V1JobsServlet.java:323)
        ... 26 more

```

**Comment by denniszag** [comment]
This happens because of incompatible Oozie version (below 4.3).
You can disable Oozie filtering in the `hue.ini` configuration file:
`# Flag to enable Oozie backend filtering instead of doing it at the page level in Javascript. Requires Oozie 4.3+.`
https://github.com/cloudera/hue/blob/ae5fa81776cf30493bd22b1943a37c8542f4b89c/desktop/conf.dist/hue.ini#L1148
or upgrade your Oozie to version 4.3+

In addition, you will need to use Hue 3 UI (Hue 4 doesn't support client side filtering).

**Comment by josh-uken** [comment]
Also hitting this bug on AWS EMR 5.11.1 which is on Hue 4.0.1 and Oozie 4.3.0 -- we're unable to search/filter through our workflows/coordinators which makes the UI hard to use.

**Comment by romainr** [comment]
Sounds like the Oozie is too old there:
https://github.com/cloudera/hue/blob/master/desktop/conf.dist/hue.ini#L1174
```
 [ooize] 
 # Flag to enable Oozie backend filtering instead of doing it at the page level in Javascript. Requires Oozie 4.3+.
  enable_oozie_backend_filtering=true
```

**Comment by vapiravfif** [comment]
@romainr 
Thanks for the reply!
We running hue 4.1.0 with Oozie 4.3.0 (on EMR)

**Comment by vapiravfif** [comment]
@romainr 
Thanks for the reply!
We running hue 4.1.0 with Oozie 4.3.0 (on EMR), and this option is set to true, as you mentioned.

In legacy Hue 3 GUI, the error is a bit more informative -  'Invalid jobs filter [text=xxxxxxxx;status=RUNNING;status=PREP;status=SUSPENDED], invalid name [text]"
