### ISSUE TITLE
hive can't use from hue query editors in kerberos . 

### ISSUE THREAD

**Issue by zhoubh** [cloudera/hue#618]
Hi,

Our system is 
HDFS  2.6.0+cdh5.5.2
Hive  1.1.0+cdh5.5.2
Hue   3.9.0+cdh5.5.2 with kerberos env.

 
When open Hue Hive query UI,
return :  Expected state FINISHED, but found ERROR .

hs2 log:

2017-11-07 18:27:12,355 WARN  org.apache.hadoop.security.UserGroupInformation: [HiveServer2-Handler-Pool: Thread-1241]: PriviledgedActionException as:xionghui (auth:PROXY) via hive/xx-xx-xx@XXX.COM (auth:KERBEROS) cause:org.apache.hive.service.cli.HiveSQLException: Expected state FINISHED, but found ERROR
2017-11-07 18:27:12,355 WARN  org.apache.hive.service.cli.thrift.ThriftCLIService: [HiveServer2-Handler-Pool: Thread-1241]: Error fetching results:
org.apache.hive.service.cli.HiveSQLException: Expected state FINISHED, but found ERROR
        at org.apache.hive.service.cli.operation.Operation.assertState(Operation.java:164)
        at org.apache.hive.service.cli.operation.SQLOperation.getNextRowSet(SQLOperation.java:310)
        at org.apache.hive.service.cli.operation.OperationManager.getOperationNextRowSet(OperationManager.java:262)
        at org.apache.hive.service.cli.session.HiveSessionImpl.fetchResults(HiveSessionImpl.java:732)
        at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)

Can you give me some advice to resovle this problem. 
Thanks .

**Comment by romainr** [comment]
Until HIVE-10574 (https://issues.apache.org/jira/browse/HIVE-10574) gets fixed we suggest you doing a couple of things. Steps are listed below. - First one is to increase the token lifetime (example below is 1 year, but you may want to lower that). 1. Using Cloudera Manager, set the following configurations into both Hive Metastore Server Advanced Configuration Snippet (Safety Valve) for hive-site.xml and HiveServer2 Advanced Configuration Snippet (Safety Valve) for hive-site.xml see here: <property> <name>hive.cluster.delegation.key.update-interval</name> <value>31536000000</value> </property> <property> <name>hive.cluster.delegation.token.renew-interval</name> <value>31536000000</value> </property> <property> <name>hive.cluster.delegation.token.max-lifetime</name> <value>31536000000</value> </property> This will ensure that tokens will not expire for (in this example) a year. - Second one is to reduce the garbage collection interval of the HMS to 10 minutes - both help in reducing the frequency of the error message. 2. Use Cloudera Manager, add the following to the Hive Metastore Server Advanced Configuration Snippet (Safety Valve) for hive-site.xml <property> <name>hive.cluster.delegation.token.gc-interval</name> <value>600000</value> </property> 3. Restart the Hive service
