### ISSUE TITLE
Get NoReverseMatch error if indexer is in app_blacklist

### ISSUE THREAD

**Issue by fuellee** [cloudera/hue#625]
Hi, I'm trying to deploy hue-4.1.0 to a cluster without solr. after put indexer into `app_blacklist`, hue start to raise `NoReverseMatch` error: 
```
[15/Nov/2017 13:33:01 +0000] middleware   INFO     Processing exception: u'indexer' is not a registered namespace: Traceback (most recent call last):
  File "/home/lify/hue-4.1.0/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lify/hue-4.1.0/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lify/hue-4.1.0/desktop/core/src/desktop/views.py", line 87, in hue
    'default_cluster_interface': default_cluster_interface
  File "/home/lify/hue-4.1.0/desktop/core/src/desktop/lib/django_util.py", line 230, in render
    **kwargs)
  File "/home/lify/hue-4.1.0/desktop/core/src/desktop/lib/django_util.py", line 148, in _render_to_response
    return django_mako.render_to_response(template, *args, **kwargs)
  File "/home/lify/hue-4.1.0/desktop/core/src/desktop/lib/django_mako.py", line 125, in render_to_response
    return HttpResponse(render_to_string(template_name, data_dictionary), **kwargs)
  File "/home/lify/hue-4.1.0/desktop/core/src/desktop/lib/django_mako.py", line 114, in render_to_string_normal
    result = template.render(**data_dict)
  File "/home/lify/hue-4.1.0/build/env/lib/python2.7/site-packages/Mako-0.8.1-py2.7.egg/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/home/lify/hue-4.1.0/build/env/lib/python2.7/site-packages/Mako-0.8.1-py2.7.egg/mako/runtime.py", line 786, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/lify/hue-4.1.0/build/env/lib/python2.7/site-packages/Mako-0.8.1-py2.7.egg/mako/runtime.py", line 818, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/lify/hue-4.1.0/build/env/lib/python2.7/site-packages/Mako-0.8.1-py2.7.egg/mako/runtime.py", line 844, in _exec_template
    callable_(context, *args, **kwargs)
  File "/tmp/tmpx1l9vd/desktop/hue.mako.py", line 534, in render_body
    __M_writer(escape(unicode( assist.assistPanel() )))
  File "/tmp/tmpx1l9vd/desktop/assist.mako.py", line 494, in render_assistPanel
    __M_writer(escape(unicode( url('indexer:importer_prefill', source_type='all', target_type='table') )))
  File "/home/lify/hue-4.1.0/desktop/core/src/desktop/lib/django_mako.py", line 131, in url
    return reverse(view_name, args=args, kwargs=view_args)
  File "/home/lify/hue-4.1.0/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/urlresolvers.py", line 532, in reverse
    key)
NoReverseMatch: u'indexer' is not a registered namespace
```
I think it's similar to #562 and #214

**Comment by romainr** [comment]
Indexer should not blacklisted as it is a lib. If you want to remove Solr, blacklist 'search' and it should be good.

**Comment by fuellee** [comment]
@romainr thank you, that's real helpful
