### ISSUE TITLE
Error HUE config store data to MySQL 

### ISSUE THREAD

**Issue by nguoingoai** [cloudera/hue#628]
My HUE version:  hue-3.9.0+cdh5.11.2+5098-1.cdh5.11.2.p0.7.el6.x86_64

With default config hue.ini start command OK 
But when change config to use MySQL follow intruction on:  https://www.cloudera.com/documentation/enterprise/5-6-x/topics/cdh_ig_hue_database.html
when run command 
`hue syncdb --noinput`

`Traceback (most recent call last):
  File "./hue", line 12, in <module>
    load_entry_point('desktop==3.9.0', 'console_scripts', 'hue')()
  File "/usr/lib/hue/desktop/core/src/desktop/manage_entry.py", line 59, in entry
    execute_from_command_line(sys.argv)
  File "/usr/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/__init__.py", line 261, in fetch_command
    commands = get_commands()
  File "/usr/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/__init__.py", line 107, in get_commands
    apps = settings.INSTALLED_APPS
  File "/usr/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/lib/hue/desktop/core/src/desktop/settings.py", line 250, in <module>
    conf.initialize(_desktop_conf_modules, _config_dir)
  File "/usr/lib/hue/desktop/core/src/desktop/lib/conf.py", line 591, in initialize
    conf_data = load_confs(_configs_from_dir(config_dir))
  File "/usr/lib/hue/desktop/core/src/desktop/lib/conf.py", line 523, in load_confs
    for in_conf in conf_source:
  File "/usr/lib/hue/desktop/core/src/desktop/lib/conf.py", line 504, in _configs_from_dir
    conf = configobj.ConfigObj(os.path.join(conf_dir, filename))
  File "/usr/lib/hue/build/env/lib/python2.6/site-packages/configobj-4.6.0-py2.6.egg/configobj.py", line 1219, in __init__
    self._load(infile, configspec)
  File "/usr/lib/hue/build/env/lib/python2.6/site-packages/configobj-4.6.0-py2.6.egg/configobj.py", line 1302, in _load
    raise error
configobj.ConfigObjError: Parsing failed with several errors.
First error at line 577.
`

**Comment by nguoingoai** [comment]
My mistake , when use new engine=mysql I forgot comment the old engine=sqlLite3 !!
