### ISSUE TITLE
Error when run Pig scipt on Hue

### ISSUE THREAD

**Issue by nguoingoai** [cloudera/hue#634]
CDH version 2.6.0-cdh5.11.2

HUE Status  
![screenshot - 12122017 - 09 38 04 am](https://user-images.githubusercontent.com/28948005/33864623-33761c7e-df20-11e7-882a-05925a76eb38.png)

Pig script:
```
A = LOAD '/user/hdfs/test_data';
DUMP A;
```
When run by command on shell it working successfully , but on HUE not working :(

`{ "message": "Error submitting workflow pig-app-hue-script - hdfs", "traceback": [ [ "/usr/lib/hue/apps/oozie/src/oozie/views/editor.py", 372, "_submit_workflow", "job_id = submission.run()" ], [ "/usr/lib/hue/desktop/libs/liboozie/src/liboozie/submittion.py", 54, "decorate", "return run_func(self, deployment_dir)" ], [ "/usr/lib/hue/desktop/libs/liboozie/src/liboozie/submittion.py", 95, "run", "self.oozie_id = self.api.submit_job(self.properties)" ], [ "/usr/lib/hue/desktop/libs/liboozie/src/liboozie/oozie_api.py", 268, "submit_job", "resp = self._root.post('jobs', params, data=config_gen(properties), contenttype=_XML_CONTENT_TYPE)" ], [ "/usr/lib/hue/desktop/core/src/desktop/lib/rest/resource.py", 131, "post", "allow_redirects=allow_redirects, clear_cookies=clear_cookies)" ], [ "/usr/lib/hue/desktop/core/src/desktop/lib/rest/resource.py", 80, "invoke", "clear_cookies=clear_cookies)" ], [ "/usr/lib/hue/desktop/core/src/desktop/lib/rest/http_client.py", 196, "execute", "raise self._exc_class(ex)" ] ], "detail": "E0501: Could not perform authorization operation, Call From hdfs-namenode/x.x.x.x to localhost:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused", "title": "Error" }`

Check the oozie log file I found the error : 

```
2017-12-12 09:44:32,299  WARN AuthenticationFilter:528 - SERVER[hdfs-namenode] AuthenticationToken ignored: org.apache.hadoop.security.authentication.util.SignerException: Invalid signature
2017-12-12 09:44:32,299  WARN AuthenticationFilter:528 - SERVER[hdfs-namenode] AuthenticationToken ignored: org.apache.hadoop.security.authentication.util.SignerException: Invalid signature
2017-12-12 09:44:32,533  INFO BaseJobServlet:520 - SERVER[hdfs-namenode] USER[-] GROUP[-] TOKEN[-] APP[-] JOB[-] ACTION[-] AuthorizationException
org.apache.oozie.service.AuthorizationException: E0501: Could not perform authorization operation, Call From hdfs-namenode/x.x.x.x to localhost:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
        at org.apache.oozie.service.AuthorizationService.authorizeForApp(AuthorizationService.java:406)
        at org.apache.oozie.servlet.BaseJobServlet.checkAuthorizationForApp(BaseJobServlet.java:239)
        at org.apache.oozie.servlet.BaseJobsServlet.doPost(BaseJobsServlet.java:99)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.oozie.servlet.JsonRestServlet.service(JsonRestServlet.java:289)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.oozie.servlet.AuthFilter$2.doFilter(AuthFilter.java:171)
        at org.apache.hadoop.security.authentication.server.AuthenticationFilter.doFilter(AuthenticationFilter.java:622)
        at org.apache.hadoop.security.authentication.server.AuthenticationFilter.doFilter(AuthenticationFilter.java:574)
        at org.apache.oozie.servlet.AuthFilter.doFilter(AuthFilter.java:176)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.oozie.servlet.HostnameFilter.doFilter(HostnameFilter.java:86)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:610)
```
```
2017-12-12 10:09:25,433  WARN V1JobsServlet:523 - SERVER[hdfs-namenode] USER[-] GROUP[-] TOKEN[-] APP[-] JOB[-] ACTION[-] URL[POST http://localhost:11000/oozie/v1/jobs?timezone=Asia%2FHo_Chi_Minh&user.name=hue&doAs=hdfs] error[E0501], E0501: Could not perform authorization operation, Call From hdfs-namenode/x.x.x.x to localhost:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
org.apache.oozie.servlet.XServletException: E0501: Could not perform authorization operation, Call From hdfs-namenode7-116/10.90.7.116 to localhost:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
        at org.apache.oozie.servlet.BaseJobServlet.checkAuthorizationForApp(BaseJobServlet.java:250)
        at org.apache.oozie.servlet.BaseJobsServlet.doPost(BaseJobsServlet.java:99)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.oozie.servlet.JsonRestServlet.service(JsonRestServlet.java:289)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
```

How can I fix this ?

**Comment by nguoingoai** [comment]
I had fixed by change config in hue.ini
change all the config of yarn module from "localhost" to "hostname" fix the authorization issue
