### ISSUE TITLE
'Config' object has no attribute 'get'

### ISSUE THREAD

**Issue by arovit** [cloudera/hue#644]
I am getting following stack trace with Hue-4.1.0, I have just hadoop and spark installed.

```
[05/Jan/2018 17:16:02 -0800] decorators   INFO     args: (True,)
[05/Jan/2018 17:16:02 -0800] decorators   INFO     AXES: Calling decorated function: dt_login
[05/Jan/2018 17:16:02 -0800] middleware   INFO     Processing exception: 'Config' object has no attribute 'get': Traceback (most recent call last):
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/usr/lib/hue/desktop/core/src/desktop/views.py", line 87, in hue
    'default_cluster_interface': default_cluster_interface
  File "/usr/lib/hue/desktop/core/src/desktop/lib/django_util.py", line 230, in render
    **kwargs)
  File "/usr/lib/hue/desktop/core/src/desktop/lib/django_util.py", line 148, in _render_to_response
    return django_mako.render_to_response(template, *args, **kwargs)
  File "/usr/lib/hue/desktop/core/src/desktop/lib/django_mako.py", line 125, in render_to_response
    return HttpResponse(render_to_string(template_name, data_dictionary), **kwargs)
  File "/usr/lib/hue/desktop/core/src/desktop/lib/django_mako.py", line 114, in render_to_string_normal
    result = template.render(**data_dict)
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Mako-0.8.1-py2.7.egg/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Mako-0.8.1-py2.7.egg/mako/runtime.py", line 786, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Mako-0.8.1-py2.7.egg/mako/runtime.py", line 818, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Mako-0.8.1-py2.7.egg/mako/runtime.py", line 844, in _exec_template
    callable_(context, *args, **kwargs)
  File "/tmp/tmp2hvjIi/desktop/hue.mako.py", line 534, in render_body
    __M_writer(escape(unicode( assist.assistPanel() )))
  File "/tmp/tmp2hvjIi/desktop/assist.mako.py", line 490, in render_assistPanel
    if ENABLE_NEW_CREATE_TABLE.get():
AttributeError: 'Config' object has no attribute 'get'
[05/Jan/2018 17:16:02 -0800] resource     DEBUG    GET Got response: {"FileStatus":{"accessTime":0,"blockSize":0,"childrenNum":0,"fileId":17489,"group":"arovit","length":0,"modificationTime":1515200900601,"owner":"arovit","pathSuffix":"","permission":"755","replication":0,"storagePolicy":0,"type":"DIRECTORY"}}
[05/Jan/2018 17:16:02 -0800] connectionpool DEBUG    "ip-192-168-70-222.ec2.internal:50070 GET /webhdfs/v1/user/arovit?op=GETFILESTATUS&user.name=hue&doas=arovit HTTP/1.1" 200 None
[05/Jan/2018 17:16:02 -0800] access       INFO     192.168.70.222 arovit - "GET /hue/ HTTP/1.1"
[05/Jan/2018 17:16:02 -0800] access       INFO     192.168.70.222 arovit - "GET / HTTP/1.1"
```

**Comment by ZekeXu** [comment]
Same error. I just add

```bash
[desktop]
# Comma separated list of apps to not load at server startup.
app_blacklist=beeswax,impala,security,filebrowser,jobbrowser,rdbms,jobsub,pig,hbase,sqoop,zookeeper,metastore,spark,oozie,indexer
```
