### ISSUE TITLE
Certificate verify failed

### ISSUE THREAD

**Issue by l1x** [cloudera/hue#658]
Does anybody know how to configure Hue for self signed certs? I think it is related to that.

```[02/Feb/2018 05:07:29 -0800] cluster      ERROR    RM default is not available, skipping it: bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)
Traceback (most recent call last):
  File "/opt/cloudera/parcels/CDH-5.8.0-1.cdh5.8.0.p0.42/lib/hue/desktop/libs/hadoop/src/hadoop/cluster.py", line 223, in get_next_ha_yarncluster
    cluster_info = rm.cluster()
  File "/opt/cloudera/parcels/CDH-5.8.0-1.cdh5.8.0.p0.42/lib/hue/desktop/libs/hadoop/src/hadoop/yarn/resource_manager_api.py", line 118, in cluster
    return self._execute(self._root.get, 'cluster/info', params=params, headers={'Accept': _JSON_CONTENT_TYPE})
  File "/opt/cloudera/parcels/CDH-5.8.0-1.cdh5.8.0.p0.42/lib/hue/desktop/libs/hadoop/src/hadoop/yarn/resource_manager_api.py", line 160, in _execute
    response = function(*args, **kwargs)
  File "/opt/cloudera/parcels/CDH-5.8.0-1.cdh5.8.0.p0.42/lib/hue/desktop/core/src/desktop/lib/rest/resource.py", line 98, in get
    return self.invoke("GET", relpath, params, headers=headers, allow_redirects=True)
  File "/opt/cloudera/parcels/CDH-5.8.0-1.cdh5.8.0.p0.42/lib/hue/desktop/core/src/desktop/lib/rest/resource.py", line 79, in invoke
    urlencode=self._urlencode)
  File "/opt/cloudera/parcels/CDH-5.8.0-1.cdh5.8.0.p0.42/lib/hue/desktop/core/src/desktop/lib/rest/http_client.py", line 163, in execute
    raise self._exc_class(ex)```

**Comment by l1x** [comment]
The resolution is to turn off SSL validation for all the services.
```
[hadoop]
[[hdfs_clusters]]
[[[default]]]
ssl_cert_ca_verify = false
[beeswax]
[[ssl]]
validate=false
[impala]
[[ssl]]
validate=false
```
https://gist.github.com/l1x/bf6e10e83d2dbcefc7b5e69ea3967c70

**Comment by romainr** [comment]
+1
