### ISSUE TITLE
Hue failing to open Files

### ISSUE THREAD

**Issue by shahrukhkhan489** [cloudera/hue#663]
Hue's File browser works file.

But when opening files for editing, the operation fails with below Exceptions in the logs

```
[27/Feb/2018 05:11:22 -0800] webhdfs   WARNING   Failed to check access to path /user/skhan, CHECKACCESS operation may not be supported.
[27/Feb/2018 05:11:22 -0800] exceptions_renderable ERROR    Potential detail: IOException: com.google.protobuf.ServiceException: java.lang.NoClassDefFoundError: com/google/protobuf/UnknownFieldSet$Field (error 500)
[27/Feb/2018 05:11:22 -0800] exceptions_renderable ERROR    Potential trace: [('/usr/lib/hue/apps/filebrowser/src/filebrowser/views.py', 202, 'view', 'return display(request, path)'), ('/usr/lib/hue/apps/filebrowser/src/filebrowser/views.py', 646, 'display', 'read_contents(compression, path, request.fs, offset, length)'), ('/usr/lib/hue/apps/filebrowser/src/filebrowser/views.py', 722, 'read_contents', 'contents = fhandle.read(3)'), ('/usr/lib/hue/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py', 936, 'read', 'data = self._fs.read(self._path, self._pos, length)'), ('/usr/lib/hue/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py', 540, 'read', 'raise ex')]
[27/Feb/2018 05:11:22 -0800] middleware   INFO     Processing exception: Cannot access: /user/skhan/eloqua_loader_newcluster.py. : Traceback (most recent call last):
  File "/usr/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/usr/lib/hue/apps/filebrowser/src/filebrowser/views.py", line 229, in view
    raise PopupException(msg , detail=e)
PopupException: Cannot access: /user/skhan/abc.py.
```

Have set the proxy config's in HDFS

```
<property>
<name>dfs.webhdfs.enabled</name>
<value>true</value>
</property>
  <name>hadoop.proxyuser.hue.hosts</name>
  <value>*</value>
</property>
<property>
  <name>hadoop.proxyuser.hue.groups</name>
  <value>*</value>
</property>
<property>
    <name>hadoop.proxyuser.httpfs.hosts</name>
    <value>*</value>
</property>
<property>
    <name>hadoop.proxyuser.httpfs.groups</name>
    <value>*</value>
</property>

**Comment by shahrukhkhan489** [comment]
Closing the issue as Invalid. 

Isssue with httpfs
