### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'get'

### ISSUE THREAD

**Issue by CodeDome** [cloudera/hue#683]
The following error occurred while logging in. have added：  app_blacklist=beeswax,impala,security,filebrowser,jobbrowser,rdbms,jobsub,pig,hbase,sqoop,zookeeper,metastore,spark,oozie,indexer . But it was the same mistake.How can I solve this problem?

[22/Apr/2018 20:17:55 -0700] access       INFO     127.0.0.1 admin - "GET /hue/ HTTP/1.1"
[22/Apr/2018 20:17:56 -0700] oozie_batch  ERROR    Oozie application is not enabled: 'Config' object has no attribute 'get'
Traceback (most recent call last):
  File "/Users/qcc/Desktop/work/hue-new-4.1.0/desktop/libs/notebook/src/notebook/connectors/oozie_batch.py", line 37, in <module>
    from oozie.views.api import get_log as get_workflow_logs
  File "/Users/qcc/Desktop/work/hue-new-4.1.0/apps/oozie/src/oozie/views/__init__.py", line 18, in <module>
    from dashboard import *
  File "/Users/qcc/Desktop/work/hue-new-4.1.0/apps/oozie/src/oozie/views/dashboard.py", line 49, in <module>
    from oozie.forms import RerunForm, ParameterForm, RerunCoordForm, RerunBundleForm, UpdateCoordinatorForm
  File "/Users/qcc/Desktop/work/hue-new-4.1.0/apps/oozie/src/oozie/forms.py", line 340, in <module>
    class CoordinatorForm(forms.ModelForm):
  File "/Users/qcc/Desktop/work/hue-new-4.1.0/apps/oozie/src/oozie/forms.py", line 348, in CoordinatorForm
    class Meta:
  File "/Users/qcc/Desktop/work/hue-new-4.1.0/apps/oozie/src/oozie/forms.py", line 351, in Meta
    if ENABLE_CRON_SCHEDULING.get():
AttributeError: 'Config' object has no attribute 'get'
[22/Apr/2018 20:17:56 -0700] connectionpool DEBUG    "10.8.8.61:50070 GET /webhdfs/v1/user/admin?op=GETFILESTATUS&user.name=hue&doas=admin HTTP/1.1" 403 None
[22/Apr/2018 20:17:56 -0700] middleware   INFO     Processing exception: 'Config' object has no attribute 'get': Traceback (most recent call last):
  File "/Users/qcc/Desktop/work/hue-new-4.1.0/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/qcc/Desktop/work/hue-new-4.1.0/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/Users/qcc/Desktop/work/hue-new-4.1.0/desktop/core/src/desktop/views.py", line 87, in hue
    'default_cluster_interface': default_cluster_interface
  File "/Users/qcc/Desktop/work/hue-new-4.1.0/desktop/core/src/desktop/lib/django_util.py", line 230, in render
    **kwargs)
  File "/Users/qcc/Desktop/work/hue-new-4.1.0/desktop/core/src/desktop/lib/django_util.py", line 148, in _render_to_response
    return django_mako.render_to_response(template, *args, **kwargs)
  File "/Users/qcc/Desktop/work/hue-new-4.1.0/desktop/core/src/desktop/lib/django_mako.py", line 125, in render_to_response
    return HttpResponse(render_to_string(template_name, data_dictionary), **kwargs)
  File "/Users/qcc/Desktop/work/hue-new-4.1.0/desktop/core/src/desktop/lib/django_mako.py", line 114, in render_to_string_normal
    result = template.render(**data_dict)
  File "/Users/qcc/Desktop/work/hue-new-4.1.0/build/env/lib/python2.7/site-packages/Mako-0.8.1-py2.7.egg/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/Users/qcc/Desktop/work/hue-new-4.1.0/build/env/lib/python2.7/site-packages/Mako-0.8.1-py2.7.egg/mako/runtime.py", line 786, in _render
    **_kwargs_for_callable(callable_, data))
  File "/Users/qcc/Desktop/work/hue-new-4.1.0/build/env/lib/python2.7/site-packages/Mako-0.8.1-py2.7.egg/mako/runtime.py", line 818, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/Users/qcc/Desktop/work/hue-new-4.1.0/build/env/lib/python2.7/site-packages/Mako-0.8.1-py2.7.egg/mako/runtime.py", line 844, in _exec_template
    callable_(context, *args, **kwargs)
  File "/var/folders/jr/v257lhtj0qs9f1j9snl14wrc0000gn/T/tmpFvbprV/desktop/hue.mako.py", line 534, in render_body
    __M_writer(escape(unicode( assist.assistPanel() )))
  File "/var/folders/jr/v257lhtj0qs9f1j9snl14wrc0000gn/T/tmpFvbprV/desktop/assist.mako.py", line 490, in render_assistPanel
    if ENABLE_NEW_CREATE_TABLE.get():
AttributeError: 'Config' object has no attribute 'get'

**Comment by romainr** [comment]
'indexer' should not be blacklisted as it is a lib.
'oozie' issue was probably fixed in Hue 4.2 or master.

Are you trying to do a Solr Search only UI? http://gethue.com/solr-search-ui-only/

**Comment by AndreyEmelyanenko** [comment]
No, that doesn't work. v.4.1

**Comment by AndreyEmelyanenko** [comment]
> The following error occurred while logging in. have added： app_blacklist=beeswax,impala,security,filebrowser,jobbrowser,rdbms,jobsub,pig,hbase,sqoop,zookeeper,metastore,spark,oozie,indexer . But it was the same mistake.How can I solve this problem?
> 
> [22/Apr/2018 20:17:55 -0700] access INFO 127.0.0.1 admin - "GET /hue/ HTTP/1.1"
> [22/Apr/2018 20:17:56 -0700] oozie_batch ERROR Oozie application is not enabled: 'Config' object has no attribute 'get'
> Traceback (most recent call last):
> File "/Users/qcc/Desktop/work/hue-new-4.1.0/desktop/libs/notebook/src/notebook/connectors/oozie_batch.py", line 37, in 
> from oozie.views.api import get_log as get_workflow_logs
> File "/Users/qcc/Desktop/work/hue-new-4.1.0/apps/oozie/src/oozie/views/**init**.py", line 18, in 
> from dashboard import *
> File "/Users/qcc/Desktop/work/hue-new-4.1.0/apps/oozie/src/oozie/views/dashboard.py", line 49, in 
> from oozie.forms import RerunForm, ParameterForm, RerunCoordForm, RerunBundleForm, UpdateCoordinatorForm
> File "/Users/qcc/Desktop/work/hue-new-4.1.0/apps/oozie/src/oozie/forms.py", line 340, in 
> class CoordinatorForm(forms.ModelForm):
> File "/Users/qcc/Desktop/work/hue-new-4.1.0/apps/oozie/src/oozie/forms.py", line 348, in CoordinatorForm
> class Meta:
> File "/Users/qcc/Desktop/work/hue-new-4.1.0/apps/oozie/src/oozie/forms.py", line 351, in Meta
> if ENABLE_CRON_SCHEDULING.get():
> AttributeError: 'Config' object has no attribute 'get'
> [22/Apr/2018 20:17:56 -0700] connectionpool DEBUG "10.8.8.61:50070 GET /webhdfs/v1/user/admin?op=GETFILESTATUS&user.name=hue&doas=admin HTTP/1.1" 403 None
> [22/Apr/2018 20:17:56 -0700] middleware INFO Processing exception: 'Config' object has no attribute 'get': Traceback (most recent call last):
> File "/Users/qcc/Desktop/work/hue-new-4.1.0/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/base.py", line 112, in get_response
> response = wrapped_callback(request, *callback_args, **callback_kwargs)
> File "/Users/qcc/Desktop/work/hue-new-4.1.0/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/transaction.py", line 371, in inner
> return func(*args, **kwargs)
> File "/Users/qcc/Desktop/work/hue-new-4.1.0/desktop/core/src/desktop/views.py", line 87, in hue
> 'default_cluster_interface': default_cluster_interface
> File "/Users/qcc/Desktop/work/hue-new-4.1.0/desktop/core/src/desktop/lib/django_util.py", line 230, in render
> **kwargs)
> File "/Users/qcc/Desktop/work/hue-new-4.1.0/desktop/core/src/desktop/lib/django_util.py", line 148, in _render_to_response
> return django_mako.render_to_response(template, *args, **kwargs)
> File "/Users/qcc/Desktop/work/hue-new-4.1.0/desktop/core/src/desktop/lib/django_mako.py", line 125, in render_to_response
> return HttpResponse(render_to_string(template_name, data_dictionary), **kwargs)
> File "/Users/qcc/Desktop/work/hue-new-4.1.0/desktop/core/src/desktop/lib/django_mako.py", line 114, in render_to_string_normal
> result = template.render(**data_dict)
> File "/Users/qcc/Desktop/work/hue-new-4.1.0/build/env/lib/python2.7/site-packages/Mako-0.8.1-py2.7.egg/mako/template.py", line 443, in render
> return runtime._render(self, self.callable_, args, data)
> File "/Users/qcc/Desktop/work/hue-new-4.1.0/build/env/lib/python2.7/site-packages/Mako-0.8.1-py2.7.egg/mako/runtime.py", line 786, in _render
> **_kwargs_for_callable(callable_, data))
> File "/Users/qcc/Desktop/work/hue-new-4.1.0/build/env/lib/python2.7/site-packages/Mako-0.8.1-py2.7.egg/mako/runtime.py", line 818, in _render_context
> _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
> File "/Users/qcc/Desktop/work/hue-new-4.1.0/build/env/lib/python2.7/site-packages/Mako-0.8.1-py2.7.egg/mako/runtime.py", line 844, in _exec_template callable_(context, *args, **kwargs)
> File "/var/folders/jr/v257lhtj0qs9f1j9snl14wrc0000gn/T/tmpFvbprV/desktop/hue.mako.py", line 534, in render_body
> __M_writer(escape(unicode( assist.assistPanel() )))
> File "/var/folders/jr/v257lhtj0qs9f1j9snl14wrc0000gn/T/tmpFvbprV/desktop/assist.mako.py", line 490, in render_assistPanel
> if ENABLE_NEW_CREATE_TABLE.get():
> AttributeError: 'Config' object has no attribute 'get'

HI!

Have you found a solution? I'm facing the same error just now!

Any help is appreciated!

**Comment by romainr** [comment]
Fixed in https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/templates/global_js_constants.mako#L8
