### ISSUE TITLE
Using latest master codes to build hue and use openid to login, some error message occur

### ISSUE THREAD

**Issue by linktimecloud** [cloudera/hue#718]
![image](https://user-images.githubusercontent.com/36979861/42291461-5aa838de-7ffe-11e8-8454-cbab39b1684e.png)

Upside is my error message, pls have a look, thanks.
Using the latest master code just now.

**Comment by linktimecloud** [comment]
@wing2fly   do you happen to see this error message?

**Comment by linktimecloud** [comment]
Below is my error msg printed in hue

`[05/Jul/2018 02:50:33 +0000] middleware   DEBUG    id token is still valid (1530731096.07 > 1530730233.11)
[05/Jul/2018 02:50:33 +0000] access       INFO     172.17.0.1 admin - "GET /home/ HTTP/1.1" returned in 139ms (mem: 138mb)
172.17.0.1 - - [05/Jul/2018 02:50:33] "GET /home/?&is_embeddable=true&_=1530730189394 HTTP/1.1" 200 -
[05/Jul/2018 02:50:33 +0000] _internal    INFO     172.17.0.1 - - [05/Jul/2018 02:50:33] "GET /home/?&is_embeddable=true&_=1530730189394 HTTP/1.1" 200 -
[05/Jul/2018 02:50:33 +0000] middleware   DEBUG    id token is still valid (1530731096.07 > 1530730233.36)
[05/Jul/2018 02:50:33 +0000] middleware   DEBUG    id token is still valid (1530731096.07 > 1530730233.51)
[05/Jul/2018 02:50:33 +0000] access       INFO     172.17.0.1 admin - "GET /desktop/api2/user_preferences/default_app HTTP/1.1" returned in 33ms (mem: 138mb)
172.17.0.1 - - [05/Jul/2018 02:50:33] "GET /desktop/api2/user_preferences/default_app?_=1530730189396 HTTP/1.1" 200 -
[05/Jul/2018 02:50:33 +0000] _internal    INFO     172.17.0.1 - - [05/Jul/2018 02:50:33] "GET /desktop/api2/user_preferences/default_app?_=1530730189396 HTTP/1.1" 200 -
[05/Jul/2018 02:50:33 +0000] access       INFO     172.17.0.1 admin - "GET /desktop/api2/doc/ HTTP/1.1" returned in 254ms (mem: 138mb)
172.17.0.1 - - [05/Jul/2018 02:50:33] "GET /desktop/api2/doc/?_=1530730189395 HTTP/1.1" 200 -
[05/Jul/2018 02:50:33 +0000] _internal    INFO     172.17.0.1 - - [05/Jul/2018 02:50:33] "GET /desktop/api2/doc/?_=1530730189395 HTTP/1.1" 200 -
[05/Jul/2018 02:50:40 +0000] middleware   DEBUG    id token is still valid (1530731096.07 > 1530730240.21)
[05/Jul/2018 02:50:40 +0000] access       INFO     172.17.0.1 admin - "GET / HTTP/1.1" returned in 8ms (mem: 138mb)
172.17.0.1 - - [05/Jul/2018 02:50:40] "GET / HTTP/1.1" 302 -
[05/Jul/2018 02:50:40 +0000] _internal    INFO     172.17.0.1 - - [05/Jul/2018 02:50:40] "GET / HTTP/1.1" 302 -
[05/Jul/2018 02:50:40 +0000] middleware   DEBUG    id token is still valid (1530731096.07 > 1530730240.3)
[05/Jul/2018 02:50:40 +0000] decorators   INFO     AXES: Calling decorated function: dt_login
[05/Jul/2018 02:50:40 +0000] decorators   INFO     args: (True,)
[05/Jul/2018 02:50:40 +0000] access       INFO     172.17.0.1 admin - "GET /hue/ HTTP/1.1" returned in 572ms (mem: 139mb)
172.17.0.1 - - [05/Jul/2018 02:50:40] "GET /hue/ HTTP/1.1" 200 -
[05/Jul/2018 02:50:40 +0000] _internal    INFO     172.17.0.1 - - [05/Jul/2018 02:50:40] "GET /hue/ HTTP/1.1" 200 -
[05/Jul/2018 02:50:41 +0000] middleware   DEBUG    id token is still valid (1530731096.07 > 1530730241.1)
[05/Jul/2018 02:50:41 +0000] access       INFO     172.17.0.1 admin - "GET /desktop/globalJsConstants.js HTTP/1.1" returned in 11ms (mem: 139mb)
172.17.0.1 - - [05/Jul/2018 02:50:41] "GET /desktop/globalJsConstants.js?v=4.2.0 HTTP/1.1" 304 -
[05/Jul/2018 02:50:41 +0000] _internal    INFO     172.17.0.1 - - [05/Jul/2018 02:50:41] "GET /desktop/globalJsConstants.js?v=4.2.0 HTTP/1.1" 304 -
[05/Jul/2018 02:50:42 +0000] middleware   DEBUG    request is not refreshable
[05/Jul/2018 02:50:42 +0000] middleware   DEBUG    id token is still valid (1530731096.07 > 1530730242.49)
[05/Jul/2018 02:50:42 +0000] middleware   DEBUG    request is not refreshable
[05/Jul/2018 02:50:42 +0000] middleware   DEBUG    request is not refreshable
[05/Jul/2018 02:50:42 +0000] access       INFO     172.17.0.1 admin - "GET /jobbrowser/apps HTTP/1.1" (mem: 139mb)-- permission denied
[05/Jul/2018 02:50:42 +0000] access       INFO     172.17.0.1 admin - "GET /jobbrowser/apps HTTP/1.1" returned in 88ms (mem: 139mb)
172.17.0.1 - - [05/Jul/2018 02:50:42] "GET /jobbrowser/apps?is_embeddable=true&is_mini=true HTTP/1.1" 401 -
[05/Jul/2018 02:50:42 +0000] _internal    INFO     172.17.0.1 - - [05/Jul/2018 02:50:42] "GET /jobbrowser/apps?is_embeddable=true&is_mini=true HTTP/1.1" 401 -
[05/Jul/2018 02:50:42 +0000] access       INFO     172.17.0.1 admin - "POST /notebook/api/create_notebook HTTP/1.1" returned in 12ms (mem: 139mb)
172.17.0.1 - - [05/Jul/2018 02:50:42] "POST /notebook/api/create_notebook HTTP/1.1" 200 -
[05/Jul/2018 02:50:42 +0000] _internal    INFO     172.17.0.1 - - [05/Jul/2018 02:50:42] "POST /notebook/api/create_notebook HTTP/1.1" 200 -
[05/Jul/2018 02:50:42 +0000] access       INFO     172.17.0.1 admin - "POST /jobbrowser/jobs/ HTTP/1.1" (mem: 139mb)-- permission denied
[05/Jul/2018 02:50:42 +0000] access       INFO     172.17.0.1 admin - "POST /jobbrowser/jobs/ HTTP/1.1" returned in 160ms (mem: 139mb)
172.17.0.1 - - [05/Jul/2018 02:50:42] "POST /jobbrowser/jobs/ HTTP/1.1" 401 -
[05/Jul/2018 02:50:42 +0000] _internal    INFO     172.17.0.1 - - [05/Jul/2018 02:50:42] "POST /jobbrowser/jobs/ HTTP/1.1" 401 -
[05/Jul/2018 02:50:42 +0000] middleware   DEBUG    id token is still valid (1530731096.07 > 1530730242.77)
[05/Jul/2018 02:50:42 +0000] api2         ERROR    Error running <function get_config at 0x7fcffac46230>
Traceback (most recent call last):
  File "/hue/desktop/core/src/desktop/api2.py", line 59, in decorator
    return func(*args, **kwargs)
  File "/hue/desktop/core/src/desktop/api2.py", line 73, in get_config
    config = get_cluster_config(request.user)
  File "/hue/desktop/core/src/desktop/models.py", line 1555, in get_cluster_config
    cluster_type = Cluster(user).get_type()
  File "/hue/desktop/core/src/desktop/models.py", line 1916, in __init__
    self.data = self.clusters['Altus' if IS_MULTICLUSTER_ONLY.get() else CLUSTER_ID.get()]
KeyError: 'default'
[05/Jul/2018 02:50:42 +0000] access       INFO     172.17.0.1 admin - "POST /desktop/api2/get_config/ HTTP/1.1" returned in 527ms (mem: 139mb)
172.17.0.1 - - [05/Jul/2018 02:50:42] "POST /desktop/api2/get_config/ HTTP/1.1" 200 -
[05/Jul/2018 02:50:42 +0000] _internal    INFO     172.17.0.1 - - [05/Jul/2018 02:50:42] "POST /desktop/api2/get_config/ HTTP/1.1" 200 -
[05/Jul/2018 02:50:42 +0000] middleware   DEBUG    request is not refreshable
[05/Jul/2018 02:50:42 +0000] access       INFO     172.17.0.1 admin - "GET /notebook/api/get_history HTTP/1.1" returned in 28ms (mem: 139mb)
172.17.0.1 - - [05/Jul/2018 02:50:42] "GET /notebook/api/get_history?limit=50&page=1&doc_text=&is_notification_manager=true HTTP/1.1" 200 -
[05/Jul/2018 02:50:42 +0000] _internal    INFO     172.17.0.1 - - [05/Jul/2018 02:50:42] "GET /notebook/api/get_history?limit=50&page=1&doc_text=&is_notification_manager=true HTTP/1.1" 200 -
[05/Jul/2018 02:50:42 +0000] middleware   DEBUG    request is not refreshable
[05/Jul/2018 02:50:42 +0000] access       ERROR    172.17.0.1 admin - "POST /desktop/log_js_error HTTP/1.1" (mem: 139mb)-- JS ERROR: {"msg":"Uncaught TypeError: Cannot read property 'main_button_action' of undefined","url":"http://192.168.1.5:8787/hue/","line":13272,"column":52,"stack":"TypeError: Cannot read property 'main_button_action' of undefined\n    at http://192.168.1.5:8787/hue/:13272:52\n    at http://192.168.1.5:8787/static/desktop/js/hue-bundle.js:53:31902\n    at n (http://192.168.1.5:8787/static/desktop/js/hue-bundle.js:53:31322)\n    at http://192.168.1.5:8787/static/desktop/js/hue-bundle.js:53:31914\n    at n (http://192.168.1.5:8787/static/desktop/js/hue-bundle.js:53:31322)\n    at http://192.168.1.5:8787/static/desktop/js/hue-bundle.js:53:31914\n    at n (http://192.168.1.5:8787/static/desktop/js/hue-bundle.js:53:31322)\n    at http://192.168.1.5:8787/static/desktop/js/hue-bundle.js:53:31914\n    at n (http://192.168.1.5:8787/static/desktop/js/hue-bundle.js:53:31322)\n    at http://192.168.1.5:8787/static/desktop/js/hue-bundle.js:53:31914"}
[05/Jul/2018 02:50:42 +0000] access       INFO     172.17.0.1 admin - "POST /desktop/log_js_error HTTP/1.1" returned in 13ms (mem: 139mb)
172.17.0.1 - - [05/Jul/2018 02:50:42] "POST /desktop/log_js_error HTTP/1.1" 200 -
[05/Jul/2018 02:50:42 +0000] _internal    INFO     172.17.0.1 - - [05/Jul/2018 02:50:42] "POST /desktop/log_js_error HTTP/1.1" 200 -
[05/Jul/2018 02:50:42 +0000] access       INFO     172.17.0.1 admin - "POST /jobbrowser/jobs/ HTTP/1.1" (mem: 139mb)-- permission denied
[05/Jul/2018 02:50:42 +0000] access       INFO     172.17.0.1 admin - "POST /jobbrowser/jobs/ HTTP/1.1" returned in 63ms (mem: 139mb)
172.17.0.1 - - [05/Jul/2018 02:50:42] "POST /jobbrowser/jobs/ HTTP/1.1" 401 -
[05/Jul/2018 02:50:42 +0000] _internal    INFO     172.17.0.1 - - [05/Jul/2018 02:50:42] "POST /jobbrowser/jobs/ HTTP/1.1" 401 -`

**Comment by linktimecloud** [comment]
[hue_error_msg_0705.log](https://github.com/cloudera/hue/files/2164149/hue_error_msg_0705.log)

Log format may not be very clearly,
and I upload the log file as it is .

**Comment by xixikaikai** [comment]
Pls help and take a look, thanks

**Comment by xixikaikai** [comment]
When session is logged out in another place, HUE is not rightly log out the site, but still there.
I do not know why?

**Comment by xixikaikai** [comment]
`Traceback (most recent call last):
  File "/hue/desktop/core/src/desktop/api2.py", line 59, in decorator
    return func(*args, **kwargs)
  File "/hue/desktop/core/src/desktop/api2.py", line 73, in get_config
    config = get_cluster_config(request.user)
  File "/hue/desktop/core/src/desktop/models.py", line 1555, in get_cluster_config
    cluster_type = Cluster(user).get_type()
  File "/hue/desktop/core/src/desktop/models.py", line 1916, in __init__
    self.data = self.clusters['Altus' if IS_MULTICLUSTER_ONLY.get() else CLUSTER_ID.get()]
KeyError: 'default'`

**Comment by xixikaikai** [comment]
Traceback (most recent call last):
  File "/hue/desktop/core/src/desktop/api2.py", line 59, in decorator
    return func(*args, **kwargs)
  File "/hue/desktop/core/src/desktop/api2.py", line 73, in get_config
    config = get_cluster_config(request.user)
  File "/hue/desktop/core/src/desktop/models.py", line 1555, in get_cluster_config
    cluster_type = Cluster(user).get_type()
  File "/hue/desktop/core/src/desktop/models.py", line 1916, in __init__
    self.data = self.clusters['Altus' if IS_MULTICLUSTER_ONLY.get() else CLUSTER_ID.get()]
KeyError: 'default'

**Comment by romainr** [comment]
Should be fine if you rebase now?

**Comment by xixikaikai** [comment]
It works now. Could be closed.
