### ISSUE TITLE
HBase Browser binary row keys support?

### ISSUE THREAD

**Issue by denis111** [cloudera/hue#77]
Maybe i miss something but i can't filter table view by my binary row keys which consist of an integer concatenated with reverse timestamp (day and year only as shorts). For example, in hbase shell column key looks like \x00\x00\x01\x09x!{` so how do i put this value correctly in the search box? If it's not supported then i think it must be added...

**Comment by zeph** [comment]
yep, have issues as well, I commented on the jira ticket as too

**Comment by zeph** [comment]
regarding my specific issue... 
I manage to print the data coming into /hue/desktop/core/src/desktop/lib/django_util.py +473
...in order to have jq able to spit out the content I had to substitute the single quotes with double quotes
and forcefully escape the \x as \\x all over the place (I guess on the dict key would have been enough)

```json
{
  "limit": 50,
  "data": [
    {
      "columns": {
        "a:\\x01": {
          "timestamp": 1445742065279,
          "value": "AQAIARAKGGQgvKSwsQUovKSwsQUwCjgK"
        },
        "r:\\x00\\x00\\x04\\xcc": {
          "timestamp": 1445742065279,
          "value": "\\x01\\x00\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\n"
        }
      },
      "row": "AAAAAQAACwAQSAYgtwMBBAETAQAAAQeW"
    },
[...]
```

ah... my issue is actually binary family names, not row keys... doh :facepalm:

**Comment by Pratyay** [comment]
Same issue, using salt buckets and not able to query over Hbase via Hue. RowKey format is \x00ABC12345.

**Comment by zeph** [comment]
it's a JSONEncoder issue... 
if I manage to add a unittest to the project and test the code from this article, we shall be good to go
http://stackoverflow.com/questions/31869554/how-can-i-override-behavior-of-jsonencoder-for-binary-data

**Comment by romainr** [comment]
In case it would help, it should be fine to provide a customed JsonResponse like BinJsonResponse
https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/lib/django_util.py#L455
that has a different encoder=DjangoJSONEncoder

and then change it for the HBase app:
https://github.com/cloudera/hue/blob/master/apps/hbase/src/hbase/views.py#L29

or change it to

JsonResponse(data={...}, encoder=BinDjangoJSONEncoder...)

subclassing with different default might be a bit simpler.

And adding the above test could live in https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/lib/django_util_test.py

and should run with something like:
./build/env/bin/hue test specific desktop.lib.django_util_test:TestDjangoUtil.bin_..._test

**Comment by zeph** [comment]
@romainr I already have such a test if you want... I'm just getting crazy in reproducing the issue as HUE is using Django 1.6.10 (1.7 is already deprecated) ... such testcase on the master branch of djangoproject executes smoothly

```
$ git show ffe37c2
commit ffe37c28b806c08201cd2b88ea6df43840a7ba23
Author: Guido Serra <guido@gaikai.com>
Date:   Thu Apr 7 16:27:55 2016 +0200

    testing encoding of binary content in json

diff --git a/tests/serializers/test_json.py b/tests/serializers/test_json.py
index d8d445d..6b4bf23 100644
--- a/tests/serializers/test_json.py
+++ b/tests/serializers/test_json.py
@@ -286,3 +286,27 @@ class DjangoJSONEncoderTests(SimpleTestCase):
                 json.dumps({'lang': ugettext_lazy("French")}, cls=DjangoJSONEncoder),
                 '{"lang": "Fran\\u00e7ais"}'
             )
+
+    def test_binary_strings(self):
+        hbase_hue_thrift = {'limit': 50, 'data': [
+            {'columns': {
+                'a:\x01': {'timestamp': 1445742065279, 'value':'AQAIARAKGGQgvKSwsQUovKSwsQUwCjgK'},
+                'r:\x00\x00\x04\xcc': {'timestamp': 1445742065279, 'value': '\x01\x00\x01\x00\x00\x00\x00\n'}},
+                'row': 'AAAAAQAACwAQSAYgtwMBBAETAQAAAQeW'},
+            {'columns': {
+                'a:\x01': {'timestamp': 1446966066949, 'value': 'AQAIARALGHkgpIP7sQUopIP7sQUwCzgL'},
+                'r:\x00\x00\x06\xf4': {'timestamp': 1446966066949, 'value': '\x01\x00\x01\x00\x00\x00\x00\x0b'}},
+                'row': 'AAAAAQAACwAQSAYiCwMBBAETAQAAAQGE'}
+        ], 'truncated': True}
+
+        hbase_hue_thrift_str = '{"data": [{"columns": {"a:\\u0001": {"timestamp": 1445742065279, "value": ' \
+                               '"AQAIARAKGGQgvKSwsQUovKSwsQUwCjgK"}, "r:\\u0000\\u0000\\u0004\\u00cc": {"timestamp": ' \
+                               '1445742065279, "value": "\\u0001\\u0000\\u0001\\u0000\\u0000\\u0000\\u0000\\n"}}, ' \
+                               '"row": "AAAAAQAACwAQSAYgtwMBBAETAQAAAQeW"}, {"columns": {"a:\\u0001": {"timestamp": ' \
+                               '1446966066949, "value": "AQAIARALGHkgpIP7sQUopIP7sQUwCzgL"}, ' \
+                               '"r:\\u0000\\u0000\\u0006\\u00f4": {"timestamp": 1446966066949, "value": ' \
+                               '"\\u0001\\u0000\\u0001\\u0000\\u0000\\u0000\\u0000\\u000b"}}, "row": ' \
+                               '"AAAAAQAACwAQSAYiCwMBBAETAQAAAQGE"}], "limit": 50, "truncated": true}'
+
+        data = json.dumps(hbase_hue_thrift, cls=DjangoJSONEncoder)
+        self.assertEqual(data, hbase_hue_thrift_str)
```

I'm not convinced anymore the issue is just in such class, I tried to forcefully copy it into the docker container over the original files but the behaviour hasn't changed... 

```
root@hue:/hue# find . -name 'json.py'|grep 1.6.10
./build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/serializers/json.py
./desktop/core/ext-py/Django-1.6.10/build/lib.linux-x86_64-2.7/django/core/serializers/json.py
./desktop/core/ext-py/Django-1.6.10/django/core/serializers/json.py
```

**Comment by zeph** [comment]
p.s. thanks for the pointer on how to execute a specific test in hue, I'll concentrate on that tomorrow

**Comment by romainr** [comment]
Yes, let's see if I can help you not spend time on the project specific stuff. We are indeed stuck on Django 1.6 as we need to stay compatible with Python 2.6 (good news though it that we target Python 2.7 and Django 1.9 for Hue 4 at the end of the tear).

In the branch https://github.com/cloudera/hue/tree/ISSUES-77-hbase-binary I pushed the test:

{code}
./build/env/bin/hue test specific desktop.lib.django_util_test:TestDjangoUtil.test_binary_strings
{code}

{code}
======================================================================
ERROR: desktop.lib.django_util_test.TestDjangoUtil.test_binary_strings
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/romain/projects/hue/build/env/local/lib/python2.7/site-packages/nose-0.11.3-py2.7.egg/nose/case.py", line 186, in runTest
    self.test(*self.arg)
  File "/home/romain/projects/hue/desktop/core/src/desktop/lib/django_util_test.py", line 168, in test_binary_strings
    data = json.dumps(hbase_hue_thrift, cls=DjangoJSONEncoder)
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xcc in position 5: unexpected end of data
{code}

**Comment by tankilo** [comment]
I met this problem today, i have binary rowkey, qualifer and value. And Hue produced the following error.
```
[22/Feb/2020 22:21:29 -0800] access       INFO     10.45.18.255 tk - "POST /hbase/api/getColumnDescriptors/Cluster/TableV2 HTTP/1.1" returned in 36ms 200 258
[22/Feb/2020 22:21:29 -0800] middleware   INFO     Processing exception: 'utf8' codec can't decode byte 0xc3 in position 60: invalid continuation byte: Traceback (most recent call last):
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/usr/share/hue/apps/hbase/src/hbase/views.py", line 86, in api_router
    return api_dump(HbaseApi(request.user).query(*url_params))
  File "/usr/share/hue/apps/hbase/src/hbase/views.py", line 135, in api_dump
    'limit': trunc_limit,
  File "/usr/share/hue/desktop/core/src/desktop/lib/django_util.py", line 496, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 60: invalid continuation byte

[22/Feb/2020 22:21:29 -0800] exception    ERROR    Internal Server Error: /hbase/api/getRowQuerySet/Cluster/TableV2/[]/[{"row_key":"null","scan_length":10,"columns":[],"prefix":"false","filter":null,"editing":true}]
Traceback (most recent call last):
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/usr/share/hue/apps/hbase/src/hbase/views.py", line 86, in api_router
    return api_dump(HbaseApi(request.user).query(*url_params))
  File "/usr/share/hue/apps/hbase/src/hbase/views.py", line 135, in api_dump
    'limit': trunc_limit,
  File "/usr/share/hue/desktop/core/src/desktop/lib/django_util.py", line 496, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 60: invalid continuation byte
```

Can hue print these parts as hex instead of string, just the same way that shell does?

**Comment by romainr** [comment]
In case of error like this, Hue could indeed be changed to "printify" the bytes. Would you be able to send a pull request?
