### ISSUE TITLE
make in macOS 10.12.6 error 

### ISSUE THREAD

**Issue by gaojun2048** [cloudera/hue#809]
/Library/Developer/CommandLineTools/usr/bin/make -C core env-install
--- Building egg for cryptography-2.1.4
Download error on https://pypi.python.org/simple/cffi/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
Couldn't find index page for 'cffi' (maybe misspelled?)
Download error on https://pypi.python.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
No local packages or working download links found for cffi>=1.7
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/gaojun/workspace/hue/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 251, in run_setup
    raise
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/gaojun/workspace/hue/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/gaojun/workspace/hue/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/Users/gaojun/workspace/hue/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 144, in resume
    six.reraise(type, exc, self._tb)
  File "/Users/gaojun/workspace/hue/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/Users/gaojun/workspace/hue/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/Users/gaojun/workspace/hue/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 248, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/Users/gaojun/workspace/hue/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 278, in run
    return func()
  File "/Users/gaojun/workspace/hue/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 246, in runner
    _execfile(setup_script, ns)
  File "/Users/gaojun/workspace/hue/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "setup.py", line 307, in <module>
    **keywords_with_side_effects(sys.argv)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/Users/gaojun/workspace/hue/build/env/lib/python2.7/site-packages/setuptools/dist.py", line 315, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/Users/gaojun/workspace/hue/build/env/lib/python2.7/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
    replace_conflicting=True,
  File "/Users/gaojun/workspace/hue/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 850, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/Users/gaojun/workspace/hue/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1122, in best_match
    return self.obtain(req, installer)
  File "/Users/gaojun/workspace/hue/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1134, in obtain
    return installer(requirement)
  File "/Users/gaojun/workspace/hue/build/env/lib/python2.7/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
    return cmd.easy_install(req)
  File "/Users/gaojun/workspace/hue/build/env/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 659, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('cffi>=1.7')
make[2]: *** [/Users/gaojun/workspace/hue/desktop/core/build/cryptography-2.1.4/egg.stamp] Error 1
make[1]: *** [.recursive-env-install/core] Error 2
make: *** [desktop] Error 2

**Comment by gaojun416** [comment]
I fix it by do like this:
1、use mac os system python , not use the python installed by yourself.
2、use python 2.7
3、upgrade pip to the latest version. then execute "pip -V" you can see that:
   pip 19.0.3 from /Library/Python/2.7/site-packages/pip (python 2.7)
4、sudo pip uninstall cffi && sudo pip install cffi
5、note that: you must install package use sudo.
