### ISSUE TITLE
ImportError: Entry point ('console_scripts', 'hue') not found

### ISSUE THREAD

**Issue by chozee** [cloudera/hue#822]
when I use pycharm run hue ,i got these errors:
and i executed make install then make apps

/Users/xxx/opensource/hue/build/env/bin/hue runserver 0.0.0.0:8000
pydev debugger: process 19775 is connecting

Connected to pydev debugger (build 181.4445.76)
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/chozee/opensource/hue/build/env/bin/hue", line 11, in <module>
    load_entry_point('desktop', 'console_scripts', 'hue')()
  File "/Users/chozee/opensource/hue-py-env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/chozee/opensource/hue-py-env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2792, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('console_scripts', 'hue') not found
We've got an error while stopping in post-mortem: <type 'exceptions.KeyboardInterrupt'>

**Comment by romainr** [comment]
Do you mean how to use the PyCharm debugger with Hue?

Did you try this trick?
http://cloudera.github.io/hue/latest/developer/development/#debugging-tips-and-tricks

**Comment by jdesjean** [comment]
@chozee, I updated the docs on how to debug with PyCharm: http://cloudera.github.io/hue/latest/developer/development/#debugging-with-pycharm
