### ISSUE TITLE
There was a problem with compiling hue ValueError: The file 'desktop/ext/ext/fonts/huecharts-regular.eot' could not be found 

### ISSUE THREAD

**Issue by IVitamin-C** [cloudera/hue#843]
After downloading the dependency library during the compilation of hue 4.4, running make apps caused an error
Retry after trying to make clean but still no solution
Make install is the same problem

Post-processed 'desktop/ext/css/medium-editor.min.css' as 'desktop/ext/css/medium-editor.min.e708e7c9febc.css'
Post-processing 'desktop/ext/css/hue-charts.css' failed!

Traceback (most recent call last):
  File "/home/hadoop/hue/build/env/bin/hue", line 11, in <module>
    load_entry_point('desktop', 'console_scripts', 'hue')()
  File "/home/hadoop/hue/desktop/core/src/desktop/manage_entry.py", line 216, in entry
    execute_from_command_line(sys.argv)
  File "/home/hadoop/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/hadoop/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/hadoop/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/hadoop/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/hadoop/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/contrib/staticfiles/management/commands/collectstatic.py", line 199, in handle
    collected = self.collect()
  File "/home/hadoop/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/contrib/staticfiles/management/commands/collectstatic.py", line 145, in collect
    raise processed
ValueError: The file 'desktop/ext/ext/fonts/huecharts-regular.eot' could not be found with <django.contrib.staticfiles.storage.CachedStaticFilesStorage object at 0x7f2675a64a50>.
make[1]: Leaving directory '/home/hadoop/hue/apps'

**Comment by JohanAhlen** [comment]
Thanks for reporting this! It should be fixed with https://github.com/cloudera/hue/commit/0074b6a4e416b092d6f65a4fc633e355c3a20880
