### ISSUE TITLE
When I made a query, there was an error and the return value was "KeyError: 'statement'".

### ISSUE THREAD

**Issue by IVitamin-C** [cloudera/hue#845]
hello 
When I made a query, there was an error and the return value was "KeyError: 'statement'".

The command: show databases;

Traceback (most recent call last):
  File "/usr/local/hue/desktop/libs/notebook/src/notebook/decorators.py", line 98, in decorator
    return func(*args, **kwargs)
  File "/usr/local/hue/desktop/libs/notebook/src/notebook/api.py", line 184, in execute
    response = _execute_notebook(request, notebook, snippet)
  File "/usr/local/hue/desktop/libs/notebook/src/notebook/api.py", line 135, in _execute_notebook
    response['handle'] = interpreter.execute(notebook, snippet)
  File "/usr/local/hue/desktop/libs/notebook/src/notebook/connectors/hiveserver2.py", line 81, in decorator
    return func(*args, **kwargs)
  File "/usr/local/hue/desktop/libs/notebook/src/notebook/connectors/hiveserver2.py", line 246, in execute
    query = self._prepare_hql_query(snippet, statement['statement'], session)
KeyError: 'statement'
![image](https://user-images.githubusercontent.com/35019926/56337249-dff85400-61d6-11e9-88dc-b44f42e8081b.png)

**Comment by romainr** [comment]
With which Hue version? Which SQL? Hive?

**Comment by IVitamin-C** [comment]
I'm sorry,
hue version is 4.4   
The same environment and the same amount of hue 4.3 did not have this problem,
SQL:  spark-sql on spark-thriftserver
hadoop 2.8.5
hive 2.3.4
spark 2.3.3

**Comment by IVitamin-C** [comment]
This executed SQL was not found in yarn and this may be the problem of parsing the SQL

**Comment by IVitamin-C** [comment]
hue 4.3
![image](https://user-images.githubusercontent.com/35019926/56371319-7ce6db80-622f-11e9-8509-38e504d4ece8.png)

hue 4.4
![image](https://user-images.githubusercontent.com/35019926/56371389-9b4cd700-622f-11e9-9588-c9f3c86918a0.png)

**Comment by IVitamin-C** [comment]
I'm sorry for wasting your time. I have found the problem that I made a mistake in configuring the parameter of yarn,
I'm sorry.Thanks
