### ISSUE TITLE
hue4.1 config impala with kerberos  TSocket read 0 bytes (code THRIFTTRANSPORT): TTransportException('TSocket read 0 bytes',)

### ISSUE THREAD

**Issue by fishermancome** [cloudera/hue#849]
```
this is my  pseudo_distributed.ini 
[impala]
  # Host of the Impala Server (one of the Impalad)
  server_host=test-cdh4.lddmp.com

  # Port of the Impala Server
  server_port=21050

  # Kerberos principal
  impala_principal=impala/test-cdh4.lddmp.com

  # Turn on/off impersonation mechanism when talking to Impala
  impersonation_enabled=True

  # Number of initial rows of a result set to ask Impala to cache in order
  # to support re-fetching them for downloading them.
  # Set to 0 for disabling the option and backward compatibility.
  ## querycache_rows=50000

  # Timeout in seconds for thrift calls
  server_conn_timeout=120

  # Hue will try to close the Impala query when the user leaves the editor page.
  # This will free all the query resources in Impala, but also make its results inaccessible.
  ## close_queries=true

  # If > 0, the query will be timed out (i.e. cancelled) if Impala does not do any work
  # (compute or send back results) for that query within QUERY_TIMEOUT_S seconds.
  ## query_timeout_s=600

  # If > 0, the session will be timed out (i.e. cancelled) if Impala does not do any work
  # (compute or send back results) for that session within QUERY_TIMEOUT_S seconds (default 1 hour).
  ## session_timeout_s=3600

  # Override the desktop default username and password of the hue user used for authentications with other services.
  # e.g. Used for LDAP/PAM pass-through authentication.
  # auth_username=hue
  # auth_password=

  # A comma-separated list of white-listed Impala configuration properties that users are authorized to set.
  ## config_whitelist=debug_action,explain_level,mem_limit,optimize_partition_key_scans,query_timeout_s,request_pool

  # Path to the impala configuration dir which has impalad_flags file
  impala_conf_dir=${HUE_CONF_DIR}/impala-conf



[[interpreters]]
    # Define the name and how to connect and execute the language.

    [[[hive]]]
      # The name of the snippet.
      name=Hive
      # The backend connection to use to communicate with the server.
      interface=hiveserver2

    [[[impala]]]
      name=Impala
      interface=hiveserver2

```

```
when i open impala editor 
it shows 
```
![image](https://user-images.githubusercontent.com/14890039/56858077-42a3d980-69a7-11e9-80cd-4db2931b7ab6.png)

**Comment by jdesjean** [comment]
Hi Fisherman,

There probably will be more information in the logs. Could you take a look?
How is kerberos in Hue configured [desktop] [[kerberos]]? Can you confirm
that the Impala host / port is reachable from the Hue host?

Cheers,
Jean-Francois

**Comment by jdesjean** [comment]
In addition, do you have haproxy configured for Impala?

**Comment by fishermancome** [comment]
##### Hi, Jean-Francois,  
Thank you for your answer, here is my kerberos configuration.
```
 # Configuration options for Kerberos integration for secured Hadoop clusters
  # ------------------------------------------------------------------------
  [[kerberos]]

    # Path to Hue's Kerberos keytab file
    hue_keytab=/data/local/kerberos/hue.keytab
    # Kerberos principal name for Hue
    hue_principal=hue/test-cdh4.lddmp.com@LDDMP.COM
    # Frequency in seconds with which Hue will renew its keytab
    keytab_reinit_frequency=3600
    # Path to keep Kerberos credentials cached
    cache_path=/var/run/hue/hue_krb5_ccache
    # Path to kinit
    kinit_path=/usr/bin/kinit

    # Mutual authentication from the server, attaches HTTP GSSAPI/Kerberos Authentication to the given Request object
    ## mutual_authentication="OPTIONAL" or "REQUIRED" or "DISABLED"
    #mutual_authentication='OPTIONAL'

```

##### here is the information in the logs 

```
=============********** TSocket read 0 bytes (code THRIFTTRANSPORT): TTransportException('TSocket read 0 bytes',)
[04/May/2019 18:24:55 +0000] decorators   ERROR    Error running <function create_session at 0x7f6d5db14ed8>
Traceback (most recent call last):
  File "/opt/hue-release-4.1.0/desktop/libs/notebook/src/notebook/decorators.py", line 95, in decorator
    return func(*args, **kwargs)
  File "/opt/hue-release-4.1.0/desktop/libs/notebook/src/notebook/api.py", line 84, in create_session
    response['session'] = get_api(request, session).create_session(lang=session['type'], properties=properties)
  File "/opt/hue-release-4.1.0/desktop/libs/notebook/src/notebook/connectors/hiveserver2.py", line 89, in decorator
    raise QueryError(message)
QueryError

```


##### In addition , the impala and hue are in the same server, and i don't have haproxy configured for impala  
##### i am confused about why hive can work well  but impala is not work , they both use hiveserver2?

Cheers,
Fishermancome

**Comment by SnehasishDey** [comment]
Hi @fishermancome,
I'm facing this exact issue right now. 
Would really appreciate if you could share any information on how you fixed it.

Thanks,
Snehasish

**Comment by jdesjean** [comment]
Impala kerberos configuration used to rely (<= 4.4) on 
https://github.com/cloudera/hue/blob/cbfeb03b7303a77f9cc330f3e9e6c52a9e9ec984/desktop/conf.dist/hue.ini#L1104
```
[hadoop]
[[yarn_clusters]]
security_enabled=true
```

In 4.5 with [HUE-8932](https://issues.cloudera.org/browse/HUE-8932), a configuration was added to specify if sasl is enabled:
https://github.com/cloudera/hue/blob/cbfeb03b7303a77f9cc330f3e9e6c52a9e9ec984/desktop/conf.dist/hue.ini#L1321
```
[impala]
use_sasl
```
