### ISSUE TITLE
Hue 4.4, UI won't load

### ISSUE THREAD

**Issue by johnseekins** [cloudera/hue#851]
Trying to deploy Hue 4.4.0, I run the following to build/install it:
`JAVA_HOME=/usr/jdk64/jdk1.8.0_201/ make install`

This completes successfully, but when I try to open the UI, I get the following stack trace:
```
Traceback (most recent call last):
  File "/usr/local/hue/desktop/core/src/desktop/lib/wsgiserver.py", line 1215, in communicate
    req.respond()
  File "/usr/local/hue/desktop/core/src/desktop/lib/wsgiserver.py", line 576, in respond
    self._respond()
  File "/usr/local/hue/desktop/core/src/desktop/lib/wsgiserver.py", line 588, in _respond
    response = self.wsgi_app(self.environ, self.start_response)
  File "/usr/local/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/usr/local/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/usr/local/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/handlers/exception.py", line 143, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/usr/local/hue/desktop/core/src/desktop/views.py", line 413, in serve_500_error
    return render("500.mako", request, {'traceback': traceback.extract_tb(exc_info[2])})
  File "/usr/local/hue/desktop/core/src/desktop/lib/django_util.py", line 231, in render
    **kwargs)
  File "/usr/local/hue/desktop/core/src/desktop/lib/django_util.py", line 148, in _render_to_response
    return django_mako.render_to_response(template, *args, **kwargs)
  File "/usr/local/hue/desktop/core/src/desktop/lib/django_mako.py", line 127, in render_to_response
    return HttpResponse(render_to_string(template_name, data_dictionary), **kwargs)
  File "/usr/local/hue/desktop/core/src/desktop/lib/django_mako.py", line 116, in render_to_string_normal
    result = template.render(**data_dict)
  File "/usr/local/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/local/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/local/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/local/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "/tmp/tmpWWQXa6/desktop/500.mako.py", line 40, in render_body
    __M_writer(unicode( commonheader(_('500 - Server error'), "", user, request) ))
  File "/usr/local/hue/desktop/core/src/desktop/views.py", line 491, in commonheader
    'banner_message': get_banner_message(request)
  File "/usr/local/hue/desktop/core/src/desktop/lib/django_mako.py", line 116, in render_to_string_normal
    result = template.render(**data_dict)
  File "/usr/local/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/local/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/local/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/local/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "/tmp/tmpWWQXa6/desktop/common_header.mako.py", line 180, in render_body
    __M_writer(unicode( render_bundle('vendors~hue~notebook') ))
  File "/usr/local/hue/build/env/local/lib/python2.7/site-packages/django_webpack_loader-0.6.0-py2.7.egg/webpack_loader/templatetags/webpack_loader.py", line 12, in render_bundle
    tags = utils.get_as_tags(bundle_name, extension=extension, config=config, attrs=attrs)
  File "/usr/local/hue/build/env/local/lib/python2.7/site-packages/django_webpack_loader-0.6.0-py2.7.egg/webpack_loader/utils.py", line 45, in get_as_tags
    bundle = _get_bundle(bundle_name, extension, config)
  File "/usr/local/hue/build/env/local/lib/python2.7/site-packages/django_webpack_loader-0.6.0-py2.7.egg/webpack_loader/utils.py", line 23, in _get_bundle
    bundle = get_loader(config).get_bundle(bundle_name)
  File "/usr/local/hue/build/env/local/lib/python2.7/site-packages/django_webpack_loader-0.6.0-py2.7.egg/webpack_loader/loader.py", line 60, in get_bundle
    assets = self.get_assets()
  File "/usr/local/hue/build/env/local/lib/python2.7/site-packages/django_webpack_loader-0.6.0-py2.7.egg/webpack_loader/loader.py", line 37, in get_assets
    self._assets[self.name] = self._load_assets()
  File "/usr/local/hue/build/env/local/lib/python2.7/site-packages/django_webpack_loader-0.6.0-py2.7.egg/webpack_loader/loader.py", line 32, in _load_assets
    self.config['STATS_FILE']))
IOError: Error reading /usr/local/hue/webpack-stats.json. Are you sure webpack has generated the file and the path is correct?
```
Obviously, the `webpack-stats.json` file is missing. So, if I run the following:
```
JAVA_HOME=/usr/jdk64/jdk1.8.0_201/ make apps
JAVA_HOME=/usr/jdk64/jdk1.8.0_201/ make install
```
`webpack-stats.json` is generated and that error no longer occurs. But a cool _new_ problem occurs: The UI loads a completely empty page. Looking in the console, I see errors about missing jquery, i18n, and other javascript libraries.

Am I missing an obvious build step? Some library?

Notes:
Host: Ubuntu 16.04
Node: 8.16.0
Hue 4.3.0 built successfully on the same host.

**Comment by johnseekins** [comment]
A bit of clarification:

After building apps, the login screen _does_ load, it's only on an attempted login that I get a blank screen.

Attached is an example console output after the page failure.[
![20190501-0923](https://user-images.githubusercontent.com/5665929/57024921-02d13200-6bf3-11e9-824b-d638779f915f.png)
](url)

**Comment by jdesjean** [comment]
@johnseekins, I would delete your Hue folder, get a fresh copy, make sure you have all the dependencies http://cloudera.github.io/hue/latest/administrator/installation/dependencies/#ubuntu and run make apps.

**Comment by johnseekins** [comment]
Yes. I've installed all dependencies, and you _have_ to delete the Hue directory to re-install:

Dependencies:
```
~# dpkg -l | grep -E "git|ant|gcc|g\+\+|libffi-dev|libkrb5-dev|libmysqlclient-dev|libsasl2-dev|libsasl2-modules-gssapi-mit|libsqlite3-dev|libssl-dev|libxml2-dev|libxslt-dev|make|maven|libldap2-dev|python-dev|python-setuptools|libgmp3-dev|nodejs"
ii  ant                                           1.9.6-1ubuntu1.1                           all          Java based build tool like make
ii  g++                                           4:5.3.1-1ubuntu1                           amd64        GNU C++ compiler
ii  gcc                                           4:5.3.1-1ubuntu1                           amd64        GNU C compiler
ii  git                                           1:2.7.4-0ubuntu1.6                         amd64        fast, scalable, distributed revision control system
ii  libffi-dev:amd64                              3.2.1-4                                    amd64        Foreign Function Interface library (development files)
ii  libgmp3-dev                                   2:6.1.0+dfsg-2                             amd64        Multiprecision arithmetic library developers tools
ii  libkrb5-dev                                   1.13.2+dfsg-5ubuntu2.1                     amd64        Headers and development libraries for MIT Kerberos
ii  libldap2-dev:amd64                            2.4.42+dfsg-2ubuntu3.4                     amd64        OpenLDAP development libraries
ii  libmysqlclient-dev                            5.7.25-0ubuntu0.16.04.2                    amd64        MySQL database development files
ii  libsasl2-dev                                  2.1.26.dfsg1-14ubuntu0.1                   amd64        Cyrus SASL - development files for authentication abstraction library
ii  libsasl2-modules-gssapi-mit:amd64             2.1.26.dfsg1-14ubuntu0.1                   amd64        Cyrus SASL - pluggable authentication modules (GSSAPI)
ii  libsqlite3-dev:amd64                          3.11.0-1ubuntu1.1                          amd64        SQLite 3 development files
ii  libssl-dev:amd64                              1.0.2g-1ubuntu4.15                         amd64        Secure Sockets Layer toolkit - development files
ii  libxml2-dev:amd64                             2.9.3+dfsg1-1ubuntu0.6                     amd64        Development files for the GNOME XML library
ii  make                                          4.1-6                                      amd64        utility for directing compilation
ii  maven                                         3.3.9-3                                    all          Java software project management and comprehension tool
ii  nodejs                                        8.16.0-1nodesource1                        amd64        Node.js event-based server-side javascript engine
ii  python-dev                                    2.7.12-1~16.04                             amd64        header files and a static library for Python (default)
ii  python-setuptools                             20.7.0-1                                   all          Python Distutils Enhancements
```

Following your suggestion produces the same errors.

**Comment by alericmckearn** [comment]
sorry for the ansible commands but you get the gist..

there were 2 webpack commands.  i still have one 500 screen which is making
me think we might have a 3rd.

- name: execute some commands for webpack
command: "{{ web }}"
loop:
- /data/hue/node_modules/.bin/webpack
- /data/hue/node_modules/.bin/webpack --config='webpack.config.login.js'
loop_control:
loop_var: web
- name: execute make command
make:
target: clean install
chdir: /data/hue
- name: copy webpack files
copy:
remote_src: yes
src: "{{ web1 }}"
dest: /usr/local/hue/
loop:
- /data/hue/webpack-stats-login.json
- /data/hue/webpack-stats.json
loop_control:
loop_var: web1

**Comment by johnseekins** [comment]
So just so I'm clear, that "evaluates" to:
```
~# /data/hue/node_modules/.bin/webpack
~# /data/hue/node_modules/.bin/webpack --config='webpack.config.login.js'
~# cd /data/hue
~# make clean install
~# cp /data/hue/webpack-stats-login.json /usr/local/hue/
~# cp /data/hue/webpack-stats.json /usr/local/hue/
```
I assume this is _after_ a `make apps` call?

**Comment by johnseekins** [comment]
Ah. `make apps` calls the following webpack commands:
```
webpack --config webpack.config.js
webpack --config webpack.config.login.js
webpack --config webpack.config.workers.js
```
So perhaps `webpack.config.workers.js` is what you're missing @alericmckearn ?

**Comment by johnseekins** [comment]
Turns out I had some bad cookies. Following @alericmckearn 's suggestions worked. Thanks for the tips, everyone.
