### ISSUE TITLE
Erorr with Docker image 4.4.0

### ISSUE THREAD

**Issue by gschmutz** [cloudera/hue#855]
When I run the latest image (which is Hue 4.3.0) of the Hue docker image in Docker hub it works fine

```
docker run -it -p 38888:8888 -v $PWD/tools/docker/hue/hue.ini:/usr/share/hue/desktop/conf/hue.ini --network amundsen-atlas_default gethue/hue
```

But when I switch to version 4.4.0 (tag 4.4.0)

```
docker run -it -p 38888:8888 -v $PWD/tools/docker/hue/hue.ini:/usr/share/hue/desktop/conf/hue.ini --network amundsen-atlas_default gethue/hue:4.4.0
```

then I get the following error:

```
[03/May/2019 03:00:43 -0700] decorators   INFO     AXES: Calling decorated function: dt_login
[03/May/2019 03:00:43 -0700] decorators   INFO     args: (True,)
[03/May/2019 03:00:43 -0700] access       INFO     192.168.73.1 -anon- - "GET /hue/accounts/login HTTP/1.1" returned in 57ms
[03/May/2019 03:00:43 -0700] access       INFO     192.168.73.1 -anon- - "GET /hue/accounts/login HTTP/1.1" returned in 57ms
[03/May/2019 03:00:43 -0700] decorators   INFO     AXES: Calling decorated function: dt_login
[03/May/2019 03:00:43 -0700] middleware   INFO     Processing exception: Error reading /usr/share/hue/webpack-stats-login.json. Are you sure webpack has generated the file and the path is correct?: Traceback (most recent call last):
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/django_axes-2.2.0-py2.7.egg/axes/decorators.py", line 271, in decorated_login
    response = func(request, *args, **kwargs)
  File "/usr/share/hue/desktop/core/src/desktop/auth/views.py", line 195, in dt_login
    'user': request.user
  File "/usr/share/hue/desktop/core/src/desktop/lib/django_util.py", line 231, in render
    **kwargs)
  File "/usr/share/hue/desktop/core/src/desktop/lib/django_util.py", line 148, in _render_to_response
    return django_mako.render_to_response(template, *args, **kwargs)
  File "/usr/share/hue/desktop/core/src/desktop/lib/django_mako.py", line 127, in render_to_response
    return HttpResponse(render_to_string(template_name, data_dictionary), **kwargs)
  File "/usr/share/hue/desktop/core/src/desktop/lib/django_mako.py", line 116, in render_to_string_normal
    result = template.render(**data_dict)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "/tmp/tmpCqZYw9/desktop/login.mako.py", line 56, in render_body
    __M_writer(unicode( commonheader(_("Welcome to Hue"), "login", user, request, "50px", True, True) ))
  File "/usr/share/hue/desktop/core/src/desktop/views.py", line 491, in commonheader
    'banner_message': get_banner_message(request)
  File "/usr/share/hue/desktop/core/src/desktop/lib/django_mako.py", line 116, in render_to_string_normal
    result = template.render(**data_dict)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "/tmp/tmpCqZYw9/desktop/common_header.mako.py", line 176, in render_body
    __M_writer(unicode( render_bundle('login', config='LOGIN') ))
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/django_webpack_loader-0.6.0-py2.7.egg/webpack_loader/templatetags/webpack_loader.py", line 12, in render_bundle
    tags = utils.get_as_tags(bundle_name, extension=extension, config=config, attrs=attrs)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/django_webpack_loader-0.6.0-py2.7.egg/webpack_loader/utils.py", line 45, in get_as_tags
    bundle = _get_bundle(bundle_name, extension, config)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/django_webpack_loader-0.6.0-py2.7.egg/webpack_loader/utils.py", line 23, in _get_bundle
    bundle = get_loader(config).get_bundle(bundle_name)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/django_webpack_loader-0.6.0-py2.7.egg/webpack_loader/loader.py", line 60, in get_bundle
    assets = self.get_assets()
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/django_webpack_loader-0.6.0-py2.7.egg/webpack_loader/loader.py", line 37, in get_assets
    self._assets[self.name] = self._load_assets()
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/django_webpack_loader-0.6.0-py2.7.egg/webpack_loader/loader.py", line 32, in _load_assets
    self.config['STATS_FILE']))
IOError: Error reading /usr/share/hue/webpack-stats-login.json. Are you sure webpack has generated the file and the path is correct?

[03/May/2019 03:00:43 -0700] exception    ERROR    Internal Server Error: /hue/accounts/login
Traceback (most recent call last):
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/django_axes-2.2.0-py2.7.egg/axes/decorators.py", line 271, in decorated_login
    response = func(request, *args, **kwargs)
  File "/usr/share/hue/desktop/core/src/desktop/auth/views.py", line 195, in dt_login
    'user': request.user
  File "/usr/share/hue/desktop/core/src/desktop/lib/django_util.py", line 231, in render
    **kwargs)
  File "/usr/share/hue/desktop/core/src/desktop/lib/django_util.py", line 148, in _render_to_response
    return django_mako.render_to_response(template, *args, **kwargs)
  File "/usr/share/hue/desktop/core/src/desktop/lib/django_mako.py", line 127, in render_to_response
    return HttpResponse(render_to_string(template_name, data_dictionary), **kwargs)
  File "/usr/share/hue/desktop/core/src/desktop/lib/django_mako.py", line 116, in render_to_string_normal
    result = template.render(**data_dict)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "/tmp/tmpCqZYw9/desktop/login.mako.py", line 56, in render_body
    __M_writer(unicode( commonheader(_("Welcome to Hue"), "login", user, request, "50px", True, True) ))
  File "/usr/share/hue/desktop/core/src/desktop/views.py", line 491, in commonheader
    'banner_message': get_banner_message(request)
  File "/usr/share/hue/desktop/core/src/desktop/lib/django_mako.py", line 116, in render_to_string_normal
    result = template.render(**data_dict)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "/tmp/tmpCqZYw9/desktop/common_header.mako.py", line 176, in render_body
    __M_writer(unicode( render_bundle('login', config='LOGIN') ))
```

**Comment by romainr** [comment]
Indeed, we should re-update the image there. Should be done Monday end of day PST

**Comment by playwolf719** [comment]
> Indeed, we should re-update the image there. Should be done Monday end of day PST

@romainr do you fix it？ I get the same issue.

**Comment by playwolf719** [comment]
@gschmutz What you gonna do about it?

**Comment by gschmutz** [comment]
@playwolf719 I'm still running on 4.3.0 but will re-try 4.4.0 once it is re-built

**Comment by romainr** [comment]
4.4.0 was rebuilt (note: it contains more than 4.4 release per se). There is more to fix in the docker images because of how webpack is used but it should be good now. If people can confirm, I can update latest too.

`sudo docker run -it -p 8888:8888 -v $HOME/projects/hue/desktop/conf/pseudo-distributed.ini:/usr/share/hue/desktop/conf/z-hue.ini --network="host" gethue/hue:4.4.0`

**Comment by cctanfujun** [comment]
i build the master code use docekr file, it build success,but when i start it, i got error.

```
Traceback (most recent call last):
  File "/usr/share/hue/desktop/core/src/desktop/lib/wsgiserver.py", line 1215, in communicate
    req.respond()
  File "/usr/share/hue/desktop/core/src/desktop/lib/wsgiserver.py", line 576, in respond
    self._respond()
  File "/usr/share/hue/desktop/core/src/desktop/lib/wsgiserver.py", line 588, in _respond
    response = self.wsgi_app(self.environ, self.start_response)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/core/handlers/exception.py", line 143, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/usr/share/hue/desktop/core/src/desktop/views.py", line 413, in serve_500_error
    return render("500.mako", request, {'traceback': traceback.extract_tb(exc_info[2])})
  File "/usr/share/hue/desktop/core/src/desktop/lib/django_util.py", line 234, in render
    **kwargs)
  File "/usr/share/hue/desktop/core/src/desktop/lib/django_util.py", line 148, in _render_to_response
    return django_mako.render_to_response(template, *args, **kwargs)
  File "/usr/share/hue/desktop/core/src/desktop/lib/django_mako.py", line 127, in render_to_response
    return HttpResponse(render_to_string(template_name, data_dictionary), **kwargs)
  File "/usr/share/hue/desktop/core/src/desktop/lib/django_mako.py", line 116, in render_to_string_normal
    result = template.render(**data_dict)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "/tmp/tmp7Mz94n/desktop/500.mako.py", line 40, in render_body
    __M_writer(unicode( commonheader(_('500 - Server error'), "", user, request) ))
  File "/usr/share/hue/desktop/core/src/desktop/views.py", line 491, in commonheader
    'banner_message': get_banner_message(request)
  File "/usr/share/hue/desktop/core/src/desktop/lib/django_mako.py", line 116, in render_to_string_normal
    result = template.render(**data_dict)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "/tmp/tmp7Mz94n/desktop/common_header.mako.py", line 180, in render_body
    __M_writer(unicode( render_bundle('vendors~hue~notebook') ))
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/django_webpack_loader-0.6.0-py2.7.egg/webpack_loader/templatetags/webpack_loader.py", line 12, in render_bundle
    tags = utils.get_as_tags(bundle_name, extension=extension, config=config, attrs=attrs)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/django_webpack_loader-0.6.0-py2.7.egg/webpack_loader/utils.py", line 45, in get_as_tags
    bundle = _get_bundle(bundle_name, extension, config)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/django_webpack_loader-0.6.0-py2.7.egg/webpack_loader/utils.py", line 23, in _get_bundle
    bundle = get_loader(config).get_bundle(bundle_name)
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/django_webpack_loader-0.6.0-py2.7.egg/webpack_loader/loader.py", line 60, in get_bundle
    assets = self.get_assets()
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/django_webpack_loader-0.6.0-py2.7.egg/webpack_loader/loader.py", line 37, in get_assets
    self._assets[self.name] = self._load_assets()
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/django_webpack_loader-0.6.0-py2.7.egg/webpack_loader/loader.py", line 32, in _load_assets
    self.config['STATS_FILE']))
IOError: Error reading /usr/share/hue/webpack-stats.json. Are you sure webpack has generated the file and the path is correct?
```

**Comment by romainr** [comment]
You would need https://review.cloudera.org/r/13933/ as of today. Note that this will be reverted and moved to the Makefile itself soon

**Comment by cctanfujun** [comment]
> You would need https://review.cloudera.org/r/13933/ as of today. Note that this will be reverted and moved to the Makefile itself soon



> You would need https://review.cloudera.org/r/13933/ as of today. Note that this will be reverted and moved to the Makefile itself soon

i checkout to HUE-8687_jahlen, and update dockerfile as your commit,the docker build, i can't build it success, and got

```
> hue@4.4.0 webpack /usr/share/hue
> webpack --config webpack.config.js

clean-webpack-plugin: /usr/share/hue/desktop/core/src/desktop/static/desktop/js/bundles has been removed.
[BABEL] Note: The code generator has deoptimised the styling of /usr/share/hue/desktop/core/src/desktop/js/sql/parse/sqlSyntaxParser.js as it exceeds the max of 500KB.
Killed
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! hue@4.4.0 webpack: `webpack --config webpack.config.js`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the hue@4.4.0 webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-08T04_38_37_371Z-debug.log
The command '/bin/sh -c npm run webpack' returned a non-zero code: 137
```

**Comment by playwolf719** [comment]
> @playwolf719 I'm still running on 4.3.0 but will re-try 4.4.0 once it is re-built

I solved it by making a total new dockerfile , directly use the commond to intall hue.
You have to enter into the container to run. Then commit the container to be the image that you want. Maybe the way is terrible, but anyway it works.

````
FROM rtfpessoa/ubuntu-jdk8

RUN apt-get update -y && apt-get install -y \
  build-essential \
  libkrb5-dev \
  libmysqlclient-dev \
  libssl-dev \
  libsasl2-dev \
  libsasl2-modules-gssapi-mit \
  libsqlite3-dev \
  libtidy-dev \
  libxml2-dev \
  libxslt-dev \
  libffi-dev \
  libldap2-dev \
  libpq-dev \
  python-dev \
  python-setuptools \
  libgmp3-dev \
  libz-dev \
  software-properties-common \
  curl \
  git \
  rsync \
  sudo \
  maven \
  gcc \
  swig \
  openssl \
  xmlsec1 \
  libxmlsec1-openssl \
   && rm -rf /var/lib/apt/lists/*


COPY hue-master /tmphue
WORKDIR /tmphue

RUN curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
RUN apt-get install -y nodejs


````

**Comment by cctanfujun** [comment]
> > @playwolf719 I'm still running on 4.3.0 but will re-try 4.4.0 once it is re-built
> 
> I solved it by making a total new dockerfile , directly use the commond to intall hue.
> You have to enter into the container to run it. Then commit the container to be the image that you want. Maybe the way is terrible, anyway it works.
> 
> ```
> FROM rtfpessoa/ubuntu-jdk8
> 
> RUN apt-get update -y && apt-get install -y \
>   build-essential \
>   libkrb5-dev \
>   libmysqlclient-dev \
>   libssl-dev \
>   libsasl2-dev \
>   libsasl2-modules-gssapi-mit \
>   libsqlite3-dev \
>   libtidy-dev \
>   libxml2-dev \
>   libxslt-dev \
>   libffi-dev \
>   libldap2-dev \
>   libpq-dev \
>   python-dev \
>   python-setuptools \
>   libgmp3-dev \
>   libz-dev \
>   software-properties-common \
>   curl \
>   git \
>   rsync \
>   sudo \
>   maven \
>   gcc \
>   swig \
>   openssl \
>   xmlsec1 \
>   libxmlsec1-openssl \
>    && rm -rf /var/lib/apt/lists/*
> 
> 
> COPY hue-master /tmphue
> WORKDIR /tmphue
> 
> RUN curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
> RUN apt-get install -y nodejs
> ```

which branch should i use for your new dockerfile?

**Comment by playwolf719** [comment]
@cctanfujun Just copy it as your dockerfile.

**Comment by cctanfujun** [comment]
> @cctanfujun Just copy it as your dockerfile.

i switch to master and then change the docekrfile,

run 
```
sudo docker build . -t hue -f tools/docker/hue/Dockerfile
```
i got

```
Sending build context to Docker daemon  1.068GB
Step 1/6 : FROM rtfpessoa/ubuntu-jdk8
 ---> bab88b01cff9
Step 2/6 : RUN apt-get update -y && apt-get install -y   build-essential   libkrb5-dev   libmysqlclient-dev   libssl-dev   libsasl2-dev   libsasl2-modules-gssapi-mit   libsqlite3-dev   libtidy-dev   libxml2-dev   libxslt-dev   libffi-dev   libldap2-dev   libpq-dev   python-dev   python-setuptools   libgmp3-dev   libz-dev   software-properties-common   curl   git   rsync   sudo   maven   gcc   swig   openssl   xmlsec1   libxmlsec1-openssl    && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 8cb2e79ff403
Step 3/6 : COPY hue-master /tmphue
COPY failed: stat /var/lib/docker/tmp/docker-builder516525229/hue-master: no such file or directory
```

**Comment by gschmutz** [comment]
@romainr I have switched to the latest 4.4.0 and a quick test shows that it now works. Thanks a lot!

**Comment by playwolf719** [comment]
@romainr Awesome, man!

**Comment by romainr** [comment]
Happy to hear!

https://github.com/cloudera/hue/commit/e7c7c55624cf0ea443708c5748d412955b8f5499

**Comment by cctanfujun** [comment]
> Happy to hear!
> 
> [e7c7c55](https://github.com/cloudera/hue/commit/e7c7c55624cf0ea443708c5748d412955b8f5499)

also build fail

```
Step 15/24 : RUN npm run webpack
 ---> Running in da921f186204


> hue@4.4.0 webpack /usr/share/hue
> webpack --config webpack.config.js

clean-webpack-plugin: /usr/share/hue/desktop/core/src/desktop/static/desktop/js/bundles/hue has been removed.
Killed
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! hue@4.4.0 webpack: `webpack --config webpack.config.js`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the hue@4.4.0 webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-15T06_00_56_837Z-debug.log
The command '/bin/sh -c npm run webpack' returned a non-zero code: 137

```
