### ISSUE TITLE
submit PySpark: ImportError: No module named numpy

### ISSUE THREAD

**Issue by digitalbull** [cloudera/hue#863]
After setup notebook PySpark environment, we tested submit .py file to spark, the code can be executed successfully until ```import numpy```.

```
Traceback (most recent call last):
  File "/var/yarn/nm/usercache/cdh/appcache/application_1557806010595_0008/container_1557806010595_0008_01_000001/test.py", line 75, in <module>
    from pyspark.ml.linalg import Vectors
  File "/var/yarn/nm/usercache/cdh/appcache/application_1557806010595_0008/container_1557806010595_0008_01_000001/python/lib/pyspark.zip/pyspark/ml/__init__.py", line 22, in <module>
  File "/var/yarn/nm/usercache/cdh/appcache/application_1557806010595_0008/container_1557806010595_0008_01_000001/python/lib/pyspark.zip/pyspark/ml/base.py", line 24, in <module>
  File "/var/yarn/nm/usercache/cdh/appcache/application_1557806010595_0008/container_1557806010595_0008_01_000001/python/lib/pyspark.zip/pyspark/ml/param/__init__.py", line 26, in <module>
ImportError: No module named numpy
```

the same code can be executed in nodebook environment.

what we have done is described in the link:
https://community.cloudera.com/t5/Advanced-Analytics-Apache-Spark/ImportError-No-module-named-numpy/m-p/90312#M3731

The same job can be submitted manually. And executed successfully.

```
export SPARK_HOME=/opt/cloudera/parcels/CDH/lib/spark
export HADOOP_CONF_DIR=/etc/alternatives/hadoop-conf
PYSPARK_PYTHON=/opt/cloudera/parcels/Anaconda/bin/python spark-submit test.py
```

The full job log come from hue is in log.txt.
[log.txt](https://github.com/cloudera/hue/files/3176469/log.txt)

**Comment by digitalbull** [comment]
found solution here  https://stackoverflow.com/questions/46857090/adding-pyspark-python-path-in-oozie.
