### ISSUE TITLE
Unsupported mechanism type PLAIN

### ISSUE THREAD

**Issue by lvchongyi** [cloudera/hue#934]
Hue connection with the hive with kerberos on the hive editor page 
ERROR:

StructuredThriftTransportException: Bad status: 3 (Unsupported mechanism type PLAIN) (code THRIFTTRANSPORT): TTransportException('Bad status: 3 (Unsupported mechanism type PLAIN)',)

What is the solution to this situation? thank you!

**Comment by lvchongyi** [comment]
this is ERROR:

[30/Jul/2019 18:58:28 -0700] decorators   ERROR    error running <function create_session at 0x7f7d05ddb0c8>
Traceback (most recent call last):
  File "/usr/lib/hue/desktop/libs/notebook/src/notebook/decorators.py", line 78, in decorator
    return func(*args, **kwargs)
  File "/usr/lib/hue/desktop/libs/notebook/src/notebook/api.py", line 54, in create_session
    response['session'] = get_api(request, session).create_session(lang=session['type'], properties=properties)
  File "/usr/lib/hue/desktop/libs/notebook/src/notebook/connectors/hiveserver2.py", line 49, in decorator
    return func(*args, **kwargs)
  File "/usr/lib/hue/desktop/libs/notebook/src/notebook/connectors/hiveserver2.py", line 68, in create_session
    session = dbms.get(self.user, query_server=get_query_server_config(name=lang)).open_session(self.user)
  File "/usr/lib/hue/apps/beeswax/src/beeswax/server/dbms.py", line 290, in open_session
    return self.client.open_session(user)
  File "/usr/lib/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 1129, in open_session
    return self._client.open_session(user)
  File "/usr/lib/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 583, in open_session
    res = self._client.OpenSession(req)
  File "/usr/lib/hue/desktop/core/src/desktop/lib/thrift_util.py", line 378, in wrapper
    raise StructuredThriftTransportException(e, error_code=502)
StructuredThriftTransportException: Bad status: 3 (Unsupported mechanism type PLAIN) (code THRIFTTRANSPORT): TTransportException('Bad status: 3 (Unsupported mechanism type PLAIN)',)
