### ISSUE TITLE
Blacklisting beeswax and oozie throws errors and prevents startup 4.5.0

### ISSUE THREAD

**Issue by stefanm7** [cloudera/hue#948]
When disabling beeswax and oozie like shown on this documentation-page: http://gethue.com/mini-how-to-disabling-some-apps-from-showing-up/
with
`app_blacklist=beeswax,impala,security,filebrowser,jobbrowser,rdbms,jobsub,pig,hbase,sqoop,zookeeper,metastore,spark,oozie,indexer`

the following errors are thrown on hue-startup:
 `RuntimeError: Model class beeswax.models.QueryHistory doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.`
and 
`Oozie application is not enabled: Model class oozie.models.Job doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.`

Version is 4.5.0

**Comment by romainr** [comment]
While not perfect his should not affect Hue from running normally though

**Comment by stefanm7** [comment]
I am using the hue-docker image gethue/hue:4.5.0 and it does shutdown if this error is thrown.
I attached the log of the hue-container.

**Comment by romainr** [comment]
beeswax should not be blacklisted very probably as it is a core lib. It was replaced by 'hive', could you switch beeswax with 'hive' in the app_blacklist?

**Comment by szitnik** [comment]
Yes, beeswax and oozie should not be blacklisted obviously.

**Comment by AndreyEmelyanenko** [comment]
HUE 4.5. Blacklist is empty. Facing the same error. Can't start hue. Traceback after `/usr/lib/hue/build/env/bin/supervisor`:

$ /usr/lib/hue/build/env/bin/supervisor
[INFO] Not running as root, skipping privilege drop
[21/Oct/2019 12:31:54 +0000] settings     DEBUG    DESKTOP_DB_TEST_NAME SET: /usr/lib/hue/desktop/desktop-test.db
[21/Oct/2019 12:31:54 +0000] settings     DEBUG    DESKTOP_DB_TEST_USER SET: hue_test
[21/Oct/2019 12:31:54 +0000] settings     DEBUG    DESKTOP_DB_TEST_NAME SET: /usr/lib/hue/desktop/desktop-test.db
[21/Oct/2019 12:31:54 +0000] settings     DEBUG    DESKTOP_DB_TEST_USER SET: hue_test
[21/Oct/2019 05:31:57 +0000] decorators   INFO     AXES: BEGIN LOG
[21/Oct/2019 05:31:57 +0000] decorators   INFO     Using django-axes 2.2.0
[21/Oct/2019 05:31:57 +0000] decorators   INFO     AXES: BEGIN LOG
[21/Oct/2019 05:31:57 +0000] decorators   INFO     Using django-axes 2.2.0
Traceback (most recent call last):
  File "/usr/lib/hue/build/env/bin/hue", line 14, in <module>
Traceback (most recent call last):
  File "/usr/lib/hue/build/env/bin/hue", line 14, in <module>
    load_entry_point('desktop', 'console_scripts', 'hue')()
  File "/usr/lib/hue/desktop/core/src/desktop/manage_entry.py", line 219, in entry
    load_entry_point('desktop', 'console_scripts', 'hue')()
  File "/usr/lib/hue/desktop/core/src/desktop/manage_entry.py", line 219, in entry
    execute_from_command_line(sys.argv)
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/management/__init__.py", line 364, in execute_from_command_line
    execute_from_command_line(sys.argv)
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/management/base.py", line 283, in run_from_argv
    utility.execute()
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/management/base.py", line 327, in execute
    self.check()
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/checks/registry.py", line 81, in run_checks
    self.execute(*args, **cmd_options)
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/management/base.py", line 327, in execute
    self.check()
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/checks/urls.py", line 16, in check_url_config
    new_errors = check(app_configs=app_configs)
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/urls/resolvers.py", line 256, in check
    return check_resolver(resolver)
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/utils/functional.py", line 35, in __get__
    for pattern in self.url_patterns:
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/hue/desktop/core/src/desktop/urls.py", line 50, in <module>
    __import__(name)
  File "/usr/lib/hue/desktop/core/src/desktop/urls.py", line 50, in <module>
    from desktop.configuration import api as desktop_configuration_api
  File "/usr/lib/hue/desktop/core/src/desktop/configuration/api.py", line 32, in <module>
    from desktop.configuration import api as desktop_configuration_api
  File "/usr/lib/hue/desktop/core/src/desktop/configuration/api.py", line 32, in <module>
    from notebook.connectors.hiveserver2 import HiveConfiguration, ImpalaConfiguration
  File "/usr/lib/hue/desktop/libs/notebook/src/notebook/connectors/hiveserver2.py", line 48, in <module>
    from notebook.connectors.hiveserver2 import HiveConfiguration, ImpalaConfiguration
  File "/usr/lib/hue/desktop/libs/notebook/src/notebook/connectors/hiveserver2.py", line 48, in <module>
    from beeswax.api import _autocomplete, _get_sample_data
  File "/usr/lib/hue/apps/beeswax/src/beeswax/api.py", line 39, in <module>
    from beeswax.api import _autocomplete, _get_sample_data
  File "/usr/lib/hue/apps/beeswax/src/beeswax/api.py", line 39, in <module>
    import beeswax.models
  File "/usr/lib/hue/apps/beeswax/src/beeswax/models.py", line 51, in <module>
    import beeswax.models
  File "/usr/lib/hue/apps/beeswax/src/beeswax/models.py", line 51, in <module>
    class QueryHistory(models.Model):
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/db/models/base.py", line 118, in __new__
    class QueryHistory(models.Model):
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.22-py2.7.egg/django/db/models/base.py", line 118, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class beeswax.models.QueryHistory doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class beeswax.models.QueryHistory doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

**Comment by oisinBates** [comment]
I encountered the same issue with `beeswax` via the Hue Docker image.
[The Hue documentation is still providing an example with beeswax and oozie](https://gethue.com/mini-how-to-disabling-some-apps-from-showing-up/). It would be useful to remove it from the documentation.
