### ISSUE TITLE
Presto over HTTPS from HUE throws SSL Exception

### ISSUE THREAD

**Issue by sandredd** [cloudera/hue#950]
If https is enabled in PRESTO then presto cli from HUE throws SSL Exception. Hue doesnt read properties/options like SSL, SSLKEYSTOREPATH, SSLKEYSTOREPASSWORD. 

Error says cant make connection with username and password and SSL is false

**Comment by sandeepreddy3647** [comment]
After making change in following python files i see HUE reads SSL=TRUE but throws different exception.

librdms/jdbc.py

 def __init__(self, driver_name, url, username, password, ssl, impersonation_property=None, impersonation_user=None):
   self.jdbc_driver = driver_name
    self.db_url = url
    self.username = username
    self.password = password 
    self.ssl = ssl

  def connect(self):
    if self.conn is None:
      self.gateway.jvm.Class.forName(self.jdbc_driver)
      self.conn = self.gateway.jvm.java.sql.DriverManager.getConnection(self.db_url, self.username, self.password, self.ssl)


notebook/connectors/jdbc.py

      self.db = API_CACHE[self.cache_key] = Jdbc(self.options['driver'], self.options['url'], username, self.options['password'], impersonation_property=impersonation_property, impersonation_user=user.username, self.options['ssl'])


    if self.db is None or not self.db.test_connection(throw_exception='password' not in properties):
      if 'password' in properties:
        user = properties.get('user') or self.options.get('user')
        props['properties'] = {'user': user}
        self.db = API_CACHE[self.cache_key] = Jdbc(self.options['driver'], self.options['url'], user, properties.pop('password'), self.options['ssl'])
        self.db.test_connection(throw_exception=True)


Please let me know if i'm missing something. I can create PR based on the suggestions. Thanks for the help.


ERROR:

[20/Aug/2019 20:18:49 -0700] java_gateway DEBUG    Answer received: xspy4j.Py4JException: Method getConnection([class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.String]) does not exist\n	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:335)\n	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:360)\n	at py4j.Gateway.invoke(Gateway.java:254)\n	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)\n	at py4j.commands.CallCommand.execute(CallCommand.java:79)\n	at py4j.GatewayConnection.run(GatewayConnection.java:209)\n	at java.lang.Thread.run(Thread.java:748)\n
[20/Aug/2019 20:18:49 -0700] decorators   ERROR    Error running create_session
Traceback (most recent call last):
  File "/hadoop01/hue/desktop/libs/notebook/src/notebook/decorators.py", line 98, in decorator
    return func(*args, **kwargs)
  File "/hadoop01/hue/desktop/libs/notebook/src/notebook/api.py", line 97, in create_session
    response['session'] = get_api(request, session).create_session(lang=session['type'], properties=properties)
  File "/hadoop01/hue/desktop/libs/notebook/src/notebook/connectors/jdbc.py", line 82, in create_session
    self.db.test_connection(throw_exception=True)
  File "/hadoop01/hue/desktop/libs/librdbms/src/librdbms/jdbc.py", line 83, in test_connection
    self.connect()
  File "/hadoop01/hue/desktop/libs/librdbms/src/librdbms/jdbc.py", line 99, in connect
    self.conn = self.gateway.jvm.java.sql.DriverManager.getConnection(self.db_url, self.username, self.password, self.ssl)
  File "/hadoop01/hue/build/env/lib/python2.7/site-packages/py4j-0.9-py2.7.egg/py4j/java_gateway.py", line 813, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/hadoop01/hue/build/env/lib/python2.7/site-packages/py4j-0.9-py2.7.egg/py4j/protocol.py", line 312, in get_return_value
    format(target_id, ".", name, value))
Py4JError: An error occurred while calling z:java.sql.DriverManager.getConnection. Trace:
py4j.Py4JException: Method getConnection([class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.String]) does not exist
at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:335)
at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:360)
at py4j.Gateway.invoke(Gateway.java:254)
at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
at py4j.commands.CallCommand.execute(CallCommand.java:79)
at py4j.GatewayConnection.run(GatewayConnection.java:209)
at java.lang.Thread.run(Thread.java:748)

**Comment by romainr** [comment]
Not sure SSL will work with the JDBC proxy. However, it should be easier with the SqlAlchemy connector:

https://docs.gethue.com/latest/administrator/configuration/editor/#presto
https://github.com/dropbox/PyHive/issues/203

**Comment by sandeepreddy3647** [comment]
I used this presto interface and options in url for https which has jdbc:presto and SSL options and i can make connection to presto.

I’m thinking to update document for presto HTTPS connection or work on the above code fix which we don’t know if it works. 
Let me know your thoughts.

**Comment by romainr** [comment]
In any case updating the doc would be great: https://github.com/cloudera/hue/blob/master/docs/docs-site/content/administrator/configuration/editor/_index.md#presto

Long term plan is to move to SqlAlchemy and avoid using the JDBC proxy, so giving a try there would make sense

**Comment by sandeepreddy3647** [comment]
Updated the document https://github.com/cloudera/hue/issues/950
I'll check on SqlAlchemy and update details.
