### ISSUE TITLE
Hue 4.4.0 does not display all results

### ISSUE THREAD

**Issue by frmlof** [cloudera/hue#969]
Hive query result in Hue 4.4.0 does not display all columns in result if column count is more than 12. 

![Screen Shot 2019-09-18 at 14 51 28](https://user-images.githubusercontent.com/5782335/65182467-f70dcd00-da26-11e9-998a-cd992452f3e7.png)

**Comment by frmlof** [comment]
In error logs I see:
```
AttributeError: 'NoneType' object has no attribute 'update'
[18/Sep/2019 13:11:57 -0700] access       ERROR    172.31.71.197 root - "POST /desktop/log_js_error HTTP/1.1"-- JS ERROR: {"msg":"SyntaxError: expected expression, got '<'","url":"http://ec2-18-207-101-217.compute-1.amazonaws.com:8888/desktop/workers/aceSqlLocationWorker.js?v=4.4.0","line":10,"column":0}
[18/Sep/2019 13:11:57 -0700] access       ERROR    172.31.71.197 root - "POST /desktop/log_js_error HTTP/1.1"-- JS ERROR: {"msg":"SyntaxError: expected expression, got '<'","url":"http://ec2-18-207-101-217.compute-1.amazonaws.com:8888/desktop/workers/aceSqlSyntaxWorker.js?v=4.4.0","line":10,"column":0}
[18/Sep/2019 13:12:02 -0700] decorators   ERROR    Error running fetch_result_size
Traceback (most recent call last):
  File "/usr/lib/hue/desktop/libs/notebook/src/notebook/decorators.py", line 97, in decorator
    return func(*args, **kwargs)
  File "/usr/lib/hue/desktop/libs/notebook/src/notebook/api.py", line 276, in fetch_result_size
    response['result'] = get_api(request, snippet).fetch_result_size(notebook, snippet)
  File "/usr/lib/hue/desktop/libs/notebook/src/notebook/connectors/hiveserver2.py", line 85, in decorator
    return func(*args, **kwargs)
  File "/usr/lib/hue/desktop/libs/notebook/src/notebook/connectors/hiveserver2.py", line 333, in fetch_result_size
    raise QueryError(_('Result status is not available'))
QueryError
```

**Comment by zevektor** [comment]
I think this could be related to issue #898 as I'm seeing similar errors in my JavaScript console.

**Comment by romainr** [comment]
+1, there was a few bad bugs on the horizontal scrolls. Should be good in master of upcoming 4.6 release
