### ISSUE TITLE
Building hue fails in no-internet env

### ISSUE THREAD

**Issue by AndreyEmelyanenko** [cloudera/hue#972]
Building hue fails, trace is below. Need your help!
I'm building in a no-internet environment. All components are in desktop/core/ext-py/, but it tries to download them from internet. How can I fix it?! OS is centos-7.
Thanks in advance

**Comment by AndreyEmelyanenko** [comment]
--- Building egg for cryptography-1.3.1
make[2]: Leaving directory `/ws/build/hue/rpm/BUILD/hue-release-4.1.0/desktop/core'
make[1]: Leaving directory `/ws/build/hue/rpm/BUILD/hue-release-4.1.0/desktop'


RPM build errors:

> Task :hue-rpm FAILED
Download error on https://pypi.python.org/simple/cffi/: [Errno 101] Network is unreachable -- Some packages may not be found!
Couldn't find index page for 'cffi' (maybe misspelled?)
Download error on https://pypi.python.org/simple/: [Errno 101] Network is unreachable -- Some packages may not be found!
No local packages or download links found for cffi>=1.4.1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/ws/build/hue/rpm/BUILD/hue-release-4.1.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 238, in run_setup
    raise
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/ws/build/hue/rpm/BUILD/hue-release-4.1.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 191, in setup_context
    yield
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/ws/build/hue/rpm/BUILD/hue-release-4.1.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 162, in save_modules
    saved_exc.resume()
  File "/ws/build/hue/rpm/BUILD/hue-release-4.1.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 137, in resume
    compat.reraise(type, exc, self._tb)
  File "/ws/build/hue/rpm/BUILD/hue-release-4.1.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 150, in save_modules
    yield saved
  File "/ws/build/hue/rpm/BUILD/hue-release-4.1.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 191, in setup_context
    yield
  File "/ws/build/hue/rpm/BUILD/hue-release-4.1.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 235, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/ws/build/hue/rpm/BUILD/hue-release-4.1.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 265, in run
    return func()
  File "/ws/build/hue/rpm/BUILD/hue-release-4.1.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 234, in runner
    _execfile(setup_script, ns)
  File "/ws/build/hue/rpm/BUILD/hue-release-4.1.0/build/env/lib/python2.7/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "setup.py", line 335, in <module>
    **keywords_with_side_effects(sys.argv)
  File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
    _setup_distribution = dist = klass(attrs)
  File "/ws/build/hue/rpm/BUILD/hue-release-4.1.0/build/env/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/ws/build/hue/rpm/BUILD/hue-release-4.1.0/build/env/lib/python2.7/site-packages/setuptools/dist.py", line 311, in fetch_build_eggs
    replace_conflicting=True,
  File "/ws/build/hue/rpm/BUILD/hue-release-4.1.0/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 797, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/ws/build/hue/rpm/BUILD/hue-release-4.1.0/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1047, in best_match
    return self.obtain(req, installer)
  File "/ws/build/hue/rpm/BUILD/hue-release-4.1.0/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1059, in obtain
    return installer(requirement)
  File "/ws/build/hue/rpm/BUILD/hue-release-4.1.0/build/env/lib/python2.7/site-packages/setuptools/dist.py", line 378, in fetch_build_egg
    return cmd.easy_install(req)
  File "/ws/build/hue/rpm/BUILD/hue-release-4.1.0/build/env/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 617, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('cffi>=1.4.1')
make[2]: *** [/ws/build/hue/rpm/BUILD/hue-release-4.1.0/desktop/core/build/cryptography-1.3.1/egg.stamp] Error 1
make[1]: *** [.recursive-env-install/core] Error 2
make: *** [desktop] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.hVcKwa (%build)
    Bad exit status from /var/tmp/rpm-tmp.hVcKwa (%build)
5 actionable tasks: 5 executed

FAILURE: Build failed with an exception.

* Where:
Script '/ws/packages.gradle' line: 469

* What went wrong:
Execution failed for task ':hue-rpm'.
> Process 'command 'rpmbuild'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 40s

**Comment by jdesjean** [comment]
Can you confirm you installed all dependencies https://docs.gethue.com/latest/administrator/installation/dependencies/ ?

**Comment by AndreyEmelyanenko** [comment]
> Can you confirm you installed all dependencies https://docs.gethue.com/latest/administrator/installation/dependencies/ ?

Yes, i confirm. i have two absolutely identical machines, the only difference is that one has internet connection and can download and install dependencies (like ['cffi>=1.4.1'] and others) and another cannot. But all these dependencies are already in desktop/core/ext-py/ and it is possible to install them manually one by one, but i need them to be installed automatically, as it was planned. But i can't understand why builder doesn't see them...

**Comment by romainr** [comment]
Thanks for the infos and should get much simpler after https://issues.cloudera.org/browse/HUE-8737
